package recovered.strings;

public class StringTable08 {
   public static String[] field_0000 = new String[]{
      "Starting to get data",
      "Reached EOF, closing connection",
      "Caught SocketException, closing connection",
      "Got IOException, closing connection",
      "Got ClassNotFoundException, closing connection",
      "maxhistory",
      "FailureViewClass",
      "Could not create Failure DetailView - using default view",
      " Exit ",
      "JV",
      "JUnit Version ",
      "Use a custom class loader to reload the classes for every run",
      "Select a Test class",
      "Results:",
      "No Test Cases found.\nCheck that the configured 'TestCollector' is supported on this platform.",
      "TestCollectorClass",
      "Could not create TestCollector - using default collector",
      ".junitsession",
      "TestRunner-Thread",
      "Couldn't save test run history",
      "Warning: could not load \"",
      "\" icon",
      "ACTIVITY_JOIN",
      "ACTIVITY_SPECTATE",
      "ACTIVITY_JOIN_REQUEST",
      ".fml.client.SplashProgress",
      "http://optifine.net/crashReport",
      "OF-Summary",
      "OptiFineVersion: ",
      "Summary: ",
      ") [",
      "OptiFine Version",
      "OptiFine Build",
      "Render Distance Chunks",
      "Mipmaps",
      "Anisotropic Filtering",
      "Antialiasing",
      "Multitexture",
      "Couldn't connect to server",
      "Unknown host",
      "Name cannot be null!",
      "Ignoring attempt to add an existent listener.",
      "No appenders could be found for logger (",
      "Please initialize the log4j system properly.",
      "See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.",
      "Could not convert [",
      "] to Level.",
      "The Hiearchy.overrideAsNeeded method has been deprecated.",
      "The Hiearchy.setDisableOverride method has been deprecated.",
      "unexpected object type ",
      " in ht.",
      "BASE",
      "SQUARE_BOTTOM_LEFT",
      "square_bottom_left",
      "bl",
      "SQUARE_BOTTOM_RIGHT",
      "square_bottom_right",
      "br",
      "SQUARE_TOP_LEFT",
      "square_top_left",
      "tl",
      "SQUARE_TOP_RIGHT",
      "square_top_right",
      "tr",
      "STRIPE_BOTTOM",
      "stripe_bottom",
      "bs",
      "STRIPE_TOP",
      "stripe_top",
      "ts",
      "STRIPE_LEFT",
      "stripe_left",
      "ls",
      "STRIPE_RIGHT",
      "stripe_right",
      "rs",
      "STRIPE_CENTER",
      "stripe_center",
      "cs",
      "STRIPE_MIDDLE",
      "stripe_middle",
      "STRIPE_DOWNRIGHT",
      "stripe_downright",
      "drs",
      "STRIPE_DOWNLEFT",
      "stripe_downleft",
      "dls",
      "STRIPE_SMALL",
      "small_stripes",
      "ss",
      "CROSS",
      "cross",
      "cr",
      "STRAIGHT_CROSS",
      "straight_cross",
      "TRIANGLE_BOTTOM",
      "triangle_bottom",
      "bt",
      "TRIANGLE_TOP",
      "triangle_top",
      "tt",
      "TRIANGLES_BOTTOM",
      "triangles_bottom",
      "bts",
      "TRIANGLES_TOP",
      "triangles_top",
      "tts",
      "DIAGONAL_LEFT",
      "diagonal_left",
      "ld",
      "DIAGONAL_RIGHT",
      "diagonal_up_right",
      "rd",
      " ##",
      "DIAGONAL_LEFT_MIRROR",
      "diagonal_up_left",
      "lud",
      "DIAGONAL_RIGHT_MIRROR",
      "diagonal_right",
      "rud",
      "CIRCLE_MIDDLE",
      "circle",
      "mc",
      "RHOMBUS_MIDDLE",
      "rhombus",
      "mr",
      "HALF_VERTICAL",
      "half_vertical",
      "vh",
      "HALF_HORIZONTAL",
      "half_horizontal",
      "hh",
      "HALF_VERTICAL_MIRROR",
      "half_vertical_right",
      "vhr",
      "HALF_HORIZONTAL_MIRROR",
      "half_horizontal_bottom",
      "hhb",
      "BORDER",
      "border",
      "bo",
      "CURLY_BORDER",
      "curly_border",
      "cbo",
      "CREEPER",
      "cre",
      "GRADIENT",
      "gradient",
      "gra",
      "GRADIENT_UP",
      "gradient_up",
      "gru",
      "bri",
      "SKULL",
      "sku",
      "FLOWER",
      "flo",
      "moj",
      "Animations",
      "Set visuals to legacy and modern versions alike.",
      "1.7 <-> 1.8",
      "OrangeMarshall (Original)",
      "Sk1er (Revised)",
      "1.7 Visuals",
      "Old Animations",
      "Punch During Usage is disabled.",
      "minemenclub",
      "Position Settings",
      "Item Positions",
      "Change all item models to be in the same position as 1.7.",
      "1.8",
      "Bow Pullback",
      "Change the bow pullback animation to be like 1.7.",
      "Block Animation",
      "Change the sword block animation to be like 1.7.",
      "Rod Position",
      "3rd Person Block Animation",
      "Change the 3rd person blocking animation to be like 1.7.",
      "Interaction Settings",
      "Consume Animation",
      "Change the eating and drinking animation to look like 1.7.",
      "Block-Hitting Animation",
      "Makes block hitting look much smoother, like it did in 1.7.",
      "Smooth Sneaking",
      "Makes the transition between sneaking/not sneaking smooth.\\n§eCombine with longer unsneak to match 1.7.",
      "Longer Unsneak",
      "Makes moving up take longer than moving down\\n§eCombine with smooth sneaking to match 1.7.",
      "Punching During Usage",
      "Allows you to punch blocks whilst using an item.\\n§eVisual only.",
      "Item Switching Animation",
      "Stop held items from playing the switching animation when right clicking on blocks.",
      "Hit Color Armor",
      "1.7: Make the hit color apply to the armor.\n1.8: Make the hit color only apply to the player skin.",
      "Hit Color Brightness",
      "Set the hit color to use 1.7's brightness system, darkening the hit color.",
      "HUD Settings",
      "Health Bar Flashing",
      "Stops your health bar flashing when you take damage.",
      "shutter",
      "Couldn't save screenshot",
      "Info",
      "&9Copied &fscreenshot.",
      "screenshot.success",
      "screenshot.failure",
      "Lost ownership",
      " [OPN]",
      " [Open]",
      " [CPY]",
      " [Copy]",
      "Copy the screenshot",
      " [UPL]",
      " [Upload]",
      "Upload to ",
      "imgur.com & open",
      "Saved",
      " and copied ",
      "screenshot",
      "ENTER_COMBAT",
      "END_COMBAT",
      "ENTITY_DIED",
      "Unexpected exception from the global event executor: ",
      "fmt ",
      "mob.ghast.moan",
      "mob.ghast.scream",
      "mob.ghast.death",
      "player_death",
      "killer",
      "channel gone inactive with ",
      " missing response(s)",
      "Stopping due to interrupt",
      "Batching chunks",
      " when I expected it to be pending; ignoring task",
      " when I expected it to be compiling; aborting task",
      "Fetching addPacket for removed entity",
      "Don't know how to add ",
      "Select world",
      "stat.generalButton",
      "stat.blocksButton",
      "stat.itemsButton",
      "stat.mobsButton",
      "Unexpected failure while binding MarkerFactory",
      "failed to read a file: ",
      "found no certificates: ",
      "found no private key: ",
      "Failed to close a stream.",
      "-+BEGIN\\s+.*CERTIFICATE[^-]*-+(?:\\s|\\r|\\n)+([a-z0-9+/=\\r\\n]+)-+END\\s+.*CERTIFICATE[^-]*-+",
      "-+BEGIN\\s+.*PRIVATE\\s+KEY[^-]*-+(?:\\s|\\r|\\n)+([a-z0-9+/=\\r\\n]+)-+END\\s+.*PRIVATE\\s+KEY[^-]*-+",
      ".red_sandstone.name",
      " (length: >= 1)",
      "WOOD",
      "EMERALD",
      "DebugLevelSource",
      "frameLength must be a positive integer: ",
      "uvlock",
      "Invalid BlockModelRotation x: ",
      ", y: ",
      "Trying to find [",
      "] using context classloader ",
      "org.apache.log4j.helpers.Loader",
      "] using ",
      " class loader.",
      "Caught Exception while in Loader.getResource. This may be innocuous.",
      "] using ClassLoader.getSystemResource().",
      "java.lang.Thread",
      "getContextClassLoader",
      "log4j.ignoreTCL",
      "i1",
      "i2",
      "mob.magmacube.big",
      "mob.magmacube.small",
      "unable to create JavaSound device: ",
      "javazoom.jl.player.JavaSoundAudioDevice",
      "Cannot create JavaSound device",
      "PASS_THROUGH",
      "AWAIT_HEADERS",
      "AWAIT_CONTENT",
      "Can't dye non-leather!",
      "minecraft:items/empty_armor_slot_helmet",
      "minecraft:items/empty_armor_slot_chestplate",
      "minecraft:items/empty_armor_slot_leggings",
      "minecraft:items/empty_armor_slot_boots",
      "_log4j_obj_tcpaccept_appender.local.",
      "closing SocketHubAppender ",
      "SocketHubAppender ",
      " closed",
      "stopping ServerSocket",
      "closing client connections",
      "could not close oos.",
      "dropped connection",
      "prohibited trailing header: ",
      "SOCKS_MESSAGE_ENCODER",
      "queue full",
      "c == this",
      "Elder",
      "mob.guardian.land.idle",
      "mob.guardian.elder.idle",
      "mob.guardian.idle",
      "mob.guardian.land.hit",
      "mob.guardian.elder.hit",
      "mob.guardian.hit",
      "mob.guardian.land.death",
      "mob.guardian.elder.death",
      "mob.guardian.death",
      "mob.guardian.flop",
      "textures/gui/title/background",
      "optifine/gui/background",
      "/panorama_0.png",
      "optifine/gui",
      "CustomPanorama: ",
      "/background.properties",
      "responseType",
      "selectWorld.title",
      "Couldn't load level list",
      "Unable to load worlds",
      "selectWorld.world",
      "selectWorld.conversion",
      "gameMode.survival",
      "gameMode.creative",
      "gameMode.adventure",
      "gameMode.spectator",
      "selectWorld.select",
      "selectWorld.rename",
      "selectWorld.delete",
      "selectWorld.recreate",
      "selectWorld.deleteQuestion",
      "selectWorld.deleteWarning",
      "selectWorld.deleteButton",
      "x0",
      "y0",
      "z0",
      "x1",
      "y1",
      "z1",
      "Error : MultiTexID.base mismatch: ",
      ", texid: ",
      "allocateTextureMap ",
      "Setting ID is not valid: ",
      "--> ",
      " (persist value: ",
      "; persisted: ",
      "SHADOW",
      "GBUFFERS",
      "DEFERRED",
      "COMPOSITE",
      "connection refused",
      "FLIP_DOWN",
      "FLIP_UP",
      "FLIP_NORTH",
      "FLIP_SOUTH",
      "FLIP_WEST",
      "FLIP_EAST",
      "arrowDamage",
      "ndc",
      "of.options.capeOF.title",
      "of.options.capeOF.openEditor",
      "of.options.capeOF.reloadCape",
      "of.options.capeOF.copyEditorLink",
      "https://optifine.net/capeChange?u=",
      "&n=",
      "&s=",
      "of.message.capeOF.openEditor",
      "of.message.capeOF.openEditorError",
      "of.message.capeOF.error1",
      "of.message.capeOF.error2",
      "Mojang authentication failed",
      "Error opening OptiFine cape link",
      "of.message.capeOF.reloadCape",
      "commands.generic.num.tooSmall",
      "commands.generic.num.tooBig",
      "commands.generic.double.tooSmall",
      "commands.generic.double.tooBig",
      "You must specify which player you wish to perform this action on.",
      "commands.generic.entity.invalidUuid",
      "commands.give.item.notFound",
      "commands.give.block.notFound",
      "mob.wolf.step",
      "Angry",
      "CollarColor",
      "mob.wolf.growl",
      "mob.wolf.whine",
      "mob.wolf.panting",
      "mob.wolf.bark",
      "mob.wolf.hurt",
      "mob.wolf.death",
      "mob.wolf.shake",
      "Failed to initialize a channel. Closing: ",
      "LocationInfo failed using JDK 1.4 methods",
      "Detected IBM VisualAge environment.",
      "getMethodName",
      "getFileName",
      "getLineNumber",
      "LocationInfo will use pre-JDK 1.4 methods to determine location.",
      "com.sun.jndi.dns.DnsContextFactory",
      "dns:",
      "com.sun.jndi.dns.timeout.retries",
      "_minecraft._tcp.",
      "SRV",
      "srv",
      "textures/entity/armorstand/wood.png",
      "global.cfg",
      "mutes.cfg",
      "default.cfg",
      "([a-zA-Z0-9/]+)/",
      "Created default configuration presets",
      " custom profiles",
      "Profile 1",
      "State",
      "WasRenderHUD",
      "RenderHUD",
      "xTranslation",
      "yTranslation",
      "keycode:",
      "mouse:",
      ";mouse:",
      ";keycode:",
      "mouse boolean: ",
      "value: ",
      "rainbow",
      "FavoriteColors",
      "FavoriteStations",
      "XrayBlocks",
      "ProfileIndexes",
      "]\\[",
      "ActiveProfile",
      "# MC_Client: GLOBAL SETTINGS",
      "ActiveProfile=",
      ";rainbow",
      "FavoriteColors=",
      "FavoriteStations=",
      "XrayBlocks=",
      "ProfileIndexes=",
      "# MC_Client: MODULE SETTINGS",
      "-State=",
      "-WasRenderHUD=",
      "-Position=",
      "-xTranslation=",
      "-yTranslation=",
      "-RenderHUD=",
      "# Customize your HUD info display string.",
      "# (& color formatting is allowed)",
      "# Optional uses:",
      "# %FPS% - Display current FPS.",
      "# %DIR% - Display current look direction.",
      "# %CPS% - Display CPS.",
      "# %COORDS% - Display coordinates.",
      "# %IP% - Current server IP.",
      "# %X% - Your X location.",
      "# %Y% - Your (foot) Y location.",
      "# %Z% - Your Z location.",
      "# %NL% - Break into a new line.",
      "Toggle",
      "UUID of player ",
      " is ",
      "Failed to verify username but will let them in anyway!",
      "Failed to verify username!",
      "Username '",
      "' tried to join with an invalid session",
      "Authentication servers are down but will let them in anyway!",
      "Authentication servers are down. Please try again later, sorry!",
      "Couldn't verify username because servers are unavailable",
      "RG",
      "RGB",
      "BGR",
      "RGBA",
      "BGRA",
      "RED_INTEGER",
      "RG_INTEGER",
      "RGB_INTEGER",
      "BGR_INTEGER",
      "RGBA_INTEGER",
      "BGRA_INTEGER",
      "Unknown Status",
      "Informational",
      "Successful",
      "Redirection",
      "Client Error",
      "Server Error",
      "reasonPhrase",
      "reasonPhrase contains one of the following prohibited characters: \\r\\n: ",
      "Continue",
      "Switching Protocols",
      "Processing",
      "Accepted",
      "Non-Authoritative Information",
      "No Content",
      "Reset Content",
      "Partial Content",
      "Multi-Status",
      "Multiple Choices",
      "Moved Permanently",
      "Found",
      "See Other",
      "Not Modified",
      "Use Proxy",
      "Temporary Redirect",
      "Bad Request",
      "Unauthorized",
      "Payment Required",
      "Forbidden",
      "Not Found",
      "Method Not Allowed",
      "Not Acceptable",
      "Proxy Authentication Required",
      "Request Timeout",
      "Conflict",
      "Gone",
      "Length Required",
      "Precondition Failed",
      "Request Entity Too Large",
      "Request-URI Too Long",
      "Unsupported Media Type",
      "Requested Range Not Satisfiable",
      "Expectation Failed",
      "Unprocessable Entity",
      "Failed Dependency",
      "Unordered Collection",
      "Upgrade Required",
      "Precondition Required",
      "Too Many Requests",
      "Request Header Fields Too Large",
      "Internal Server Error",
      "Not Implemented",
      "Bad Gateway",
      "Service Unavailable",
      "Gateway Timeout",
      "HTTP Version Not Supported",
      "Variant Also Negotiates",
      "Insufficient Storage",
      "Not Extended",
      "Network Authentication Required",
      "An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.",
      "Discarded inbound message {} that reached at the tail of the pipeline. Please check your pipeline configuration.",
      "Style.ROOT",
      "DATABITS_5",
      "DATABITS_6",
      "DATABITS_7",
      "DATABITS_8",
      "CustomSky",
      "startFadeIn",
      "endFadeIn",
      "startFadeOut",
      "endFadeOut",
      "days",
      "daysLoop",
      "rain",
      "transition",
      "Unknown weather: ",
      "Invalid time: ",
      "Unknown boolean: ",
      "Invalid axis: ",
      "Invalid axis values: ",
      "No source texture: ",
      "Invalid fadeIn/fadeOut times, sum is not 24h: ",
      "Invalid speed: ",
      "Invalid daysLoop: ",
      "Invalid times, required are: startFadeIn, endFadeIn and endFadeOut.",
      "START_DESTROY_BLOCK",
      "ABORT_DESTROY_BLOCK",
      "STOP_DESTROY_BLOCK",
      "DROP_ALL_ITEMS",
      "DROP_ITEM",
      "RELEASE_USE_ITEM",
      "Hide from HUD",
      "Add to HUD",
      "329/329",
      "Speed II",
      "0:42",
      ": Hey.",
      ": Hi!",
      "delete-64.png",
      "plus-64.png",
      "Return to HUD",
      "pressed",
      " (incompatible)",
      "WebSocket version 08 client handshake key: {}, expected response: {}",
      "Command",
      "TrackOutput",
      "LastOutput",
      "Executing command block",
      "Command to be executed",
      "SelectorComponent{pattern='",
      "tf",
      "LIMB_SWING",
      "limb_swing",
      "LIMB_SWING_SPEED",
      "limb_speed",
      "AGE",
      "HEAD_YAW",
      "head_yaw",
      "HEAD_PITCH",
      "head_pitch",
      "SCALE",
      "HEALTH",
      "HURT_TIME",
      "hurt_time",
      "IDLE_TIME",
      "idle_time",
      "MAX_HEALTH",
      "max_health",
      "MOVE_FORWARD",
      "move_forward",
      "MOVE_STRAFING",
      "move_strafing",
      "PARTIAL_TICKS",
      "partial_ticks",
      "pos_x",
      "pos_y",
      "pos_z",
      "REVENGE_TIME",
      "revenge_time",
      "SWING_PROGRESS",
      "swing_progress",
      "Bitstream errorcode ",
      "org.apache.log4j.varia.Roller",
      "host_name port_number",
      "Second argument ",
      " is not a valid integer.",
      "Roll over signal acknowledged by remote appender.",
      "Unexpected return code ",
      " from remote entity.",
      "Could not send roll signal on host ",
      " port ",
      " .",
      "True",
      "False",
      "REQUESTS",
      "FRIENDS",
      "Loaded Overlay Gui",
      "FRIENDS (",
      "REQUESTS (",
      "Error finding Chunk.hasEntities",
      "hasEntities",
      "lockCount: ",
      "Entity is already tracked!",
      "Adding entity to track",
      "Entity To Track",
      "Tracking range",
      " blocks",
      "Update interval",
      "Entity That Is Already Tracked",
      "\"Silently\" catching entity tracking error.",
      "recycled multiple times",
      "Key pair generation failed!",
      "SHA-1",
      "ISO_8859_1",
      "Public key reconstitute failed!",
      "Cipher data failed!",
      "Cipher creation failed!",
      "AES/CFB8/NoPadding",
      "characters",
      "Invalid font->characters: expected object, was ",
      "Invalid font->characters->default: expected object, was ",
      "Invalid default width",
      "Invalid default spacing",
      "Invalid default left",
      "characters[",
      "Invalid spacing",
      "Invalid left",
      "font",
      "Mega Spruce Taiga",
      "*(",
      "):",
      " a LogTableColumn.",
      "Setting user: ",
      "Setting UUID: ",
      "Initializing game",
      "Initialization",
      "Reported exception thrown!",
      "Unexpected error",
      "Unreported exception thrown!",
      "LWJGL Version: ",
      "server-resource-packs",
      "Skins",
      "skins",
      "Sound Handler",
      "Font Renderers",
      "textures/font/ascii.png",
      "textures/font/ascii_sga.png",
      "Pre startup",
      "Startup",
      "Textures",
      "Achievements",
      "Effects",
      "Post startup",
      "Couldn't initialize twitch stream",
      "Couldn't set pixel format",
      "client/icon-1.png",
      "client/icon-2.png",
      "Couldn't set icon",
      "Timer hack thread",
      "-client.txt",
      "#@!@# Game crashed! Crash report saved to: #@!@# ",
      "#@?@# Game crashed! Crash report could not be saved. #@?@#",
      "Caught error stitching, removing all assigned resourcepacks",
      "Unable to load logo: ",
      "########## GL ERROR ##########",
      "@ ",
      "Stopping!",
      "Pre render",
      "gameRenderer",
      "submit",
      "Post render",
      "%d fps (%d chunk update%s) T: %s%s%s%s%s",
      "inf",
      " vsync",
      " fast",
      " fast-clouds",
      " fancy-clouds",
      " vbo",
      "fpslimit_wait",
      "display_update",
      "##0.00",
      "[0] ",
      "ROOT ",
      "[?] ",
      "Null returned as 'hitResult', this shouldn't happen!",
      "org.lwjgl.opengl.Window.undecorated",
      "Couldn't toggle fullscreen",
      "Updating screen events",
      "Affected screen",
      "Ticking screen",
      "keyboard",
      "Manually triggered debug crash",
      "levelRenderer",
      "Exception in world tick",
      "Affected level",
      "Problem",
      "Level is null!",
      "animateTick",
      "pendingConnection",
      "hold ",
      " for ",
      "click ",
      "Streamer mode is ",
      "! Press escape and ",
      " to open the Mod Menu.",
      "Starting integrated server",
      "Level ID",
      "Level Name",
      "(+NBT)",
      "Launched Version",
      "LWJGL",
      "OpenGL",
      "GL Caps",
      "Using VBOs",
      "Resource Packs",
      "Current Language",
      "CPU",
      "fps",
      "vsync_enabled",
      "display_frequency",
      "display_type",
      "windowed",
      "current_action",
      "little",
      "resource_packs",
      "resource_pack[",
      "hosting_lan",
      "playing_lan",
      "multiplayer",
      "out_of_game",
      "opengl_version",
      "opengl_vendor",
      "client_brand",
      "launched_version",
      "gl_caps[ARB_arrays_of_arrays]",
      "gl_caps[ARB_base_instance]",
      "gl_caps[ARB_blend_func_extended]",
      "gl_caps[ARB_clear_buffer_object]",
      "gl_caps[ARB_color_buffer_float]",
      "gl_caps[ARB_compatibility]",
      "gl_caps[ARB_compressed_texture_pixel_storage]",
      "gl_caps[ARB_compute_shader]",
      "gl_caps[ARB_copy_buffer]",
      "gl_caps[ARB_copy_image]",
      "gl_caps[ARB_depth_buffer_float]",
      "gl_caps[ARB_depth_clamp]",
      "gl_caps[ARB_depth_texture]",
      "gl_caps[ARB_draw_buffers]",
      "gl_caps[ARB_draw_buffers_blend]",
      "gl_caps[ARB_draw_elements_base_vertex]",
      "gl_caps[ARB_draw_indirect]",
      "gl_caps[ARB_draw_instanced]",
      "gl_caps[ARB_explicit_attrib_location]",
      "gl_caps[ARB_explicit_uniform_location]",
      "gl_caps[ARB_fragment_layer_viewport]",
      "gl_caps[ARB_fragment_program]",
      "gl_caps[ARB_fragment_shader]",
      "gl_caps[ARB_fragment_program_shadow]",
      "gl_caps[ARB_framebuffer_object]",
      "gl_caps[ARB_framebuffer_sRGB]",
      "gl_caps[ARB_geometry_shader4]",
      "gl_caps[ARB_gpu_shader5]",
      "gl_caps[ARB_half_float_pixel]",
      "gl_caps[ARB_half_float_vertex]",
      "gl_caps[ARB_instanced_arrays]",
      "gl_caps[ARB_map_buffer_alignment]",
      "gl_caps[ARB_map_buffer_range]",
      "gl_caps[ARB_multisample]",
      "gl_caps[ARB_multitexture]",
      "gl_caps[ARB_occlusion_query2]",
      "gl_caps[ARB_pixel_buffer_object]",
      "gl_caps[ARB_seamless_cube_map]",
      "gl_caps[ARB_shader_objects]",
      "gl_caps[ARB_shader_stencil_export]",
      "gl_caps[ARB_shader_texture_lod]",
      "gl_caps[ARB_shadow]",
      "gl_caps[ARB_shadow_ambient]",
      "gl_caps[ARB_stencil_texturing]",
      "gl_caps[ARB_sync]",
      "gl_caps[ARB_tessellation_shader]",
      "gl_caps[ARB_texture_border_clamp]",
      "gl_caps[ARB_texture_buffer_object]",
      "gl_caps[ARB_texture_cube_map]",
      "gl_caps[ARB_texture_cube_map_array]",
      "gl_caps[ARB_texture_non_power_of_two]",
      "gl_caps[ARB_uniform_buffer_object]",
      "gl_caps[ARB_vertex_blend]",
      "gl_caps[ARB_vertex_buffer_object]",
      "gl_caps[ARB_vertex_program]",
      "gl_caps[ARB_vertex_shader]",
      "gl_caps[EXT_bindable_uniform]",
      "gl_caps[EXT_blend_equation_separate]",
      "gl_caps[EXT_blend_func_separate]",
      "gl_caps[EXT_blend_minmax]",
      "gl_caps[EXT_blend_subtract]",
      "gl_caps[EXT_draw_instanced]",
      "gl_caps[EXT_framebuffer_multisample]",
      "gl_caps[EXT_framebuffer_object]",
      "gl_caps[EXT_framebuffer_sRGB]",
      "gl_caps[EXT_geometry_shader4]",
      "gl_caps[EXT_gpu_program_parameters]",
      "gl_caps[EXT_gpu_shader4]",
      "gl_caps[EXT_multi_draw_arrays]",
      "gl_caps[EXT_packed_depth_stencil]",
      "gl_caps[EXT_paletted_texture]",
      "gl_caps[EXT_rescale_normal]",
      "gl_caps[EXT_separate_shader_objects]",
      "gl_caps[EXT_shader_image_load_store]",
      "gl_caps[EXT_shadow_funcs]",
      "gl_caps[EXT_shared_texture_palette]",
      "gl_caps[EXT_stencil_clear_tag]",
      "gl_caps[EXT_stencil_two_side]",
      "gl_caps[EXT_stencil_wrap]",
      "gl_caps[EXT_texture_3d]",
      "gl_caps[EXT_texture_array]",
      "gl_caps[EXT_texture_buffer_object]",
      "gl_caps[EXT_texture_integer]",
      "gl_caps[EXT_texture_lod_bias]",
      "gl_caps[EXT_texture_sRGB]",
      "gl_caps[EXT_vertex_shader]",
      "gl_caps[EXT_vertex_weighting]",
      "gl_caps[gl_max_vertex_uniforms]",
      "gl_caps[gl_max_fragment_uniforms]",
      "gl_caps[gl_max_vertex_attribs]",
      "gl_caps[gl_max_vertex_texture_image_units]",
      "gl_caps[gl_max_texture_image_units]",
      "gl_max_texture_size",
      "stream.confirm_start",
      "Not ready to start streaming yet!",
      "X-Minecraft-Username",
      "X-Minecraft-UUID",
      "X-Minecraft-Version",
      "Using epoll channel type",
      "Using default channel type",
      "Interrupted whilst closing channel",
      "Ticking memory connection",
      "Ticking connection",
      "Failed to handle packet for ",
      "Internal server error",
      "MOVE_UP",
      "MOVE_DOWN",
      "MOVE_BACK",
      "syslogHost",
      "Malformed URL: will attempt to interpret as InetAddress.",
      "Could not find ",
      ". All logging will FAIL.",
      "Could not instantiate DatagramSocket to ",
      "Error in class '",
      "Tree.leafIcon",
      "Tree.closedIcon",
      "AllTests",
      "CLIENT",
      "canSee",
      "container.furnace",
      "BurnTime",
      "CookTime",
      "CookTimeTotal",
      "OUT: [{}:{}] {}",
      "Can't serialize unregistered packet",
      "PACKET_SENT",
      "%s (%s)",
      "pattern",
      "Unrecognized format specifier [",
      "Class for conversion pattern %",
      " not found",
      "Bad map entry for conversion pattern %",
      "newInstance",
      "[Ljava.lang.String;",
      " does not extend PatternConverter.",
      "Error creating converter for ",
      "Empty conversion specifier starting at position ",
      "Unrecognized conversion specifier [",
      "] starting at position ",
      " in conversion pattern.",
      "org.apache.log4j.pattern.LoggerPatternConverter",
      "org.apache.log4j.pattern.ClassNamePatternConverter",
      "org.apache.log4j.pattern.DatePatternConverter",
      "org.apache.log4j.pattern.FileLocationPatternConverter",
      "org.apache.log4j.pattern.FullLocationPatternConverter",
      "org.apache.log4j.pattern.LineLocationPatternConverter",
      "org.apache.log4j.pattern.MessagePatternConverter",
      "org.apache.log4j.pattern.LineSeparatorPatternConverter",
      "org.apache.log4j.pattern.MethodLocationPatternConverter",
      "org.apache.log4j.pattern.LevelPatternConverter",
      "org.apache.log4j.pattern.RelativeTimePatternConverter",
      "relative",
      "t",
      "org.apache.log4j.pattern.ThreadPatternConverter",
      "org.apache.log4j.pattern.NDCPatternConverter",
      "org.apache.log4j.pattern.PropertiesPatternConverter",
      "org.apache.log4j.pattern.SequenceNumberPatternConverter",
      "sequenceNumber",
      "org.apache.log4j.pattern.ThrowableInformationPatternConverter",
      "org.apache.log4j.pattern.FileDatePatternConverter",
      "i",
      "org.apache.log4j.pattern.IntegerPatternConverter",
      "merchant.deprecated",
      "Uninitalized",
      "ConnectingToServer",
      "TestingServer",
      "DoneTestingServer",
      "Cancelling",
      "Failed",
      "'.'yyyy-MM-dd",
      "Either File or DatePattern options are not set for appender [",
      "Appender [",
      "] to be rolled every minute.",
      "] to be rolled on top of every hour.",
      "] to be rolled at midday and midnight.",
      "] to be rolled at midnight.",
      "] to be rolled at start of week.",
      "] to be rolled at start of every month.",
      "Unknown periodicity for appender [",
      "Missing DatePattern option in rollOver().",
      "Failed to rename [",
      "rollOver() failed.",
      "wood_old",
      "BRICK",
      "SMOOTHBRICK",
      "smoothStoneBrick",
      "NETHERBRICK",
      "QUARTZ",
      "Invalid forwards & up combination",
      "com.mojang.realmsclient.RealmsMainScreen",
      "Realms module missing",
      "com.mojang.realmsclient.gui.screens.RealmsNotificationsScreen",
      "Once per ",
      " ticks",
      "Maximum (",
      "<custom>",
      "of.shaders.profile",
      "of.general.custom",
      "profile.comment",
      ". ",
      "Getting biome",
      "Coordinates of biome request",
      "checkLight",
      "Exception while updating neighbours",
      "Block being updated",
      "Source block type",
      "Ticking entity",
      "Entity being ticked",
      "Entity",
      "regular",
      "blockEntities",
      "Ticking block entity",
      "Block entity being ticked",
      "pendingBlockEntities",
      "chunkCheck",
      "All: ",
      "buildList",
      "playerCheckLight",
      "moodSound",
      "ambient.cave.cave",
      "getBrightness",
      "checkedPosition < toCheckCount",
      "Playing level event",
      "Level event being played",
      "Block coordinates",
      "Event source",
      "Event type",
      "Event data",
      "Level name",
      "????",
      "All players",
      "Chunk stats",
      "Level Data Unobtainable",
      "RequestAuthTokenDoneCallback got failure: %s",
      "LoginCallback got failure: %s",
      "IngestListCallback got failure: %s",
      "UserInfoDoneCallback got failure: %s",
      "StreamInfoDoneCallback got failure: %s",
      "RunCommercialCallback got failure: %s",
      "SetStreamInfoCallback got failure: %s",
      "GameNameListCallback got failure: %s",
      "startCallback got failure: %s",
      "stopCallback got failure: %s",
      "sendActionMetaDataCallback got failure: %s",
      "sendStartSpanMetaDataCallback got failure: %s",
      "sendEndSpanMetaDataCallback got failure: %s",
      "Cannot bind to this type of address: ",
      "Not connected/not bound",
      "[fd=",
      "; file=",
      "; connected=",
      "; bound=",
      "Unsupported value: ",
      "Value must not be null",
      "Unsupported option: ",
      "Error while getting option",
      "Only accepting Boolean.FALSE here",
      "Error while setting option",
      "Stream-ID cannot be negative: "
   };
}
