package recovered.strings;

public class StringTable14 {
   public static String[] field_0000 = new String[]{
      "Bob the camera screen when moving.",
      "Bob Hand",
      "Bob the hand when moving.",
      "Bob Only While Sprinting",
      "Bob the hand only when sprinting.",
      "Only Hand",
      "Only Screen",
      "Screen Bobbing Intensity",
      "Hand Bobbing Intensity",
      "Camera Options",
      "Damage affects camera",
      "Hurt Camera Intensity",
      "Static Swiftness",
      "Determines if your FOV changes as you move.",
      "Default FOV",
      " FOV",
      "Aiming Multiplier",
      "https://cdn.discordapp.com/avatars/",
      "a_",
      ".gif",
      "https://discordapp.com/assets/",
      "<@",
      "U:",
      "give",
      "commands.give.usage",
      "commands.give.tagError",
      "commands.give.success",
      "textures/gui/stream_indicator.png",
      "requestType",
      "ID #%d (%s // %s)",
      "ID #",
      "OptiFine_1.8.9_HD_U_M6_pre2",
      "DL: ",
      "optifine.ForgeSplashCompatible",
      "Build: ",
      "VM: ",
      "LWJGL: ",
      ", version ",
      "OpenGL Mipmap levels: Not available (GL12.GL_TEXTURE_MAX_LEVEL)",
      "OpenGL Fancy fog: Not available (GL_NV_fog_distance)",
      "OpenGL Occlussion culling: Not available (GL_ARB_occlusion_query)",
      "Maximum texture size: ",
      "/buildof.txt",
      "([0-9]+)\\.([0-9]+)(\\.([0-9]+))?(.+)?",
      "Texture pack clouds: ",
      " x",
      "OpenGL error: %s (%s), at: %s",
      "ShowGlError",
      "([A-Z])([0-9]+)(.*)",
      "FSAA Samples: ",
      "Error setting FSAA: ",
      "icons/icon_16x16.png",
      "icons/icon_32x32.png",
      "Error setting window icon: ",
      " fps, C: ",
      ", E: ",
      ", U: ",
      "ProgramFiles(X86)",
      "textures/gui/title/mojang.png",
      "Error opening link: ",
      "No error",
      "Invalid enum",
      "Invalid value",
      "Invalid operation",
      "Stack overflow",
      "Stack underflow",
      "Out of memory",
      "Invalid framebuffer operation",
      "board",
      "Field not found: TileEntitySignRenderer.model",
      "Invalid tag encountered, expected '{' as first char.",
      "Encountered multiple top tags, only one expected",
      "Illegal use of \\\": ",
      "Unbalanced curly brackets {}: ",
      "Unbalanced square brackets []: ",
      "Unbalanced quotation: ",
      "Unbalanced brackets: ",
      "Unexpected token '",
      "' at: ",
      "Unable to locate name/value separator for string: ",
      "Name error at: ",
      "\\[[-+\\d|,\\s]+\\]",
      "BlockModel requires either elements or parent, found neither",
      "BlockModel requires either elements or parent, found both",
      "parent",
      "ambientocclusion",
      "elements",
      "recheckGaps",
      "Getting block",
      "Block being got",
      "Getting block state",
      "Wrong location! (",
      ") should be (",
      "Could not set level chunk sections, array length is ",
      " instead of ",
      "Could not set level chunk biomes, array length is ",
      "Could not set level chunk heightmap, array length is ",
      "bat",
      "outer_right_wing",
      "outer_left_wing",
      "Sunflower Plains",
      "WINGS",
      "EMOTE",
      "icon",
      "SUBICON",
      "subicon",
      "\\{",
      "org.apache.log4j.LogSF",
      "BaseComponent{style=",
      "stat.craftItem.",
      "stat.craftItem",
      "stat.mineBlock.",
      "stat.mineBlock",
      "stat.useItem.",
      "stat.useItem",
      "stat.breakItem.",
      "stat.breakItem",
      "stat.killEntity.",
      "stat.entityKill",
      "stat.entityKilledBy.",
      "stat.leaveGame",
      "stat.playOneMinute",
      "stat.timeSinceDeath",
      "stat.walkOneCm",
      "stat.crouchOneCm",
      "stat.sprintOneCm",
      "stat.swimOneCm",
      "stat.fallOneCm",
      "stat.climbOneCm",
      "stat.flyOneCm",
      "stat.diveOneCm",
      "stat.minecartOneCm",
      "stat.boatOneCm",
      "stat.pigOneCm",
      "stat.horseOneCm",
      "stat.jump",
      "stat.drop",
      "stat.damageDealt",
      "stat.damageTaken",
      "stat.deaths",
      "stat.mobKills",
      "stat.animalsBred",
      "stat.playerKills",
      "stat.fishCaught",
      "stat.junkFished",
      "stat.treasureFished",
      "stat.talkedToVillager",
      "stat.tradedWithVillager",
      "stat.cakeSlicesEaten",
      "stat.cauldronFilled",
      "stat.cauldronUsed",
      "stat.armorCleaned",
      "stat.bannerCleaned",
      "stat.brewingstandInteraction",
      "stat.beaconInteraction",
      "stat.dropperInspected",
      "stat.hopperInspected",
      "stat.dispenserInspected",
      "stat.noteblockPlayed",
      "stat.noteblockTuned",
      "stat.flowerPotted",
      "stat.trappedChestTriggered",
      "stat.enderchestOpened",
      "stat.itemEnchanted",
      "stat.recordPlayed",
      "stat.furnaceInteraction",
      "stat.craftingTableInteraction",
      "stat.workbenchInteraction",
      "stat.chestOpened",
      "Multiple values have the same name '",
      " certificate with unknown fingerprint: ",
      "mob.spider.say",
      "mob.spider.death",
      "mob.spider.step",
      "Floss",
      "poolType",
      "poolName",
      "priority: ",
      " (expected: Thread.MIN_PRIORITY <= priority <= Thread.MAX_PRIORITY)",
      "pending",
      "commandBlockOutput",
      "effect",
      "commands.effect.usage",
      "commands.effect.failure.notActive.all",
      "commands.effect.success.removed.all",
      "commands.effect.success",
      "commands.effect.success.removed",
      "commands.effect.failure.notActive",
      "commands.effect.notFound",
      "SHA256WithRSAEncryption",
      "disconnect.lost",
      "mount.onboard",
      "Unable to locate sign at ",
      "demo.help.movement",
      "demo.help.jump",
      "demo.help.inventory",
      "random.successful_hit",
      "mob.guardian.curse",
      "Couldn't load trade info",
      "Could not spawn particle effect ",
      "Server tried to update attributes of a non-living entity (actually: ",
      "potion.prefix.mundane",
      "potion.prefix.uninteresting",
      "potion.prefix.bland",
      "potion.prefix.clear",
      "potion.prefix.milky",
      "potion.prefix.diffuse",
      "potion.prefix.artless",
      "potion.prefix.thin",
      "potion.prefix.awkward",
      "potion.prefix.flat",
      "potion.prefix.bulky",
      "potion.prefix.bungling",
      "potion.prefix.buttered",
      "potion.prefix.smooth",
      "potion.prefix.suave",
      "potion.prefix.debonair",
      "potion.prefix.thick",
      "potion.prefix.elegant",
      "potion.prefix.fancy",
      "potion.prefix.charming",
      "potion.prefix.dashing",
      "potion.prefix.refined",
      "potion.prefix.cordial",
      "potion.prefix.sparkling",
      "potion.prefix.potent",
      "potion.prefix.foul",
      "potion.prefix.odorless",
      "potion.prefix.rank",
      "potion.prefix.harsh",
      "potion.prefix.acrid",
      "potion.prefix.gross",
      "potion.prefix.stinky",
      "0 & !1 & !2 & !3 & 0+6",
      "!0 & 1 & !2 & !3 & 1+6",
      "0 & 1 & !2 & !3 & 0+6",
      "0 & !1 & 2 & !3",
      "!0 & !1 & 2 & !3 & 2+6",
      "!0 & !1 & !2 & 3 & 3+6",
      "!0 & !1 & 2 & 3",
      "!0 & 1 & !2 & 3 & 3+6",
      "0 & !1 & !2 & 3 & 3+6",
      "!0 & 1 & 2 & !3 & 2+6",
      "!0 & 1 & 2 & 3 & 2+6",
      "0 & !1 & 2 & 3 & 2+6",
      "0 & 1 & !2 & 3 & 3+6",
      "5",
      "bidirectional",
      "Invalid language->'",
      "'->region: empty value",
      "'->name: empty value",
      "Duplicate language->'",
      "' defined",
      "bad Base64 input character at ",
      " (decimal)",
      "not encoded in Base64",
      "Disposing of the default LogBrokerMonitor instance",
      "Profession",
      "Riches",
      "Career",
      "CareerLevel",
      "Willing",
      "Offers",
      "mob.villager.haggle",
      "mob.villager.idle",
      "mob.villager.hit",
      "mob.villager.death",
      "mob.villager.yes",
      "mob.villager.no",
      "entity.Villager.",
      "CONFI",
      "acceptHandshakeAsServer - Wrong websocket version.",
      "Sec-WebSocket-Extensions",
      "acceptHandshakeAsServer - Matching extension found: {}",
      "acceptHandshakeAsServer - No matching extension or protocol found.",
      "acceptHandshake - Matching protocol found: {}",
      "acceptHandshakeAsClient - Missing/wrong upgrade or connection in handshake.",
      "acceptHandshakeAsClient - Missing Sec-WebSocket-Key or Sec-WebSocket-Accept",
      "acceptHandshakeAsClient - Wrong key for Sec-WebSocket-Key.",
      "acceptHandshakeAsClient - Matching extension found: {}",
      "acceptHandshakeAsClient - No matching extension or protocol found.",
      "websocket",
      "missing Sec-WebSocket-Key",
      "Web Socket Protocol Handshake",
      "TooTallNate Java-WebSocket",
      "afterEnconding({}): {}",
      "too big to display",
      "Size representation not supported/specified",
      "afterDecoding({}): {}",
      "Invalid frame: more than 125 octets",
      "more than 125 octets",
      "Limit exedeed: Payloadsize is to big...",
      "Payloadsize is to big...",
      "Payload limit reached. Allowed: {} Current: {}",
      "Payload limit reached.",
      "Limit underflow: Payloadsize is to little...",
      "Payloadsize is to little...",
      "Incomplete frame: maxpacketsize < realpacketsize",
      "EEE, dd MMM yyyy HH:mm:ss z",
      "Unknown opcode ",
      "Protocol error: Continuous frame sequence not completed.",
      "Continuous frame sequence not completed.",
      "non control or continious frame expected",
      "Protocol error: Continuous frame sequence was not started.",
      "Continuous frame sequence was not started.",
      "Protocol error: Payload is not UTF8",
      "Runtime exception during onWebsocketMessage",
      "Protocol error: Previous continuous frame sequence not completed.",
      "Previous continuous frame sequence not completed.",
      " extension: ",
      " protocol: ",
      " max frame size: ",
      "Can only connect to endpoints of type ",
      "AFUNIXSocket[fd=",
      "AFUNIXSocket[unconnected]",
      "name cannot be length zero",
      "name exceeds allowable length: ",
      "name contains null character: ",
      "value contains null character: ",
      "sun.security.ssl.NextProtoNegoExtension",
      "Details: ",
      "Nothing selected",
      "org.apache.log4j.chainsaw.DetailPanel",
      "<b>Time:</b> <code>{0,time,medium}</code>&nbsp;&nbsp;<b>Priority:</b> <code>{1}</code>&nbsp;&nbsp;<b>Thread:</b> <code>{2}</code>&nbsp;&nbsp;<b>NDC:</b> <code>{3}</code><br><b>Logger:</b> <code>{4}</code><br><b>Location:</b> <code>{5}</code><br><b>Message:</b><pre>{6}</pre><b>Throwable:</b><pre>{7}</pre>",
      "commands.help.usage",
      "commands.help.header",
      "commands.help.footer",
      "of.options.qualityTitle",
      "\t\t",
      ":\n",
      " Hitbox Options",
      "Show ",
      " Hitbox",
      " Hitbox Outline",
      " Eye Height",
      " Look Vector",
      "Show Own Hitbox",
      " Dashed Line",
      " Line Distance",
      " Line Thickness",
      "Own Hitbox Outline Color",
      " Outline Color",
      " Eye Height Color",
      " Look Vector Color",
      "#.00",
      "%BOOST%",
      "Don't know how to turn ",
      " into a Component",
      "text",
      "with",
      "score",
      "objective",
      "A score component needs a least a name and an objective",
      "selector",
      "extra",
      "Unexpected empty array of components",
      "Don't know how to serialize ",
      " as a Component",
      "Unable to evaluate property ",
      "Unable to get property descriptors",
      "ws-encoder",
      "VersionCheck",
      "Checking for new version",
      "http://optifine.net/version/1.8.9/HD_U.txt",
      "OF-MC-Version",
      "OF-MC-Brand",
      "OF-Edition",
      "OF-Release",
      "OF-Java-Version",
      "OF-CpuCount",
      "OF-OpenGL-Version",
      "OF-OpenGL-Vendor",
      "Version found: ",
      "container.chest",
      "resourceType",
      "samplingInterval: ",
      " (expected: 1+)",
      "maxActive: ",
      "LEAK: You are creating too many ",
      " instances.  ",
      " is a shared resource that must be reused across the JVM,",
      "so that only a few instances are created.",
      "LEAK: {}.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-D{}={}' or call {}.setLevel()",
      "io.netty.leakDetectionLevel",
      "LEAK: {}.release() was not called before it's garbage-collected.{}",
      "io.netty.noResourceLeakDetection",
      "-Dio.netty.noResourceLeakDetection: {}",
      "-Dio.netty.noResourceLeakDetection is deprecated. Use '-D{}={}' instead.",
      "-D{}: {}",
      "io.netty.buffer.AbstractByteBufAllocator.toLeakAwareBuffer(",
      ", line: ",
      "vec4",
      " ()",
      "save-on",
      "commands.save-on.usage",
      "commands.save.enabled",
      "commands.save-on.alreadyOn",
      "Test Selector",
      "Select the Test class:",
      "hp",
      "--> ID = ",
      " username: ",
      " or password: ",
      " values should be in pure ascii",
      "Could not save the list after adding a user.",
      "Could not save the list after removing a user.",
      "windir",
      "\\system32\\tasklist.exe",
      "mcpatcher/cit.properties",
      "CustomItems: Loading ",
      "useGlint",
      "mcpatcher/cit/",
      "CustomItems: ",
      "CustomItems file not found: ",
      "linger",
      "mcpatcher/cit/potion/",
      "mcpatcher/cit/Potion/",
      "Potion not found for image: ",
      "mundane",
      "awkward",
      "thick",
      "potent",
      "movespeed",
      "fireresistance",
      "heal",
      "nightvision",
      "bungling",
      "charming",
      "rank",
      "damageboost",
      "moveslowdown",
      "leaping",
      "harm",
      "waterbreathing",
      "thin",
      "debonair",
      "sparkling",
      "stinky",
      "Invalid item ID: ",
      "_layer_",
      "not an http header",
      "^ +",
      "Invalid request method received: %s Status line: %s",
      "HTTP/1.1",
      "Invalid status line received: %s Status line: %s",
      "101",
      "Invalid status code received: %s Status line: %s",
      "upgrade",
      "Only Opcode.BINARY or  Opcode.TEXT are allowed",
      "GET ",
      " HTTP/1.1",
      "HTTP/1.1 101 ",
      "unknown role",
      "Negative count",
      "kill",
      "commands.kill.usage",
      "commands.kill.successful",
      "Model renderer not found, model: ",
      "Model adapter already registered for id: ",
      ", class: ",
      "has_record",
      "Stop failed: ",
      "tile.skull.skeleton.name",
      "^^^",
      "nodrop",
      "ridx=",
      "widx=",
      "not a replayable operation",
      "Twitch",
      "nmt37qblda36pvonovdkbopzfzw3wlq",
      "Twitch authenticator",
      "Shutdown streaming",
      "Disconnecting from twitch chat per user options",
      "Connecting to twitch chat per user options",
      "Disconnecting from twitch chat as user is no longer streaming",
      "Connecting to twitch chat as user is streaming",
      "Invalid twitch chat state {}",
      "Couldn't send stream metadata action at {}: {}",
      "Sent stream metadata action at {}: {}",
      "Could not send stream metadata sequence from {} to {}: {}",
      "Sent stream metadata sequence from {} to {}: {}",
      "Half-sent stream metadata sequence from {} to {}: {}",
      "Requested commercial from Twitch",
      "Could not request commercial from Twitch",
      "Streaming at {}/{} at {} kbps to {}",
      "Minecraft",
      "Stopped streaming to Twitch",
      "Could not stop streaming to Twitch",
      "Login attempt successful",
      "Login attempt unsuccessful: {} (error code {})",
      "Broadcast state changed to {}",
      "Logged out of twitch",
      "Stream info updated; {} viewers on stream ID {}",
      "Issue submitting frame: {} (Error code {})",
      "Issue streaming frame: ",
      "Broadcast to Twitch has started",
      "Broadcast to Twitch has stopped",
      "stream.unavailable.soundflower.chat.link",
      "https://help.mojang.com/customer/portal/articles/1374877-configuring-soundflower-for-streaming-on-apple-computers",
      "stream.unavailable.soundflower.chat",
      "stream.unavailable.unknown.chat",
      "Ingest test state changed to {}",
      "Chat failed to initialize",
      "Chat failed to shutdown",
      "chat.stream.",
      "stream.userinfo.chatTooltip",
      "Chat connected",
      "Chat disconnected",
      "STREAM",
      "avutil-ttv-51",
      "swresample-ttv-0",
      "libmp3lame-ttv",
      "libmfxsw64",
      "libmfxsw32",
      ".comment",
      "/cb_decrease_time",
      "Decreased time by ",
      "NeBCr",
      "NeBEF",
      "NeBS",
      "NeCCS",
      "NeCTB",
      "NeCE",
      "NeSCSC",
      "NeSCLT",
      "NeSC",
      "NeSCRT",
      "NeCSR",
      "NeMT",
      "NeRC",
      "NeSR",
      "NeStart",
      "disarmed",
      "2345345",
      "client/icons/garbage-26.png",
      "client/logo_26.png",
      "item.record.",
      "tickDuration must be greater than 0: ",
      "ticksPerWheel must be greater than 0: ",
      "tickDuration: %d (expected: 0 < tickDuration in nanos < %d",
      "ticksPerWheel may not be greater than 2^30: ",
      "cannot be started once stopped",
      "Invalid WorkerState",
      ".stop() cannot be called from ",
      "workerState",
      "client/icons/plus-64.png",
      "Open Profiles Folder",
      "(COPIES CURRENT PROFILE) ",
      "ADD NEW PROFILE",
      "Map colour ID must be between 0 and 63 (inclusive)",
      "§1",
      "stream.user.subscription.subscriber",
      "stream.user.subscription.subscriber.self",
      "stream.user.subscription.subscriber.other",
      "stream.user.subscription.turbo",
      "stream.user.mode.administrator",
      "stream.user.mode.banned",
      "stream.user.mode.banned.self",
      "stream.user.mode.banned.other",
      "stream.user.mode.broadcaster",
      "stream.user.mode.broadcaster.self",
      "stream.user.mode.broadcaster.other",
      "stream.user.mode.moderator",
      "stream.user.mode.moderator.self",
      "stream.user.mode.moderator.other",
      "stream.user.mode.staff",
      "stream.userinfo.timeout",
      "stream.userinfo.ban",
      "stream.userinfo.mod",
      "stream.userinfo.unban",
      "stream.userinfo.unmod",
      "/ban ",
      "/unban ",
      "/mod ",
      "/unmod ",
      "/timeout ",
      "nThreads: %d (expected: > 0)",
      "failed to create a child event loop",
      "POSITION",
      "COLOR",
      "Vertex Color",
      "UV",
      "MATRIX",
      "Bone Matrix",
      "BLEND_WEIGHT",
      "Blend Weight",
      "PADDING",
      "Padding",
      " is an invalid choice",
      "LEATHER",
      "CHAIN",
      "chainmail",
      "IRON",
      "DIAMOND",
      "SERVER",
      "Lo6a$DMR",
      "aAO20DQ6iIlP",
      "yh9bV53gfZv4tBa49MF2G",
      "u2CXyEg4Fy32",
      "ip",
      "acceptTextures",
      "Connecting to ",
      "Server Connector #",
      "Aborted",
      "connect.connecting",
      "connect.authorizing",
      "r.",
      "HANDSHAKE",
      "FRAME",
      "CLOSE",
      "complete already: ",
      "too many waiters: ",
      "Failed to submit a listener notification task. Event loop shut down?",
      ".operationComplete()",
      ".operationProgressed()",
      "(success)",
      "(uncancellable)",
      "(failure(",
      "(incomplete)",
      ".rejectedExecution",
      ".UNCANCELLABLE",
      "OwnerUUID",
      "Sitting",
      "INVALID_TOKEN",
      "Metadata section name cannot be null",
      "Invalid metadata for '",
      "' - expected object, found ",
      "Don't know how to handle metadata section '",
      "checkTexture: act: ",
      ", glAct: ",
      ", tex: ",
      ", glTex: ",
      "Customize World Presets",
      "createWorld.customize.custom.presets.title",
      "{ \"coordinateScale\":684.412, \"heightScale\":684.412, \"upperLimitScale\":512.0, \"lowerLimitScale\":512.0, \"depthNoiseScaleX\":200.0, \"depthNoiseScaleZ\":200.0, \"depthNoiseScaleExponent\":0.5, \"mainNoiseScaleX\":5000.0, \"mainNoiseScaleY\":1000.0, \"mainNoiseScaleZ\":5000.0, \"baseSize\":8.5, \"stretchY\":8.0, \"biomeDepthWeight\":2.0, \"biomeDepthOffset\":0.5, \"biomeScaleWeight\":2.0, \"biomeScaleOffset\":0.375, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":false, \"seaLevel\":255 }",
      "textures/gui/presets/water.png",
      "createWorld.customize.custom.preset.waterWorld",
      "{\"coordinateScale\":3000.0, \"heightScale\":6000.0, \"upperLimitScale\":250.0, \"lowerLimitScale\":512.0, \"depthNoiseScaleX\":200.0, \"depthNoiseScaleZ\":200.0, \"depthNoiseScaleExponent\":0.5, \"mainNoiseScaleX\":80.0, \"mainNoiseScaleY\":160.0, \"mainNoiseScaleZ\":80.0, \"baseSize\":8.5, \"stretchY\":10.0, \"biomeDepthWeight\":1.0, \"biomeDepthOffset\":0.0, \"biomeScaleWeight\":1.0, \"biomeScaleOffset\":0.0, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":false, \"seaLevel\":63 }",
      "textures/gui/presets/isles.png",
      "createWorld.customize.custom.preset.isleLand",
      "{\"coordinateScale\":684.412, \"heightScale\":684.412, \"upperLimitScale\":512.0, \"lowerLimitScale\":512.0, \"depthNoiseScaleX\":200.0, \"depthNoiseScaleZ\":200.0, \"depthNoiseScaleExponent\":0.5, \"mainNoiseScaleX\":5000.0, \"mainNoiseScaleY\":1000.0, \"mainNoiseScaleZ\":5000.0, \"baseSize\":8.5, \"stretchY\":5.0, \"biomeDepthWeight\":2.0, \"biomeDepthOffset\":1.0, \"biomeScaleWeight\":4.0, \"biomeScaleOffset\":1.0, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":false, \"seaLevel\":63 }",
      "textures/gui/presets/delight.png",
      "createWorld.customize.custom.preset.caveDelight",
      "{\"coordinateScale\":738.41864, \"heightScale\":157.69133, \"upperLimitScale\":801.4267, \"lowerLimitScale\":1254.1643, \"depthNoiseScaleX\":374.93652, \"depthNoiseScaleZ\":288.65228, \"depthNoiseScaleExponent\":1.2092624, \"mainNoiseScaleX\":1355.9908, \"mainNoiseScaleY\":745.5343, \"mainNoiseScaleZ\":1183.464, \"baseSize\":1.8758626, \"stretchY\":1.7137525, \"biomeDepthWeight\":1.7553768, \"biomeDepthOffset\":3.4701107, \"biomeScaleWeight\":1.0, \"biomeScaleOffset\":2.535211, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":false, \"seaLevel\":63 }",
      "textures/gui/presets/madness.png",
      "createWorld.customize.custom.preset.mountains",
      "{\"coordinateScale\":684.412, \"heightScale\":684.412, \"upperLimitScale\":512.0, \"lowerLimitScale\":512.0, \"depthNoiseScaleX\":200.0, \"depthNoiseScaleZ\":200.0, \"depthNoiseScaleExponent\":0.5, \"mainNoiseScaleX\":1000.0, \"mainNoiseScaleY\":3000.0, \"mainNoiseScaleZ\":1000.0, \"baseSize\":8.5, \"stretchY\":10.0, \"biomeDepthWeight\":1.0, \"biomeDepthOffset\":0.0, \"biomeScaleWeight\":1.0, \"biomeScaleOffset\":0.0, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":false, \"seaLevel\":20 }",
      "textures/gui/presets/drought.png",
      "createWorld.customize.custom.preset.drought",
      "{\"coordinateScale\":684.412, \"heightScale\":684.412, \"upperLimitScale\":2.0, \"lowerLimitScale\":64.0, \"depthNoiseScaleX\":200.0, \"depthNoiseScaleZ\":200.0, \"depthNoiseScaleExponent\":0.5, \"mainNoiseScaleX\":80.0, \"mainNoiseScaleY\":160.0, \"mainNoiseScaleZ\":80.0, \"baseSize\":8.5, \"stretchY\":12.0, \"biomeDepthWeight\":1.0, \"biomeDepthOffset\":0.0, \"biomeScaleWeight\":1.0, \"biomeScaleOffset\":0.0, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":false, \"seaLevel\":6 }",
      "textures/gui/presets/chaos.png",
      "createWorld.customize.custom.preset.caveChaos",
      "{\"coordinateScale\":684.412, \"heightScale\":684.412, \"upperLimitScale\":512.0, \"lowerLimitScale\":512.0, \"depthNoiseScaleX\":200.0, \"depthNoiseScaleZ\":200.0, \"depthNoiseScaleExponent\":0.5, \"mainNoiseScaleX\":80.0, \"mainNoiseScaleY\":160.0, \"mainNoiseScaleZ\":80.0, \"baseSize\":8.5, \"stretchY\":12.0, \"biomeDepthWeight\":1.0, \"biomeDepthOffset\":0.0, \"biomeScaleWeight\":1.0, \"biomeScaleOffset\":0.0, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":true, \"seaLevel\":40 }",
      "textures/gui/presets/luck.png",
      "createWorld.customize.custom.preset.goodLuck",
      "resourcePack.available.title",
      "online",
      "sample",
      "player[",
      "textures/blocks/destroy_stage_0.png",
      "textures/blocks/destroy_stage_1.png",
      "textures/blocks/destroy_stage_2.png",
      "textures/blocks/destroy_stage_3.png",
      "textures/blocks/destroy_stage_4.png",
      "textures/blocks/destroy_stage_5.png",
      "textures/blocks/destroy_stage_6.png",
      "textures/blocks/destroy_stage_7.png",
      "textures/blocks/destroy_stage_8.png",
      "textures/blocks/destroy_stage_9.png",
      "Not represented by a file",
      "Missing type on ListTag",
      "Invalid TagEnd added to ListTag",
      "Adding mismatching tag types to tag list",
      "index out of bounds to set tag in tag list",
      "o does not belong to handle",
      "io.netty.recycler.maxCapacity.default",
      "-Dio.netty.recycler.maxCapacity.default: {}",
      "Enchantment Glint",
      "Glint Options",
      "Inventory Glint",
      "Dropped Item Glint",
      "Thrown Item Glint",
      "Held Item Glint",
      "Armor Glint",
      "Potion Options",
      "Show Potion Color (Inventory)",
      "Only Render Potion Glint (Inventory)",
      "Exclude Potion Glint (Inventory)",
      "Shiny Pots",
      "Show a glint box around potions.",
      "Shiny Pots Boundary",
      "Entire Slot",
      "To Border",
      "Inventory Glint Color",
      "Dropped Item Glint Color",
      "Thrown Item Glint Color",
      "Held Item Glint Color",
      "Armor Glint Color",
      "client/icons/mods/ench_sword.png",
      "Customize the enchantment glint and/or enable shiny pots overlay.",
      "(?:^\\s+|\\s+$|\\n)",
      "[\\r\\t]",
      "ID %02d - %s, ver %d. Features enabled: %b",
      "ALLOWED",
      "PlayerItemsLayer not registered",
      "StoredEnchantments",
      "..",
      "([^/]+/)shaders/",
      "Client is now connected and ready!",
      "Sending RichPresence to discord: ",
      "cmd",
      "SET_ACTIVITY",
      "args",
      "pid",
      "activity",
      "Cannot subscribe to ",
      " event!",
      "Subscribing to Event: %s",
      "SUBSCRIBE",
      "evt",
      "Failed to close pipe",
      "IPCClient (ID: %d) is not connected!",
      "IPCClient (ID: %d) is already connected!",
      "Starting IPCClient reading thread!",
      "nonce",
      "Reading thread received a 'join' event.",
      "Reading thread received a 'spectate' event.",
      "Reading thread received a 'join request' event.",
      "Reading thread encountered an event with an unknown type: ",
      "DISPATCH",
      "secret",
      "discriminator",
      "avatar",
      "Exception when handling event: ",
      "Reading thread encountered an IOException",
      "Reading thread encountered an JSONException",
      "not a WebSocket handshake request: missing upgrade",
      "WebSocket Protocol Handshake",
      "WebSocket-Origin",
      "WebSocket-Location",
      "WebSocket-Protocol",
      "[^0-9]",
      "[^ ]",
      "jeb_",
      "textures/entity/sheep/sheep_fur.png",
      "samplers",
      "samplers[",
      "attributes",
      "attribute",
      "attributes[",
      "uniforms",
      "uniforms[",
      "Shader ",
      "could not find sampler named ",
      " in the specified shader program.",
      "Could not find uniform named ",
      "sampler",
      "Invalid amount of values specified (expected ",
      "values[",
      "Exception preparing structure feature",
      "Feature being prepared",
      "Is feature chunk",
      "Chunk location",
      "Chunk pos hash",
      "Structure type",
      "scaleMode",
      "dim",
      "full",
      "stretch",
      "Invalid scale mode: ",
      "Invalid scale: ",
      "defaultgamemode",
      "commands.defaultgamemode.usage",
      "commands.defaultgamemode.success",
      "Username",
      "ADD",
      "No friend requests",
      "Disable",
      "Enable",
      " incoming friend requests",
      "([a-zA-Z0-9_]+)",
      "Error!",
      "Incorrect username.",
      "Reach Display",
      "[2.8 blocks]",
      "Displays how far you hit an entity.",
      "dewgs",
      "WebSocket version 08 server handshake key: {}, response: {}",
      "Alt Login Thread",
      "DONKEY",
      "MULE",
      "LLAMA",
      "DROPPER",
      "Was not allowed to read system property \"",
      "Could not find value for key ",
      "] is not in proper int form.",
      "toLevel:class=[",
      ":pri=[",
      "custom level class [",
      " does not have a class function toLevel(String, Level)",
      " could not be instantiated",
      "class [",
      "] is not a subclass of org.apache.log4j.Level",
      "] cannot be instantiated due to access restrictions",
      "], level [",
      "] conversion failed.",
      "KB",
      "GB",
      "] not in expected format.",
      "Bad option value [",
      "A \"",
      "\" object is not assignable to a \"",
      "\" variable.",
      "The class \"",
      "\" was loaded by ",
      "] whereas object of type ",
      "\" was loaded by [",
      "Could not instantiate class [",
      "\" has no closing brace. Opening brace at position ",
      "Preferred configurator class: ",
      "org.apache.log4j.spi.Configurator",
      "Could not instantiate configurator [",
      "org.apache.log4j.xml.DOMConfigurator",
      "${",
      "parameters must not be null",
      "process({}): ({})",
      "Closing due to wrong handshake",
      "wrong http function",
      "Closing due to wrong handshake. Possible handshake rejection",
      "Closing due to internal server error",
      "Closing due to protocol error: no draft matches",
      "no draft matches",
      "Closing due to protocol error: wrong http function",
      "Closing due to protocol error: the handshake did finally not match",
      "the handshake did finally not match",
      "Closing due to invalid data exception. Possible handshake rejection",
      "Closing since client was never connected",
      "Closing due to protocol error: draft {} refuses handshake",
      "draft ",
      " refuses handshake",
      "Closing due to invalid handshake",
      "matched frame: {}",
      "Closing due to invalid size of frame",
      "Closing due to invalid data in frame",
      "404 WebSocket Upgrade Failure",
      "500 Internal Server Error",
      "HTTP/1.1 ",
      "\r\nContent-Type: text/html\nServer: TooTallNate Java-WebSocket\r\nContent-Length: ",
      "\r\n\r\n<html><head></head><body><h1>",
      "</h1></body></html>",
      "generated frame is invalid",
      "Broken pipe",
      "Caught IOException: Broken pipe during closeConnection()",
      "Exception during channel.close()",
      "this method must be used in conjunction with flushAndClose",
      "Exception in onWebsocketClosing",
      "Cannot send 'null' data to a WebSocketImpl.",
      "send frame: {}",
      "onPreparePing(WebSocket) returned null. PingFrame to sent can't be null.",
      "Handshake data rejected by client.",
      "Exception in startHandshake",
      "rejected because of ",
      "write({}): {}",
      "open using draft: {}",
      "This websocket uses ws instead of wss. No SSLSession available.",
      "cf2O02b1QJSZOcVHphHucA",
      "m)",
      "textures/entity/sign.png",
      "Created Friend Manager",
      "Unsupported mob type for DoorInteractGoal",
      "failed to initialize the default SSL context",
      "TLSv1.1",
      "TLSv1",
      "SSLv3",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_RC4_128_SHA",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
      "TLS_RSA_WITH_AES_128_GCM_SHA256",
      "SSL_RSA_WITH_RC4_128_SHA",
      "SSL_RSA_WITH_RC4_128_MD5",
      "TLS_RSA_WITH_AES_128_CBC_SHA",
      "TLS_RSA_WITH_AES_256_CBC_SHA",
      "SSL_RSA_WITH_DES_CBC_SHA",
      "Default protocols (JDK): {} ",
      "Default cipher suites (JDK): {}",
      "NOT_SET",
      "SURVIVAL",
      "ADVENTURE",
      "SPECTATOR",
      "W#W",
      "#W#",
      "~~ ",
      "~O ",
      "  ~",
      "X#X",
      " X ",
      "AAA",
      "BEB",
      "XRX",
      "XSX",
      "#  ",
      "## ",
      "  #",
      " X",
      "#R#",
      "TTT",
      "P",
      "D#D",
      " i ",
      "iii",
      "QQQ",
      "WWW",
      "I I",
      "ICI",
      " I ",
      "///",
      "/_/",
      "Invalid shapeless recipe: unknown type ",
      "axis=y",
      "axis=x",
      "axis=z",
      "CustomGuis",
      "container",
      "large",
      "trapped",
      "christmas",
      "ender",
      "professions",
      "No container found: ",
      "No texture found: ",
      "Invalid variants: ",
      "Invalid colors: ",
      "name: ",
      ", container: ",
      ", textures: ",
      "textures/gui/container/crafting_table.png",
      "textures/gui/container/furnace.png",
      "textures/gui/container/shulker_box.png",
      "textures/gui/container/villager.png",
      "hr",
      "sc",
      "hps",
      "Num",
      "ChannelTC",
      "spread",
      "io.netty.util.internal.__matchers__.",
      "Matcher",
      "match",
      "{ return $1 instanceof ",
      "; }",
      "defineClass",
      "Generated: {}",
      "[]",
      "Holder{width=",
      "Sequence Number",
      "sn",
      "Getting initial context.",
      "java.naming.factory.initial",
      "java.naming.provider.url",
      "You have set InitialContextFactoryName option but not the ProviderURL. This is likely to cause problems.",
      "java.naming.factory.url.pkgs",
      "java.naming.security.principal",
      "java.naming.security.credentials",
      "You have set SecurityPrincipalName option but not the SecurityCredentials. This is likely to cause problems.",
      "Looking up [",
      "About to create TopicConnection.",
      "Creating TopicSession, non-transactional, in AUTO_ACKNOWLEDGE mode.",
      "Looking up topic name [",
      "Creating TopicPublisher.",
      "Starting TopicConnection.",
      "Error while activating options for appender named [",
      "No TopicConnection",
      "No TopicSession",
      "No TopicPublisher",
      " for JMSAppender named [",
      "Closing appender [",
      "Error while closing JMSAppender [",
      "Could not publish message in JMSAppender [",
      "Ticking Particle",
      "Particle being ticked",
      "Particle",
      "Particle Type",
      "Rendering Particle",
      "Particle being rendered",
      "Pkt:",
      "Missing close quote '",
      "Bad character '",
      "' (",
      "slate",
      "stand",
      "Field not found: TileEntityBannerRenderer.bannerModel",
      "Source",
      "Unable to load variant: ",
      "Unable to load definition ",
      "Encountered an exception when loading model definition of '",
      "' from: '",
      "' in resourcepack: '",
      "Encountered an exception when loading model definition of model ",
      "Unable to load block model: '",
      "' for variant: '",
      "builtin/generated",
      "builtin/entity",
      "builtin/",
      "mcpatcher",
      "optifine",
      "Unable to load item model: '",
      "' for item: '",
      "Unable to load item model: '{}' for item: '{}'",
      "#.*",
      "Missing model for: ",
      "No weighted models for: ",
      "In parent chain: ",
      "; unable to load model: '",
      "blocks/water_flow",
      "blocks/water_still",
      "blocks/lava_flow",
      "blocks/lava_still",
      "blocks/destroy_stage_0",
      "blocks/destroy_stage_1",
      "blocks/destroy_stage_2",
      "blocks/destroy_stage_3",
      "blocks/destroy_stage_4",
      "blocks/destroy_stage_5"
   };
}
