package recovered.strings;

public class StringTable13 {
   public static String[] field_0000 = new String[]{
      "%LABEL%: %VALUE%",
      "close() must be invoked after the channel is closed.",
      "close() must be invoked after all flushed writes are handled.",
      "Failed to mark a promise as success because it is done already: {}",
      "Failed to mark a promise as failure because it's done already: {}",
      "processor",
      "writable",
      "totalPendingSize",
      "uri",
      "(decodeResult: ",
      "%d game time, %d day time",
      "_min",
      "Nametags",
      " | ",
      "java.lang.ThreadLocal",
      "livingEntityBaseTick",
      "doMobLoot",
      "HealF",
      "Health",
      "HurtTime",
      "HurtByTimestamp",
      "DeathTime",
      "AbsorptionAmount",
      "Attributes",
      "ActiveEffects",
      "random.break",
      "game.neutral.hurt",
      "game.neutral.die",
      "game.neutral.hurt.fall.big",
      "game.neutral.hurt.fall.small",
      "headTurn",
      "rangeChecks",
      "ai",
      "newAi",
      "jump",
      "travel",
      "push",
      "662A6B8D-DA3E-4C1C-8813-96EA6097278D",
      "Sprinting speed boost",
      "Failed to introspect ",
      "layout",
      "errorhandler",
      "org.apache.log4j.spi.OptionHandler",
      "Failed to set property [",
      "] to value \"",
      "\". ",
      "No such property [",
      "] in ",
      "No setter for property [",
      "#params for setter != 1",
      "Conversion to type [",
      "] failed. Reason: ",
      "] failed.",
      "Setting property [",
      "] to [",
      "java.lang.String",
      "org.apache.log4j.Priority",
      "org.apache.log4j.spi.ErrorHandler",
      "Entity: ",
      ", offsetY: ",
      "Missing particle!",
      "x",
      "y",
      "Z",
      "z",
      "NONE",
      "none",
      "particle",
      "layer0",
      "layer1",
      "layer2",
      "layer3",
      "layer4",
      "TOP",
      "top",
      "BOTTOM",
      "bottom",
      "Usage: jla <filename>",
      " e.g. : java javazoom.jl.player.advanced.jlap localfile.mp3",
      "MM/dd/yyyy",
      "https://api.mojang.com/user/profiles/",
      "/names",
      "{\"Names\": ",
      "}",
      "Names",
      "changedToAt",
      "0123456789abcdef",
      "(?i)§[0-9a-fklmnor]",
      "func",
      "srcrgb",
      "dstrgb",
      "srcalpha",
      "dstalpha",
      "add",
      "subtract",
      "reversesubtract",
      "reverse_subtract",
      "min",
      "max",
      "one",
      "1",
      "zero",
      "minus",
      "srccolor",
      "1-srccolor",
      "dstcolor",
      "1-dstcolor",
      "1-srcalpha",
      "1-dstalpha",
      "the Unsafe",
      "initialCapacity must be >= 1",
      "loadFactor must be > 0 and <= 1",
      "Unable to insert",
      "(this Map)",
      "minecraft:minecart.base",
      "Rain time: %d (now: %b), thunder time: %d (now: %b)",
      "shadow",
      "watershadow",
      "shadowtex",
      "shadowcolor",
      "depthtex",
      "gaux",
      "colortex",
      "\\s*uniform\\s+\\w+\\s+(\\w+).*",
      "\\s*attribute\\s+\\w+\\s+(\\w+).*",
      "\\s*const\\s+int\\s+(\\w+)\\s*=\\s*([-+.\\w]+)\\s*;.*",
      "\\s*const\\s+float\\s+(\\w+)\\s*=\\s*([-+.\\w]+)\\s*;.*",
      "\\s*const\\s+vec4\\s+(\\w+)\\s*=\\s*(.+)\\s*;.*",
      "\\s*const\\s+bool\\s+(\\w+)\\s*=\\s*(\\w+)\\s*;.*",
      "\\s*(/\\*|//)?\\s*([A-Z]+):\\s*(\\w+)\\s*(\\*/.*|\\s*)",
      "\\s*#\\s*extension\\s+(\\w+)\\s*:\\s*(\\w+).*",
      ".*deferred[0-9]*\\.fsh",
      ".*composite[0-9]*\\.fsh",
      ".*final\\.fsh",
      "[0-7N]*",
      "client/icons/error-64.png",
      "client/icons/delete-64.png",
      "client/icons/cb.png",
      "servers/",
      "/icon",
      "lunarnetwork",
      "Client out of date!",
      "Server out of date!",
      "(no connection)",
      "Pinging...",
      "Must be 64 pixels wide",
      "Must be 64 pixels high",
      "Invalid icon for server ",
      "Can't resolve hostname",
      "Can't connect to server.",
      "Server Pinger #%d",
      "textures/misc/unknown_server.png",
      "textures/gui/server_selection.png",
      "*",
      "mobGriefing",
      "Error shutting down the Twitch sdk: %s",
      "Error shutting down Twith chat: %s",
      "playsound",
      "commands.playsound.usage",
      "commands.playsound.playerTooFar",
      "commands.playsound.success",
      "of.options.detailsTitle",
      "thorns",
      "damage.thorns",
      ":0",
      "(?i)\\u00A7[0-9A-FK-OR]",
      " bytes (",
      " MB) / ",
      " MB) up to ",
      " MB)",
      "textures/colormap/foliage.png",
      "PushX",
      "PushZ",
      "Fuel",
      " // ",
      "group",
      "group set already",
      "channelClass",
      "channelFactory",
      "channelFactory set already",
      "option",
      "key",
      "group not set",
      "channel or channelFactory not set",
      "localAddress not set",
      "localAddress",
      "handler",
      "group: ",
      "channelFactory: ",
      "localAddress: ",
      "options: ",
      "attrs: ",
      "handler: ",
      ".HANDSHAKER",
      "CatType",
      "mob.cat.purr",
      "mob.cat.purreow",
      "mob.cat.meow",
      "mob.cat.hitt",
      "entity.Cat.name",
      "OPENING",
      "WOOD_DOOR",
      "GRATES",
      "IRON_DOOR",
      "Failed reading metadata of: ",
      "COMMON",
      "Common",
      "UNCOMMON",
      "Uncommon",
      "RARE",
      "Rare",
      "EPIC",
      "Epic",
      "Container Blur",
      "Adds a blur to containers.",
      "SUCCESS",
      "FAILURE",
      ": no factories registered",
      "Cannot create AudioDevice",
      "dead_bush",
      "normal",
      "game.tnt.primed",
      "java.class.path",
      "junit.framework.",
      "junit.extensions.",
      "junit.runner.",
      "path.separator",
      ".class",
      ".jar",
      ".zip",
      "excluded.properties",
      "excluded.",
      "backlog: ",
      "Wrong number of arguments.",
      "Listening on port ",
      "Waiting to accept a new client.",
      "Connected to client at ",
      "Starting new socket node.",
      "Usage: java ",
      "org.apache.log4j.net.SocketServer",
      " port configFile directory",
      "Could not interpret port number [",
      "] is not a directory.",
      "Locating configuration file for ",
      "/",
      "Could not parse the inetAddress [",
      "]. Using default hierarchy.",
      "Could not find config file [",
      "]. Will use the default hierarchy.",
      "generic",
      ".lcf",
      "Leave",
      "Get me out of here!",
      "I understand the risk, continue anyways ",
      "THIS SERVER IS ",
      "BLOCKED",
      "WARNING!",
      "Join at ",
      "your own",
      " risk!",
      "Log4J Log Messages",
      "text/html",
      "<tr>",
      "<td>",
      "</td>",
      "<td title=\"",
      " thread\">",
      "<td title=\"Level\">",
      "<font color=\"#339933\">",
      "</font>",
      "<font color=\"#993300\"><strong>",
      "</strong></font>",
      " category\">",
      "<td title=\"Message\">",
      "</tr>",
      "<tr><td bgcolor=\"#EEEEEE\" style=\"font-size : xx-small;\" colspan=\"6\" title=\"Nested Diagnostic Context\">",
      "NDC: ",
      "</td></tr>",
      "<tr><td bgcolor=\"#993300\" style=\"color:White; font-size : xx-small;\" colspan=\"6\">",
      "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">",
      "<html>",
      "<head>",
      "<title>",
      "</title>",
      "<style type=\"text/css\">",
      "<!--",
      "body, table {font-family: arial,sans-serif; font-size: x-small;}",
      "th {background: #336699; color: #FFFFFF; text-align: left;}",
      "</style>",
      "</head>",
      "<body bgcolor=\"#FFFFFF\" topmargin=\"6\" leftmargin=\"6\">",
      "<hr size=\"1\" noshade>",
      "Log session start time ",
      "<br>",
      "<table cellspacing=\"0\" cellpadding=\"4\" border=\"1\" bordercolor=\"#224466\" width=\"100%\">",
      "<th>Time</th>",
      "<th>Thread</th>",
      "<th>Level</th>",
      "<th>Category</th>",
      "<th>File:Line</th>",
      "<th>Message</th>",
      "</table>",
      "</body></html>",
      "<br>&nbsp;&nbsp;&nbsp;&nbsp;",
      "item.charcoal",
      "item.coal",
      "missingno",
      "client/logo_outer.png",
      "client/logo_inner.png",
      "title.oldgl1",
      "title.oldgl2",
      "https://help.mojang.com/customer/portal/articles/325948?ref=game",
      "background",
      "Happy birthday, ez!",
      "Happy birthday, Notch!",
      "Merry X-mas!",
      "Happy new year!",
      "OOoooOOOoooo! Spooky!",
      "menu.options",
      "menu.quit",
      "menu.singleplayer",
      "menu.multiplayer",
      "menu.playdemo",
      "menu.resetdemo",
      "Demo_World",
      "Couldn't open link",
      "CheatBreaker ",
      "Copyright Mojang AB. Do not distribute!",
      "texts/splashes.txt",
      "textures/gui/title/minecraft.png",
      "textures/gui/title/background/panorama_0.png",
      "textures/gui/title/background/panorama_1.png",
      "textures/gui/title/background/panorama_2.png",
      "textures/gui/title/background/panorama_3.png",
      "textures/gui/title/background/panorama_4.png",
      "textures/gui/title/background/panorama_5.png",
      "Please click ",
      "here",
      " for more information.",
      "Scaled: (%d, %d). Absolute: (%d, %d). Scale factor of %d",
      "lanServer.scanning",
      "O o o",
      "o O o",
      "o o O",
      "channel",
      "options",
      "connectTimeoutMillis: %d (expected: >= 0)",
      "maxMessagesPerRead: ",
      " (expected: > 0)",
      "writeSpinCount must be a positive integer.",
      "allocator",
      "writeBufferHighWaterMark cannot be less than writeBufferLowWaterMark (",
      "): ",
      "writeBufferHighWaterMark must be >= 0",
      "writeBufferLowWaterMark cannot be greater than writeBufferHighWaterMark (",
      "writeBufferLowWaterMark must be >= 0",
      "estimator",
      "textures/gui/widgets.png",
      "The coordinate is out of range",
      "Expected exception ",
      "Mob",
      "Blaze",
      "-01-",
      "-02-",
      "-03-",
      "-04-",
      "-05-",
      "-06-",
      "-07-",
      "-08-",
      "-09-",
      "-10-",
      "-11-",
      "-12-",
      "-NA-",
      "game.hostile.swim",
      "game.hostile.swim.splash",
      "game.hostile.hurt",
      "game.hostile.die",
      "game.hostile.hurt.fall.big",
      "game.hostile.hurt.fall.small",
      "upper",
      "lower",
      "UPPER",
      "LOWER",
      "null as draft is permitted for `WebSocketServer` only!",
      "You cannot initialize a reconnect out of the websocket thread. Use reconnect in another thread to insure a successful cleanup.",
      "WebSocketClient objects are not reuseable",
      "WebSocketConnectReadThread-",
      "wss",
      "TLSv1.2",
      "HTTPS",
      "ws",
      "unknown scheme: ",
      "Host",
      "socket has already been set",
      "SkullType",
      "Rot",
      "Owner",
      "ExtraType",
      "textures",
      "mooshroom",
      "client/dash-logo-54.png",
      "client/icons/play-24.png",
      "Filter",
      "Unpin",
      "Pin",
      "client/songs/",
      "REBUILD_CHUNK",
      "RESORT_TRANSPARENCY",
      "Only supported on Linux",
      "netty-transport-native-epoll",
      "defined_",
      "Unknown macro value: ",
      "Direction HUD",
      "textures/gui/compass.png",
      "Show While Typing",
      "Show the mod when opening chat.",
      "Highlight North",
      "Make North highlight a different color.",
      "Show Background",
      "Draw a background.",
      "Show Border",
      "Draw a border around the background.",
      "Border Thickness",
      "Change the thickness of the border.",
      "px",
      "Marker Color",
      "Change the marker color.",
      "Direction Color",
      "Change the direction color.",
      "Highlight Color",
      "Change the highlight color.",
      "Background Color",
      "Change the background color.",
      "Border Color",
      "Sets the color for the border.",
      "client/icons/mods/dirhud.png",
      "Displays your cardinal direction.",
      "bspkrs",
      "jadedcat",
      "|",
      "|§r",
      "random.burp",
      "AUTH_PASSWORD",
      "Rendering Block Entity",
      "Block Entity Details",
      "/bad-request",
      "Name cannot be null",
      "Prefix cannot be null",
      "Unable to create Channel from class ",
      "textures/entity/sheep/sheep.png",
      "textures/entity/witch.png",
      "minecraft:",
      "hasPlacedChest0",
      "hasPlacedChest1",
      "hasPlacedChest2",
      "hasPlacedChest3",
      "head.main",
      "head.nose",
      "head.ear1",
      "head.ear2",
      "[Shaders] Delayed loading of entity mappings after resources are loaded",
      "/shaders/entity.properties",
      "shaders/entity.properties",
      "[Shaders] Parsing entity mappings: ",
      "entity.",
      "[Shaders] Invalid entity ID: ",
      "[Shaders] Invalid entity alias ID: ",
      "[Shaders] Invalid entity ID mapping: ",
      "[Shaders] Error reading: ",
      "windowBits: ",
      " (expected: 9-15)",
      "memLevel: ",
      " (expected: 1-9)",
      "wrapper '",
      "' is not ",
      "allowed for compression.",
      "not added to a pipeline",
      "compression failure",
      "REQUEST",
      "RESPONSE",
      "Wait time must be >= 0",
      "readTime must be >= 0",
      "COOL_WARM",
      "HEAT_ICE",
      "SPECIAL",
      "language",
      "Unable to parse metadata section of resourcepack: ",
      "en_US",
      "ALLOCATOR",
      "RCVBUF_ALLOCATOR",
      "MESSAGE_SIZE_ESTIMATOR",
      "CONNECT_TIMEOUT_MILLIS",
      "MAX_MESSAGES_PER_READ",
      "WRITE_SPIN_COUNT",
      "WRITE_BUFFER_HIGH_WATER_MARK",
      "WRITE_BUFFER_LOW_WATER_MARK",
      "ALLOW_HALF_CLOSURE",
      "AUTO_READ",
      "AUTO_CLOSE",
      "SO_BROADCAST",
      "SO_KEEPALIVE",
      "SO_SNDBUF",
      "SO_RCVBUF",
      "SO_REUSEADDR",
      "SO_LINGER",
      "SO_BACKLOG",
      "SO_TIMEOUT",
      "IP_TOS",
      "IP_MULTICAST_ADDR",
      "IP_MULTICAST_IF",
      "IP_MULTICAST_TTL",
      "IP_MULTICAST_LOOP_DISABLED",
      "TCP_NODELAY",
      "AIO_READ_TIMEOUT",
      "AIO_WRITE_TIMEOUT",
      "DATAGRAM_CHANNEL_ACTIVE_ON_REGISTRATION",
      "Couldn't read statistics file ",
      "Couldn't parse statistics file ",
      "Couldn't save stats",
      "chat.type.achievement",
      "chat.type.achievement.taken",
      "progress",
      "Invalid statistic progress in ",
      "Invalid statistic in ",
      ": Don't know what ",
      " is",
      "Couldn't save statistic ",
      ": error serializing progress",
      "entry",
      "replace",
      "category",
      "Invalid category",
      "sounds",
      "sound",
      "Invalid type",
      "volume",
      "Invalid volume",
      "pitch",
      "Invalid pitch",
      "weight",
      "Invalid weight",
      "stream",
      "Origin",
      "Request origin [",
      "] was not among the configured origins ",
      "Vary",
      "Access-Control-Allow-Origin",
      "Access-Control-Allow-Credentials",
      "Access-Control-Request-Method",
      "Access-Control-Expose-Headers",
      "Access-Control-Allow-Methods",
      "Access-Control-Allow-Headers",
      "Access-Control-Max-Age",
      "Caught error in CorsHandler",
      "playlist",
      "artist",
      "album",
      "cover",
      "duration",
      "programStartTS",
      "dd MMM yy hh:mm:ss",
      "UTC",
      "Station(streamUrl=",
      ", currentSongUrl=",
      ", genre=",
      ", logoUrl=",
      ", favorite=",
      ", startTime=",
      ", title=",
      ", artist=",
      ", album=",
      ", coverUrl=",
      ", duration=",
      ", RESOURCE_CURRENT=",
      ", RESOURCE_PREVIOUS=",
      ", play=",
      "up",
      "SIDE",
      "side",
      "create",
      "using JmDNS version 3 to construct serviceInfo instance",
      "using JmDNS version 1.0 to construct serviceInfo instance",
      "Unable to instantiate JMDNS",
      "Unable to instantiate jmdns class",
      "Unable to access constructor",
      "Unable to call constructor",
      "java.util.Hashtable",
      "created serviceinfo: ",
      "Unable to construct ServiceInfo instance",
      "Unable to get ServiceInfo constructor",
      "java.util.Map",
      "Unable to invoke create method",
      "Unable to find create method",
      "registerService",
      "registered serviceInfo: ",
      "Unable to invoke registerService method",
      "No registerService method",
      "unregisterService",
      "unregistered serviceInfo: ",
      "Unable to invoke unregisterService method",
      "No unregisterService method",
      "javax.jmdns.JmDNS",
      "javax.jmdns.ServiceInfo",
      "JmDNS or serviceInfo class not found",
      "doTileDrops",
      "[Crash Handler] Sent Post",
      "CheatBreaker Client Version: ",
      "\n\n",
      "= [ StackTrace ] =\n",
      "= [ User Info ] =\n",
      "Username: ",
      "UUID: ",
      "= [ Options.txt ] =\n",
      "key_",
      "soundCategory",
      "\n= [ OptionsOF.txt ] =\n",
      "ofAnimated",
      "Unknown",
      "label",
      "Global Settings",
      " options",
      "OpenGlVersion",
      "OpenGlRenderer",
      "OpenGlVendor",
      "CpuCount",
      "Your client has crashed. \n\nPlease use the following code (also copied to your clipboard) when submitting a bug report: ",
      "Something went wrong (Closing in 5 seconds)",
      "Repair",
      "cause",
      "javaSocket",
      "Can only changed before channel was registered",
      "A non-root user can't receive a broadcast packet if the socket is not bound to a wildcard address; setting the SO_BROADCAST flag anyway as requested on the socket which is bound to ",
      "shape",
      "Saddle",
      "mob.pig.say",
      "mob.pig.death",
      "mob.pig.step",
      "ANTIALIASING",
      "of.options.shaders.ANTIALIASING",
      "antialiasingLevel",
      "NORMAL_MAP",
      "of.options.shaders.NORMAL_MAP",
      "normalMapEnabled",
      "SPECULAR_MAP",
      "of.options.shaders.SPECULAR_MAP",
      "specularMapEnabled",
      "RENDER_RES_MUL",
      "of.options.shaders.RENDER_RES_MUL",
      "renderResMul",
      "1.0",
      "SHADOW_RES_MUL",
      "of.options.shaders.SHADOW_RES_MUL",
      "shadowResMul",
      "HAND_DEPTH_MUL",
      "of.options.shaders.HAND_DEPTH_MUL",
      "handDepthMul",
      "0.125",
      "CLOUD_SHADOW",
      "of.options.shaders.CLOUD_SHADOW",
      "cloudShadow",
      "OLD_HAND_LIGHT",
      "of.options.shaders.OLD_HAND_LIGHT",
      "oldHandLight",
      "default",
      "OLD_LIGHTING",
      "of.options.shaders.OLD_LIGHTING",
      "oldLighting",
      "SHADER_PACK",
      "of.options.shaders.SHADER_PACK",
      "shaderPack",
      "TWEAK_BLOCK_DAMAGE",
      "of.options.shaders.TWEAK_BLOCK_DAMAGE",
      "tweakBlockDamage",
      "SHADOW_CLIP_FRUSTRUM",
      "of.options.shaders.SHADOW_CLIP_FRUSTRUM",
      "shadowClipFrustrum",
      "TEX_MIN_FIL_B",
      "of.options.shaders.TEX_MIN_FIL_B",
      "TexMinFilB",
      "TEX_MIN_FIL_N",
      "of.options.shaders.TEX_MIN_FIL_N",
      "TexMinFilN",
      "TEX_MIN_FIL_S",
      "of.options.shaders.TEX_MIN_FIL_S",
      "TexMinFilS",
      "TEX_MAG_FIL_B",
      "of.options.shaders.TEX_MAG_FIL_B",
      "TexMagFilB",
      "TEX_MAG_FIL_N",
      "of.options.shaders.TEX_MAG_FIL_N",
      "TexMagFilN",
      "TEX_MAG_FIL_S",
      "of.options.shaders.TEX_MAG_FIL_S",
      "TexMagFilS",
      "Use NearestAttackableTargetGoal.class for PathfinerMob mobs!",
      "witch",
      "mole",
      "hat",
      "arms",
      "left_leg",
      "right_leg",
      "nose",
      "START_SNEAKING",
      "STOP_SNEAKING",
      "STOP_SLEEPING",
      "START_SPRINTING",
      "STOP_SPRINTING",
      "RIDING_JUMP",
      "OPEN_INVENTORY",
      "> ",
      " <",
      "item.flowerPot.name",
      "legacy_data",
      "contents",
      "next",
      "boat",
      "back",
      "front",
      "Field not found: RenderBoat.modelBoat",
      "junixsocket-native-2.0.4",
      "java.io.tmpdir",
      "os.arch",
      "i386-Linux",
      "i386-Linux-ecpc",
      "i386-Linux-gpp",
      "i386-Linux-icc",
      "i386-Linux-ecc",
      "i386-Linux-icpc",
      "i386-Linux-linker",
      "i386-Linux-gcc",
      "x86-Windows",
      "x86-Windows-linker",
      "x86-Windows-gpp",
      "x86-Windows-msvc",
      "x86-Windows-icl",
      "x86-Windows-gcc",
      "amd64-Linux",
      "amd64-Linux-gpp",
      "amd64-Linux-icpc",
      "amd64-Linux-gcc",
      "amd64-Linux-linker",
      "amd64-Windows",
      "amd64-Windows-gpp",
      "amd64-Windows-msvc",
      "amd64-Windows-icl",
      "amd64-Windows-linker",
      "amd64-Windows-gcc",
      "amd64-FreeBSD",
      "amd64-FreeBSD-gpp",
      "amd64-FreeBSD-gcc",
      "amd64-FreeBSD-linker",
      "ppc-MacOSX",
      "ppc-MacOSX-gpp",
      "ppc-MacOSX-linker",
      "ppc-MacOSX-gcc",
      "x86_64-MacOSX",
      "x86_64-MacOSX-icc",
      "x86_64-MacOSX-icpc",
      "x86_64-MacOSX-gpp",
      "x86_64-MacOSX-linker",
      "x86_64-MacOSX-gcc",
      "ppc-AIX",
      "ppc-AIX-gpp",
      "ppc-AIX-xlC",
      "ppc-AIX-gcc",
      "ppc-AIX-linker",
      "i386-FreeBSD",
      "i386-FreeBSD-gpp",
      "i386-FreeBSD-gcc",
      "i386-FreeBSD-linker",
      "sparc-SunOS",
      "sparc-SunOS-cc",
      "sparc-SunOS-CC",
      "sparc-SunOS-linker",
      "arm-Linux",
      "arm-Linux-gpp",
      "arm-Linux-linker",
      "arm-Linux-gcc",
      "x86-SunOS",
      "x86-SunOS-g++",
      "x86-SunOS-linker",
      "i386-MacOSX",
      "i386-MacOSX-gpp",
      "i386-MacOSX-gcc",
      "i386-MacOSX-linker",
      "Unhandled architecture/OS: ",
      "file",
      "../nar/",
      "-jni/lib/",
      "/jni/",
      "lib/",
      "Library '",
      "' not found!",
      "Multicast not supported",
      "Saturation",
      "10",
      "Displays your current food saturation level.",
      "Eum3 (Number HUD)",
      "squeek502 (AppleSkin)",
      "client/icons/mods/saturation.png",
      "#.",
      "%.",
      "%VALUE%",
      "Hide in Creative Mode",
      "Hide the mod in Creative mode.",
      "Color Based on Amount",
      "Make the text color be based off the amount of saturation levels you have.",
      "AppleSkin Options",
      "Show Saturation Overlay",
      "Shows the AppleSkin Saturation Overlay",
      "Show Food Values Overlay",
      "Shows the AppleSkin Food Values Overlay",
      "Show trailing zeros",
      "Show all trailing zeros.",
      "Decimals",
      "Change how many decimals the mod should display.",
      "Highest Amount Color",
      "The text color that will show when the saturation level is over 15.",
      "High Amount Color",
      "The text color that will show when the saturation level is between 11-15.",
      "Medium Amount Color",
      "The text color that will show when the saturation level is between 6-10.",
      "Low Amount Color",
      "The text color that will show when the saturation level is between 1-5.",
      "Empty Amount Color",
      "The text color that will show when the saturation level is empty.",
      "client/appleskin/icons.png",
      "Cancel",
      "I understand, continue",
      "Leaving competitive games may result in penalties.",
      "You may be suspended from competitive games if you continue leaving games!",
      "IDENTIFIER",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_:.",
      "NUMBER",
      "0123456789",
      "0123456789.",
      "OPERATOR",
      "+-*/%!&|<>=",
      "&|=",
      "COMMA",
      "BRACKET_OPEN",
      "BRACKET_CLOSE",
      "factory",
      "request",
      "charset",
      "Cannot create a Encoder if not a POST",
      "datas",
      "text/plain",
      "application/octet-stream",
      "Different array length",
      "Cannot add value once finalized",
      "\r\n--",
      "--",
      "Content-Type: text/plain; charset=",
      "Content-Disposition",
      "form-data",
      "; ",
      "multipart/mixed",
      "boundary",
      "\r\n\r\n",
      "attachment",
      "Content-Disposition: attachment; filename=\"",
      "Content-Type: ",
      "\r\nContent-Transfer-Encoding: ",
      "--\r\n",
      "Header already encoded",
      "Transfer-Encoding",
      "multipart/form-data",
      "application/x-www-form-urlencoded",
      "multipart/form-data; boundary=",
      "chunked",
      "&",
      "\\*",
      "%2A",
      "\\+",
      "%20",
      "%7E",
      "~",
      "textures/entity/endermite.png",
      "Couldn't load layered image",
      "box[",
      " -> ",
      "GMatrix0",
      "GMatrix1",
      "GMatrix2",
      "GMatrix3",
      "GMatrix4",
      "GMatrix5",
      "GMatrix6",
      "GMatrix7",
      "GMatrix8",
      "GMatrix9",
      "GMatrix28",
      "GMatrix10",
      "GMatrix11",
      "GMatrix12",
      "GMatrix13",
      "GMatrix14",
      "GMatrix15",
      "GMatrix16",
      "GMatrix17",
      " 0.0     ",
      "GMatrix18",
      "GMatrix25",
      "GMatrix26",
      "GMatrix19",
      "GMatrix27",
      "GMatrix20",
      "GMatrix21",
      "GMatrix22",
      "GMatrix24",
      "\ns =",
      "e =",
      "topr    =",
      "bottomr =",
      "cosr =",
      "sinr =",
      "\nm =",
      "\nv =",
      "\nt*m =",
      "\nm=",
      "\nu=",
      "\nt*m=",
      "\n m = \n",
      "0.0000 ",
      " \ns = ",
      " \ne = ",
      " \nu  = \n",
      " \nv  = \n",
      " \nm  = \n",
      " \n u.transpose*m*v.transpose  = \n",
      "achievement.openInventory",
      "openInventory",
      "achievement.mineWood",
      "mineWood",
      "achievement.buildWorkBench",
      "buildWorkBench",
      "achievement.buildPickaxe",
      "buildPickaxe",
      "achievement.buildFurnace",
      "buildFurnace",
      "achievement.acquireIron",
      "acquireIron",
      "achievement.buildHoe",
      "buildHoe",
      "achievement.makeBread",
      "makeBread",
      "achievement.bakeCake",
      "bakeCake",
      "achievement.buildBetterPickaxe",
      "buildBetterPickaxe",
      "achievement.cookFish",
      "cookFish",
      "achievement.onARail",
      "onARail",
      "achievement.buildSword",
      "buildSword",
      "achievement.killEnemy",
      "killEnemy",
      "achievement.killCow",
      "killCow",
      "achievement.flyPig",
      "flyPig",
      "achievement.snipeSkeleton",
      "snipeSkeleton",
      "achievement.diamonds",
      "diamonds",
      "achievement.diamondsToYou",
      "diamondsToYou",
      "achievement.portal",
      "portal",
      "achievement.ghast",
      "ghast",
      "achievement.blazeRod",
      "blazeRod",
      "achievement.potion",
      "potion",
      "achievement.theEnd",
      "theEnd",
      "achievement.theEnd2",
      "theEnd2",
      "achievement.enchantments",
      "enchantments",
      "achievement.overkill",
      "overkill",
      "achievement.bookcase",
      "bookcase",
      "achievement.breedCow",
      "breedCow",
      "achievement.spawnWither",
      "spawnWither",
      "achievement.killWither",
      "killWither",
      "achievement.fullBeacon",
      "fullBeacon",
      "achievement.exploreAllBiomes",
      "exploreAllBiomes",
      "achievement.overpowered",
      "overpowered",
      "WS403Responder",
      "://",
      "Decoder errorcode ",
      "uuid",
      "expiresOn",
      "entity.Villager.name",
      ".mcr",
      "Error",
      "Ok",
      "Center",
      "South",
      "FileName",
      "textures/particle/footprint.png",
      "log4j.dtd",
      "-//APACHE//DTD LOG4J 1.2//EN",
      "/org/apache/log4j/xml/log4j.dtd",
      "Could not find [log4j.dtd] using [",
      "] class loader, parsed without DTD.",
      "command",
      "textures/entity/steve.png",
      "pack.mcmeta",
      "Hitboxes"
   };
}
