package recovered.strings;

public class StringTable16 {
   public static String[] field_0000 = new String[]{
      "freeSweepAllocationThreshold: ",
      "Freed {} thread-local buffer(s) from thread: {}",
      "READ_COMMON_HEADER",
      "READ_DATA_FRAME",
      "READ_SYN_STREAM_FRAME",
      "READ_SYN_REPLY_FRAME",
      "READ_RST_STREAM_FRAME",
      "READ_SETTINGS_FRAME",
      "READ_SETTING",
      "READ_PING_FRAME",
      "READ_GOAWAY_FRAME",
      "READ_HEADERS_FRAME",
      "READ_WINDOW_UPDATE_FRAME",
      "READ_HEADER_BLOCK",
      "DISCARD_FRAME",
      "FRAME_ERROR",
      "Sort by this NDC: ",
      "Sort Log Records by NDC",
      "PopSize",
      "Radius",
      "Golems",
      "Stable",
      "MTick",
      "CX",
      "CY",
      "CZ",
      "ACX",
      "ACY",
      "ACZ",
      "Doors",
      "IDX",
      "IDZ",
      "TS",
      "header block contains too many headers",
      "header exceeds allowable length: ",
      "(Reflector) Field not found: ",
      "(Reflector) More than one match found for field: ",
      "length wider than 21-bit",
      "vines",
      "death.attack.generic",
      "death.fell.assist.item",
      "death.fell.assist",
      "death.fell.finish.item",
      "death.fell.finish",
      "death.fell.killer",
      "death.fell.accident.",
      " (Bryce)",
      "size",
      "FlatLevelSource",
      "minecraft:anvil",
      "head_skeleton",
      "Field not found: TileEntitySkullRenderer.humanoidHead",
      "textures/entity/bat.png",
      "SOCKS_CMD_RESPONSE_DECODER",
      "MENU",
      "minecraft:music.menu",
      "GAME",
      "minecraft:music.game",
      "minecraft:music.game.creative",
      "CREDITS",
      "minecraft:music.game.end.credits",
      "NETHER",
      "minecraft:music.game.nether",
      "END_BOSS",
      "minecraft:music.game.end.dragon",
      "minecraft:music.game.end",
      "This branch does not contain any changes.",
      "\"?\"",
      "dev",
      "options.modelPart.",
      "CAPE",
      "JACKET",
      "jacket",
      "LEFT_SLEEVE",
      "left_sleeve",
      "RIGHT_SLEEVE",
      "right_sleeve",
      "LEFT_PANTS_LEG",
      "left_pants_leg",
      "RIGHT_PANTS_LEG",
      "right_pants_leg",
      "HAT",
      "commands.scoreboard.usage",
      "objectives",
      "commands.scoreboard.objectives.usage",
      "commands.scoreboard.objectives.add.usage",
      "commands.scoreboard.objectives.remove.usage",
      "setdisplay",
      "commands.scoreboard.objectives.setdisplay.usage",
      "commands.scoreboard.players.usage",
      "commands.scoreboard.players.list.usage",
      "commands.scoreboard.players.add.usage",
      "commands.scoreboard.players.remove.usage",
      "commands.scoreboard.players.set.usage",
      "commands.scoreboard.players.reset.usage",
      "commands.scoreboard.players.enable.usage",
      "commands.scoreboard.players.test.usage",
      "operation",
      "commands.scoreboard.players.operation.usage",
      "commands.scoreboard.teams.usage",
      "commands.scoreboard.teams.list.usage",
      "commands.scoreboard.teams.add.usage",
      "commands.scoreboard.teams.remove.usage",
      "empty",
      "commands.scoreboard.teams.empty.usage",
      "join",
      "commands.scoreboard.teams.join.usage",
      "leave",
      "commands.scoreboard.teams.leave.usage",
      "commands.scoreboard.teams.option.usage",
      "commands.scoreboard.noMultiWildcard",
      "commands.scoreboard.allMatchesFailed",
      "commands.scoreboard.objectiveNotFound",
      "commands.scoreboard.objectiveReadOnly",
      "commands.scoreboard.teamNotFound",
      "commands.scoreboard.objectives.add.wrongType",
      "commands.scoreboard.objectives.add.alreadyExists",
      "commands.scoreboard.objectives.add.tooLong",
      "commands.scoreboard.objectives.add.displayTooLong",
      "commands.scoreboard.objectives.add.success",
      "commands.scoreboard.teams.add.alreadyExists",
      "commands.scoreboard.teams.add.tooLong",
      "commands.scoreboard.teams.add.displayTooLong",
      "commands.scoreboard.teams.add.success",
      "friendlyfire",
      "seeFriendlyInvisibles",
      "nametagVisibility",
      "deathMessageVisibility",
      "commands.scoreboard.teams.option.noValue",
      "commands.scoreboard.teams.option.success",
      "commands.scoreboard.teams.remove.success",
      "commands.scoreboard.teams.list.player.empty",
      "commands.scoreboard.teams.list.player.count",
      "commands.scoreboard.teams.list.empty",
      "commands.scoreboard.teams.list.count",
      "commands.scoreboard.teams.list.entry",
      "commands.scoreboard.teams.join.success",
      "commands.scoreboard.teams.join.failure",
      "commands.scoreboard.teams.leave.success",
      "commands.scoreboard.teams.leave.failure",
      "commands.scoreboard.teams.empty.alreadyEmpty",
      "commands.scoreboard.teams.empty.success",
      "commands.scoreboard.objectives.remove.success",
      "commands.scoreboard.objectives.list.empty",
      "commands.scoreboard.objectives.list.count",
      "commands.scoreboard.objectives.list.entry",
      "commands.scoreboard.objectives.setdisplay.invalidSlot",
      "commands.scoreboard.objectives.setdisplay.successSet",
      "commands.scoreboard.objectives.setdisplay.successCleared",
      "commands.scoreboard.players.list.player.empty",
      "commands.scoreboard.players.list.player.count",
      "commands.scoreboard.players.list.player.entry",
      "commands.scoreboard.players.list.empty",
      "commands.scoreboard.players.list.count",
      "commands.scoreboard.players.name.tooLong",
      "commands.scoreboard.players.set.tagMismatch",
      "commands.scoreboard.players.set.tagError",
      "commands.scoreboard.players.set.success",
      "commands.scoreboard.players.resetscore.success",
      "commands.scoreboard.players.reset.success",
      "commands.scoreboard.players.enable.noTrigger",
      "commands.scoreboard.players.enable.success",
      "commands.scoreboard.players.test.notFound",
      "commands.scoreboard.players.test.success",
      "commands.scoreboard.players.test.failed",
      "commands.scoreboard.players.operation.notFound",
      "+=",
      "-=",
      "*=",
      "/=",
      "%=",
      "><",
      "commands.scoreboard.players.operation.invalidOperation",
      "commands.scoreboard.players.operation.success",
      "Accessed Items before Bootstrap!",
      "fish",
      "cooked_fish",
      "dye",
      "spawn_egg",
      "enchanted_book",
      "STRING_ARRAY",
      "BOOLEAN",
      "ARRAYLIST",
      "FILE",
      "About confidential builds",
      "PLEASE READ THIS SECTION CAREFULLY.\n\nYou are currently using a private CheatBreaker build. Private builds have certain restrictions in place which are described below:\n\nBranch ",
      " restrictions:\n- Disclosure to any user below the lowest authorized ranking is prohibited. This includes but is not limited to new changes inside the build such as new features, fixes, and improvements.\n- Recording/streaming on this build is not recommended, but allowed to a certain extent. If any capturing software is showing this build, do not show any changes from this build that differ from the master branch. If, however, you are recording to submit a bug report, these restrictions do not apply.\n\nManagement reserves the rights to restrict your access to future builds if you violate any restrictions applied.",
      "dateFormat cannot be null",
      "expiration must be non-negative",
      "654",
      "987",
      "ABC",
      "000",
      "WebSocket version 13 server handshake key: {}, response: {}",
      "HALF_FLOAT",
      "UNSIGNED_BYTE",
      "UNSIGNED_BYTE_3_3_2",
      "UNSIGNED_BYTE_2_3_3_REV",
      "UNSIGNED_SHORT",
      "UNSIGNED_SHORT_5_6_5",
      "UNSIGNED_SHORT_5_6_5_REV",
      "UNSIGNED_SHORT_4_4_4_4",
      "UNSIGNED_SHORT_4_4_4_4_REV",
      "UNSIGNED_SHORT_5_5_5_1",
      "UNSIGNED_SHORT_1_5_5_5_REV",
      "UNSIGNED_INT",
      "UNSIGNED_INT_8_8_8_8",
      "UNSIGNED_INT_8_8_8_8_REV",
      "UNSIGNED_INT_10_10_10_2",
      "UNSIGNED_INT_2_10_10_10_REV",
      "/cb debug",
      " Build (",
      "Debug: ",
      "/cb credits",
      "/cb aero",
      "Aero Client is BACK!",
      "/cb emote",
      "Usage: /cb emote <id>",
      " (ID: ",
      "Emotes: ",
      "Doing emote: ",
      "Invalid Emote ID: ",
      "minecraft:container",
      "minecraft:furnace",
      "portal.trigger",
      "Unsupported mob type for TemptGoal",
      "Profile Name: ",
      "Name must be at least 3 characters long.",
      "That name is already in use.",
      "([a-zA-Z0-9-_ \\]\\[]+)",
      "Illegal characters in name.",
      "Could not save profile.",
      "Nametag",
      "$",
      "`",
      "Show Sub Icons",
      "Shown own Nametag",
      "Show Nametags when GUI is hidden",
      "Displays the username above players.",
      "Removed selected resource pack {} because it's no longer compatible",
      "Unable to recreate resourcepack folder, it exists but is not a directory: ",
      "Unable to create resourcepack folder: ",
      "^[a-f0-9]{40}$",
      "File ",
      " had wrong hash (expected ",
      ", found ",
      "). Deleting it.",
      " couldn't be hashed. Deleting it.",
      "Deleting old server resource pack ",
      "Last-good-stream-ID cannot be negative: ",
      "--> Last-good-stream-ID = ",
      ", func: ",
      ", ref: ",
      "ctx",
      "oooooo",
      "Oooooo",
      "oOoooo",
      "ooOooo",
      "oooOoo",
      "ooooOo",
      "oooooO",
      "-url",
      "Usage: jlp [-url] <filename>",
      " e.g. : java javazoom.jl.player.jlp localfile.mp3",
      "        java javazoom.jl.player.jlp -url http://www.server.com/remotefile.mp3",
      "        java javazoom.jl.player.jlp -url http://www.shoutcastserver.com:8000",
      "playing ",
      "Problem playing file ",
      "File Location",
      "netty-tcnative",
      "provided",
      "Failed to load netty-tcnative; ",
      " will be unavailable.",
      "Warning: Clientside chunk ticking took {} ms",
      "MultiplayerChunkCache: ",
      "Invalid animated texture length: ",
      ", frameWidth: ",
      ", frameHeight: ",
      "tile.0",
      "duration.",
      "skip",
      "textures/entity/wolf/wolf_collar.png",
      "->",
      "(Unknown file) ",
      "(Unknown file)",
      "Converting... ",
      "timeout.deadline (%d) > deadline (%d)",
      "Connection lost",
      "No friends",
      "T-Pose",
      "commands.generic.entity.notFound",
      "textures/gui/options_background.png",
      "textures/gui/container/stats_icons.png",
      "READY",
      "READING_PREAMBLE",
      "READING_TAG",
      "READING_LITERAL",
      "READING_COPY",
      "container.enchant.clue",
      "Level Requirement: ",
      "container.enchant.lapis.one",
      "container.enchant.lapis.many",
      "container.enchant.level.one",
      "container.enchant.level.many",
      "textures/gui/container/enchanting_table.png",
      "Thread death watcher task raised an exception:",
      "Potion Effects",
      "Component Options",
      "Icon",
      "Effect Name",
      "Effect Name Text",
      "Effect Amplifier Text",
      "Show Roman Numerals",
      "Show Level 1",
      "Max Roman Numeral",
      "Effect Spacing",
      "Sorting Options",
      "Sorting Method",
      "Alphabetical",
      "Reverse Sorting",
      "Blink Options",
      "Blink",
      "Make Effect Name Text Blink",
      "Make Effect Icon Blink",
      "Make Duration Text Blink",
      "Blink Duration",
      "Blink Speed",
      "Excluding Options",
      "Exclude Permanent Effects",
      "Exclude Set Duration",
      "Exclude all active effects above a set duration.",
      "Effects Above",
      "Effects Below",
      "Effects At",
      "Effects Not At",
      "Excluded Duration",
      "The duration effects are excluded",
      "Exclude Set Amplifier",
      "Exclude all active effects below a set amplifier.",
      "Excluded Amplifier",
      "Exclude Helpful/Harmful Effects",
      "Only Helpful",
      "Only Harmful",
      "Exclude Specific Effects",
      "Override Name Color With Pack Format",
      "Color Name Based On",
      "Effect",
      "Color Duration Based On",
      "Color Type",
      "Potion Colors",
      "Color Codes",
      "Good/Bad",
      "Vibrant",
      "Name Color",
      "Duration Color",
      "client/icons/mods/speed_icon.png",
      "Displays your active potion effects.",
      "Potion Status",
      "Status Effects",
      "IIIII",
      "V",
      "IIII",
      "IV",
      "VV",
      "VIV",
      "IX",
      "XXXXX",
      "XXXX",
      "XL",
      "LL",
      "C",
      "LXL",
      "XC",
      "CCCCC",
      "D",
      "CCCC",
      "DD",
      "DCD",
      "CM",
      "(?i)§[0-9A-F]",
      "AsyncAppender-Dispatcher-",
      "Got an InterruptedException while waiting for the dispatcher to finish.",
      "Min value of ",
      " must be 0 or greater",
      "Max value of ",
      " must be greater than min (",
      "[WS] Key was smaller than nothing!  Weird key!",
      "START",
      "Attribute is already registered!",
      "portal.portal",
      "shrub",
      "flower",
      "rose",
      "stainedGlassPane",
      "shovelIron",
      "pickaxeIron",
      "hatchetIron",
      "flintAndSteel",
      "ingotIron",
      "ingotGold",
      "swordIron",
      "swordWood",
      "shovelWood",
      "pickaxeWood",
      "hatchetWood",
      "swordStone",
      "shovelStone",
      "pickaxeStone",
      "hatchetStone",
      "swordDiamond",
      "shovelDiamond",
      "pickaxeDiamond",
      "hatchetDiamond",
      "mushroomStew",
      "swordGold",
      "shovelGold",
      "pickaxeGold",
      "hatchetGold",
      "sulphur",
      "+14&13-13",
      "hoeWood",
      "hoeStone",
      "hoeIron",
      "hoeDiamond",
      "hoeGold",
      "seeds",
      "helmetCloth",
      "chestplateCloth",
      "leggingsCloth",
      "bootsCloth",
      "helmetChain",
      "chestplateChain",
      "leggingsChain",
      "bootsChain",
      "helmetIron",
      "chestplateIron",
      "leggingsIron",
      "bootsIron",
      "helmetDiamond",
      "chestplateDiamond",
      "leggingsDiamond",
      "bootsDiamond",
      "helmetGold",
      "chestplateGold",
      "leggingsGold",
      "bootsGold",
      "porkchopRaw",
      "porkchopCooked",
      "appleGold",
      "bucketWater",
      "bucketLava",
      "-5+6-7",
      "milk",
      "slimeball",
      "minecartChest",
      "minecartFurnace",
      "fishingRod",
      "yellowDust",
      "+5-6-7",
      "dyePowder",
      "-0+1-2-3&4-4+13",
      "seeds_pumpkin",
      "seeds_melon",
      "beefRaw",
      "beefCooked",
      "chickenRaw",
      "chickenCooked",
      "rottenFlesh",
      "enderPearl",
      "ghastTear",
      "+0-1-2-3&4-4+13",
      "goldNugget",
      "netherStalkSeeds",
      "+4",
      "glassBottle",
      "spiderEye",
      "-0-1+2-3&4-4+13",
      "fermentedSpiderEye",
      "-0+3-4+13",
      "blazePowder",
      "+0-1-2+3&4-4+13",
      "magmaCream",
      "+0+1-2-3&4-4+13",
      "eyeOfEnder",
      "speckledMelon",
      "+0-1+2-3&4-4+13",
      "monsterPlacer",
      "expBottle",
      "writingBook",
      "writtenBook",
      "potatoBaked",
      "potatoPoisonous",
      "emptyMap",
      "carrotGolden",
      "-0+1+2-3+13&4-4",
      "carrotOnAStick",
      "netherStar",
      "pumpkinPie",
      "fireworksCharge",
      "enchantedBook",
      "minecartTnt",
      "minecartHopper",
      "prismarineShard",
      "prismarineCrystals",
      "rabbitRaw",
      "rabbitCooked",
      "rabbitStew",
      "rabbitFoot",
      "+0+1-2+3&4-4+13",
      "rabbitHide",
      "armorStand",
      "horsearmormetal",
      "horsearmorgold",
      "horsearmordiamond",
      "leash",
      "nameTag",
      "minecartCommandBlock",
      "muttonRaw",
      "muttonCooked",
      "cat",
      "chirp",
      "mall",
      "mellohi",
      "stal",
      "strad",
      "ward",
      "11",
      "wait",
      "CB3F55D3-645C-4F38-A497-9C13A33DB5CF",
      "Forge dummy class",
      "sessionReceiveWindowSize",
      "invalid PING ID: ",
      "Stream closed",
      "cleaner",
      "java.nio.ByteBuffer.cleaner(): {}",
      "İNFO",
      " km",
      " m",
      " cm",
      "HTTP header is larger than ",
      "This MBean acts as a management facade for log4j layouts.",
      "LayoutDynamicMBean(): Constructs a LayoutDynamicMBean instance",
      "activateOptions(): add an layout",
      "----name=",
      ", mu=",
      "org.apache.log4j.jmx.LayoutDynamicMBean",
      "Lazy NDC removal for thread [",
      "] (",
      "decayable",
      "check_decay",
      " y",
      " d",
      " h",
      " s",
      "CustomDisplayTile",
      "DisplayData",
      "DisplayTile",
      "DisplayOffset",
      "xx",
      "Couldn't open file",
      "resourcePack.title",
      "testfor",
      "commands.testfor.usage",
      "commands.testfor.tagError",
      "commands.testfor.failure",
      "commands.testfor.success",
      "[WS NetHandler] (OUT) id: ",
      " Name: ",
      "[WS NetHandler] (IN) id: ",
      "Error from: ",
      "Connection established",
      " says:",
      "Friend Request",
      "Request has been sent.",
      " wants to be your friend.",
      "result",
      "Connected",
      "Welcome, ",
      "emote",
      "dragon_wings",
      "Connection closed: ",
      ") - ",
      "Invalid Credentials",
      "Please login to connect to the player assets server.",
      "Authentication Error",
      "Please Login to Connect to the Assets Server",
      "A Unknown Error Happened when Connecting to the Assets Server.",
      "profiles.txt",
      "################################",
      "# MC_Client: PROFILES",
      "item.comparator.name",
      "mode",
      "Logger",
      "container.hopper",
      "line length was zero. If this happens please contribute unit test that provokes this failure to the project!",
      "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~",
      "\"'‘’“”?./!,;:_",
      "Dispatcher-",
      "Select a team to teleport to",
      "Teleport to team member",
      "Classloader",
      "Failed to open a server socket.",
      "xp",
      "commands.xp.usage",
      "commands.xp.success.negative.levels",
      "commands.xp.success.levels",
      "commands.xp.failure.widthdrawXp",
      "commands.xp.success",
      "EMPTY",
      "OAK_SAPLING",
      "SPRUCE_SAPLING",
      "BIRCH_SAPLING",
      "JUNGLE_SAPLING",
      "ACACIA_SAPLING",
      "DARK_OAK_SAPLING",
      "MUSHROOM_RED",
      "mushroom_red",
      "MUSHROOM_BROWN",
      "mushroom_brown",
      "DEAD_BUSH",
      "FERN",
      "CACTUS",
      "blocks/grass_top",
      "blocks/grass_side",
      "blocks/mycelium_top",
      "blocks/dirt_podzol_top",
      "blocks/snow",
      "optifine/bettergrass.properties",
      "BetterGrass: Parsing default configuration ",
      "BetterGrass: Parsing configuration ",
      "grass.snow",
      "mycelium.snow",
      "podzol.snow",
      "grass.multilayer",
      "texture.grass",
      "texture.grass_side",
      "texture.mycelium",
      "texture.podzol",
      "texture.snow",
      "Error reading: ",
      "BetterGrass texture not found: ",
      "tentacle9",
      " packet ",
      " is already known to ID ",
      "HANDSHAKING",
      "STATUS",
      "LOGIN",
      "Invalid protocol ID ",
      " is already assigned to protocol ",
      " - can't reassign to ",
      " fails instantiation checks! ",
      "thirdperson",
      "firstperson",
      "gui",
      "ground",
      "Log4j",
      "Could not register event source.",
      "ia64",
      "x86",
      "NTEventLogAppender.",
      "NTEventLogAppender",
      "OMB",
      "OMCR",
      "OMDXR",
      "OMDXYR",
      "OMDYR",
      "OMDYZR",
      "OMDZR",
      "OMEntry",
      "OMPenthouse",
      "OMSimple",
      "OMSimpleT",
      "head1",
      "head2",
      "head3",
      "Running...",
      "Stopped",
      "Finished: ",
      " seconds",
      "achievement.get",
      "playerGameType",
      "Ticking player",
      "Player being ticked",
      "showDeathMessages",
      "container.isLocked",
      "minecraft:villager",
      "MC|TrList",
      "MC|BOpen",
      "help",
      "Entrances",
      "ConnectedTextures",
      "matchBlocks",
      "metadata",
      "matchTiles",
      "tiles",
      "faces",
      "biomes",
      "heights",
      "minHeight",
      "maxHeight",
      "renderPass",
      "innerSeams",
      "weights",
      "randomLoops",
      "symmetry",
      "linked",
      "connectBlocks",
      "connectTiles",
      "tintIndex",
      "tintBlock",
      "ctm.",
      "Invalid CTM tile index: ",
      "Invalid CTM index: ",
      "opposite",
      "Unknown symmetry: ",
      "material",
      "Unknown connect: ",
      "ctm",
      "ctm_compact",
      "random",
      "repeat",
      "horizontal+vertical",
      "h+v",
      "vertical+horizontal",
      "v+h",
      "overlay_fixed",
      "overlay_random",
      "overlay_repeat",
      "overlay_ctm",
      "No matchBlocks or matchTiles specified: ",
      "No method: ",
      "Invalid connect in: ",
      "Render pass not supported: ",
      "Invalid faces in: ",
      "Invalid symmetry in: ",
      "No tiles specified: ",
      "0-11 16-27 32-43 48-58",
      "Invalid tiles, must be at least 47: ",
      "0-4",
      "Invalid tiles, must be at least 5: ",
      "0-16",
      "Invalid tiles, must be at least 17: ",
      "Invalid overlay layer: ",
      "12-15",
      "Invalid tiles, must be exactly 4: ",
      "No tiles defined for vertical: ",
      "No tiles defined for horizontal+vertical: ",
      "Invalid tiles, must be exactly 7: ",
      "No tiles defined for vertical+horizontal: ",
      "More weights defined than tiles, trimming weights: ",
      "Less weights defined than tiles, expanding weights: ",
      "Invalid randomLoops: ",
      "Tiles not defined: ",
      "Invalid width: ",
      "Invalid height: ",
      "Number of tiles does not equal width x height: ",
      "Number of tiles should be 1 for method: fixed.",
      "66",
      "Invalid tiles, must be exactly 1: ",
      "<skip>.png",
      "<default>.png",
      "CTM name: ",
      ", basePath: ",
      ", matchBlocks: ",
      ", matchTiles: ",
      "That name is already taken.",
      "container.enderchest",
      ".spriteSingle",
      "Unable to load miplevel: %d, image is size: %dx%d, expected %dx%d",
      "broken aspect ratio and not an animation",
      "invalid frameindex ",
      "minecraft:blocks/leaves_",
      "Generating mipmaps for frame",
      "Frame being iterated",
      "Frame index",
      "Frame sizes",
      "TextureAtlasSprite{name='",
      ", frameCount=",
      ", rotated=",
      ", x=",
      ", y=",
      ", u0=",
      ", u1=",
      ", v0=",
      ", v1=",
      "_n",
      "_s",
      "builtin/clock",
      "builtin/compass",
      "The total length of the specified arrays is too big.",
      "The total length of the specified buffers is too big.",
      "inconsistent byte order",
      "Sublist is not linked, from: ",
      ", to: ",
      "Node has different parent, node: ",
      ", this: ",
      "saves",
      "Starting integrated minecraft server version 1.9",
      "Generating keypair",
      "Saving and pausing game...",
      "Changing view distance to {}, from {}",
      "Changing difficulty to {}, from {}",
      "Locking difficulty to {}",
      "Is Modded",
      "snooper_partner",
      "Started on ",
      "Parent can only be boolean.",
      "item.diode.name",
      "locked",
      "delay",
      "pos: ",
      ", frameIndex: ",
      "Pack Display",
      "(?i)§[1-69A-E]",
      "Displays your active Resource Pack(s).",
      "canelex",
      "Rotate",
      "Top-Bottom",
      "Bottom-Top",
      "Randomized",
      "Bottom",
      "Pack",
      "Pack Order",
      "Top",
      "Rotation Order",
      "Rotation Interval",
      "Remove zip string",
      "Removes the \".zip\" part of a pack name if the file is in a zip.",
      "Remove prefixes",
      "Removes ! and # prefixes from a pack.",
      "Strip Color Formatting",
      "Remove all color formatting so you can set your own color.",
      "Not Neutral",
      "IPv4",
      "IPv6",
      "over ",
      "frame length (",
      ") exceeds the allowed maximum (",
      "item.banner.white.name",
      "textures/entity/lead_knot.png",
      "Error occured while converting date.",
      "villager",
      "TeDP",
      "TeJP",
      "TeSH",
      "ExplosionPower",
      "chest_large",
      "Field not found: TileEntityChestRenderer.largeChest",
      "client/logo_108.png",
      "headwear",
      "shade",
      "Expected shade to be a Boolean",
      "origin",
      "rescale",
      "angle",
      " found, only -45/-22.5/0/22.5/45 allowed",
      "Invalid rotation axis: ",
      "Expected between 1 and 6 unique faces, got 0",
      "Unknown facing: ",
      "'to' specifier exceeds the allowed boundaries: ",
      "'from' specifier exceeds the allowed boundaries: ",
      "commands.generic.notFound",
      "commands.generic.permission",
      "commands.generic.usage",
      "commands.generic.exception",
      "Couldn't process command: '",
      "head_humanoid",
      "fill",
      "commands.fill.usage",
      "commands.fill.tooManyBlocks",
      "commands.fill.outOfWorld",
      "commands.fill.tagError",
      "outline",
      "hollow",
      "destroy",
      "keep",
      "commands.fill.failed",
      "commands.fill.success",
      "Controls",
      "controls.resetAll",
      "controls.title",
      "lightMap",
      "shaders/post/creeper.json",
      "shaders/post/spider.json",
      "shaders/post/invert.json",
      "pick",
      "lightTex",
      "mouse",
      "Rendering screen",
      "Screen render details",
      "Screen name",
      "Mouse location",
      "Screen size",
      "frustum",
      "sky",
      "prepareterrain",
      "terrain_setup",
      "updatechunks",
      "terrain",
      "finish",
      "destroyProgress",
      "litParticles",
      "aboveClouds",
      "forge_render_last",
      "ambient.weather.rain",
      "HD Ultra",
      "Light",
      "of.message.newVersion",
      "§n",
      "https://optifine.net/downloads",
      "of.message.java64Bit",
      "CheckGlErrorFrameFinish",
      "Happy birthday, OptiFine!",
      "Happy birthday, sp614x!",
      "shaders/post/fxaa_of_",
      "x.json",
      "of.message.loadingVisibleChunks",
      "Loading visible chunks",
      "Chunks loaded: ",
      "Finished loading visible chunks",
      "textures/environment/rain.png",
      "textures/environment/snow.png",
      "shaders/post/notch.json",
      "shaders/post/fxaa.json",
      "shaders/post/art.json",
      "shaders/post/bumpy.json",
      "shaders/post/blobs2.json",
      "shaders/post/pencil.json",
      "shaders/post/color_convolve.json",
      "shaders/post/deconverge.json",
      "shaders/post/flip.json",
      "shaders/post/ntsc.json",
      "shaders/post/outline.json",
      "shaders/post/phosphor.json",
      "shaders/post/scan_pincushion.json",
      "shaders/post/sobel.json",
      "shaders/post/bits.json",
      "shaders/post/desaturate.json",
      "shaders/post/green.json",
      "shaders/post/blur.json",
      "shaders/post/wobble.json",
      "shaders/post/blobs.json",
      "shaders/post/antialias.json",
      "shaders/post/animblur.json",
      "shaders/post/motionblur.json",
      "shaders/post/lunar_motionblur.json",
      "save-off",
      "commands.save-off.usage",
      "commands.save.disabled",
      "commands.save-off.alreadyOff",
      "mob.enderdragon.wings",
      "mob.enderdragon.growl",
      "mob.enderdragon.hit",
      "SKIP_CONTROL_CHARS",
      "READ_INITIAL",
      "READ_HEADER",
      "READ_VARIABLE_LENGTH_CONTENT",
      "READ_FIXED_LENGTH_CONTENT",
      "READ_CHUNK_SIZE",
      "READ_CHUNKED_CONTENT",
      "READ_CHUNK_DELIMITER",
      "READ_CHUNK_FOOTER",
      "BAD_MESSAGE",
      "UPGRADED",
      " task: ",
      "WebSocket version 13 client handshake key: {}, expected response: {}",
      "load file called",
      "Need to load a file",
      "loading the contents of ",
      "Loaded ",
      " events.",
      "caught an exception loading the file",
      "Error parsing file - ",
      "<?xml version=\"1.0\" standalone=\"yes\"?>\n",
      "<!DOCTYPE log4j:eventSet ",
      "[<!ENTITY data SYSTEM \"file:///",
      "\">]>\n",
      "<log4j:eventSet xmlns:log4j=\"Claira\">\n",
      "&data;\n",
      "</log4j:eventSet>\n",
      "org.apache.log4j.chainsaw.LoadXMLAction",
      "ScoreComponent{name='",
      "objective='",
      "increment: ",
      "decrement: ",
      "refCnt",
      "group-0x",
      "matcher",
      "(name: ",
      ", size: ",
      "invalid character in name",
      "PUT",
      "PATCH",
      "DELETE",
      "Wrong array length: ",
      ", array: ",
      "Weight",
      "Perspective",
      "Allows you to change how your perspective looks.",
      "Freelook",
      "Snaplook",
      "360 Perspective",
      "Drag to Look is disabled.\nDamage affects camera is enabled.",
      "Third Person Options",
      "Toggle Back Camera",
      "Make the back camera keybind toggled instead of held.",
      "Toggle Front Camera",
      "Make the front camera keybind toggled instead of held.",
      "Drag to Look Options",
      "Look View",
      "Change which perspective mode to use when toggling Drag to Look.",
      "Third",
      "Reverse",
      "First",
      "Toggle Drag to Look",
      "Make the Drag to Look keybind toggled instead of held.",
      "Pitch Lock",
      "Toggle the pitch axis limitation.",
      "Invert Pitch (Up and Down)",
      "Invert the rotation pitch when moving the camera.",
      "Invert Yaw (Left and Right)",
      "Invert the rotation yaw when moving the camera.",
      "View Bobbing Options",
      "Bob Screen"
   };
}
