package recovered.strings;

public class StringTable05 {
   public static String[] field_0000 = new String[]{
      "Projectile",
      "Exp Orb",
      "Shows an outline around an entity's hitbox.",
      "Mineshaft",
      "chance",
      "SPDY_3_1",
      "spdy/3.1",
      "HTTP_1_1",
      "http/1.1",
      "HTTP_1_0",
      "http/1.0",
      "CANARY",
      "//canary.discordapp.com/api",
      "PTB",
      "//ptb.discordapp.com/api",
      "STABLE",
      "//discordapp.com/api",
      "ANY",
      "System.out",
      "System.err",
      "] should be System.out or System.err.",
      "Using previously set target, System.out by default.",
      "length: ",
      "Too many bytes to be read - Needs ",
      ", maximum is ",
      "fieldSize cannot be a negative number",
      "fieldSize is too long! Length is ",
      ", but maximum is ",
      "snooper_count",
      "snooper_token",
      "server",
      "client",
      "ClearWater (",
      ") relighted ",
      " chunks",
      "Matrix3f0",
      "Matrix3f1",
      "Matrix3f3",
      "Matrix3f5",
      "Matrix3f6",
      "Matrix3f9",
      "Matrix3f12",
      "Matrix3f13",
      "decoderResult",
      " static",
      ") => ",
      " => ",
      "*** Exception outside of method ***",
      "Method deactivated: ",
      "*** IllegalArgumentException ***",
      "Method: ",
      "Object: ",
      "Parameter classes: ",
      "Parameters: ",
      "*** Exception outside of constructor ***",
      "Constructor deactivated: ",
      "Constructor: ",
      "[OptiFine] ",
      "*** Reflector Forge ***",
      "mods.betterfoliage.client.BetterFoliageClient",
      "net.minecraftforge.fml.common.asm.transformers.BlamingTransformer",
      "onCrash",
      "net.minecraftforge.event.world.ChunkWatchEvent$UnWatch",
      "net.minecraftforge.fml.relauncher.CoreModManager",
      "net.minecraftforge.common.DimensionManager",
      "createProviderFor",
      "getStaticDimensionIDs",
      "net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Pre",
      "net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Post",
      "net.minecraftforge.client.event.EntityViewRenderEvent$CameraSetup",
      "yaw",
      "roll",
      "net.minecraftforge.client.event.EntityViewRenderEvent$FogColors",
      "blue",
      "net.minecraftforge.fml.common.eventhandler.Event",
      "isCanceled",
      "net.minecraftforge.fml.common.eventhandler.EventBus",
      "post",
      "net.minecraftforge.fml.common.eventhandler.Event$Result",
      "DENY",
      "ALLOW",
      "DEFAULT",
      "net.minecraftforge.common.property.ExtendedBlockState",
      "net.minecraftforge.fml.client.FMLClientHandler",
      "instance",
      "handleLoadingScreen",
      "isLoading",
      "trackBrokenTexture",
      "trackMissingTexture",
      "net.minecraftforge.fml.common.FMLCommonHandler",
      "callFuture",
      "enhanceCrashReport",
      "getBrandings",
      "handleServerAboutToStart",
      "handleServerStarting",
      "getWaterColorMultiplier",
      "addDestroyEffects",
      "addHitEffects",
      "canCreatureSpawn",
      "canRenderInLayer",
      "doesSideBlockRendering",
      "getBedDirection",
      "getExtendedState",
      "getLightOpacity",
      "getLightValue",
      "hasTileEntity",
      "isAir",
      "isBed",
      "isBedFoot",
      "isSideSolid",
      "canRiderInteract",
      "captureDrops",
      "capturedDrops",
      "shouldRenderInPass",
      "shouldRiderSit",
      "net.minecraftforge.event.ForgeEventFactory",
      "canEntityDespawn",
      "canEntitySpawn",
      "doSpecialSpawn",
      "getMaxSpawnPackSize",
      "renderBlockOverlay",
      "renderFireOverlay",
      "renderWaterOverlay",
      "net.minecraftforge.common.ForgeHooks",
      "onLivingAttack",
      "onLivingDeath",
      "onLivingDrops",
      "onLivingFall",
      "onLivingHurt",
      "onLivingJump",
      "onLivingSetAttackTarget",
      "onLivingUpdate",
      "net.minecraftforge.client.ForgeHooksClient",
      "applyTransform",
      "dispatchRenderLast",
      "drawScreen",
      "fillNormal",
      "handleCameraTransforms",
      "getArmorModel",
      "getArmorTexture",
      "getFogDensity",
      "getFOVModifier",
      "getMatrix",
      "getOffsetFOV",
      "loadEntityShader",
      "onDrawBlockHighlight",
      "onFogRender",
      "onTextureStitchedPre",
      "onTextureStitchedPost",
      "orientBedCamera",
      "putQuadColor",
      "renderFirstPersonHand",
      "renderMainMenu",
      "setRenderLayer",
      "setRenderPass",
      "transform",
      "delegate",
      "getDurabilityForDisplay",
      "getModel",
      "onEntitySwing",
      "shouldCauseReequipAnimation",
      "showDurabilityBar",
      "net.minecraftforge.common.ForgeModContainer",
      "forgeLightPipelineEnabled",
      "isCurativeItem",
      "canRenderBreaking",
      "getRenderBoundingBox",
      "hasFastRenderer",
      "preDraw",
      "postDraw",
      "countEntities",
      "getPerWorldStorage",
      "getCloudRenderer",
      "getSkyRenderer",
      "getWeatherRenderer",
      "getSaveFolder",
      "net.minecraftforge.fml.client.GuiModList",
      "net.minecraftforge.client.model.IColoredBakedQuad",
      "net.minecraftforge.common.property.IExtendedBlockState",
      "getClean",
      "net.minecraftforge.client.model.IModel",
      "getTextures",
      "net.minecraftforge.client.IRenderHandler",
      "render",
      "net.minecraftforge.client.ItemModelMesherForge",
      "net.minecraft.launchwrapper.Launch",
      "blackboard",
      "net.minecraftforge.client.model.pipeline.LightUtil",
      "itemConsumer",
      "putBakedQuad",
      "renderQuadColor",
      "tessellator",
      "net.minecraftforge.fml.common.Loader",
      "getActiveModList",
      "net.minecraftforge.common.MinecraftForge",
      "EVENT_BUS",
      "net.minecraftforge.client.MinecraftForgeClient",
      "getRenderPass",
      "onRebuildChunk",
      "net.minecraftforge.fml.common.ModContainer",
      "getModId",
      "net.minecraftforge.client.model.ModelLoader",
      "stateModels",
      "onRegisterItems",
      "getInventoryVariant",
      "net.minecraftforge.client.model.ModelLoader$VanillaLoader",
      "loadModel",
      "net.minecraftforge.client.event.RenderBlockOverlayEvent$OverlayType",
      "net.minecraftforge.fml.client.registry.RenderingRegistry",
      "loadEntityRenderers",
      "net.minecraftforge.client.event.RenderItemInFrameEvent",
      "net.minecraftforge.client.event.RenderLivingEvent$Pre",
      "net.minecraftforge.client.event.RenderLivingEvent$Post",
      "net.minecraftforge.client.event.RenderLivingEvent$Specials$Pre",
      "net.minecraftforge.client.event.RenderLivingEvent$Specials$Post",
      "net.minecraftforge.fml.client.SplashProgress",
      "net.minecraftforge.event.world.WorldEvent$Load",
      "*** Reflector Vanilla ***",
      "EntityVillager.careerId",
      "EntityVillager.careerLevel",
      "optifine.OptiFineClassTransformer",
      "getOptiFineResource",
      "logo.gif",
      "junit.runner.BaseTestRunner",
      "sign.edit",
      "PlayerItem",
      "Unknown model type: ",
      "textureSize",
      "Missing texture size",
      "usePlayerTexture",
      "models",
      "Missing elements",
      "baseId",
      "BaseID not found: ",
      "Duplicate model ID: ",
      "leftArm",
      "rightArm",
      "leftLeg",
      "rightLeg",
      "cape",
      "Unknown attachModel: ",
      "ModelBox",
      "attachTo",
      "invertAxis",
      "translate",
      "rotate",
      "mirrorTexture",
      "u",
      "v",
      "boxes",
      "textureOffset",
      "Texture offset not specified",
      "coordinates",
      "Coordinates not specified",
      "sizeAdd",
      "sprites",
      "submodel",
      "submodels",
      "uvDown",
      "uvUp",
      "uvNorth",
      "uvSouth",
      "uvWest",
      "uvEast",
      "uvFront",
      "uvBack",
      "uvLeft",
      "uvRight",
      "javaChannel",
      "Loading http texture from local cache ({})",
      "Couldn't load skin ",
      "Texture Downloader #",
      "http://",
      "Couldn't download http texture: ",
      "Invalid uniform type for enum: ",
      ", uniform: ",
      "Unknown uniform type: ",
      "Invalid index2, parameter: ",
      ", index: ",
      "Invalid index1, parameter: ",
      "BIOME",
      "biome",
      "TEMPERATURE",
      "temperature",
      "RAINFALL",
      "rainfall",
      "HELD_ITEM_ID",
      "HELD_BLOCK_LIGHT_VALUE",
      "HELD_ITEM_ID2",
      "HELD_BLOCK_LIGHT_VALUE2",
      "WORLD_TIME",
      "WORLD_DAY",
      "MOON_PHASE",
      "FRAME_COUNTER",
      "FRAME_TIME",
      "FRAME_TIME_COUNTER",
      "SUN_ANGLE",
      "SHADOW_ANGLE",
      "RAIN_STRENGTH",
      "ASPECT_RATIO",
      "VIEW_WIDTH",
      "VIEW_HEIGHT",
      "NEAR",
      "FAR",
      "WETNESS",
      "EYE_ALTITUDE",
      "EYE_BRIGHTNESS",
      "TERRAIN_TEXTURE_SIZE",
      "TERRRAIN_ICON_SIZE",
      "IS_EYE_IN_WATER",
      "NIGHT_VISION",
      "BLINDNESS",
      "SCREEN_BRIGHTNESS",
      "HIDE_GUI",
      "CENTER_DEPT_SMOOTH",
      "ATLAS_SIZE",
      "CAMERA_POSITION",
      "PREVIOUS_CAMERA_POSITION",
      "SUN_POSITION",
      "MOON_POSITION",
      "SHADOW_LIGHT_POSITION",
      "UP_POSITION",
      "SKY_COLOR",
      "r",
      "g",
      "b",
      "GBUFFER_PROJECTION",
      "2",
      "3",
      "GBUFFER_PROJECTION_INVERSE",
      "GBUFFER_PREVIOUS_PROJECTION",
      "GBUFFER_MODEL_VIEW",
      "GBUFFER_MODEL_VIEW_INVERSE",
      "GBUFFER_PREVIOUS_MODEL_VIEW",
      "SHADOW_PROJECTION",
      "SHADOW_PROJECTION_INVERSE",
      "SHADOW_MODEL_VIEW",
      "SHADOW_MODEL_VIEW_INVERSE",
      "local:E",
      "empty id",
      "local:",
      "client/logo_42.png",
      "client/icons/globe-24.png",
      "OPTIONS",
      "CHANGELOG",
      "COSMETICS",
      "CheatBreaker (",
      "Unauthorized disclosure of this build in any manner may result in disciplinary action up to and including termination of an assignment.",
      "client/panorama/0.png",
      "client/panorama/1.png",
      "client/panorama/2.png",
      "client/panorama/3.png",
      "client/panorama/4.png",
      "client/panorama/5.png",
      "launcher_accounts.json",
      "minecraftProfile",
      "displayName",
      "username",
      "accessToken",
      "mojangClientToken",
      "CheatBreaker",
      "mojang",
      "authenticationDatabase",
      "profiles",
      "Updated accessToken and logged user in.",
      "maxContentLength must be a positive integer: ",
      "maxCumulationBufferComponents: ",
      " (expected: >= 2)",
      "decoder properties cannot be changed once the decoder is added to a pipeline.",
      "HTTP content length exceeded ",
      " bytes.",
      "Arial",
      "too many thread-local indexed variables",
      "Date",
      "DANDELION",
      "dandelion",
      "POPPY",
      "poppy",
      "BLUE_ORCHID",
      "blue_orchid",
      "blueOrchid",
      "ALLIUM",
      "allium",
      "HOUSTONIA",
      "houstonia",
      "RED_TULIP",
      "red_tulip",
      "tulipRed",
      "ORANGE_TULIP",
      "orange_tulip",
      "tulipOrange",
      "WHITE_TULIP",
      "white_tulip",
      "tulipWhite",
      "PINK_TULIP",
      "pink_tulip",
      "tulipPink",
      "OXEYE_DAISY",
      "oxeye_daisy",
      "oxeyeDaisy",
      "  ",
      "    ",
      "        ",
      "                ",
      "                                ",
      "Block Overlay",
      "General Options",
      "Outline",
      "OFF",
      "Overlay",
      "Line Width",
      "Gap",
      "Render without Depth",
      "Hide Plants",
      "Color Options",
      "Outline Color",
      "Outline 2 Color",
      "Overlay Color",
      "Overlay 2 Color",
      "client/icons/mods/overlay.png",
      "Replace the Vanilla outline with a customizable outline and overlay.",
      "aycy",
      "Duplicate packet class (",
      "), already used by ",
      "Duplicate packet ID (",
      "), already used by",
      "Key was smaller than nothing!  Weird key!",
      "goalSetup",
      "goalTick",
      "io.netty.allocator.type",
      "unpooled",
      "-Dio.netty.allocator.type: {}",
      "pooled",
      "-Dio.netty.allocator.type: unpooled (unknown: {})",
      "io.netty.threadLocalDirectBufferSize",
      "-Dio.netty.threadLocalDirectBufferSize: {}",
      "LOCKED",
      "LOCKED_HOVER",
      "LOCKED_DISABLED",
      "UNLOCKED",
      "UNLOCKED_HOVER",
      "UNLOCKED_DISABLED",
      "gui.toMenu",
      "Reconnect",
      "textures/gui/container/dispenser.png",
      "Hypixel Collection",
      "§m----------------------------------------------------Friend request from (?<name>.+)\\[ACCEPT\\] - \\[DENY\\] - \\[IGNORE\\].*",
      "BED DESTRUCTION > Your Bed .*",
      "You have been eliminated!",
      "Reward Summary",
      "Guild > (?<name>.+) joined\\..*",
      "Friend > (?<name>.+) joined\\..*",
      "Auto Command Options",
      "Auto Tip",
      "Auto Friend",
      "Auto Friend Mode",
      "Accept",
      "Deny",
      "Ignore",
      "Auto Friend Delay",
      "Auto Chat Options",
      "Auto GG",
      "Send GG Message Delay",
      "Auto GG String",
      "Auto GL",
      "Send GL Message Delay",
      "Auto GL String",
      "Auto WB",
      "Welcome Back Friends",
      "Welcome Back Guild Members",
      "Send WB Message Delay",
      "Auto WB String",
      "Welcome back %USER%!",
      "Chat Filter Options",
      "Hide GG",
      "Hide GL",
      "Bed Wars Options",
      "Hardcore Hearts",
      "Changes your hearts to show hardcore hearts when you lose your own bed.",
      "client/icons/mods/hypixel.png",
      "A collection of mods made for the Hypixel Network.",
      "2Pi (Auto GG, Auto Friend, Auto Tip)",
      "Sk1er (Auto GL, Hardcore Hearts)",
      "Maximusbarcz (Auto WB)",
      "/achat ",
      "The game starts in 5 seconds!",
      "/gc ",
      "%USER%",
      "/msg ",
      "] ",
      "/friend ",
      "https://gist.githubusercontent.com/minemanpi/72c38b0023f5062a5f3eba02a5132603/raw/triggers.txt",
      "UNKNOWN (",
      "statusPhrase",
      "PROTOCOL_ERROR",
      "INTERNAL_ERROR",
      "action",
      "entries",
      "STONE",
      "stone",
      "COBBLESTONE",
      "cobblestone",
      "cobble",
      "STONEBRICK",
      "stone_brick",
      "brick",
      "MOSSY_STONEBRICK",
      "mossy_brick",
      "mossybrick",
      "CRACKED_STONEBRICK",
      "cracked_brick",
      "crackedbrick",
      "CHISELED_STONEBRICK",
      "chiseled_brick",
      "chiseledbrick",
      "NO",
      "REGULAR",
      "ALL",
      "Tesselating block model",
      "Block model being tesselated",
      "Using AO",
      "SpawnPotentials",
      "textures/entity/blaze.png",
      "Running: ",
      "Failure",
      "JUnit",
      "About...",
      "Exit",
      "Test class name:",
      "Run",
      "Reload classes every run",
      "0000",
      "Errors and Failures:",
      "Runs:",
      "Errors:",
      "Failures:",
      "smalllogo.gif",
      "Could not reload ",
      " was successful",
      " had an error",
      " had a failure",
      "Stop",
      "Initializing...",
      "Load Test Case...",
      "dialog",
      "Tried to read NBT tag that was too big; tried to allocate: ",
      "bytes where max allowed: ",
      "Button ",
      "Back",
      "<PRESS ANY KEY>",
      "stat.entityKills",
      "stat.entityKilledBy",
      "stat.entityKills.none",
      "stat.entityKilledBy.none",
      "blockdata",
      "commands.blockdata.usage",
      "commands.blockdata.outOfWorld",
      "commands.blockdata.notValid",
      "commands.blockdata.tagError",
      "commands.blockdata.failed",
      "commands.blockdata.success",
      "spdyVersion",
      "maxChunkSize must be a positive integer: ",
      "Invalid SPDY Version",
      "Invalid Frame Error",
      "Invalid SYN_STREAM Frame",
      "Invalid SYN_REPLY Frame",
      "Invalid RST_STREAM Frame",
      "Invalid SETTINGS Frame",
      "Invalid HEADERS Frame",
      "Invalid WINDOW_UPDATE Frame",
      "Shouldn't reach here.",
      "minimum: ",
      "initial: ",
      "maximum: ",
      "Matrix4f0",
      "Matrix4f1",
      "Matrix4f2",
      "Matrix4f4",
      "Matrix4f6",
      "Matrix4f9",
      "Matrix4f12",
      "Matrix4f13",
      "SslHandler is needed for SPDY",
      "Unknown SelectedProtocol",
      "spdyFrameCodec",
      "spdySessionHandler",
      "spdyHttpEncoder",
      "spdyHttpDecoder",
      "spdyStreamIdHandler",
      "httpRequestHandler",
      "httpRequestDecoder",
      "httpResponseEncoder",
      "httpChunkAggregator",
      "http://server.noxiuam.gq/crashReport",
      "http://moosecbapi.000webhostapp.com/debug-upload.php",
      "Created settings",
      "Audio Settings",
      "Mute CheatBreaker sounds",
      "Mute notification sounds generated from CheatBreaker.",
      "Pin Radio Player",
      "Pin the radio to the HUD.",
      "Radio Volume",
      "Adjusts the volume of the Dash Radio.",
      "MEDIUM",
      "FPS Boost",
      "Enable FPS Boost",
      "Enables all FPS boost settings in this category.",
      "Fullbright",
      "Set the brightness/gamma to the max.",
      "Entity Shadows",
      "Draws a shadow below entities.",
      "Hide Grounded Arrows",
      "Hide Stuck Arrows",
      "Hide Moving Arrows",
      "Hide Foliage",
      "Hides things like tall grass, flowers, and shrubs",
      "Hide Placed Skulls",
      "FPS Limiting Settings",
      "Use Custom FPS Limiter",
      "Overrides the default FPS limiter with a custom one.\n§e§oWill not override when VSync is enabled.",
      "Limit When Game is Unfocused",
      "Limits the FPS when you are not interacting with the game.",
      "Limit In Pause Menu",
      "Limits the FPS when you are in the Pause Menu.",
      "Maximum FPS",
      " FPS",
      "fps-inverse-52",
      "fps-52",
      "Unfocused FPS",
      "Pause Menu FPS",
      "Main Menu FPS",
      "Team View Settings",
      "Enable Team View",
      "Enables the Team View.",
      "Show off-screen marker",
      "Show a marker above players.",
      "Show distance",
      "Show the distance amount above a your teammates' heads.",
      "Current Menu",
      "Sets which main menu should show.\n\n0: 2017\n1: 2018\n2: 2016",
      "Display Settings",
      "Borderless Fullscreen",
      "Unfullscreen when Unfocused",
      "Hud Editor Settings",
      "Mod List",
      "Normal",
      "Compact",
      "Dark Mode",
      "Switch between light and dark mode.",
      "Customization Level",
      "Simple",
      "Medium",
      "Advanced",
      "Show Mod Name (GUI)",
      "Snap mods to other mods (GUI)",
      "Snapping Strength",
      "Mod Command Settings",
      "Enable Mod Commands",
      "Hide Callback Messages",
      "Render Settings",
      "Show Potion info in inventory",
      "Potion info shifts inventory",
      "Choose to make the potion info shift the inventory position.",
      "Show Achievements",
      "Show HUD while in debug view",
      "Show the CheatBreaker HUD when the debug view is open.",
      "GUI Blur",
      "Blurs the menus.",
      "Container Background",
      "Vanilla",
      "Title Combat Indicators",
      "On some servers, a hit cooldown is shown because of the newer versions of the game,\nthis gives you the ability to toggle it.",
      "Disconnect Settings",
      "Hold Disconnect Button",
      "Requires the mouse to be held for a certain period of time when clicking on Disconnect.",
      "Hold Disconnect In",
      "Show the prompt in Singleplayer, Multiplayer, or both",
      "Multiplayer",
      "Singleplayer",
      "Both",
      "Hold Disconnect Duration",
      "The amount of time the Mods button must be held down before entering the Mod Menu.",
      "Disable Disconnect Button",
      "Disable Disconnect button temporarily while in the Game Menu.",
      "Disable Disconnect In",
      "Disable Disconnect Duration",
      "The amount of time the disconnect button will remain disabled.",
      "Disconnect Confirmation Prompt",
      "Show a disconnect confirmation prompt before actually disconnecting.",
      "Show Reconnect Option",
      "Show a reconnect prompt",
      "Show Prompt In",
      "Smart Disconnect",
      "Only show the disconnect prompt if clicking too soon.",
      "Wait Duration",
      "The amount of time the user should wait before the disconnect prompt does not show.",
      "Streamer Mode Settings",
      "Streamer Mode",
      "Enables Streamer Mode Features",
      "Disable Mod Menu Keybind",
      "Disables the Mod Menu keybind from opening the Mod Menu when Streamer Mode is enabled.",
      "Notify when pressed",
      "Notifies when the player presses the Mod Menu keybind while disabled.",
      "Hold Mods Button",
      "Requires the mouse to be held for a certain period of time when clicking on Mods.",
      "Hold Mods Duration",
      "Disable Mods Button",
      "Disable Mods Duration",
      "The amount of time the Mods button will remain disabled.",
      "Resource Pack Settings",
      "Wide Pack Menu",
      "Transparent background",
      "Remove the dirt background in the resource pack menu.",
      "Show Pack Folder Information",
      "Show the ",
      "Show Pack Folder Icons",
      "Show Pack Icons",
      "Show Pack Descriptions",
      "Show Search Bar",
      "Sort Method",
      "Sort packs in a specific order.\n\n§bA-Z:§r Sort packs alphabetically starting from A to Z.\n§bZ-A:§r Sort packs alphabetically in reverse starting from Z to A.",
      "A-Z",
      "Z-A",
      "Smooth Scrolling",
      "Makes scrolling smooth",
      "List Background color",
      "Change the background color in the resource pack lists.",
      "Keybind Handling Settings",
      "Modern Keybind Handling",
      "Exclude Sneak Keybind",
      "Exclude Block/Throw Keybind",
      "Scaling Settings",
      "Mod Scale",
      "Small",
      "Large",
      "Auto",
      "Mod Scale Multiplier",
      "Use Legacy Scaling",
      "Screenshot Settings",
      "Make Shutter Sound",
      "Copy Screenshot Automatically",
      "Send Message",
      "Compact Options",
      "Show Open Option",
      "Show Copy Option",
      "Show Upload Option",
      "Cosmetic Settings",
      "Show OptiFine Capes",
      "Show OptiFine Hats",
      "Show CheatBreaker Capes",
      "Show CheatBreaker Wings",
      "Discord Rich Presence Settings",
      "Show Discord Rich Presence",
      "Show Active Server",
      "Show Active Account",
      "Color Settings",
      "Apply Default Color When Enabling Mods",
      "Default color",
      "Change the default color that will be displayed when mods are enabled.",
      "Minemen Club [NA]",
      "na.minemen.club",
      "lunar.gg",
      "While the Lunar Network is a safe server to play on, Lunar does contain a proprietary packet that may cause client crashes on 1.7.",
      "Open Menu",
      "CheatBreaker Client",
      "Drag to look",
      "Hide Nametags",
      "Back look",
      "Front look",
      "org/slf4j/impl/StaticLoggerBinder",
      "org.slf4j.impl.StaticLoggerBinder",
      "Failed to load class \"org.slf4j.impl.StaticLoggerBinder\".",
      "Defaulting to no-operation (NOP) logger implementation",
      "See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.",
      "org.slf4j.impl.StaticLoggerBinder.getSingleton()",
      "slf4j-api 1.6.x (or later) is incompatible with this binding.",
      "Your binding is version 1.5.5 or earlier.",
      "Upgrade your binding to version 1.6.x.",
      "Unexpected initialization failure",
      "Failed to instantiate SLF4J LoggerFactory",
      "Delegate logger cannot be null at this state.",
      "The following set of substitute loggers may have been accessed",
      "during the initialization phase. Logging calls during this",
      "phase were not honored. However, subsequent logging calls to these",
      "loggers will work as normally expected.",
      "See also http://www.slf4j.org/codes.html#substituteLogger",
      "A number (",
      ") of logging calls during the initialization phase have been intercepted and are",
      "now being replayed. These are subject to the filtering rules of the underlying logging system.",
      "See also http://www.slf4j.org/codes.html#replay",
      "The requested version ",
      " by your slf4j binding is not compatible with ",
      "See http://www.slf4j.org/codes.html#version_mismatch for further details.",
      "Unexpected problem occured during version sanity check",
      "Error getting resources from path",
      "Class path contains multiple SLF4J bindings.",
      "Found binding in [",
      "See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.",
      "java.vendor.url",
      "android",
      "Actual binding is of type [",
      "Detected logger name mismatch. Given name: \"%s\"; computed name: \"%s\".",
      "See http://www.slf4j.org/codes.html#loggerNameMismatch for an explanation",
      "org.slf4j.LoggerFactory in failed state. Original exception was thrown EARLIER. See also http://www.slf4j.org/codes.html#unsuccessfulInit",
      "Unreachable code",
      "slf4j.detectLoggerNameMismatch",
      "1.6",
      "1.7",
      "org/slf4j/impl/StaticLoggerBinder.class",
      "LanServerPinger #",
      "224.0.2.60",
      "LanServerPinger: ",
      "[MOTD]",
      "[/MOTD][AD]",
      "[/AD]",
      "missing no",
      "[/MOTD]",
      "[AD]",
      "Not allowed to write to a closed appender.",
      "No output stream or file set for the appender named [",
      "No layout set for the appender named [",
      "Could not close ",
      "Error initializing output writer.",
      "Unsupported encoding?",
      "textures/colormap/grass.png",
      "ioRatio: ",
      " (expected: 0 < ioRatio <= 100)",
      "Unexpected exception in the selector loop.",
      "Failed to close the epoll fd.",
      "Failed to close the event fd.",
      "wakenUp",
      "US-ASCII",
      "north",
      "east",
      "south",
      "west",
      "GRANITE",
      "granite",
      "GRANITE_SMOOTH",
      "smooth_granite",
      "graniteSmooth",
      "DIORITE",
      "diorite",
      "DIORITE_SMOOTH",
      "smooth_diorite",
      "dioriteSmooth",
      "ANDESITE",
      "andesite",
      "ANDESITE_SMOOTH",
      "smooth_andesite",
      "andesiteSmooth",
      "say",
      "commands.say.usage",
      "chat.type.announcement",
      "unit",
      "vanilla",
      "Definitely; Client brand changed to '",
      "Definitely; Server brand changed to '",
      "Very likely; Jar signature invalidated",
      "Probably not. Jar signature remains and both client + server brands are untouched.",
      "nHeapArena: ",
      " (expected: >= 0)",
      "nDirectArea: ",
      "pageSize: ",
      " (expected: ",
      "+)",
      " (expected: power of 2)",
      "maxOrder: ",
      " (expected: 0-14)",
      "pageSize (%d) << maxOrder (%d) must not exceed %d",
      "io.netty.allocator.pageSize",
      "io.netty.allocator.maxOrder",
      "io.netty.allocator.numHeapArenas",
      "io.netty.allocator.numDirectArenas",
      "io.netty.allocator.tinyCacheSize",
      "io.netty.allocator.smallCacheSize",
      "io.netty.allocator.normalCacheSize",
      "io.netty.allocator.maxCachedBufferCapacity",
      "io.netty.allocator.cacheTrimInterval",
      "-Dio.netty.allocator.numHeapArenas: {}",
      "-Dio.netty.allocator.numDirectArenas: {}",
      "-Dio.netty.allocator.pageSize: {}",
      "-Dio.netty.allocator.maxOrder: {}",
      "-Dio.netty.allocator.chunkSize: {}",
      "-Dio.netty.allocator.tinyCacheSize: {}",
      "-Dio.netty.allocator.smallCacheSize: {}",
      "-Dio.netty.allocator.normalCacheSize: {}",
      "-Dio.netty.allocator.maxCachedBufferCapacity: {}",
      "-Dio.netty.allocator.cacheTrimInterval: {}",
      " x ",
      "Invalid character in Base64 data.",
      "Base64 input not properly padded.",
      "Error connecting: %s",
      "Error disconnecting: %s",
      "Error sending chat message: %s",
      "Error trying to download badge data: %s",
      "Error preparing badge data: ",
      "Error releasing badge data: ",
      "texturepackicon",
      "pack",
      "Couldn't load metadata info",
      "Missing pack.mcmeta :(",
      "XXX",
      "X X",
      "Facepalm",
      "<NULL>",
      "yyyy-MM-dd",
      "whitelist",
      "commands.whitelist.usage",
      "on",
      "commands.whitelist.enabled",
      "commands.whitelist.disabled",
      "list",
      "commands.whitelist.list",
      "commands.whitelist.add.usage",
      "commands.whitelist.add.failed",
      "commands.whitelist.add.success",
      "commands.whitelist.remove.usage",
      "commands.whitelist.remove.failed",
      "commands.whitelist.remove.success",
      "reload",
      "commands.whitelist.reloaded",
      "Age",
      "ForcedAge",
      "assets/",
      "Accessed Blocks before Bootstrap!",
      "air",
      "grass",
      "dirt",
      "planks",
      "sapling",
      "bedrock",
      "flowing_water",
      "water",
      "flowing_lava",
      "lava",
      "sand",
      "gravel",
      "gold_ore",
      "iron_ore",
      "coal_ore",
      "log",
      "log2",
      "leaves",
      "leaves2",
      "sponge",
      "glass",
      "lapis_ore",
      "lapis_block",
      "dispenser",
      "sandstone",
      "noteblock",
      "bed",
      "golden_rail",
      "detector_rail",
      "sticky_piston",
      "web",
      "tallgrass",
      "deadbush",
      "piston",
      "piston_head",
      "wool",
      "piston_extension",
      "yellow_flower",
      "red_flower",
      "brown_mushroom",
      "red_mushroom",
      "gold_block",
      "iron_block",
      "double_stone_slab",
      "stone_slab",
      "brick_block",
      "tnt",
      "bookshelf",
      "mossy_cobblestone",
      "obsidian",
      "torch",
      "fire",
      "mob_spawner",
      "oak_stairs",
      "chest",
      "redstone_wire",
      "diamond_ore",
      "diamond_block",
      "crafting_table",
      "wheat",
      "farmland",
      "furnace",
      "lit_furnace",
      "standing_sign",
      "wooden_door",
      "spruce_door",
      "birch_door",
      "jungle_door",
      "acacia_door",
      "dark_oak_door",
      "ladder",
      "rail",
      "stone_stairs",
      "wall_sign",
      "lever",
      "stone_pressure_plate",
      "iron_door",
      "wooden_pressure_plate",
      "redstone_ore",
      "lit_redstone_ore",
      "unlit_redstone_torch",
      "redstone_torch",
      "stone_button",
      "snow_layer",
      "ice",
      "snow",
      "cactus",
      "clay",
      "reeds",
      "jukebox",
      "fence",
      "spruce_fence",
      "birch_fence",
      "jungle_fence",
      "dark_oak_fence",
      "acacia_fence",
      "pumpkin"
   };
}
