package recovered.strings;

public class StringTable11 {
   public static String[] field_0000 = new String[]{
      "Netty Client IO #%d",
      "This MBean acts as a management facade for log4j appenders.",
      "AppenderDynamicMBean(): Constructs a AppenderDynamicMBean instance",
      "Dynamic",
      "activateOptions",
      "activateOptions(): add an appender",
      "void",
      "layout class",
      "setLayout",
      "setLayout(): add a layout",
      "getMBeanInfo called.",
      "Options activated.",
      "org.apache.log4j.Layout",
      ",layout=",
      "Adding LayoutMBean:",
      "log4j:appender=",
      "appender=",
      " layout.",
      "Could not add DynamicLayoutMBean for [",
      "getAttribute called with [",
      ",layout",
      "attributeName",
      "FIXME",
      ".layout",
      "Attribute ",
      " not found in ",
      "org.apache.log4j.jmx.AppenderDynamicMBean",
      "LINUX_32",
      "LINUX_64",
      "WINDOWS_32",
      "WINDOWS_64",
      "OSX_32",
      "OSX_64",
      "OSX_PPC",
      "INIT",
      "AUTH",
      "log4j warning: ",
      "log4j error: ",
      "SOCKS_AUTH_REQUEST_DECODER",
      ": not in use)",
      ", offset: ",
      ", length: ",
      ", elemSize: ",
      "silverfish",
      "wing",
      "body1",
      "body2",
      "body3",
      "body4",
      "body5",
      "body6",
      "body7",
      "wing1",
      "wing2",
      "wing3",
      "Leaked resource: '",
      "' loaded from pack: '",
      "'\n",
      "An exception has been raised by {}",
      "client/icons/headphones.png",
      "client/icons/speaker.png",
      "client/icons/speaker-mute.png",
      "client/icons/microphone-64.png",
      "Join Channel",
      "Un-deafen",
      "Deafen",
      "VOICE CHAT",
      "VOICE CHAT IS NOT SUPPORTED",
      "Attempted to reset the LoggerFactory without possessing the guard.",
      "RepositorySelector must be non-null.",
      "org.apache.catalina.loader.WebappClassLoader.stop",
      "Class invariant violation",
      "log4j called after unloading, see http://logging.apache.org/log4j/1.2/faq.html#unload.",
      "log4j.defaultInitOverride",
      "log4j.configuration",
      "log4j.configuratorClass",
      "log4j.xml",
      "log4j.properties",
      "Using URL [",
      "] for automatic log4j configuration.",
      "Error during default initialization",
      "Could not find resource: [",
      "Default initialization of overridden by log4j.defaultInitOverrideproperty.",
      "Weapon modifier",
      "jdbc:odbc:myDB",
      "me",
      "mypassword",
      "sun.jdbc.odbc.JdbcOdbcDriver",
      "Error closing connection",
      "Failed to excute sql",
      "Failed to load driver",
      "client/emote/",
      "INTEGER",
      "integer",
      "HEARTS",
      "hearts",
      "Unclosed CDATA",
      "Missing ';' in XML entity: &",
      "Misshaped meta tag",
      "Unterminated string",
      "Misshaped element",
      "Misplaced '<'",
      "Bad character in a name",
      "amp",
      "apos",
      "gt",
      "lt",
      "quot",
      "short",
      "lang/%s.lang",
      "port out of range:",
      "holder",
      "port",
      "Could not set port",
      "org.newsclub.net.unix.NarSystem",
      "loadLibrary",
      "Could not find NarSystem class.\n\n*** ECLIPSE USERS ***\nIf you're running from within Eclipse, please try closing the \"junixsocket-native-common\" project\n",
      "Uninitialized",
      "Initializing",
      "Initialized",
      "ShuttingDown",
      "textureUnit: ",
      ", path: ",
      ", glTextureId: ",
      "options.chat.title",
      "StringToMatch",
      "AcceptOnMatch",
      ".pre",
      "selectorProvider",
      "failed to open a new selector",
      "sun.nio.ch.SelectorImpl",
      "selectedKeys",
      "publicSelectedKeys",
      "Instrumented an optimized java.util.Set into: {}",
      "Failed to instrument an optimized java.util.Set into: {}",
      "ch",
      "interestOps must be non-zero.",
      "invalid interestOps: ",
      "(validOps: ",
      "task",
      "event loop shut down",
      "failed to register a channel",
      "Failed to create a new Selector.",
      "Failed to re-register a Channel to the new Selector.",
      "Failed to close the old Selector.",
      "Migrated ",
      " channel(s) to the new Selector.",
      "Unexpected exception while running NioTask.channelUnregistered()",
      "Selector.select() returned prematurely because Thread.currentThread().interrupt() was called. Use NioEventLoop.shutdownGracefully() to shutdown the NioEventLoop.",
      "Selector.select() returned prematurely {} times in a row; rebuilding selector.",
      "Selector.select() returned prematurely {} times in a row.",
      " raised by a Selector - JDK bug?",
      "Failed to update SelectionKeys.",
      "io.netty.noKeySetOptimization",
      "sun.nio.ch.bugLevel",
      "Unable to get/set System Property: {}",
      "io.netty.selectorAutoRebuildThreshold",
      "-Dio.netty.noKeySetOptimization: {}",
      "-Dio.netty.selectorAutoRebuildThreshold: {}",
      "Channel:",
      " Not Unsuspend: ",
      " Unsuspend: ",
      " Normal Unsuspend: ",
      " Unsupsend final status => ",
      "Response",
      "Exception",
      "/shaders/shaders.properties",
      "version.1.8.9",
      "M6_pre2",
      "HD_U_",
      "of.message.shaders.nv1",
      "of.message.shaders.nv2",
      "of.options.shaders.packNone",
      "(internal)",
      "of.options.shaders.packDefault",
      "android.app.Application",
      "Platform: Android",
      "Platform: Windows",
      "/usr/bin/id",
      "/bin/id",
      "/usr/xpg4/bin/id",
      "^(?:0|[1-9][0-9]*)$",
      "-u",
      "UID: {}",
      "Could not determine the current UID using /usr/bin/id; attempting to bind at privileged ports.",
      ".*(?:denied|not.*permitted).*",
      "UID: 0 (succeded to bind at port {})",
      "UID: non-root (failed to bind at any privileged ports)",
      "java.time.Clock",
      "java.util.concurrent.LinkedTransferQueue",
      "Java version: {}",
      "io.netty.noUnsafe",
      "-Dio.netty.noUnsafe: {}",
      "sun.misc.Unsafe: unavailable (Android)",
      "sun.misc.Unsafe: unavailable (io.netty.noUnsafe)",
      "io.netty.tryUnsafe",
      "org.jboss.netty.tryUnsafe",
      "sun.misc.Unsafe: unavailable (io.netty.tryUnsafe/org.jboss.netty.tryUnsafe)",
      "sun.misc.Unsafe: {}",
      "available",
      "unavailable",
      "sun.misc.VM",
      "maxDirectMemory",
      "java.lang.management.ManagementFactory",
      "java.lang.management.RuntimeMXBean",
      "getRuntimeMXBean",
      "getInputArguments",
      "maxDirectMemory: {} bytes (maybe)",
      "maxDirectMemory: {} bytes",
      "io.netty.noJavassist",
      "-Dio.netty.noJavassist: {}",
      "Javassist: unavailable (io.netty.noJavassist)",
      "Javassist: available",
      "Javassist: unavailable",
      "You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.",
      "io.netty.tmpdir",
      "-Dio.netty.tmpdir: {}",
      "-Dio.netty.tmpdir: {} (java.io.tmpdir)",
      "TEMP",
      "-Dio.netty.tmpdir: {} (%TEMP%)",
      "USERPROFILE",
      "\\AppData\\Local\\Temp",
      "-Dio.netty.tmpdir: {} (%USERPROFILE%\\AppData\\Local\\Temp)",
      "\\Local Settings\\Temp",
      "-Dio.netty.tmpdir: {} (%USERPROFILE%\\Local Settings\\Temp)",
      "TMPDIR",
      "-Dio.netty.tmpdir: {} ($TMPDIR)",
      "C:\\Windows\\Temp",
      "/tmp",
      "Failed to get the temporary directory; falling back to: {}",
      "io.netty.bitMode",
      "-Dio.netty.bitMode: {}",
      "sun.arch.data.model",
      "-Dio.netty.bitMode: {} (sun.arch.data.model)",
      "com.ibm.vm.bitmode",
      "-Dio.netty.bitMode: {} (com.ibm.vm.bitmode)",
      "amd64",
      "x86_64",
      "i386",
      "i486",
      "i586",
      "i686",
      "-Dio.netty.bitMode: {} (os.arch: {})",
      "java.vm.name",
      "([1-9][0-9]+)-?bit",
      "\\s*-XX:MaxDirectMemorySize\\s*=\\s*([0-9]+)\\s*([kKmMgG]?)\\s*$",
      "io.netty.noPreferDirect",
      "-Dio.netty.noPreferDirect: {}",
      "Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.",
      "BAUD_RATE",
      "DTR",
      "RTS",
      "STOP_BITS",
      "DATA_BITS",
      "PARITY_BIT",
      "WAIT_TIME",
      "READ_TIMEOUT",
      "TNTFuse",
      "Snooper Timer",
      "http://snoop.minecraft.net/",
      "?version=",
      "os_name",
      "os_version",
      "os.version",
      "os_architecture",
      "java_version",
      "java.version",
      "-X",
      "jvm_arg[",
      "jvm_args",
      "memory_total",
      "memory_max",
      "memory_free",
      "cpu_cores",
      "Needed to grow BufferBuilder buffer: Old size ",
      " bytes, new size ",
      "Already building!",
      "Not building!",
      "Unable process configuration file at ",
      ". Error Message=",
      "searchtext",
      "Categories",
      "selected",
      "expanded",
      "colorlevel",
      "column",
      "Cannot delete ",
      " because a security violation occured.",
      "lf5_configuration.xml",
      "\t<loglevels>\r\n",
      "\t</loglevels>\r\n",
      "\t<loglevelcolors>\r\n",
      "\t</loglevelcolors>\r\n",
      "\t<logtablecolumns>\r\n",
      "\t</logtablecolumns>\r\n",
      "\t<",
      "/>\r\n",
      "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n",
      "<configuration>\r\n",
      "</configuration>\r\n",
      "\" ",
      "\"/>\r\n",
      "\t\t<",
      "JTree.lineStyle",
      "Angled",
      "KEBAB",
      "Kebab",
      "AZTEC",
      "Aztec",
      "ALBAN",
      "Alban",
      "AZTEC_2",
      "Aztec2",
      "BOMB",
      "Bomb",
      "PLANT",
      "Plant",
      "WASTELAND",
      "Wasteland",
      "POOL",
      "Pool",
      "COURBET",
      "Courbet",
      "SEA",
      "Sea",
      "SUNSET",
      "Sunset",
      "CREEBET",
      "Creebet",
      "WANDERER",
      "Wanderer",
      "GRAHAM",
      "Graham",
      "MATCH",
      "Match",
      "BUST",
      "Bust",
      "STAGE",
      "Stage",
      "VOID",
      "Void",
      "SKULL_AND_ROSES",
      "SkullAndRoses",
      "WITHER",
      "Wither",
      "FIGHTERS",
      "Fighters",
      "POINTER",
      "Pointer",
      "PIGSCENE",
      "Pigscene",
      "BURNING_SKULL",
      "BurningSkull",
      "SKELETON",
      "DONKEY_KONG",
      "DonkeyKong",
      "/assets/",
      "pack.png",
      "minecraft",
      "realms",
      "Options",
      "options.sounds.title",
      "Write failure.",
      "MC|Beacon",
      "tile.beacon.primary",
      "tile.beacon.secondary",
      "textures/gui/container/beacon.png",
      "example.com",
      "Failed to generate a self-signed X.509 certificate using sun.security.x509:",
      "Failed to generate a self-signed X.509 certificate using Bouncy Castle:",
      "No provider succeeded to generate a self-signed certificate. See debug log for the root cause.",
      "-----BEGIN PRIVATE KEY-----\n",
      "\n-----END PRIVATE KEY-----\n",
      "keyutil_",
      ".key",
      "-----BEGIN CERTIFICATE-----\n",
      "\n-----END CERTIFICATE-----\n",
      ".crt",
      "Failed to delete a file: ",
      "Failed to close a file: ",
      "WHITE",
      "white",
      "ORANGE",
      "orange",
      "MAGENTA",
      "magenta",
      "LIGHT_BLUE",
      "light_blue",
      "lightBlue",
      "YELLOW",
      "LIME",
      "lime",
      "PINK",
      "pink",
      "GRAY",
      "gray",
      "SILVER",
      "silver",
      "CYAN",
      "cyan",
      "PURPLE",
      "purple",
      "BLUE",
      "BROWN",
      "brown",
      "GREEN",
      "RED",
      "BLACK",
      "black",
      "horse/",
      "textures/entity/",
      "textures/painting/",
      ", properties: ",
      "Properties not found: ",
      "File not found: ",
      ".properties",
      "textures/",
      "optifine/random/",
      "mcpatcher/mob/",
      ", variants: ",
      "RandomEntities: ",
      "_armor",
      "_eyes",
      "_exploding",
      "_shooting",
      "_fur",
      "_invulnerable",
      "_angry",
      "_tame",
      "_collar",
      "JSON object is null, player: ",
      "items",
      "active",
      "Item type is null, player: ",
      "items/",
      "/model.cfg",
      "/users/",
      "optifine.net",
      "Error loading item texture ",
      "Error loading item model ",
      "30",
      "60",
      " MB/s",
      "bold",
      "italic",
      "underlined",
      "strikethrough",
      "obfuscated",
      "color",
      "insertion",
      "clickEvent",
      "hoverEvent",
      "dummy",
      "Mipmap levels: ",
      "Multitexture: ",
      "Custom loader (skipped): ",
      "Custom loader: ",
      "Invalid sprite size: ",
      "Scaled non power of 2: ",
      "Scaled too small texture: ",
      "Unable to load extra miplevels, source-texture is not power of two",
      "Unable to load miplevel {} from: {}",
      "animation",
      "Unable to parse metadata from ",
      "Using missing texture, unable to load ",
      "Texture {} with size {}x{} limits mip level from {} to {}",
      "Custom loader sprites: ",
      "Custom loader sprites (skipped): ",
      "{}: dropping miplevel from {} to {}, because of minimum power of two: {}",
      "Applying mipmap",
      "Sprite being mipmapped",
      "Sprite name",
      "Sprite size",
      "Sprite frames",
      "Mipmap levels",
      "Created: {}x{} {}-atlas",
      "Stitching texture atlas",
      "Texture being stitched together",
      "Atlas path",
      "Sprite",
      "Animated sprites: ",
      "Error uploading sprite single: ",
      ", parent: ",
      "saveTextureMap",
      "Exporting texture map: ",
      "debug/",
      "%s/%s%s",
      "%s/mipmaps/%s.%d%s",
      "Location cannot be null!",
      "Sprite size: ",
      "png",
      "Invalid grid V: ",
      ", icon: ",
      "Invalid grid U: ",
      "fml.skipFirstTextureLoad",
      "textures/atlas/blocks.png",
      "packet_handler",
      "textures/entity/snowman.png",
      "Failed Start with id ",
      "Skipping Structure with id ",
      "Failed Piece with id ",
      "Skipping Piece with id ",
      "Village",
      "Fortress",
      "Temple",
      "Monument",
      "Method \"",
      "\" not found",
      "\" should be public",
      "Trailer",
      "EmptyLastHttpContent",
      "Listener already listening",
      "Dev",
      "Beta",
      "Preview",
      "Development builds are not intended for bug testing purposes; however, expect bugs to appear.",
      "Beta builds are used to test for potential issues. Expect bugs to occur over time.",
      "Preview builds are intended to become the next stable build. Bugs should be less prominent.",
      "Production",
      "Commit: ",
      "Minecraft Version: 1.8.9",
      "Build Version: ",
      "http://skins.minecraft.net/MinecraftSkins/%s.png",
      "skins/",
      "textures/entity/elytra.png",
      "L",
      "java.vendor",
      "flush() raised a masked exception.",
      "Duplicate id: ",
      " is missing a mapping! This is a bug!",
      "Skipping BlockEntity with id ",
      "Actual block type",
      "Actual block data value",
      "Furnace",
      "Chest",
      "EnderChest",
      "RecordPlayer",
      "Trap",
      "Dropper",
      "Sign",
      "MobSpawner",
      "Music",
      "Piston",
      "Cauldron",
      "EnchantTable",
      "Airportal",
      "Control",
      "Beacon",
      "Skull",
      "DLDetector",
      "Hopper",
      "Comparator",
      "FlowerPot",
      "Banner",
      "generation",
      "book.generation.",
      "resolved",
      "options.snooper.title",
      "options.snooper.desc",
      "C ",
      "S ",
      "Processed",
      "maxObjectSize: ",
      "invalid data length: ",
      "data length too big: ",
      " (max: ",
      "SHCC",
      "SHFC",
      "SH5C",
      "SHLT",
      "SHLi",
      "SHPR",
      "SHPH",
      "SHRT",
      "SHRC",
      "SHSD",
      "SHStart",
      "SHS",
      "SHSSD",
      "age",
      "failed to load the required native library",
      "PEACEFUL",
      "options.difficulty.peaceful",
      "EASY",
      "options.difficulty.easy",
      "options.difficulty.normal",
      "HARD",
      "options.difficulty.hard",
      "key parameter cannot be null",
      "MDCAdapter cannot be null. See also http://www.slf4j.org/codes.html#null_MDCA",
      "StaticMDCBinder",
      "Failed to load class \"org.slf4j.impl.StaticMDCBinder\".",
      "Defaulting to no-operation MDCAdapter implementation.",
      "See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.",
      "MDC binding unsuccessful.",
      "Connection lost timer stopped",
      "Connection lost timer restarted",
      "Exception during connection lost restart",
      "Connection lost timer deactivated",
      "Connection lost timer started",
      "connectionLostChecker",
      "Closing connection due to no pong received: {}",
      "The connection was closed because the other endpoint did not respond with a pong in time. For more information check: https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection",
      "Trying to ping a non open connection: {}",
      "LINUX",
      "SOLARIS",
      "WINDOWS",
      "OSX",
      "acacia",
      "birch",
      "dark_oak",
      "jungle",
      "oak",
      "spruce",
      "Enable face culling: ",
      "blockstates/",
      "_leaves.json",
      "models/block/",
      "_leaves",
      "SmartLeaves: Model is not cube, general quads: ",
      "SmartLeaves: Model is not cube, side: ",
      ", quads: ",
      "This method should only be called for matching effects!",
      ", Duration: ",
      ", Splash: true",
      ", Particles: false",
      "Id",
      "Amplifier",
      "Duration",
      "Ambient",
      "ShowParticles",
      "slim",
      "Rendering entity in world",
      "Post-rendering entity in world",
      "Rendering entity hitbox in world",
      "Entity being rendered",
      "Renderer details",
      "Assigned renderer",
      "Location",
      "Rotation",
      "Delta",
      "NOP",
      "No error code reported",
      "glGenLists returned an ID of 0 for a count of ",
      ", GL error (",
      "Value length is not 2, length: ",
      "Value length is not 3, length: ",
      "Value length is not 4, length: ",
      "BOOL",
      "VEC2",
      "VEC3",
      "VEC4",
      " / ",
      "Not supported",
      "listener",
      "listeners",
      "WARN_STATUS",
      "liquid.water",
      "liquid.lavapop",
      "liquid.lava",
      "Invalid material",
      "latency",
      "gameMode",
      "profile",
      "initialCapacity: ",
      " (expectd: 0+)",
      "initialCapacity: %d (expected: not greater than maxCapacity(%d)",
      "(directByDefault: ",
      "Repetition count must be > 0",
      "(repeated)",
      "Back to Game Menu",
      "menu.disconnect",
      "Are you sure you want to disconnect?",
      "X-SPDY-Stream-ID",
      "X-SPDY-Associated-To-Stream-ID",
      "X-SPDY-Priority",
      "X-SPDY-URL",
      "X-SPDY-Scheme",
      "Invul",
      "mob.wither.idle",
      "mob.wither.hurt",
      "mob.wither.death",
      "Invalid pack.mcmeta (or missing 'pack' section)",
      "%s:%s:%d",
      "folder",
      "zip",
      "<log4j:event logger=\"",
      "\" timestamp=\"",
      "\" level=\"",
      "\" thread=\"",
      "\">\r\n",
      "<log4j:message><![CDATA[",
      "]]></log4j:message>\r\n",
      "<log4j:NDC><![CDATA[",
      "]]></log4j:NDC>\r\n",
      "<log4j:throwable><![CDATA[",
      "]]></log4j:throwable>\r\n",
      "<log4j:locationInfo class=\"",
      "\" method=\"",
      "\" file=\"",
      "\" line=\"",
      "<log4j:properties>\r\n",
      "<log4j:data name=\"",
      "\" value=\"",
      "</log4j:properties>\r\n",
      "</log4j:event>\r\n\r\n",
      "connection timed out: ",
      "Netty Local Client IO #%d",
      "FB: Adding logger [",
      "FB: The following error reported: ",
      "FB: INITIATING FALLBACK PROCEDURE.",
      "FB: Searching for [",
      "] in logger [",
      "FB: Replacing [",
      "] by [",
      "FB: Adding appender [",
      "] to logger ",
      "FB: Setting primary appender to [",
      "FB: Setting backup appender to [",
      "textures/entity/cow/mooshroom.png",
      "survival",
      "selectWorld.newWorld",
      "selectWorld.create",
      "selectWorld.gameMode",
      "selectWorld.moreWorldOptions",
      "selectWorld.mapFeatures",
      "selectWorld.bonusItems",
      "selectWorld.mapType",
      "selectWorld.allowCommands",
      "selectWorld.customizeType",
      "World",
      "selectWorld.gameMode.",
      ".line1",
      ".line2",
      "[\\./\"]",
      "creative",
      "spectator",
      "selectWorld.enterSeed",
      "selectWorld.seedInfo",
      "selectWorld.mapFeatures.info",
      "selectWorld.allowCommands.info",
      "selectWorld.resultFolder",
      "selectWorld.newWorld.copyOf",
      "CON",
      "COM",
      "PRN",
      "AUX",
      "CLOCK$",
      "NUL",
      "COM1",
      "COM2",
      "COM3",
      "COM4",
      "COM5",
      "COM6",
      "COM7",
      "COM8",
      "COM9",
      "LPT1",
      "LPT2",
      "LPT3",
      "LPT4",
      "LPT5",
      "LPT6",
      "LPT7",
      "LPT8",
      "LPT9",
      "message",
      "DeliveryMode=",
      "NON_PERSISTENT",
      "PERSISTENT",
      ", CorrelationID=",
      ", Destination=",
      ", Expiration=",
      ", MessageID=",
      ", Priority=",
      ", Redelivered=",
      ", ReplyTo=",
      ", Timestamp=",
      ", Type=",
      "Could not parse Message.",
      "layers",
      "Don't know how to search for ",
      "CN=",
      "serialNumber",
      "subject",
      "issuer",
      "validity",
      "algorithmID",
      "SHA1withRSA",
      "algorithmID.algorithm",
      "x509.algorithm",
      "tile.bed.occupied",
      "tile.bed.noSleep",
      "tile.bed.notSafe",
      "occupied",
      "Decoding WebSocket Frame opCode={}",
      "RSV != 0 and no extension negotiated, RSV:",
      "unmasked client to server frame",
      "fragmented control frame",
      "control frame with payload length > 125 octets",
      "control frame using reserved opcode ",
      "received close control frame with payload len 1",
      "data frame using reserved opcode ",
      "received continuation data frame outside fragmented message",
      "received non-continuation data frame while inside fragmented message",
      "invalid data frame length (not using minimal length encoding)",
      "Max frame length of ",
      " has been exceeded.",
      "Decoding WebSocket Frame length={}",
      "Cannot decode web socket frame with opcode: ",
      "Length:",
      "Invalid close frame body",
      "Invalid close frame getStatus code: ",
      "time",
      "commands.time.usage",
      "set",
      "day",
      "night",
      "commands.time.set",
      "commands.time.added",
      "query",
      "daytime",
      "commands.time.query",
      "gametime",
      "MpServer",
      "reEntryProcessing",
      "chunkCache",
      "blocks",
      "Quitting",
      "Forced entities",
      "Retry entities",
      "Server brand",
      "Server type",
      "placedMainChest",
      "placedHiddenChest",
      "placedTrap1",
      "placedTrap2",
      "textures/gui/",
      "optifine/gui/container/",
      "CustomGuis: ",
      "CustomGuis file not found: ",
      "Invalid container: ",
      "[CustomGuis] ",
      "bypassesPlayerLimit",
      "commands.generic.snytax",
      "gameMode.hardcore",
      "selectWorld.cheats",
      "testforblock",
      "commands.testforblock.usage",
      "commands.setblock.notFound",
      "commands.testforblock.outOfWorld",
      "commands.setblock.tagError",
      "commands.testforblock.failed.tile",
      "commands.testforblock.failed.data",
      "commands.testforblock.failed.tileEntity",
      "commands.testforblock.failed.nbt",
      "commands.testforblock.success",
      "header not found: ",
      "header not found: Content-Length",
      "Header names cannot be null",
      "Header name cannot contain non-ASCII characters: ",
      "Header name cannot contain the following prohibited characters: =,;: \\t\\r\\n\\v\\f: ",
      "Header values cannot be null",
      "Header value contains a prohibited character '\\v': ",
      "Header value contains a prohibited character '\\f': ",
      "Only '\\n' is allowed after '\\r': ",
      "Only ' ' and '\\t' are allowed after '\\n': ",
      "Header value must not end with '\\r' or '\\n':",
      "headers",
      "close",
      "keep-alive",
      "Expect",
      "100-continue",
      "Sec-WebSocket-Key1",
      "Sec-WebSocket-Key2",
      "Sec-WebSocket-Origin",
      "Sec-WebSocket-Location",
      "key cannot be null",
      "textures/entity/enderman/enderman_eyes.png",
      "old! ",
      "ONEWAY",
      "TWOWAY",
      "replaceitem",
      "commands.replaceitem.usage",
      "entity",
      "commands.replaceitem.block.usage",
      "commands.replaceitem.entity.usage",
      "commands.replaceitem.tagError",
      "commands.replaceitem.noContainer",
      "commands.replaceitem.failed",
      "Air",
      "commands.replaceitem.success",
      "commands.generic.parameter.invalid",
      "slot.container.",
      "slot.hotbar.",
      "slot.inventory.",
      "slot.enderchest.",
      "slot.villager.",
      "slot.horse.",
      "slot.weapon",
      "slot.armor.head",
      "slot.armor.chest",
      "slot.armor.legs",
      "slot.armor.feet",
      "slot.horse.saddle",
      "slot.horse.armor",
      "slot.horse.chest",
      "ADD_PLAYER",
      "UPDATE_GAME_MODE",
      "UPDATE_LATENCY",
      "UPDATE_DISPLAY_NAME",
      "REMOVE_PLAYER",
      "Slot{originX=",
      ", originY=",
      ", width=",
      ", height=",
      ", texture=",
      ", subSlots=",
      "Empty string not allowed",
      "\\\"",
      "Invalid rotation ",
      " found, only 0/90/180/270 allowed",
      "uv",
      "Expected 4 uv values, found: ",
      "uv[",
      "ONLINE",
      "AWAY",
      "OFFLINE",
      "SERVERBOUND",
      "CLIENTBOUND",
      "enchant",
      "commands.enchant.usage",
      "commands.enchant.noItem",
      "commands.enchant.notFound",
      "commands.enchant.cantEnchant",
      "commands.enchant.cantCombine",
      "lvl",
      "commands.enchant.success",
      "Failed to write [",
      "Failed to flush writer,",
      "Attempted to set null ErrorHandler.",
      "minecraft:blocks/",
      "grass_top",
      "grass_side",
      "grass_side_overlay",
      "grass_side_snowed",
      "mycelium_side",
      "mycelium_top",
      "water_still",
      "water_flow",
      "lava_still",
      "lava_flow",
      "fire_layer_0",
      "fire_layer_1",
      "glass_pane_top",
      "minecraft:items/",
      "compass",
      "clock",
      "/mob/zombie",
      "/mob/pigzombie",
      "*** Reloading custom textures ***",
      "optifine/TickableTextures",
      "assets/minecraft/",
      "/~",
      "Exported: ",
      "Error writing: ",
      "HEADER_START",
      "HEADER_END",
      "FLG_READ",
      "XLEN_READ",
      "SKIP_FNAME",
      "SKIP_COMMENT",
      "PROCESS_FHCRC",
      "FOOTER_START",
      "pattern:",
      "ipattern:",
      "regex:",
      "iregex:",
      "count",
      "Unknown NbtTagValue type: ",
      " = ",
      "^#[0-9a-f]{6}+$",
      "Matrix3d0",
      "Matrix3d1",
      "Matrix3d2",
      "Matrix3d4",
      "Matrix3d6",
      "Matrix3d9",
      "Matrix3d12",
      "Matrix3d13",
      "det= ",
      "Bad XML",
      "Expected a closing name instead of '",
      "'.",
      "Bad tagName '",
      "tagName",
      "childNode",
      "Reserved attribute.",
      "Mismatched '",
      "' and '",
      "childNodes",
      "Non-integrated multiplayer server",
      "Integrated singleplayer server",
      "_log4j_obj_tcpconnect_appender.local.",
      "Could not close oos.",
      "Could not connect to remote log4j server at [",
      " We will try again later.",
      " We are not retrying.",
      "No remote host is set for SocketAppender named \"",
      "\".",
      "application",
      "Detected problem with connection: ",
      "Detected problem with connection, not reconnecting.",
      "Starting a new connector thread.",
      "Could not find address of [",
      "clone",
      "commands.clone.usage",
      "commands.clone.tooManyBlocks",
      "force",
      "move",
      "commands.clone.noOverlap",
      "filtered",
      "commands.clone.failed"
   };
}
