package io.netty.handler.codec.http;

import io.netty.util.Version;
import net.minecraft.world.gen.feature.WorldGenMelon;

public class HttpHeaders$Names {
   public static String PROXY_AUTHENTICATE;
   public static String LAST_MODIFIED;
   public static String SET_COOKIE;
   public static String MAX_FORWARDS;
   public static String ACCESS_CONTROL_REQUEST_HEADERS;
   public static String ACCESS_CONTROL_ALLOW_ORIGIN;
   public static String ACCEPT;
   public static String RANGE;
   public WorldGenMelon __junk4594036091755408449;
   public static String LOCATION;
   public static String DATE;
   public static String VARY;
   public static String WEBSOCKET_LOCATION;
   public static String ACCESS_CONTROL_EXPOSE_HEADERS;
   public static String EXPECT;
   public static String ACCESS_CONTROL_REQUEST_METHOD;
   public static String SERVER;
   public static String ACCEPT_CHARSET;
   public static String ETAG;
   public static String COOKIE;
   public static String CONTENT_TYPE;
   public static String CONTENT_ENCODING;
   public static String SEC_WEBSOCKET_VERSION;
   public static String ACCEPT_LANGUAGE;
   public static String ACCESS_CONTROL_ALLOW_METHODS;
   public static String ORIGIN;
   public static String CONNECTION;
   public static String PRAGMA;
   public static String PROXY_AUTHORIZATION;
   public static String WARNING;
   public static String CONTENT_LANGUAGE;
   public static String IF_RANGE;
   public static String CONTENT_TRANSFER_ENCODING;
   public static String WWW_AUTHENTICATE;
   public static String TRANSFER_ENCODING;
   public static String EXPIRES;
   public static String TE;
   public static String ACCEPT_RANGES;
   public static String TRAILER;
   public Version __junk2812620675959421009;
   public static String UPGRADE;
   public static String REFERER;
   public static String IF_MATCH;
   public static String AGE;
   public static String WEBSOCKET_ORIGIN;
   public static String ACCESS_CONTROL_ALLOW_CREDENTIALS;
   public static String ACCEPT_PATCH;
   public static String SET_COOKIE2;
   public static String ACCESS_CONTROL_ALLOW_HEADERS;
   public static String SEC_WEBSOCKET_KEY;
   public static String SEC_WEBSOCKET_KEY1;
   public static String CONTENT_LENGTH;
   public static String SEC_WEBSOCKET_KEY2;
   public static String SEC_WEBSOCKET_PROTOCOL;
   public static String IF_NONE_MATCH;
   public static String CONTENT_RANGE;
   public static String USER_AGENT;
   public static String CONTENT_MD5;
   public static String FROM;
   public static String HOST;
   public static String ACCEPT_ENCODING;
   public static String VIA;
   public static String ALLOW;
   public static String ACCESS_CONTROL_MAX_AGE;
   public static String IF_UNMODIFIED_SINCE;
   public static String RETRY_AFTER;
   public static String CACHE_CONTROL;
   public static String CONTENT_LOCATION;
   public static String WEBSOCKET_PROTOCOL;
   public static String SEC_WEBSOCKET_ACCEPT;
   public static String SEC_WEBSOCKET_LOCATION;
   public static String AUTHORIZATION;
   public static String SEC_WEBSOCKET_ORIGIN;
   public static String IF_MODIFIED_SINCE;
   public static String CONTENT_BASE;
}
