package recovered.strings;

public class StringTable06 {
   public static String[] recoveredField3959 = new String[]{
      " cannot support property ",
      "appender",
      "No appender named [",
      "] could be found.",
      "ref",
      "Unrecognized element ",
      "Error in extension content: ",
      "class",
      "Class name: [",
      "param",
      "filter",
      "errorHandler",
      "appender-ref",
      "Attaching appender named [",
      "] to appender named [",
      "Requesting attachment of appender named [",
      "] which does not implement org.apache.log4j.spi.AppenderAttachable.",
      "Could not create an Appender. Reported error follows.",
      "logger-ref",
      "root-ref",
      "org.apache.log4j.spi.Filter",
      "Adding filter of type [",
      "Retreiving an instance of org.apache.log4j.Logger.",
      "Desired logger sub-class: [",
      "getLogger",
      "Could not retrieve category [",
      "]. Reported error follows.",
      "additivity",
      "Setting [",
      "] additivity to [",
      "Category Factory tag class attribute not found.",
      "No Category Factory configured.",
      "Desired category factory: [",
      "org.apache.log4j.spi.LoggerFactory",
      "Category Factory class ",
      " does not implement org.apache.log4j.LoggerFactory",
      "Adding appender named [",
      "] to category [",
      "Appender named [",
      "priority",
      "Parsing layout of class: \"",
      "Could not create the Layout. Reported error follows.",
      "renderingClass",
      "renderedClass",
      "Parsing throwableRenderer of class: \"",
      "Could not create the ThrowableRenderer. Reported error follows.",
      "Level value for ",
      " is  [",
      "inherited",
      "Root level cannot be inherited. Ignoring directive.",
      "Desired Level sub-class: [",
      "Could not create level [",
      " level set to ",
      "dummy://log4j.dtd",
      "System property is :",
      "javax.xml.parsers.DocumentBuilderFactory",
      "Standard DocumentBuilderFactory search succeded.",
      "DocumentBuilderFactory is: ",
      "Could not instantiate a DocumentBuilderFactory.",
      "Could not parse ",
      "log4j:configuration",
      "configuration",
      "The <configuration> element has been deprecated.",
      "Use the <log4j:configuration> element instead.",
      "DOM element is - not a <log4j:configuration> element.",
      "debug attribute= \"",
      "Ignoring debug attribute.",
      "reset",
      "reset attribute= \"",
      "configDebug",
      "The \"configDebug\" attribute is deprecated.",
      "Use the \"debug\" attribute instead.",
      "Threshold =\"",
      "categoryFactory",
      "loggerFactory",
      "renderer",
      "throwableRenderer",
      "Could not perform variable substitution.",
      "log4j:event",
      "log4j:NDC",
      "log4j:message",
      "log4j:throwable",
      "\n\t",
      "\t",
      "thread",
      "timestamp",
      "log4j:locationInfo",
      "'%s' is already in use",
      "Thread",
      "Message #",
      "NDC",
      "Category",
      "Thrown",
      "NULL Column",
      "The column number ",
      "must be between 0 and 8",
      "Mipmaps not possible (power of 2 dimensions needed), texture: ",
      ", dim: ",
      "XZ",
      "XYZ",
      "wolf",
      "tail",
      "explode",
      "Disconnected!",
      "Received packet: %s",
      "Closing IPC pipe...",
      "stage",
      "worldborder",
      "commands.worldborder.usage",
      "commands.worldborder.set.usage",
      "commands.worldborder.setSlowly.shrink.success",
      "%.1f",
      "commands.worldborder.setSlowly.grow.success",
      "commands.worldborder.set.success",
      "commands.worldborder.add.usage",
      "commands.worldborder.center.usage",
      "commands.worldborder.center.success",
      "commands.worldborder.damage.usage",
      "commands.worldborder.damage.buffer.usage",
      "commands.worldborder.damage.buffer.success",
      "amount",
      "commands.worldborder.damage.amount.usage",
      "commands.worldborder.damage.amount.success",
      "warning",
      "commands.worldborder.warning.usage",
      "commands.worldborder.warning.time.usage",
      "commands.worldborder.warning.time.success",
      "distance",
      "commands.worldborder.warning.distance.usage",
      "commands.worldborder.warning.distance.success",
      "get",
      "commands.worldborder.get.success",
      "%.0f",
      "textures/entity/beacon_beam.png",
      "note",
      "User-Agent",
      "CheatBreaker-Client",
      "Mozilla/4.0",
      "spider",
      "leg5",
      "leg6",
      "leg7",
      "leg8",
      "of.options.performanceTitle",
      "textures/gui/container/horse.png",
      "arrowKnockback",
      "resourcePack.selected.title",
      "lanServer.start",
      "commands.publish.started",
      "commands.publish.failed",
      "lanServer.otherPlayers",
      "maxChannels: %d (expected: >= 0)",
      "threadFactory",
      "too many channels (max: ",
      "POSITIVE",
      "Towards positive",
      "NEGATIVE",
      "Towards negative",
      "Downloading http texture from {} to {}",
      "commands.particle.usage",
      "commands.particle.notFound",
      "commands.particle.success",
      "Vec2f[",
      "Type \"exit\" to quit JMSSink.",
      "exit",
      "Exiting. Kill the application if it does not exit due to daemon threads.",
      "Could not read JMS message.",
      "Received message is of type ",
      ", was expecting ObjectMessage.",
      "Exception thrown while processing incoming message.",
      "Could not find name [",
      "org.apache.log4j.net.JMSSink",
      " TopicConnectionFactoryBindingName TopicBindingName username password configFile",
      "ChannelPipeline does not contain a HttpResponseDecoder or HttpClientCodec",
      "ChannelPipeline does not contain a HttpRequestEncoder or HttpClientCodec",
      "ws-decoder",
      "EVERYTHING",
      "spacing",
      "separation",
      "failed to create a new socket",
      "Failed to configure the datagram socket timeout.",
      "socket closed",
      " must be bound to join a group.",
      "org.apache.log4j.CategoryKey",
      "minecraft:air",
      "Count",
      "Damage",
      "tag",
      "Unbreakable",
      "ench",
      "display",
      "#%04d/%d%s",
      "#%04d%s",
      " #",
      "HideFlags",
      "Color: #",
      "item.dyed",
      "Lore",
      "attribute.modifier.plus.",
      "attribute.name.",
      "attribute.modifier.take.",
      "item.unbreakable",
      "CanDestroy",
      "item.canBreak",
      "CanPlaceOn",
      "item.canPlace",
      "Durability: ",
      "NBT: ",
      " tag(s)",
      "RepairCost",
      "AttributeModifiers",
      "AttributeName",
      "#.###",
      "end_crystal",
      "cube",
      "Not an instance of RenderEnderCrystal: ",
      "Field not found: RenderEnderCrystal.modelEnderCrystal",
      "Property{",
      "property",
      "Unexpected exception while extracting MDC keys",
      "UP_RIGHT",
      "DOWN_RIGHT",
      "DOWN_LEFT",
      "UP_LEFT",
      "Cannot get property ",
      " as it does not exist in ",
      "Cannot set property ",
      " on block ",
      ", it is not an allowed value",
      "mappedLib is ",
      ".jnilib",
      "URL is ",
      "URL path is ",
      "Couldn't find resource ",
      "Extracting libraries registered in classloader ",
      "AUTOEXTRACT.LIST",
      "Extracting libraries listed in ",
      "Couldn't find native library ",
      "on the classpath",
      "Extracting '",
      "' to '",
      "org.scijava.nativelib.BaseJniExtractor",
      " must produce at least one message.",
      "textures/entity/creeper/creeper_armor.png",
      "-Dio.netty.tmpdir: ",
      " (java.io.tmpdir)",
      " (%TEMP%)",
      " (%USERPROFILE%\\AppData\\Local\\Temp)",
      " (%USERPROFILE%\\Local Settings\\Temp)",
      " ($TMPDIR)",
      "Failed to get the temporary directory; falling back to: ",
      "windows",
      "macosx",
      "osx",
      "META-INF/native/",
      "META-INF/native/lib",
      ".dynlib",
      "could not load a native library: ",
      "[^a-z0-9]+",
      "io.netty.native.workdir",
      "-Dio.netty.netty.workdir: ",
      " (io.netty.tmpdir)",
      "msgInfo",
      "SctpFrame{streamIdentifier=",
      ", protocolIdentifier=",
      ", data=(FREED)}",
      ", data=",
      "Property and user values have different lengths: ",
      " != ",
      "Invalid default value: ",
      " [",
      "], value: ",
      "Result",
      "gui.back",
      "container.enchant",
      "minecraft:enchanting_table",
      "Value",
      "random.orb",
      "Cannot modify read-only score",
      "textures/entity/minecart.png",
      "RSV1 bit can only be set for the first frame.",
      "permessage-deflate",
      "client_no_context_takeover",
      "server_no_context_takeover",
      "permessage-deflate; server_no_context_takeover; client_no_context_takeover",
      "permessage-deflate; server_no_context_takeover",
      "; client_no_context_takeover",
      "RSV1 bit must be set for DataFrames.",
      "bad rsv RSV1: ",
      " RSV2: ",
      " RSV3: ",
      "PerMessageDeflateExtension",
      "Waiting (Background)",
      "Waiting (No Background)",
      "%LABEL%",
      "Unknown?",
      "McRegion",
      "Anvil",
      "0x%05X - %s",
      "Toast",
      "textures/entity/rabbit/brown.png",
      "textures/entity/rabbit/white.png",
      "textures/entity/rabbit/black.png",
      "textures/entity/rabbit/gold.png",
      "textures/entity/rabbit/salt.png",
      "textures/entity/rabbit/white_splotched.png",
      "textures/entity/rabbit/toast.png",
      "textures/entity/rabbit/caerbannog.png",
      "textures/gui/container/brewing_stand.png",
      "This MBean acts as a management facade for a org.apache.log4j.Logger instance.",
      "Received notification: ",
      "The name of this Logger.",
      "The priority of this logger.",
      "add an appender to this logger",
      "appender name",
      "name of the appender",
      "addAppender",
      "addAppender(): add an appender",
      "Hello world.",
      "addAppender called with ",
      "org.apache.log4j.Appender",
      "NULL",
      "Adding AppenderMBean for appender named ",
      " appender.",
      "Could not add appenderMBean for [",
      "org.apache.log4j.jmx.LoggerDynamicMBean",
      "DISABLED",
      "PARANOID",
      "client/icons/sun-64.png",
      "client/icons/moon-64.png",
      "client/icons/volume-mute-64.png",
      "client/icons/volume-up-64.png",
      "client/icons/circle-64.png",
      "client/icons/circle-hollow-64.png",
      "client/icons/letter-t-64.png",
      "client/icons/",
      "Opacity",
      "Volume",
      "World Time",
      "Scale",
      "Scale Multiplier",
      "DESCRIBE",
      "ANNOUNCE",
      "SETUP",
      "PLAY",
      "PAUSE",
      "TEARDOWN",
      "GET_PARAMETER",
      "SET_PARAMETER",
      "REDIRECT",
      "RECORD",
      "Netty Server IO #%d",
      "Playing",
      "Offline for ",
      " day",
      " days",
      " hour",
      " hours",
      " minute",
      " minutes",
      "authSchemes",
      "READ_AUTH_SCHEMES",
      "options.stream.title",
      "options.stream.chat.title",
      "options.stream.ingestSelection",
      "options.stream.changes",
      "Block",
      "DropItem",
      "HurtEntities",
      "FallHurtAmount",
      "FallHurtMax",
      "TileEntityData",
      "TileID",
      "Tile",
      "Immitating block ID",
      "Immitating block data",
      "Auto Text",
      "/skyblock",
      "/play",
      "/lobby",
      "/hub",
      "/spawn",
      "/main",
      "/leave",
      "/warp",
      "/rejoin",
      "Send a command or message with a press of a key or button!",
      "The allowed commands are: ",
      "\\[",
      "\" is not allowed on Hypixel.",
      "You have hit the limit of 50 hotkeys.",
      "Hot key ",
      "/Command",
      "Minimum value cannot be bigger than maximum value!",
      "Default value cannot be lower than minimum value!",
      "Default value cannot be bigger than maximum value!",
      "FATAL",
      "multiplayer.downloadingTerrain",
      "MATCHED",
      "NOT_MATCHED",
      "causes",
      "causes must be non empty",
      "~~NULL~~",
      "~~ERROR~~ ",
      "lightmap",
      "normals",
      "specular",
      "shadowtex0",
      "shadowtex1",
      "depthtex0",
      "depthtex1",
      "shadowcolor0",
      "shadowcolor1",
      "noisetex",
      "gcolor",
      "gdepth",
      "gnormal",
      "composite",
      "gaux1",
      "gaux2",
      "gaux3",
      "gaux4",
      "colortex0",
      "colortex1",
      "colortex2",
      "colortex3",
      "colortex4",
      "colortex5",
      "colortex6",
      "colortex7",
      "gdepthtex",
      "depthtex2",
      "tex",
      "heldItemId",
      "heldBlockLightValue",
      "fogMode",
      "fogColor",
      "skyColor",
      "worldTime",
      "moonPhase",
      "frameTimeCounter",
      "sunAngle",
      "shadowAngle",
      "rainStrength",
      "aspectRatio",
      "viewWidth",
      "viewHeight",
      "near",
      "far",
      "sunPosition",
      "moonPosition",
      "upPosition",
      "previousCameraPosition",
      "cameraPosition",
      "gbufferModelView",
      "gbufferModelViewInverse",
      "gbufferPreviousProjection",
      "gbufferProjection",
      "gbufferProjectionInverse",
      "gbufferPreviousModelView",
      "shadowProjection",
      "shadowProjectionInverse",
      "shadowModelView",
      "shadowModelViewInverse",
      "wetness",
      "eyeAltitude",
      "eyeBrightness",
      "eyeBrightnessSmooth",
      "terrainTextureSize",
      "terrainIconSize",
      "isEyeInWater",
      "hideGUI",
      "centerDepthSmooth",
      "atlasSize",
      ".tooltip.",
      "minecraft:blocks/fire_layer_0",
      "deadmau5",
      "client/icons/nametag/logo_white_",
      "client/icons/nametag/subicons/",
      "textures/misc/shadow.png",
      "textures/entity/iron_golem.png",
      "commands.debug.usage",
      "start",
      "commands.debug.start",
      "commands.debug.notStarted",
      "commands.debug.stop",
      "profile-results-",
      ".txt",
      "Could not save profiler results to ",
      "---- Minecraft Profiler Results ----\n",
      "// ",
      "Time span: ",
      " ms\n",
      "Tick span: ",
      " ticks\n",
      "// This is approximately ",
      " ticks per second. It should be ",
      " ticks per second\n\n",
      "--- BEGIN PROFILE DUMP ---\n\n",
      "--- END PROFILE DUMP ---\n\n",
      "[%02d] ",
      "%/",
      "%\n",
      "unspecified",
      "[[ EXCEPTION ",
      " ]]",
      "Shiny numbers!",
      "Am I not running fast enough? :(",
      "I'm working as hard as I can!",
      "Will I ever be good enough for you? :(",
      "Speedy. Zoooooom!",
      "Hello world",
      "40% better than a crash report.",
      "Now with extra numbers",
      "Now with less numbers",
      "Now with the same numbers",
      "You should add flames to things, it makes them go faster!",
      "Do you feel the need for... optimization?",
      "*cracks redstone whip*",
      "Maybe if you treated it better then it'll have more motivation to work faster! Poor server.",
      "Witty comment unavailable :(",
      "addServer.resourcePack.",
      "ENABLED",
      "PROMPT",
      "prompt",
      "maxFrameSize must be > 0",
      "WebSocket frame was not of type TextWebSocketFrame or BinaryWebSocketFrame",
      "WebSocketFrame length exceeded ",
      "minecraft:chest",
      "(Unknown)",
      "Banned by an operator.",
      "created",
      "reason",
      "forever",
      "Armor Status",
      "Item Name",
      "Item Count",
      "Equipped Item",
      "Damage Options",
      "Damage Overlay",
      "Show Damage Amount",
      "If Damaged",
      "Show Item Damage",
      "Show Armor Damage",
      "Show Max Damage",
      "Damage Display",
      "Damage Display Type",
      "Percent",
      "Damage Threshold Type",
      "7",
      "client/icons/mods/diamond_chestplate.png",
      "Displays your current armor and holding item durability.",
      "vertical",
      "horizontal",
      "Seed",
      "IngestTester.stopCallback failed to stop - ",
      "Already connected",
      "Timeout ",
      "Response out of order: ",
      "http:",
      "Connection not keep-alive",
      ",;",
      "^[a-zA-Z]+://.*",
      "Something went wrong when converting from HSV to RGB. Input was ",
      "RIFF",
      "DDC_SUCCESS",
      "DDC_FAILURE",
      "DDC_OUT_OF_MEMORY",
      "DDC_FILE_ERROR",
      "DDC_INVALID_CALL",
      "DDC_USER_ABORT",
      "DDC_INVALID_FILE",
      "Unknown Error",
      "(Reflector) More than one method found: ",
      "(Reflector)  - ",
      "North Carolina",
      "cached(",
      "textures/entity/experience_orb.png",
      "Tree.textBackground",
      "/org/apache/log4j/lf5/viewer/images/channelexplorer_satellite.gif",
      " contains a total of ",
      " LogRecords.",
      " Right-click for more info.",
      "[^a-z]",
      "DARK_BLUE",
      "DARK_GREEN",
      "DARK_AQUA",
      "DARK_RED",
      "DARK_PURPLE",
      "GOLD",
      "DARK_GRAY",
      "AQUA",
      "LIGHT_PURPLE",
      "OBFUSCATED",
      "BOLD",
      "STRIKETHROUGH",
      "UNDERLINE",
      "ITALIC",
      "(?i)§[0-9A-FK-OR]",
      "(?i)§[0-9A-FR]",
      "buy",
      "sell",
      "buyB",
      "uses",
      "maxUses",
      "rewardExp",
      "thread was not started",
      "delay: %d (expected: >= 0)",
      "callable",
      "initialDelay: %d (expected: >= 0)",
      "period: %d (expected: > 0)",
      "delay: %d (expected: > 0)",
      ".slice(",
      "sliced buffer",
      "RFC2253",
      "TransferCooldown",
      "minecraft:hopper",
      "addServer.add",
      "addServer.resourcePack",
      "addServer.title",
      "addServer.enterName",
      "RAIN",
      "THUNDER",
      "Only GZIP or ZLIB is supported, but you used ",
      "decompression failure, unable to set dictionary as non was specified",
      "Input is not in the GZIP format",
      "Unsupported compression method ",
      " in the GZIP header",
      "Reserved flags are set in the GZIP header",
      "Number of bytes mismatch. Expected: ",
      ", Got: ",
      "CRC value missmatch. Expected: ",
      "Outdated server! I'm still on 1.8.9",
      "Outdated client! Please use 1.8.9",
      "Invalid intention ",
      "MMM dd HH:mm:ss ",
      "\" is an unknown syslog facility. Defaulting to \"USER\".",
      "user:",
      "kern",
      "user",
      "mail",
      "daemon",
      "auth",
      "syslog",
      "lpr",
      "news",
      "uucp",
      "cron",
      "authpriv",
      "ftp",
      "local0",
      "local1",
      "local2",
      "local3",
      "local4",
      "local5",
      "local6",
      "local7",
      "KERN",
      "USER",
      "MAIL",
      "DAEMON",
      "SYSLOG",
      "LPR",
      "NEWS",
      "UUCP",
      "CRON",
      "AUTHPRIV",
      "FTP",
      "LOCAL0",
      "LOCAL1",
      "LOCAL2",
      "LOCAL3",
      "LOCAL4",
      "LOCAL5",
      "LOCAL6",
      "LOCAL7",
      "No syslog host is set for SyslogAppedender named \"",
      "] is an unknown syslog facility. Defaulting to [USER].",
      "UNKNOWN_HOST",
      "the elder scrolls klaatu berata niktu xyzzy bless curse light darkness fire air earth water hot dry cold wet ignite snuff embiggen twist shorten stretch fiddle destroy imbue galvanize enchant free limited range of towards inside sphere cube self other ball mental physical grow shrink demon elemental spirit animal creature beast humanoid undead fresh stale ",
      "bottle_splash",
      "bottle_drinkable",
      "difficulty",
      "commands.difficulty.usage",
      "commands.difficulty.success",
      "peaceful",
      "easy",
      "n",
      "hard",
      "Not found in: ",
      "Failed to find constructor",
      "Failed to create entry",
      "NO_AUTH",
      "AUTH_GSSAPI",
      "values",
      "waist",
      "success",
      "failure(",
      "unfinished",
      ".UNFINISHED",
      ".SUCCESS",
      "[Shaders] Delayed loading of item mappings after resources are loaded",
      "/shaders/item.properties",
      "shaders/item.properties",
      "[Shaders] Parsing item mappings: ",
      "[Shaders] Invalid item ID: ",
      "[Shaders] Invalid item alias ID: ",
      "[Shaders] Invalid item ID mapping: ",
      "textures/entity/arrow.png",
      "stats",
      "commands.stats.usage",
      "commands.stats.block.usage",
      "commands.stats.entity.usage",
      "commands.stats.block.set.usage",
      "commands.stats.entity.set.usage",
      "clear",
      "commands.stats.block.clear.usage",
      "commands.stats.entity.clear.usage",
      "commands.stats.failed",
      "commands.stats.noCompatibleBlock",
      "commands.stats.success",
      "commands.stats.cleared",
      "textures/entity/skeleton/skeleton.png",
      "textures/entity/skeleton/wither_skeleton.png",
      "Debug",
      "LogRecord: [",
      "fireworks.launch",
      "Life",
      "LifeTime",
      "FireworksItem",
      "LogFactor5",
      "0123456789abcdefklmnor",
      "Wrong component type",
      "JDK",
      "OPENSSL",
      "A task raised an exception.",
      "Shutdown hook raised an exception.",
      "quietPeriod: ",
      " (expected >= 0)",
      "timeout: ",
      " (expected >= quietPeriod (",
      "must be invoked from an event loop",
      "cannot await termination of the current thread",
      "event executor terminated",
      "java.vm.info",
      "), ",
      "java.vm.vendor",
      "textures/entity/explosion.png",
      "filled_map",
      "textures/entity/slime/magmacube.png",
      "Marker name cannot be null",
      "map_",
      "soundCategory.",
      "Boss Bar",
      "Render Text",
      "Render Health",
      "Boss Bar Texture",
      "Texture Pack",
      "Blurred",
      "Custom",
      "Text Position",
      "Boss Bar Width",
      "Boss Bar Height",
      "Boss Bar Color",
      "Top Boss Bar Color",
      "Bottom Boss Bar Color",
      "Outline Boss Bar Color",
      "client/icons/mods/bossbar.png",
      "Displays the current boss and health.",
      "client/icons/bossbar/",
      "ban-ip",
      "commands.banip.usage",
      "commands.banip.invalid",
      "You have been IP banned.",
      "commands.banip.success",
      "commands.banip.success.players",
      "^([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])$",
      "Press Shift + Tab",
      "CommandStats",
      "RFC1738",
      "RFC3986",
      "segments",
      "segmentShift",
      "segmentMask",
      "sizeCtl",
      "transferIndex",
      "transferOrigin",
      "baseCount",
      "cellsBusy",
      "Throwable",
      "throwable",
      "ambient.weather.thunder",
      "random.explode",
      "minecraft:blocks/destroy_stage_",
      "shaders/post/entity_outline.json",
      "final",
      "Failed to load shader: ",
      "prepare",
      "global",
      "entityOutlines",
      "entities",
      "blockentities",
      "C: %d/%d %sD: %d, %s",
      "(s) ",
      "E: ",
      ", B: ",
      ", I: ",
      "camera",
      "renderlistcamera",
      "cull",
      "culling",
      "update",
      "iteration",
      "captureFrustum",
      "rebuildNear",
      "build near",
      "translucent_sort",
      "filterempty",
      "render_",
      "Exception while adding particle",
      "Particle being added",
      "ID",
      "Parameters",
      "Position",
      "mob.wither.spawn",
      "mob.enderdragon.end",
      "random.click",
      "random.door_open",
      "records.",
      "random.door_close",
      "mob.ghast.charge",
      "mob.ghast.fireball",
      "mob.zombie.wood",
      "mob.zombie.metal",
      "mob.zombie.woodbreak",
      "mob.wither.shoot",
      "mob.bat.takeoff",
      "mob.zombie.infect",
      "mob.zombie.unfect",
      "random.anvil_break",
      "random.anvil_use",
      "game.potion.smash",
      "textures/environment/moon_phases.png",
      "textures/environment/sun.png",
      "textures/environment/clouds.png",
      "textures/misc/forcefield.png",
      "SOLID",
      "Solid",
      "CUTOUT_MIPPED",
      "Mipped Cutout",
      "CUTOUT",
      "Cutout",
      "TRANSLUCENT",
      "Translucent",
      "Show icon",
      "Show an icon corresponding to the mod.",
      "Extend Width",
      "Scale Text",
      "Block not found for id: ",
      "Block not found for name: ",
      "Invalid block property: ",
      "Property not found: ",
      ", block: ",
      "Property value not found: ",
      ", property: ",
      "Biome not found: ",
      "nether",
      "Invalid number: ",
      " ,",
      "Invalid interval: ",
      ", when parsing: ",
      "sides",
      "Unknown face: ",
      "Invalid boolean: ",
      "Invalid profession: ",
      "farmer",
      "librarian",
      "priest",
      "blacksmith",
      "butcher",
      "nitwit",
      "fisherman",
      "shepherd",
      "fletcher",
      "cartographer",
      "cleric",
      "weapon",
      "tool",
      "Item has no ID: ",
      ", name: ",
      "IMMEDIATE",
      "QUEUED",
      "CHECK",
      "IS_ALIVE",
      "is_alive",
      "IS_BURNING",
      "is_burning",
      "IS_CHILD",
      "is_child",
      "IS_GLOWING",
      "is_glowing",
      "IS_HURT",
      "is_hurt",
      "IS_IN_LAVA",
      "is_in_lava",
      "IS_IN_WATER",
      "is_in_water",
      "IS_INVISIBLE",
      "is_invisible",
      "IS_ON_GROUND",
      "is_on_ground",
      "IS_RIDDEN",
      "is_ridden",
      "IS_RIDING",
      "is_riding",
      "IS_SNEAKING",
      "is_sneaking",
      "IS_SPRINTING",
      "is_sprinting",
      "IS_WET",
      "is_wet",
      "java.lang.Throwable",
      "getStackTrace",
      "java.lang.StackTraceElement",
      "getClassName",
      "\tat ",
      "Attribute",
      "FileUpload",
      "InternalAttribute",
      "optifine/gui/loading/background",
      "Invalid dimension ID: ",
      "optifine/gui/loading/loading.properties",
      "CustomLoadingScreens",
      "CustomLoadingScreen: ",
      "Vec2d[",
      "Required array size too large",
      "(this Collection)",
      "client/icons/info-64.png",
      "ExternallyRolledFileAppender-HUP",
      "UNDEAD",
      "ARTHROPOD",
      "Created Dash Manager",
      "pointer cannot be null",
      "#/",
      "utf-8",
      "a JSON pointer should start with '/' or '#/'",
      "~1",
      "~0",
      "\\\\",
      "\\",
      "value [%s] is not an array or object therefore its key %s cannot be resolved",
      "index %d is out of bounds - the array has %d elements",
      "%s is not an array index",
      "deop",
      "commands.deop.usage",
      "commands.deop.failed",
      "commands.deop.success",
      "LABEL",
      "ICON",
      "textures/map/map_icons.png",
      "initialArray",
      "expected not same",
      "expected same:<",
      "> was not:<",
      "expected:<",
      "> but was:<",
      "Environment Changer",
      "Allows you to change the environment around you to your liking.",
      "Fyu (Time Changer)",
      "Sk1er (Snow)",
      "client/icons/mods/env-changer.png",
      "Time Settings",
      "Time Type",
      "Real Time",
      "Time Multiplier Type",
      "Accelerate",
      "Decelerate",
      "Time Multiplier Delay",
      "Time Multiplier Amount",
      "Increase/Decrease Amount",
      "Increase Time Keybind",
      "Decrease Time Keybind",
      "Weather Settings",
      "Allow Through Blocks",
      "Custom Weather",
      "Current Weather",
      "Clear",
      "Rain",
      "Snow",
      "seamless",
      "iron_golem",
      "left_arm",
      "right_arm",
      "java.lang.Boolean",
      "java.lang.Object",
      "In strange state",
      "Total time [ms]: ",
      " in update, size: ",
      "org.apache.log4j.chainsaw.MyTableModel",
      "Priority",
      "Trace",
      "THIRD_PERSON",
      "FIRST_PERSON",
      "HEAD",
      "GUI",
      "GROUND",
      "FIXED",
      "# #",
      "#-",
      "#E#",
      "RGR",
      "GGG",
      "GSG",
      "OOO",
      "NN",
      "CQ",
      "QC",
      "DG",
      "GD",
      "SS",
      "SSS",
      "SIS",
      "SCS"
   };
}
