package recovered.strings;

public class StringTable04 {
   public static String[] recoveredField3967 = new String[]{
      "Delta-Window-Size must be positive: ",
      "--> Delta-Window-Size = ",
      "item.fireCharge.use",
      "VCount",
      "Above",
      "Below",
      "At",
      "Not At",
      "Change the scale of the mod.",
      "1.0x",
      "GUI Scale",
      "Toggle Mod Keybind",
      "Toggle HUD Keybind",
      "Temp Toggle HUD Keybind",
      "commands.weather.usage",
      "commands.weather.clear",
      "commands.weather.rain",
      "commands.weather.thunder",
      "Payload may not be larger than 32767 bytes",
      "Sending Custom Payload with Channel: ",
      "Channel: ",
      "Client (map_client.txt)",
      "mob.bat.idle",
      "mob.bat.hurt",
      "mob.bat.death",
      "BatFlags",
      "OpenGL 1.3, ARB_copy_buffer",
      "OpenGL 1.4",
      "VboRegions not supported, missing: ",
      "Using ARB_multitexture.\n",
      "Using GL 1.3 multitexturing.\n",
      "Using ARB_texture_env_combine.\n",
      "Using GL 1.3 texture combiners.\n",
      "Using framebuffer objects because ",
      "OpenGL 3.0 is supported and separate blending is supported.\n",
      "ARB_framebuffer_object is supported and separate blending is supported.\n",
      "EXT_framebuffer_object is supported.\n",
      "Not using framebuffer objects because ",
      "OpenGL 1.4 is ",
      "not ",
      "supported, ",
      "EXT_blend_func_separate is ",
      "OpenGL 3.0 is ",
      "ARB_framebuffer_object is ",
      "supported, and ",
      "EXT_framebuffer_object is ",
      "supported.\n",
      "Shaders are ",
      "available because ",
      "OpenGL 2.1 is supported.\n",
      "ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.\n",
      "OpenGL 2.1 is ",
      "ARB_shader_objects is ",
      "ARB_vertex_shader is ",
      "ARB_fragment_shader is ",
      "VBOs are ",
      "ARB_vertex_buffer_object is supported.\n",
      "OpenGL 1.5 is supported.\n",
      "%dx %s",
      "\\s+",
      "<unknown>",
      " ...",
      "note.",
      "harp",
      "bd",
      "snare",
      "bassattack",
      "Netty Local Server IO #%d",
      "Chunk file at ",
      " is missing level data, skipping",
      " is missing block data, skipping",
      " is in the wrong location; relocating. (Expected ",
      "Failed to save chunk",
      "ThreadedAnvilChunkStorage ({}): All chunks are saved",
      "LightPopulated",
      "InhabitedTime",
      "Add",
      "Framedata{ optcode:",
      ", fin:",
      ", rsv1:",
      ", rsv2:",
      ", rsv3:",
      ", payloadlength:[pos:",
      ", len:",
      "], payload:",
      "(too big to display)",
      "Supplied opcode cannot be null",
      "Supplied opcode is invalid",
      "DOMAIN",
      "ocelot",
      "container.minecart",
      "item.fireworksCharge.type.",
      "item.fireworksCharge.type",
      "item.fireworksCharge.",
      "item.fireworksCharge.customColor",
      "item.fireworksCharge.fadeTo",
      "item.fireworksCharge.trail",
      "item.fireworksCharge.flicker",
      "Console",
      "wsReconnect",
      "Invalid URL: ",
      "banwave start",
      "Tellinq",
      "Moose1301",
      "Noxiuam",
      "98ping",
      "Serversided",
      "dollarsignjay",
      "FreddieJLH",
      "Decencies",
      " has been CheatBreaker Banned (#000",
      "resetInterval: ",
      ".OOS",
      "bufferSize must greater than 0: ",
      "TelnetAppender v1.0 (",
      " active connections)\r\n\r\n",
      "Too many connections.\r\n",
      "Encountered error while in SocketHandler loop.",
      "TelnetAppender-",
      "Suppressed ",
      " OpenGL errors",
      "GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT",
      "GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT",
      "GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER",
      "GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER",
      "glCheckFramebufferStatus returned unknown status:",
      " Subfolder",
      " Subfolders",
      " Pack",
      " Packs",
      "Back to Main Folder",
      "client/icons/folder.png",
      "DiffuseSampler",
      "AuxSize",
      "ProjMat",
      "InSize",
      "OutSize",
      "ScreenSize"
   };
}
