package recovered.strings;

public class StringTable02 {
   public static String[] recoveredField3955 = new String[]{
      "netherrack",
      "soul_sand",
      "glowstone",
      "lit_pumpkin",
      "cake",
      "unpowered_repeater",
      "powered_repeater",
      "trapdoor",
      "monster_egg",
      "stonebrick",
      "brown_mushroom_block",
      "red_mushroom_block",
      "iron_bars",
      "glass_pane",
      "melon_block",
      "pumpkin_stem",
      "melon_stem",
      "vine",
      "fence_gate",
      "spruce_fence_gate",
      "birch_fence_gate",
      "jungle_fence_gate",
      "dark_oak_fence_gate",
      "acacia_fence_gate",
      "brick_stairs",
      "stone_brick_stairs",
      "mycelium",
      "waterlily",
      "nether_brick",
      "nether_brick_fence",
      "nether_brick_stairs",
      "nether_wart",
      "enchanting_table",
      "brewing_stand",
      "cauldron",
      "end_portal",
      "end_portal_frame",
      "end_stone",
      "dragon_egg",
      "redstone_lamp",
      "lit_redstone_lamp",
      "double_wooden_slab",
      "wooden_slab",
      "cocoa",
      "sandstone_stairs",
      "emerald_ore",
      "ender_chest",
      "tripwire_hook",
      "tripwire",
      "emerald_block",
      "spruce_stairs",
      "birch_stairs",
      "jungle_stairs",
      "command_block",
      "beacon",
      "cobblestone_wall",
      "flower_pot",
      "carrots",
      "potatoes",
      "wooden_button",
      "skull",
      "anvil",
      "trapped_chest",
      "light_weighted_pressure_plate",
      "heavy_weighted_pressure_plate",
      "unpowered_comparator",
      "powered_comparator",
      "daylight_detector",
      "daylight_detector_inverted",
      "redstone_block",
      "quartz_ore",
      "hopper",
      "quartz_block",
      "quartz_stairs",
      "activator_rail",
      "dropper",
      "stained_hardened_clay",
      "barrier",
      "iron_trapdoor",
      "hay_block",
      "carpet",
      "hardened_clay",
      "coal_block",
      "packed_ice",
      "acacia_stairs",
      "dark_oak_stairs",
      "slime",
      "double_plant",
      "stained_glass",
      "stained_glass_pane",
      "prismarine",
      "sea_lantern",
      "standing_banner",
      "wall_banner",
      "red_sandstone",
      "red_sandstone_stairs",
      "double_stone_slab2",
      "stone_slab2",
      "Duplicate enchantment id!",
      "enchantment.",
      "enchantment.level.",
      "protection",
      "fire_protection",
      "feather_falling",
      "blast_protection",
      "projectile_protection",
      "respiration",
      "aqua_affinity",
      "depth_strider",
      "sharpness",
      "smite",
      "bane_of_arthropods",
      "knockback",
      "fire_aspect",
      "looting",
      "efficiency",
      "silk_touch",
      "unbreaking",
      "fortune",
      "power",
      "punch",
      "flame",
      "infinity",
      "luck_of_the_sea",
      "lure",
      "#X#",
      "##",
      "blur",
      "clamp",
      "mipmaps",
      "Invalid texture->mipmap->",
      ": expected number, was ",
      "Invalid texture->mipmaps: expected array, was ",
      "Content-Encoding",
      "identity",
      "gzip",
      "deflate",
      "file [",
      "Combo Counter",
      "[6 Combo]",
      "Displays how many times you hit someone in a row within 2 seconds.",
      "Erouax",
      "Combo",
      "No %LABEL%",
      "6",
      "-wait",
      "-c",
      "-m",
      "-v",
      "JUnit ",
      " by Kent Beck and Erich Gamma",
      "Usage: TestRunner [-wait] testCaseName, where name is the name of the TestCase class",
      "Could not create and run test suite: ",
      "Cooldowns",
      "Color Theme",
      "Bright",
      "Dark",
      "Colored",
      "No Ring",
      "List Mode",
      "Horizontal",
      "Vertical",
      "Use Pearl Cooldown via XP",
      "Colored color",
      "Allows servers to display items or abilities that are on cooldown.",
      "CombatTag",
      "EnderPearl",
      "textures/environment/end_sky.png",
      "textures/entity/end_portal.png",
      "@Sharable annotation is not allowed",
      "executor",
      "GlobalTC",
      "doFireTick",
      "Netty Epoll Client IO #%d",
      "progress: ",
      " (expected: 0 <= progress <= total (",
      "))",
      "complete already",
      "byteOrder",
      "maxFrameLength must be a positive integer: ",
      "lengthFieldOffset must be a non-negative integer: ",
      "initialBytesToStrip must be a non-negative integer: ",
      "maxFrameLength (",
      "must be equal to or greater than ",
      "lengthFieldOffset (",
      ") + ",
      "lengthFieldLength (",
      "negative pre-adjustment length field: ",
      "Adjusted frame length (",
      ") is less ",
      "than lengthFieldEndOffset: ",
      "than initialBytesToStrip: ",
      "unsupported lengthFieldLength: ",
      " (expected: 1, 2, 3, 4, or 8)",
      "Adjusted frame length exceeds ",
      " - discarded",
      " - discarding",
      "book",
      "cover_right",
      "cover_left",
      "pages_right",
      "pages_left",
      "flipping_page_right",
      "flipping_page_left",
      "book_spine",
      "Field not found: TileEntityEnchantmentTableRenderer.modelBook",
      "failed to create a server socket",
      "socket",
      "Failed to set the server socket timeout.",
      "Failed to create a new channel from an accepted socket.",
      "Failed to close a socket.",
      "options.skinCustomisation.title",
      "of.options.skinCustomisation.ofCape",
      "options.on",
      "options.off",
      "Posted by ",
      "Entity render map not found, custom entity models are DISABLED.",
      "Tile entity render map not found, custom entity models are DISABLED.",
      "CustomEntityModel: ",
      "Unknown renderer type: ",
      "optifine/cem/",
      ".jem",
      "Entity not found: ",
      "Entity class not found: ",
      "Entity renderer is null, model: ",
      ", adapter: ",
      "Model part not found: ",
      ", model: ",
      "textures/entity/silverfish.png",
      "READ_PREFFERED_AUTH_TYPE",
      "doDaylightCycle",
      "mobSpawner",
      "doMobSpawning",
      "chunkSource",
      "tickPending",
      "tickBlocks",
      "chunkMap",
      "village",
      "portalForcer",
      "getChunk",
      "tickChunk",
      "thunder",
      "iceandsnow",
      "randomTickSpeed",
      "TickNextTick list out of synch",
      "cleaning",
      "ticking",
      "Exception while ticking a block",
      "Block being ticked",
      "Exception initializing level",
      "Unable to find spawn biome",
      "Saving level",
      "Saving chunks",
      "Invalid ",
      "File not found",
      "Naruto Run",
      "Stream-ID must be positive: ",
      "3.8.2",
      "ROUGH",
      "rough",
      "BRICKS",
      "prismarine_bricks",
      "bricks",
      "DARK",
      "dark_prismarine",
      "dark",
      "icons/failure.gif",
      "icons/error.gif",
      "client/icons/star-64.png",
      "textures/gui/resource_packs.png",
      "textures/misc/unknown_pack.png",
      "enchantment.damage.",
      "all",
      "undead",
      "arthropods",
      "Probably not. Jar signature remains and client brand is untouched.",
      "Sprint Reset Counter",
      "[4 WTaps]",
      "Displays the amount of times you sprint reset.",
      "AgentManny",
      "Forward",
      "Higher",
      "Tap",
      "4",
      "Counter",
      "Backwards",
      "Hide When Not Attacking",
      "optifine/block.properties",
      "CustomBlockLayers",
      "shaders/block.properties",
      "CustomBlockLayers: ",
      "solid",
      "cutout",
      "cutout_mipped",
      "translucent",
      "layer.",
      "CustomBlockLayers: Block layer is already set, block: ",
      ", layer: ",
      "vertex: ",
      ", tint: ",
      ", facing: ",
      ", sprite: ",
      "toLevel",
      "Level deserialization failed, reverting to default.",
      "org.apache.log4j.Level",
      "a text frame should not contain 0xFF.",
      "x-gzip",
      "x-deflate",
      "%r [%t] %p %c %x - %m%n",
      "death.attack.",
      ".item",
      "4F",
      "2F",
      "NaturalTextures: Unknown type: ",
      "Nether",
      "_nether",
      "GetFloat not supported for: ",
      "SetFloat not supported for: ",
      "POS_X",
      "tx",
      "POS_Y",
      "ty",
      "POS_Z",
      "tz",
      "ANGLE_X",
      "rx",
      "ANGLE_Y",
      "ry",
      "ANGLE_Z",
      "rz",
      "OFFSET_X",
      "ox",
      "OFFSET_Y",
      "oy",
      "OFFSET_Z",
      "oz",
      "SCALE_X",
      "sx",
      "SCALE_Y",
      "sy",
      "SCALE_Z",
      "sz",
      "/assets/minecraft/lang/en_US.lang",
      "%$1s",
      "Format error: ",
      "%(\\d+\\$)?[\\d\\.]*[df]",
      "§8",
      "of.general.id",
      "of.general.from",
      "of.general.ambiguous",
      "\\. ",
      "- ",
      "options.language",
      "options.languageWarning",
      "HELLO",
      "KEY",
      "AUTHENTICATING",
      "READY_TO_ACCEPT",
      "DELAY_ACCEPT",
      "ACCEPTED",
      " - ",
      "Sound engine started",
      "Clock",
      "[11:11 AM]",
      "Displays the current time.",
      "h",
      "HH",
      ":mm",
      ":ss",
      " a",
      "Military (24 hour) time",
      "Show the clock time in military time format.",
      "Show Meridiem (AM/PM) Marker",
      "Show the AM/PM marker.",
      "Show Seconds",
      "Displays the seconds.",
      "mob.slime.big",
      "mob.slime.small",
      "SOCKS_CMD_REQUEST_DECODER",
      "spawnpoint",
      "commands.spawnpoint.usage",
      "commands.spawnpoint.success",
      "ID is already registered: ",
      "Cannot register to reserved id: ",
      "Cannot register null clazz for id: ",
      "Minecart",
      "Skipping Entity with id ",
      "XPOrb",
      "ThrownEgg",
      "LeashKnot",
      "Painting",
      "Arrow",
      "Snowball",
      "Fireball",
      "SmallFireball",
      "ThrownEnderpearl",
      "EyeOfEnderSignal",
      "ThrownPotion",
      "ThrownExpBottle",
      "ItemFrame",
      "WitherSkull",
      "PrimedTnt",
      "FallingSand",
      "FireworksRocketEntity",
      "ArmorStand",
      "Boat",
      "Monster",
      "Creeper",
      "Skeleton",
      "Spider",
      "Giant",
      "Zombie",
      "Slime",
      "Ghast",
      "PigZombie",
      "Enderman",
      "CaveSpider",
      "Silverfish",
      "LavaSlime",
      "EnderDragon",
      "WitherBoss",
      "Bat",
      "Witch",
      "Endermite",
      "Guardian",
      "Pig",
      "Sheep",
      "Cow",
      "Chicken",
      "Squid",
      "Wolf",
      "MushroomCow",
      "SnowMan",
      "Ozelot",
      "VillagerGolem",
      "EntityHorse",
      "Rabbit",
      "Villager",
      "EnderCrystal",
      "CustomEntityModels",
      "shadowSize",
      "Missing models",
      "model",
      ".jpm",
      "Model not found: ",
      "./",
      "~/",
      "Empty model ID: ",
      "part",
      "Model part not specified, missing \"replace\" or \"attachTo\".",
      "attach",
      "animations",
      "bape ship#5604",
      "5604-2.0++-2/28/2020",
      "[C",
      "B",
      "Credits: ",
      "CheatBreaker LLC for the original client.",
      "Tellinq and Moose1301 for managing this version.",
      "88051637-26cb-49a4-8f42-04e06264de79",
      "2f6f44cf-19a2-442a-944b-ede88be55651",
      "DIRT",
      "COARSE_DIRT",
      "coarse_dirt",
      "coarse",
      "PODZOL",
      "podzol",
      "minecraft:minecart.inside",
      "log4j: ",
      "log4j:ERROR ",
      "log4j:WARN ",
      "log4j.debug",
      "log4j.configDebug",
      "loading",
      "filterstack",
      "Class not found \"",
      "suite",
      "Suite() method must be static",
      "Failed to invoke suite():",
      "-noloading",
      "-nofilterstack",
      "Missing Test class name",
      "Default package for",
      "junit.properties",
      "com.ibm.uvm.tools.DebugSupport",
      "mrj.version",
      "junit.framework.TestCase",
      "junit.framework.TestResult",
      "junit.framework.TestSuite",
      "junit.framework.Assert.",
      "junit.swingui.TestRunner",
      "junit.awtui.TestRunner",
      "junit.textui.TestRunner",
      "java.lang.reflect.Method.invoke(",
      "maxmessage",
      " M",
      "Resume",
      "Pause",
      "WebSocketWorker-",
      "Error while reading from remote connection",
      "Please avoid temperatures in the range 0.1 - 0.2 because of snow",
      "Biome ID is out of bounds: ",
      ", defaulting to 0 (Ocean)",
      "Ocean",
      "Plains",
      "Desert",
      "Extreme Hills",
      "Forest",
      "Taiga",
      "Swampland",
      "River",
      "Hell",
      "The End",
      "FrozenOcean",
      "FrozenRiver",
      "Ice Plains",
      "Ice Mountains",
      "MushroomIsland",
      "MushroomIslandShore",
      "Beach",
      "DesertHills",
      "ForestHills",
      "TaigaHills",
      "Extreme Hills Edge",
      "Jungle",
      "JungleHills",
      "JungleEdge",
      "Deep Ocean",
      "Stone Beach",
      "Cold Beach",
      "Birch Forest",
      "Birch Forest Hills",
      "Roofed Forest",
      "Cold Taiga",
      "Cold Taiga Hills",
      "Mega Taiga",
      "Mega Taiga Hills",
      "Extreme Hills+",
      "Savanna",
      "Savanna Plateau",
      "Mesa",
      "Mesa Plateau F",
      "Mesa Plateau",
      "Redwood Taiga Hills M",
      "Biome \"",
      "\" is defined as both ID ",
      "textures/entity/enderman/enderman.png",
      "UTF-8",
      "Unable to encode SMTP subject",
      "Could not activate SMTPAppender options.",
      "mail.smtp",
      "mail.transport.protocol",
      "mail.",
      ".host",
      ".port",
      ".auth",
      "rfc822",
      "Message object not configured.",
      "No TriggeringEventEvaluator is set for appender [",
      "No layout set for appender named [",
      "Could not parse address [",
      "quoted-printable",
      "; charset=UTF-8",
      "Content-Transfer-Encoding",
      "Error occured while sending e-mail notification.",
      "org.apache.log4j.spi.TriggeringEventEvaluator",
      "trigger",
      "triggeringPolicy",
      "alloc",
      "BE",
      "LE",
      "endianness",
      "minWritableBytes: ",
      "MOSSY",
      "mossy_stonebrick",
      "mossy",
      "CRACKED",
      "cracked_stonebrick",
      "cracked",
      "CHISELED",
      "chiseled_stonebrick",
      "chiseled",
      "This MBean acts as a management facade for org.apache.log4j.Hierarchy.",
      "HierarchyDynamicMBean(): Constructs a HierarchyDynamicMBean instance",
      "threshold",
      "The \"threshold\" state of the hiearchy.",
      "Create a logger MBean",
      "addLoggerMBean",
      "addLoggerMBean(): add a loggerMBean",
      "javax.management.ObjectName",
      "log4j",
      "logger",
      "addAppender.",
      "---Adding logger [",
      "] as listener.",
      "logger=",
      "The ",
      " logger.",
      "Could not add loggerMBean for [",
      "Operation name cannot be null",
      "Cannot invoke a null operation in ",
      "Cannot find the operation ",
      " in ",
      "Attribute name cannot be null",
      " with null attribute name",
      "Called getAttribute with [",
      "%3D",
      "log4j:",
      "Could not create ObjectName",
      "Cannot find ",
      " attribute in ",
      "addAppenderEvent called: logger=",
      ", appender=",
      "sending notification.",
      "removeAppenderCalled: logger=",
      "postRegister is called.",
      "Attribute cannot be null",
      " with null attribute",
      "Cannot invoke the setter of ",
      "org.apache.log4j.jmx.HierarchyDynamicMBean",
      "mob.cow.say",
      "mob.cow.hurt",
      "mob.cow.step",
      " R ",
      "CPM",
      " B ",
      "CPD",
      "MMM",
      "M",
      "fast",
      "fancy",
      "Fast",
      "Fancy",
      "optifine/textures/icons.png",
      "this",
      "Keybind",
      "position must be >= 0 but was ",
      "count must be >= 0 but was ",
      "position out of range: ",
      " (expected: 0 - ",
      "DIM-1",
      "DIM1",
      "Sec-WebSocket-Key",
      "not a WebSocket request: missing key",
      "258EAFA5-E914-47DA-95CA-C5AB0DC85B11",
      "WebSocket version 07 server handshake key: {}, response: {}.",
      "Upgrade",
      "WebSocket",
      "Connection",
      "Sec-WebSocket-Accept",
      "Sec-WebSocket-Protocol",
      "Requested subprotocol(s) not supported: {}",
      "Full Location",
      "fullLocation",
      "client/icons/cog-64.png",
      "eye-64.png",
      "?",
      "Bug report",
      "Staff Mods",
      "Mods",
      "cog-64.png",
      "profiles-64.png",
      "Zans",
      "Bug Description (Press ENTER to send)",
      "| CHEAT",
      "BREAKER",
      "Shortcuts & Movement",
      "CMD",
      "CTRL",
      "Mouse1",
      "| ",
      "HOLD",
      " Add mods to selected region",
      " Select & drag mods",
      "Mouse2",
      "CLICK",
      " Reset mod to closest position",
      " Don't lock mods while dragging",
      "+",
      "| Toggle (multiple) mod selection",
      "A",
      "| Select all mods",
      "| Remove selected mod(s) from HUD",
      "| Reset selected mod(s) scale",
      "| Undo mod movements",
      "| Redo mod movements",
      "SHIFT",
      "Arrows",
      "| Smaller mod movements",
      "| Larger mod movements",
      "Up",
      "Left",
      "Down",
      "Right",
      "| Move selected mod(s) with precision",
      " (Hidden)",
      "createWorld.customize.presets.title",
      "createWorld.customize.presets.share",
      "createWorld.customize.presets.list",
      "createWorld.customize.presets.select",
      "Classic Flat",
      "Tunnelers' Dream",
      "biome_1",
      "dungeon",
      "decoration",
      "stronghold",
      "mineshaft",
      "Water World",
      "oceanmonument",
      "Overworld",
      "lake",
      "lava_lake",
      "Snowy Kingdom",
      "Bottomless Pit",
      "Redstone Ready",
      "Potion",
      "potionValue",
      "textures/entity/horse/horse_white.png",
      "textures/entity/horse/mule.png",
      "textures/entity/horse/donkey.png",
      "textures/entity/horse/horse_zombie.png",
      "textures/entity/horse/horse_skeleton.png",
      "CHAINSAW - Log4J Log Viewer",
      "File",
      "Load file...",
      "Missing classes for XML parser",
      "XML parser not in classpath - unable to load XML events.",
      "CHAINSAW",
      "Unable to create the action to load XML files",
      "Unable to create a XML parser - unable to load XML events.",
      "North",
      "Events: ",
      "chainsaw.port",
      "Unable to parse chainsaw.port property with value ",
      "Unable to parse port number from '",
      "', quitting.",
      "Unable to connect to socket server, quiting",
      "Unable to create socket on port ",
      ", quitting.",
      "log4j.rootLogger",
      "DEBUG, A1",
      "log4j.appender.A1",
      "org.apache.log4j.ConsoleAppender",
      "log4j.appender.A1.layout",
      "org.apache.log4j.TTCCLayout",
      "org.apache.log4j.chainsaw.Main",
      "execute",
      "commands.execute.usage",
      "detect",
      "commands.execute.failed",
      "commands.execute.allInvocationsFailed",
      "certChainFile",
      "keyFile",
      "NPN/ALPN unsupported: ",
      "ssl.KeyManagerFactory.algorithm",
      "SunX509",
      "JKS",
      "X.509",
      "RSA",
      "DSA",
      "TLS",
      "failed to initialize the server-side SSL context",
      "NORTH_WEST",
      "north_west",
      "NORTH_EAST",
      "north_east",
      "CENTER",
      "center",
      "SOUTH_WEST",
      "south_west",
      "SOUTH_EAST",
      "south_east",
      "STEM",
      "stem",
      "ALL_INSIDE",
      "all_inside",
      "ALL_OUTSIDE",
      "all_outside",
      "ALL_STEM",
      "all_stem",
      "SkullOwner",
      "MASTER",
      "master",
      "MUSIC",
      "music",
      "RECORDS",
      "record",
      "WEATHER",
      "weather",
      "BLOCKS",
      "block",
      "MOBS",
      "hostile",
      "ANIMALS",
      "neutral",
      "PLAYERS",
      "player",
      "AMBIENT",
      "ambient",
      "Clash in Sound Category ID & Name pools! Cannot insert ",
      "buf",
      "**:**",
      "speed",
      "potion.moveSpeed",
      "91AEAA56-376B-4498-935B-2F7F68070635",
      "slowness",
      "potion.moveSlowdown",
      "7107DE5E-7CE8-4030-940E-514C1F160890",
      "haste",
      "potion.digSpeed",
      "mining_fatigue",
      "potion.digSlowDown",
      "strength",
      "potion.damageBoost",
      "648D7064-6A60-4F59-8ABE-C2C23A6DD7A9",
      "instant_health",
      "potion.heal",
      "instant_damage",
      "potion.harm",
      "jump_boost",
      "potion.jump",
      "nausea",
      "potion.confusion",
      "regeneration",
      "potion.regeneration",
      "resistance",
      "potion.resistance",
      "fire_resistance",
      "potion.fireResistance",
      "water_breathing",
      "potion.waterBreathing",
      "invisibility",
      "potion.invisibility",
      "blindness",
      "potion.blindness",
      "night_vision",
      "potion.nightVision",
      "hunger",
      "potion.hunger",
      "weakness",
      "potion.weakness",
      "22653B89-116E-49DC-9B6B-9971489B5BE5",
      "poison",
      "potion.poison",
      "wither",
      "potion.wither",
      "health_boost",
      "potion.healthBoost",
      "5D6F0BA2-1186-46AC-B896-C61C5CEE99CC",
      "absorption",
      "potion.absorption",
      "saturation",
      "potion.saturation",
      "level",
      "clazz",
      "REGISTERED",
      "UNREGISTERED",
      "ACTIVE",
      "INACTIVE",
      "EXCEPTION: ",
      "USER_EVENT: ",
      "BIND(",
      "CONNECT(",
      "DISCONNECT()",
      "CLOSE()",
      "DEREGISTER()",
      "RECEIVED",
      "WRITE",
      "FLUSH",
      "         +-------------------------------------------------+",
      "         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |",
      "+--------+-------------------------------------------------+----------------+",
      " |",
      "   ",
      "[Shaders] ",
      "Chat",
      "(?i)§[0-689A-E]",
      "Discord",
      "www.discord.gg/kjgm75FZRC",
      "GitHub",
      "https://github.com/TellinqBreaker",
      "Master Opacity",
      "Unlimited Chat",
      "Clear Chat on Relog",
      "Background Options",
      "Draw a background behind chat.",
      "Show Input Field Background",
      "Draw a background behind the chat text input field.",
      "Background Width",
      "Width",
      "Focused Height",
      "Unfocused Height",
      "Text Options",
      "Text Shadow",
      "Strip Formatting Colors",
      "Text Color",
      "Text Opacity",
      "Text Scale",
      "Animation Options",
      "Smooth Chat",
      "Smooth Chat Speed",
      "Highlighting Options",
      "Highlight Own Name",
      "Highlight Colour",
      "Play Notification Sound",
      "Position Options",
      "Chat Height Position",
      "Move and customize the Minecraft chat to your liking.",
      "LlamaLad7 (Smooth Chat)",
      "§7§m",
      "Welcome to §cCheatBreaker§f!",
      "- §c",
      ": §f",
      "Purple",
      "Red",
      "Gold",
      "Cyan",
      "Blue",
      "Green",
      "Aqua",
      "§r",
      "About",
      "Close",
      "cow",
      "testforblocks",
      "commands.compare.usage",
      "commands.compare.tooManyBlocks",
      "masked",
      "commands.compare.failed",
      "commands.compare.success",
      "commands.compare.outOfWorld",
      "ERROR",
      "WARN",
      "INFO",
      "DEBUG",
      "TRACE",
      "MSCorridor",
      "MSCrossing",
      "MSRoom",
      "MSStairs",
      "Failed to open a socket.",
      "Not a float expression: ",
      "Not a boolean expression: ",
      "Missing expression",
      "Invalid operator: ",
      "Invalid infix expression, expressions: ",
      ", operators: ",
      "Error merging operators, expressions: ",
      "Invalid infix precedence, min: ",
      ", max: ",
      "Invalid expression: ",
      "Invalid float value: ",
      "Unknown function: ",
      "Missing arguments: ",
      "Invalid number of arguments, function: \"",
      "\", count arguments: ",
      ", should be: ",
      "Invalid argument type, function: \"",
      "\", index: ",
      ", type: ",
      "Unknown function type: ",
      ", function: ",
      "Model variable not found: ",
      "Missing end token: ",
      "textures/gui/container/hopper.png",
      "@",
      "!",
      "commands.generic.entity.invalidType",
      "e",
      "lm",
      "l",
      "m",
      "team",
      "rm",
      "rym",
      "rxm",
      "dx",
      "dy",
      "dz",
      "a",
      "p",
      "c",
      "score_",
      "^@([pare])(?:\\[([\\w=,!-]*)\\])?$",
      "\\G([-!]?[\\w-]*)(?:$|,)",
      "\\G(\\w+)=([-!]?[\\w-]*)(?:$|,)",
      "Nick Hider",
      "Skin Options",
      "Hide Own Skin",
      "Hide Other Skins",
      "Name Options",
      "Hide Real Name",
      "Custom Name String",
      "client/icons/mods/nickhider.png",
      "Hides your identity client-sided.",
      "Sk1er",
      "Unable to get CW facing for axis ",
      "Unable to get Y-rotated facing of ",
      "Unable to get X-rotated facing of ",
      "Unable to get Z-rotated facing of ",
      "Unable to get CCW facing of ",
      "No such direction: ",
      "down",
      "resourcePack.openFolder",
      "Clear Glass: ",
      "Red String: ",
      "Background: ",
      "TRANSPARENT",
      "NORMAL",
      "No resource packs found.",
      "Discovering resource packs...",
      "Select resource packs.",
      "resourcePack.folderInfo",
      "Search...",
      "Failed to open file",
      "status",
      "digging",
      "freelook",
      "auto text",
      "READ_AUTH_RESPONSE",
      "Could not create shader program (returned program ID ",
      "Error encountered when linking program containing VS ",
      " and FS ",
      ". Log output:"
   };
}
