package recovered.strings;

public class StringTable03 {
   public static String[] recoveredField3960 = new String[]{
      "CCC",
      "SHOW_TEXT",
      "show_text",
      "SHOW_ACHIEVEMENT",
      "show_achievement",
      "SHOW_ITEM",
      "show_item",
      "SHOW_ENTITY",
      "show_entity",
      "Loading file...",
      "[slf5s.start]",
      "Invalid log file format",
      "Error - Invalid log file format.\nPlease see documentation on how to load log files.",
      "Error - Unable to load log file!",
      "[slf5s.DATE]",
      "[slf5s.PRIORITY]",
      "[slf5s.THREAD]",
      "[slf5s.CATEGORY]",
      "[slf5s.LOCATION]",
      "[slf5s.MESSAGE]",
      "[slf5s.NDC]",
      "[slf5s.",
      "dd MMM yyyy HH:mm:ss,S",
      "MISC_TEXTURE",
      "TERRAIN_TEXTURE",
      "ENTITY_PARTICLE_TEXTURE",
      "Unknown - ",
      "Cannot encode frame of type: ",
      "Encoding WebSocket Frame opCode=",
      " length=",
      "invalid payload for PING (payload length must be <= 125, was ",
      "stream.unavailable.title",
      "https://account.mojang.com/me/settings",
      "https://account.mojang.com/migrate",
      "http://www.apple.com/osx/",
      "http://bugs.mojang.com/browse/MC",
      "stream.unavailable.no_fbo.version",
      "stream.unavailable.no_fbo.blend",
      "stream.unavailable.no_fbo.arb",
      "stream.unavailable.no_fbo.ext",
      "Can't load AMD 64-bit .dll on a IA 32-bit platform",
      "twitch_access_token",
      "stream.unavailable.initialization_failure.extra",
      "Load shaders configuration.",
      "Failed to open the shaderpacks directory: ",
      "Unknown option: ",
      "Save shaders configuration.",
      "Error saving configuration: ",
      "Shaders can not be loaded, Antialiasing is enabled: ",
      "Shaders can not be loaded, Anisotropic Filtering is enabled: ",
      "Shaders can not be loaded, Fast Render is enabled.",
      "Loaded shaderpack: ",
      "No shaderpack loaded.",
      "/shaders/world",
      "[Shaders] Worlds: ",
      "texture.noise",
      ".0",
      ".1",
      ".2",
      ".3",
      ".4",
      ".5",
      ".6",
      ".7",
      ".8",
      ".9",
      "Invalid texture name: ",
      "Custom texture: ",
      "minecraft:textures/",
      "_n.png",
      "_s.png",
      "texture type",
      "Invalid raw texture type: ",
      "internal format",
      "Invalid raw texture internal format: ",
      "pixel format",
      "Invalid raw texture pixel format: ",
      "pixel type",
      "Invalid raw texture pixel type: ",
      "Invalid raw texture, too many parameters: ",
      "Invalid raw texture size: ",
      "shaders/",
      "Raw texture not found: ",
      "Error loading raw texture: ",
      "Error loading texture: ",
      "screen",
      "[Shaders] Error saving configuration for ",
      "shaderpacks/",
      "[Shaders] Invalid value, option: ",
      ", value: ",
      "[Shaders] Error reading configuration for ",
      "shaders",
      "FramebufferStatus 0x%04X at %s\n",
      "OpenGL error: %s (%s)%s, at: %s",
      "ShowGlErrorShaders",
      "of.message.openglError",
      ", fbStatus: ",
      ", program: ",
      "setDrawBuffers",
      ", drawBuffers: ",
      "Undefined",
      "Complete",
      "Incomplete attachment",
      "Incomplete missing attachment",
      "Incomplete draw buffer",
      "Incomplete read buffer",
      "Unsupported",
      "Incomplete multisample",
      "Incomplete layer targets",
      " [pos ",
      " lim ",
      " cap ",
      " :",
      "OpenGL Version: ",
      "Vendor:  ",
      "Renderer: ",
      "Capabilities: ",
      " 2.0 ",
      " 2.1 ",
      " 3.0 ",
      " 3.2 ",
      " 4.0 ",
      "GL_MAX_DRAW_BUFFERS: ",
      "GL_MAX_COLOR_ATTACHMENTS_EXT: ",
      "GL_MAX_TEXTURE_IMAGE_UNITS: ",
      "Shaders.init pre",
      "No OpenGL 2.0",
      "No EXT_framebuffer_object",
      "world",
      "Program disabled: ",
      "<disabled>",
      ".vsh",
      ".gsh",
      ".fsh",
      "Program loaded: ",
      "usedColorBuffers: ",
      "usedDepthBuffers: ",
      "usedShadowColorBuffers: ",
      "usedShadowDepthBuffers: ",
      "usedColorAttachs: ",
      "usedDrawBuffers: ",
      "[Shaders] Error: Not enough draw buffers, needed: ",
      ", available: ",
      "Shaders.init",
      "Reset model renderers",
      "Reset world renderers",
      "pre setupProgram",
      "arbGeometryShader4",
      "mc_Entity",
      "mc_midTexCoord",
      "at_tangent",
      "Error linking program: ",
      "[Shaders] Error: Invalid program ",
      "countInstances",
      "countInstances: ",
      "Couldn't read ",
      "Error compiling vertex shader: ",
      "GL_ARB_geometry_shader4",
      "enable",
      "require",
      "warn",
      "maxVerticesOut",
      "Error compiling geometry shader: ",
      "shadowMapResolution",
      "SHADOWRES",
      "shadowMapFov",
      "SHADOWFOV",
      "shadowDistance",
      "SHADOWHPL",
      "shadowDistanceRenderMul",
      "Shadow distance render mul: ",
      "shadowIntervalSize",
      "Shadow map interval size: ",
      "generateShadowMipmap",
      "Generate shadow mipmap",
      "generateShadowColorMipmap",
      "Generate shadow color mipmap",
      "shadowHardwareFiltering",
      "Hardware shadow filtering enabled.",
      "shadowHardwareFiltering0",
      "shadowHardwareFiltering1",
      "shadowtex0Mipmap",
      "shadowtexMipmap",
      "shadowtex1Mipmap",
      "shadowcolor0Mipmap",
      "shadowColor0Mipmap",
      "shadowcolor1Mipmap",
      "shadowColor1Mipmap",
      "shadowtex0Nearest",
      "shadowtexNearest",
      "shadow0MinMagNearest",
      "shadowtex1Nearest",
      "shadow1MinMagNearest",
      "shadowcolor0Nearest",
      "shadowColor0Nearest",
      "shadowColor0MinMagNearest",
      "shadowcolor1Nearest",
      "shadowColor1Nearest",
      "shadowColor1MinMagNearest",
      "wetnessHalflife",
      "WETNESSHL",
      "drynessHalflife",
      "DRYNESSHL",
      "eyeBrightnessHalflife",
      "Eye brightness halflife: ",
      "centerDepthHalflife",
      "Center depth halflife: ",
      "sunPathRotation",
      "Sun path rotation: ",
      "ambientOcclusionLevel",
      "AO Level: ",
      "superSamplingLevel",
      "Super sampling level: ",
      "noiseTextureResolution",
      "Noise texture enabled",
      "Noise texture resolution: ",
      "Format",
      "%s format: %s",
      "%s clear disabled",
      "ClearColor",
      "%s clear color: %s %s %s %s",
      "Invalid color value: ",
      "GAUX4FORMAT",
      "RGBA32F",
      "gaux4 format : RGB32AF",
      "RGB32F",
      "gaux4 format : RGB32F",
      "RGB16",
      "gaux4 format : RGB16",
      "MipmapEnabled",
      "%s mipmap enabled",
      "DRAWBUFFERS",
      "Invalid draw buffers: ",
      "Dryness halflife: ",
      "Wetness halflife: ",
      "Shadow map distance: ",
      "Shadow map field of view: ",
      "Shadow map resolution: ",
      "Error compiling fragment shader: ",
      "Error saving: ",
      " \n\r\t",
      "Info log: ",
      "File: ",
      "Shader info log: ",
      "pre-useProgram",
      "useProgram",
      "end useProgram",
      "/mc_Entity_x.txt",
      "Unknown block name %s",
      "unmatched %s\n",
      "Error parsing mc_Entity_x.txt",
      "Shaders.uninit pre",
      "del programRef",
      "del dfb",
      "del sfb",
      "del dfbDepthTextures",
      "del dfbTextures",
      "del shadow depth",
      "del shadow color",
      "Uninit",
      "Shaders.uninit",
      "FT d",
      "FT c",
      "FT ca",
      "[Shaders] Error: Failed framebuffer incomplete formats",
      "complete",
      "[Shaders] Error: Failed creating framebuffer! (Status ",
      "Framebuffer created.",
      "FT sd",
      "FT sc",
      "[Shaders] Error: Failed creating shadow framebuffer! (Status ",
      "Shadow framebuffer created.",
      "pre beginRender",
      "init",
      "Function is not supported",
      "[Shaders] Error: ",
      "beginRender",
      "end beginRender",
      "end beginRenderPass",
      "beginRenderPass",
      "shadow clear pre",
      "shadow clear",
      "clear pre",
      "setCamera",
      "preCelestialRotate",
      "postCelestialRotate",
      "pre-render Deferred",
      "pre-render CompositeFinal",
      "pre-composite",
      "pre-final",
      "renderCompositeFinal",
      "shadow endRender",
      "endRender end",
      "beginUpdateChunks1",
      "beginUpdateChunks2",
      "endUpdateChunks1",
      "endUpdateChunks2",
      "shouldRenderClouds",
      "beginBlockEntities",
      "nextBlockEntity",
      "endBlockEntities",
      "pre copy depth",
      "copy depth",
      "beginHand",
      "pre endHand",
      "endHand",
      "shadersmod.transform.SMCClassTransformer",
      "Shaders Mod detected. Please remove it, OptiFine has built-in support for shaders.",
      "/shaders/lang/",
      ".lang",
      "entityColor",
      "entityId",
      "blockEntityId",
      "heldItemId2",
      "heldBlockLightValue2",
      "fogDensity",
      "worldDay",
      "frameCounter",
      "frameTime",
      "shadowLightPosition",
      "nightVision",
      "screenBrightness",
      "blendFunc",
      "instanceId",
      "shadow_solid",
      "shadow_cutout",
      "gbuffers_basic",
      "gbuffers_textured",
      "gbuffers_textured_lit",
      "gbuffers_skybasic",
      "gbuffers_skytextured",
      "gbuffers_clouds",
      "gbuffers_terrain",
      "gbuffers_terrain_solid",
      "gbuffers_terrain_cutout_mip",
      "gbuffers_terrain_cutout",
      "gbuffers_damagedblock",
      "gbuffers_block",
      "gbuffers_beaconbeam",
      "gbuffers_item",
      "gbuffers_entities",
      "gbuffers_entities_glowing",
      "gbuffers_armor_glint",
      "gbuffers_spidereyes",
      "gbuffers_hand",
      "gbuffers_weather",
      "deferred_pre",
      "deferred",
      "gbuffers_water",
      "gbuffers_hand_water",
      "composite_pre",
      "Classic Lighting",
      "Old Hand Light",
      "Nearest",
      "Nearest-Nearest",
      "Nearest-Linear",
      "Linear",
      "clouds",
      "Clouds",
      "dynamicHandLight",
      "Dynamic Hand Light",
      "shadowTranslucent",
      "Shadow Translucent",
      "underwaterOverlay",
      "Underwater Overlay",
      "sun",
      "Sun",
      "moon",
      "Moon",
      "vignette",
      "Vignette",
      "backFace.solid",
      "Back-face Solid",
      "backFace.cutout",
      "Back-face Cutout",
      "backFace.cutoutMipped",
      "Back-face Cutout Mipped",
      "backFace.translucent",
      "Back-face Translucent",
      "rain.depth",
      "Rain Depth",
      "beacon.beam.depth",
      "separateAo",
      "Separate AO",
      "frustum.culling",
      "Frustum Culling",
      "gbuffers",
      "shaders.debug.save",
      "R8",
      "RG8",
      "RGB8",
      "RGBA8",
      "R8_SNORM",
      "RG8_SNORM",
      "RGB8_SNORM",
      "RGBA8_SNORM",
      "R16",
      "RG16",
      "RGBA16",
      "R16_SNORM",
      "RG16_SNORM",
      "RGB16_SNORM",
      "RGBA16_SNORM",
      "R16F",
      "RG16F",
      "RGB16F",
      "RGBA16F",
      "R32F",
      "RG32F",
      "R32I",
      "RG32I",
      "RGB32I",
      "RGBA32I",
      "R32UI",
      "RG32UI",
      "RGB32UI",
      "RGBA32UI",
      "R3_G3_B2",
      "RGB5_A1",
      "RGB10_A2",
      "R11F_G11F_B10F",
      "RGB9_E5",
      "\\s*([\\w:]+)\\s*=\\s*([-]?\\d+)\\s*",
      "optionsshaders.txt",
      "8",
      "13",
      "Unknown web socket version: ",
      "V00",
      "V07",
      "V08",
      "V13",
      "Continuable parsing error ",
      "Fatal parsing error ",
      "Parsing warning ",
      " and column ",
      "certChainFile is not a file: ",
      "keyPath",
      "keyPath is not a file: ",
      "failed to create an SSL_CTX",
      "failed to set cipher suite: ",
      "failed to set certificate: ",
      "error:00000000:",
      "failed to set certificate chain: ",
      "keys",
      "ECDHE-RSA-AES128-GCM-SHA256",
      "ECDHE-RSA-RC4-SHA",
      "ECDHE-RSA-AES128-SHA",
      "ECDHE-RSA-AES256-SHA",
      "AES128-GCM-SHA256",
      "RC4-SHA",
      "RC4-MD5",
      "AES128-SHA",
      "AES256-SHA",
      "DES-CBC3-SHA",
      "Default cipher suite (OpenSSL): ",
      "DateFormat",
      "TimeZone",
      "ABSOLUTE",
      "DATE",
      "ISO8601",
      "COMPARE",
      "compare",
      "SUBTRACT",
      "Detailed",
      "monitor.exit",
      " - LogFactor5",
      " not found.",
      "Text not found",
      "/org/apache/log4j/lf5/viewer/images/lf5_small_icon.gif",
      "Displaying: ",
      " records out of a total of: ",
      " records.",
      "No log records to display.",
      "Monospaced",
      "Log Level",
      "Show all LogLevels",
      "Hide all LogLevels",
      "Configure LogLevel Colors",
      "Reset LogLevel Colors",
      "Choose LogLevel Color",
      "View",
      "Show all Columns",
      "Hide all Columns",
      "Open...",
      "Open URL...",
      "control Q",
      "Configure",
      "Save",
      "Reset",
      "Set Max Number of Records",
      "' is an invalid parameter.\nPlease try again.",
      "Help",
      "LogFactor5 Properties",
      "Edit",
      "Find Next",
      "F3",
      "Find",
      "control F",
      "Sort by NDC",
      "Restore all NDCs",
      "JToolBar.isRollover",
      "org/apache/log4j/lf5/viewer/images/channelexplorer_new.gif",
      "Clear Log Table",
      "Clear Log Table.",
      "9",
      "12",
      "14",
      "16",
      "18",
      "24",
      " Font: ",
      "does not match a supported view.",
      "Open URL",
      "URL:",
      "Error reading URL.",
      "Unable to load file ",
      "Are you sure you want to close the logging ",
      "console?\n",
      "(Note: This will not shut down the Virtual Machine,\n",
      "or the Swing event thread.)",
      "Are you sure you want to exit?\n",
      "This will shut down the Virtual Machine.\n",
      "Are you sure you want to dispose of the Logging Console?",
      "Are you sure you want to exit?",
      "Error reading ",
      "Error reading URL:",
      "compressed data too large: ",
      "ownerName",
      "Created EventBus",
      "EventBus [",
      "aForkJoinWorkerThread",
      "Super Facepalm",
      "textures/entity/wither/wither_invulnerable.png",
      "textures/entity/wither/wither.png",
      ":()L",
      ":(L",
      ";)V",
      ":F",
      ":([Ljava/lang/String;)V",
      ":(Ljava/lang/String;)[B",
      ":(Ljava/lang/String;)Z",
      "Added mic option: ",
      "Sent: ",
      "tile.piston.out",
      "tile.piston.in",
      "extended",
      "arrowFire",
      "Accept-Encoding",
      "cannot send more responses than requests",
      "unexpected message type: ",
      "snowy",
      "/shaders",
      "Ambiguous shader option: ",
      " - in ",
      "profile.",
      "program.",
      "program\\.([^.]+)\\.enabled",
      "Error parsing program condition: ",
      "sliders",
      "Invalid shader option: ",
      "[Shaders] Profile already parsed: ",
      ":=",
      "Invalid program: ",
      " in profile: ",
      "[Shaders] Invalid option: ",
      "[Shaders] Invalid option value: ",
      "[Shaders] Invalid value: ",
      "<empty>",
      "[Shaders] Duplicate option: ",
      ", key: ",
      "<profile>",
      "[Shaders] Option profile can not be used, no profiles defined: ",
      "<rest>",
      "^[a-zA-Z0-9_]+$",
      "[Shaders] Invalid screen: ",
      ".columns",
      "#line ",
      "Included file not found: ",
      "#line 1 ",
      "#version ",
      "\n#line ",
      "#include depth exceeded: ",
      ", file: ",
      "uniform",
      "variable",
      "Custom ",
      "Unknown ",
      " type: ",
      "Expression type does not match ",
      " type, expression: ",
      "alphaTest",
      "Invalid program name: ",
      "Invalid alpha test: ",
      "Invalid blend mode: ",
      "Invalid render scale: ",
      "Invalid boolean value: ",
      "Invalid buffer name: ",
      "NEVER",
      "LESS",
      "EQUAL",
      "LEQUAL",
      "GREATER",
      "NOTEQUAL",
      "GEQUAL",
      "ALWAYS",
      "ZERO",
      "ONE",
      "SRC_COLOR",
      "ONE_MINUS_SRC_COLOR",
      "DST_COLOR",
      "ONE_MINUS_DST_COLOR",
      "SRC_ALPHA",
      "ONE_MINUS_SRC_ALPHA",
      "DST_ALPHA",
      "ONE_MINUS_DST_ALPHA",
      "CONSTANT_COLOR",
      "ONE_MINUS_CONSTANT_COLOR",
      "CONSTANT_ALPHA",
      "ONE_MINUS_CONSTANT_ALPHA",
      "SRC_ALPHA_SATURATE",
      "^\\s*#version\\s+.*$",
      "^\\s*#include\\s+\"([A-Za-z0-9_/\\.]+)\".*$",
      "of.options.otherTitle",
      "of.options.other.reset",
      "of.message.other.reset",
      "Error parsing: %s: %s",
      "Invalid index %d requested for %s",
      "Error while parsing: %s",
      "Could not generate value for callable [",
      "[enabled=",
      ", origins=",
      ", anyOrigin=",
      ", exposedHeaders=",
      ", isCredentialsAllowed=",
      ", allowedRequestMethods=",
      ", allowedRequestHeaders=",
      ", preflightHeaders=",
      "Couldn't connect to auth servers but will continue to join LAN",
      "disconnect.loginFailedInfo",
      "disconnect.loginFailedInfo.serversUnavailable",
      "disconnect.loginFailedInfo.invalidSession",
      "Unable to fit: %s, size: %dx%d, atlas: %dx%d, atlasMax: %dx%d - Maybe try a lower resolution resourcepack?",
      "Method must be join or leave for player constructor",
      "Players cannot be null/empty",
      "code: ",
      "Received text is no valid utf8 string!",
      "A close frame must have a closecode if it has a reason",
      "Trying to send an illegal close code!",
      "closecode must not be sent over the wire: ",
      "Unsupported version: ",
      "Unexpected class descriptor type: ",
      "Static Background Width",
      "§2Enabled:§r Background width is set by a slider.\n§4Disabled:§r Background width is set by the text size.",
      "Text Overflow",
      "What the mod will do if the text overflows from the background\n§bExtend Width:§r Increases the background width.\n§bScale Text:§r Scales the text down.\n§bDo Nothing:§r Does no action.",
      "Do Nothing",
      "Change how spaced the background width is from the text.",
      "Change the width of the background.",
      "Background Height",
      "Change the height of the background.",
      "Always Center",
      "Force the text to be centered in the mod's placement.",
      "Text Shadow (Background)",
      "Add a text shadow when the background is enabled.",
      "Text Shadow (No background)",
      "Add a text shadow when the background is disabled.",
      "Format Options",
      "Format (Background)",
      "Format (No Background)",
      "Sets the color for the text.",
      "Sets the color for the background.",
      "cb_7-27-2022",
      "Playing in Singleplayer",
      "In Menus",
      "In the Main Menu",
      "Unsafe Server",
      "unsafeserver",
      "Playing on an unsafe server",
      "Risking my security",
      "Network",
      "the ",
      "Playing on ",
      "Private Server",
      "localhost",
      "127.0.0.1",
      "192.168",
      "Local Server",
      "Numeric Server",
      "Playing on a ",
      "client context unsupported for: ",
      "ZLIB",
      "GZIP",
      "ZLIB_OR_NONE",
      "Enabled auto read",
      "disconnect.endOfStream",
      "disconnect.timeout",
      "Internal Exception: ",
      "packetListener",
      "Set listener of {} to {}",
      "Disabled auto read",
      "decrypt",
      "encrypt",
      "decompress",
      "compress",
      "Disconnected",
      "handleDisconnection() called twice",
      "NETWORK",
      "NETWORK_PACKETS",
      "java.library.path",
      "Auth token must be valid",
      "Username must be valid",
      "Error while starting to broadcast: %s",
      "Error while stopping the broadcast: %s",
      "Error pausing stream: %s\n",
      "Error while sending meta data: %s\n",
      "Error in SendStartSpanMetaData\n",
      "Invalid sequence id: %d\n",
      "Error in SendStopSpanMetaData: %s\n",
      "Error in TTV_Login: %s\n",
      "Error in TTV_GetIngestServers: %s\n",
      "Error in TTV_GetUserInfo: %s\n",
      "Error in TTV_GetArchivingState: %s\n",
      "Error in TTV_GetStreamInfo: %s",
      "Error while allocating frame buffer",
      "Out of free buffers, this should never happen",
      "Trying to submit a frame to Twitch",
      "Broadcast State",
      "Last reported errors",
      "Buffer",
      "Free buffer count",
      "Capture buffer count",
      "Warning in SubmitTexturePointer: %s\n",
      "Error in SubmitTexturePointer: %s\n",
      "<Error> ",
      "[Broadcast controller] {}",
      "<Warning> ",
      "junit.framework.Test",
      "With Clicks",
      " CPS",
      "RMB",
      "Replace Clicks",
      "com.sun.jdmk.comm.HtmlAdapterServer",
      "Registering HtmlAdaptorServer instance.",
      "Adaptor:name=html,port=8082",
      "Registering HierarchyDynamicMBean instance.",
      "log4j:hiearchy=default",
      "Problem while registering MBeans instances.",
      "org.apache.log4j.jmx.Agent",
      " Read Suspend: ",
      " Suspend final status => ",
      " will reopened at: ",
      " Write suspend: ",
      "TrafficShaping with Write Limit: ",
      " Read Limit: ",
      " and Counter: ",
      ".READ_SUSPENDED",
      ".REOPEN_TASK",
      "textures/entity/alex.png",
      "leftLow",
      "leftHigh",
      "rightLow",
      "rightHigh",
      "body.body",
      "wing.skin",
      "wingtip.skin",
      "rearleg.main",
      "rearfoot.main",
      "rearlegtip.main",
      "head.upperhead",
      "wing.bone",
      "head.upperlip",
      "jaw.jaw",
      "frontleg.main",
      "wingtip.bone",
      "frontfoot.main",
      "neck.box",
      "frontlegtip.main",
      "body.scale",
      "head.scale",
      "neck.scale",
      "head.nostril",
      "upperlip",
      "upperhead",
      "nostril",
      "jaw",
      "box",
      "skin",
      "wingtip",
      "frontleg",
      "frontlegtip",
      "frontfoot",
      "rearleg",
      "rearlegtip",
      "rearfoot",
      "Invalid/missing description!",
      "pack_format",
      "fingerprints",
      "malformed fingerprint: ",
      " (expected: SHA1)",
      "^[0-9a-fA-F:]+$",
      "eventLoop",
      "registered to an event loop already",
      "incompatible event loop type: ",
      "Force-closing a channel whose registration task was not accepted by an event loop: {}",
      "A non-root user can't receive a broadcast packet if the socket is not bound to a wildcard address; binding to a non-wildcard address (",
      ") anyway as requested.",
      "Failed to close a channel.",
      "Unexpected exception occurred while deregistering a channel.",
      "Can't invoke task later as EventLoop rejected it",
      "Unable to read or access folder where game worlds are saved!",
      "Scanning folders...",
      "Total conversion count is ",
      "region",
      "Unable to create level.dat_mcr backup",
      "level.dat",
      "level.dat_mcr",
      ".mca",
      "Failed to fetch input stream",
      "[Shaders] Delayed loading of block mappings after resources are loaded",
      "/shaders/block.properties",
      "[Shaders] Parsing block mappings: ",
      "block.",
      "[Shaders] Invalid block ID: ",
      "[Shaders] Invalid block ID mapping: ",
      "NORTH_SOUTH",
      "north_south",
      "EAST_WEST",
      "east_west",
      "ASCENDING_EAST",
      "ascending_east",
      "ASCENDING_WEST",
      "ascending_west",
      "ASCENDING_NORTH",
      "ascending_north",
      "ASCENDING_SOUTH",
      "ascending_south",
      "RecordItem",
      "Record",
      "deathCount",
      "playerKillCount",
      "totalKillCount",
      "health",
      "teamkill.",
      "killedByTeam.",
      "headRef",
      "Reloading ResourceManager: ",
      "mob.zombiepig.zpigangry",
      "Anger",
      "HurtBy",
      "mob.zombiepig.zpig",
      "mob.zombiepig.zpighurt",
      "mob.zombiepig.zpigdeath",
      "49455A49-7EC5-45BA-B886-3B90B23A1718",
      "Attacking speed boost",
      "client/icons/mods/zans.png",
      "Adds a minimap on the top right and allows you to manage waypoints.",
      "Zan",
      "&4Minimap &fis not allowed on this server. Some functions may not work.",
      "toggledownfall",
      "commands.downfall.usage",
      "commands.downfall.success",
      "]]>",
      "]]>]]&gt;<![CDATA[",
      "multiplayer.texturePrompt.line1",
      "multiplayer.texturePrompt.line2",
      "chat.link.confirmTrusted",
      "chat.link.confirm",
      "chat.link.open",
      "chat.copy",
      "chat.link.warning",
      "Unknown periodicity type.",
      "Tall",
      "EntryDoor",
      "moisture",
      "Low on Storage Space",
      "Moved Temporarily",
      "Parameter Not Understood",
      "Conference Not Found",
      "Not Enough Bandwidth",
      "Session Not Found",
      "Method Not Valid in This State",
      "Header Field Not Valid for Resource",
      "Invalid Range",
      "Parameter Is Read-Only",
      "Aggregate operation not allowed",
      "Only Aggregate operation allowed",
      "Unsupported transport",
      "Destination unreachable",
      "Key management failure",
      "RTSP Version not supported",
      "Option not supported",
      "ArrowAttackGoal requires Mob implements RangedAttackMob",
      "Float",
      "UBYTE",
      "Unsigned Byte",
      "Byte",
      "USHORT",
      "Unsigned Short",
      "Short",
      "UINT",
      "Unsigned Int",
      "Int",
      "Metadata payload is full, cannot add more to it!",
      "Metadata payload key cannot be null!",
      "Metadata payload key is too long!",
      "Metadata payload value cannot be null!",
      "Metadata payload value is too long!",
      "Error parsing expression: ",
      "Received invalid frame",
      "unknown:",
      "textures/entity/squid.png",
      "Adding duplicate key '",
      "' to registry",
      "WebSocket version 07 client handshake key: {}, expected response: {}",
      "Invalid handshake response getStatus: ",
      "Invalid handshake response upgrade: ",
      "Invalid handshake response connection: ",
      "Invalid challenge. Actual: %s. Expected: %s",
      "OAK",
      "SPRUCE",
      "BIRCH",
      "JUNGLE",
      "ACACIA",
      "DARK_OAK",
      "big_oak",
      "MISS",
      "ENTITY",
      "%s/%s/%s",
      "assets",
      "ResourcePack: ignored non-lowercase namespace: {} in {}",
      "[Icon Scaler] Scaling resource pack icon from ",
      "[Icon Scaler] Retaining pack icon scale at ",
      "const ",
      "^\\s*const\\s*(float|int)\\s*([A-Za-z0-9_]+)\\s*=\\s*(-?[0-9\\.]+f?F?)\\s*;\\s*(//.*)?$",
      "STRAIGHT",
      "straight",
      "INNER_LEFT",
      "inner_left",
      "INNER_RIGHT",
      "inner_right",
      "OUTER_LEFT",
      "outer_left",
      "OUTER_RIGHT",
      "outer_right",
      "cave_spider",
      "(=> ",
      "Invisible",
      "ShowArms",
      "DisabledSlots",
      "NoGravity",
      "NoBasePlate",
      "Marker",
      "Pose",
      "Head",
      "Body",
      "LeftArm",
      "RightArm",
      "LeftLeg",
      "RightLeg",
      "ANVIL",
      "BEACON",
      "BREWING_STAND",
      "CRAFTING",
      "DISPENSER",
      "ENCHANTMENT",
      "HORSE",
      "VILLAGER",
      "SHULKER_BOX",
      "CREATIVE",
      "INVENTORY",
      "SOCKS4a",
      "SOCKS5",
      "triggered",
      "player.models.reload",
      "unknownSize: ",
      "This OutputStream has already been closed.",
      "Unspecific error while writing",
      "url [",
      "Flower Forest",
      "Matrix4d0",
      "Matrix4d1",
      "Matrix4d2",
      "Matrix4d3",
      "Matrix4d4",
      "Matrix4d7",
      "Matrix4d10",
      "Matrix4d11",
      "UTF-16",
      "UTF-16BE",
      "UTF-16LE",
      "ISO-8859-1",
      "SAND",
      "RED_SAND",
      "System Details",
      "Minecraft Version",
      "Operating System",
      "Java Version",
      "Java VM Version",
      "Memory",
      "JVM Flags",
      "IntCache",
      "-- Head --\n",
      "Stacktrace:\n",
      "at ",
      "---- Minecraft Crash Report ----\n",
      "Description: ",
      "\n\nA detailed walkthrough of the error, its code path and all known details is as follows:\n",
      "Could not save crash report to ",
      "Negative index in crash report handler (",
      "Who set us up the TNT?",
      "Everything's going to plan. No, really, that was supposed to happen.",
      "Uh... Did I do that?",
      "Oops.",
      "Why did you do that?",
      "I feel sad now :(",
      "My bad.",
      "I'm sorry, Dave.",
      "I let you down. Sorry :(",
      "On the bright side, I bought you a teddy bear!",
      "Daisy, daisy...",
      "Oh - I know what I did wrong!",
      "Hey, that tickles! Hehehe!",
      "I blame Dinnerbone.",
      "You should try our sister game, Minceraft!"
   };
}
