package recovered.strings;

public class StringTable01 {
   public static String[] recoveredField3965 = new String[]{
      "blocks/destroy_stage_6",
      "blocks/destroy_stage_7",
      "blocks/destroy_stage_8",
      "blocks/destroy_stage_9",
      "items/empty_armor_slot_helmet",
      "items/empty_armor_slot_chestplate",
      "items/empty_armor_slot_leggings",
      "items/empty_armor_slot_boots",
      "builtin/missing",
      "missing",
      "{\"elements\":[{  \"from\": [0, 0, 0],   \"to\": [16, 16, 16],   \"faces\": {       \"down\": {\"uv\": [0, 0, 16, 16], \"texture\":\"\"}   }}]}",
      "{ \"textures\": {   \"particle\": \"missingno\",   \"missingno\": \"missingno\"}, \"elements\": [ {     \"from\": [ 0, 0, 0 ],     \"to\": [ 16, 16, 16 ],     \"faces\": {         \"down\":  { \"uv\": [ 0, 0, 16, 16 ], \"cullface\": \"down\", \"texture\": \"#missingno\" },         \"up\":    { \"uv\": [ 0, 0, 16, 16 ], \"cullface\": \"up\", \"texture\": \"#missingno\" },         \"north\": { \"uv\": [ 0, 0, 16, 16 ], \"cullface\": \"north\", \"texture\": \"#missingno\" },         \"south\": { \"uv\": [ 0, 0, 16, 16 ], \"cullface\": \"south\", \"texture\": \"#missingno\" },         \"west\":  { \"uv\": [ 0, 0, 16, 16 ], \"cullface\": \"west\", \"texture\": \"#missingno\" },         \"east\":  { \"uv\": [ 0, 0, 16, 16 ], \"cullface\": \"east\", \"texture\": \"#missingno\" }    }}]}",
      "generation marker",
      "compass generation marker",
      "class generation marker",
      "block entity marker",
      "STANDARD",
      "URL_SAFE",
      "ORDERED",
      "READER_IDLE",
      "WRITER_IDLE",
      "ALL_IDLE",
      "VarInt too big",
      "textures/entity/pig/pig.png",
      "PlayerCreated",
      "mob.irongolem.throw",
      "mob.irongolem.hit",
      "mob.irongolem.death",
      "mob.irongolem.walk",
      "wither_skull",
      "Field not found: RenderWitherSkull_model",
      "This InputStream has already been closed.",
      "authStatus",
      "SOUND_EVENT",
      "event",
      "VarLong too big",
      "The received encoded string buffer length is longer than maximum allowed (",
      "The received encoded string buffer length is less than zero! Weird string!",
      "The received string length is longer than maximum allowed (",
      "String too big (was ",
      " bytes encoded, max ",
      "Socket is closed",
      "Already bound",
      "Can only bind to endpoints of type ",
      "AFUNIXServerSocket[unbound]",
      "AFUNIXServerSocket[",
      "textures/entity/spider/cave_spider.png",
      "Modifier name cannot be empty",
      "AttributeModifier{amount=",
      ", operation=",
      ", name='",
      ", id=",
      ", serialize=",
      "lootBonusDigger",
      "lootBonusFishing",
      "lootBonus",
      "File IO Thread",
      "audioURL",
      "Audio player thread",
      "Unable to play ",
      "Problem playing audio: ",
      "%.2f,%.2f,%.2f - %s",
      "World: (%d,%d,%d)",
      "(Error finding world loc)",
      "Chunk: (at %d,%d,%d in %d,%d; contains blocks %d,0,%d to %d,255,%d)",
      "(Error finding chunk loc)",
      "Region: (%d,%d; contains chunks %d,%d to %d,%d, blocks %d,0,%d to %d,255,%d)",
      "-- ",
      " --\n",
      "Details:",
      "\nStacktrace:",
      "\n\tat ",
      "Block type",
      "Block data value",
      "Block location",
      "SUCCESSFULLY_LOADED",
      "DECLINED",
      "FAILED_DOWNLOAD",
      "RTSP/1.0",
      "RTSP",
      "magma_cube",
      "core",
      "segment",
      "segment1",
      "segment2",
      "segment3",
      "segment4",
      "segment5",
      "segment6",
      "segment7",
      "segment8",
      "\\{stream_key\\}",
      " kbps",
      "Down!",
      "1234",
      "(Preferred)",
      "(Default)",
      "Shader texture not found: ",
      ".mcmeta",
      "Error reading metadata: ",
      "LINEAR",
      "Uncaught exception in thread {}: {}",
      "NO_FBO",
      "stream.unavailable.no_fbo",
      "LIBRARY_ARCH_MISMATCH",
      "stream.unavailable.library_arch_mismatch",
      "LIBRARY_FAILURE",
      "stream.unavailable.library_failure",
      "stream.unavailable.report_to_mojang",
      "UNSUPPORTED_OS_WINDOWS",
      "stream.unavailable.not_supported.windows",
      "UNSUPPORTED_OS_MAC",
      "stream.unavailable.not_supported.mac",
      "stream.unavailable.not_supported.mac.okay",
      "UNSUPPORTED_OS_OTHER",
      "stream.unavailable.not_supported.other",
      "ACCOUNT_NOT_MIGRATED",
      "stream.unavailable.account_not_migrated",
      "stream.unavailable.account_not_migrated.okay",
      "ACCOUNT_NOT_BOUND",
      "stream.unavailable.account_not_bound",
      "stream.unavailable.account_not_bound.okay",
      "FAILED_TWITCH_AUTH",
      "stream.unavailable.failed_auth",
      "stream.unavailable.failed_auth.okay",
      "FAILED_TWITCH_AUTH_ERROR",
      "stream.unavailable.failed_auth_error",
      "INITIALIZATION_FAILURE",
      "stream.unavailable.initialization_failure",
      "stream.unavailable.unknown",
      "Server Address",
      "[minehq.com]",
      "Displays the address of the current connected server.",
      "minehq.com",
      "IP",
      "client/icons/servers/",
      "Hides the mod in Singleplayer.",
      "mob.blaze.breathe",
      "mob.blaze.hit",
      "mob.blaze.death",
      " \t",
      "define",
      "undef",
      "ifdef",
      "ifndef",
      "if",
      "elif",
      "else",
      "endif",
      "defined_$1",
      "Too many iterations: ",
      ", when resolving: ",
      "Not a boolean or float expression: ",
      "Invalid macro expression: ",
      "\\s*#\\s*(\\w+)\\s*(.*)",
      "defined\\s+(\\w+)",
      "defined\\s*\\(\\s*(\\w+)\\s*\\)",
      "(\\w+)",
      "Precision option (",
      ") isn't a positive integer.",
      "Category option \"",
      "\" not a decimal integer.",
      "Error occured in position ",
      ".\n Was expecting digit, instead got char \"",
      "Could not instantiate SimpleDateFormat with ",
      "org.apache.log4j.helpers.ISO8601DateFormat",
      "java.text.DateFormat",
      "Unexpected char [",
      "] at position ",
      " in conversion patterrn.",
      "SOCKS_INIT_RESPONSE_DECODER",
      "INTEL_32",
      "INTEL_64",
      "PPC",
      "textures/entity/spider/spider.png",
      "TextComponent{text='",
      "Failed to create watch service",
      "Hands Up",
      "Exception during the closing of the channel",
      "SSLExcpetion during unwrap",
      "Invalid SSL status: ",
      "Buffer underflow occured after a wrap. I don't think we should ever get here.",
      "This engine was forced to close inbound, without having received the proper SSL/TLS close notification message from the peer, due to end of stream.",
      "demo.help.buy",
      "demo.help.later",
      "http://www.minecraft.net/store?source=demo",
      "demo.help.title",
      "demo.help.movementShort",
      "demo.help.movementMouse",
      "demo.help.fullWrapped",
      "textures/gui/demo_background.png",
      "READ_USERNAME",
      "READ_PASSWORD",
      "ARMOR",
      "ARMOR_FEET",
      "ARMOR_LEGS",
      "ARMOR_TORSO",
      "ARMOR_HEAD",
      "WEAPON",
      "DIGGER",
      "FISHING_ROD",
      "BREAKABLE",
      ", real: ",
      "MC_OS_WINDOWS",
      "MC_OS_MAC",
      "MC_OS_LINUX",
      "MC_OS_OTHER",
      "MC_GL_VENDOR_OTHER",
      "ati",
      "MC_GL_VENDOR_ATI",
      "intel",
      "MC_GL_VENDOR_INTEL",
      "nvidia",
      "MC_GL_VENDOR_NVIDIA",
      "x.org",
      "MC_GL_VENDOR_XORG",
      "MC_GL_RENDERER_OTHER",
      "MC_GL_RENDERER_RADEON",
      "radeon",
      "gallium",
      "MC_GL_RENDERER_GALLIUM",
      "MC_GL_RENDERER_INTEL",
      "geforce",
      "MC_GL_RENDERER_GEFORCE",
      "quadro",
      "MC_GL_RENDERER_QUADRO",
      "nvs",
      "mesa",
      "MC_GL_RENDERER_MESA",
      "MC_VERSION",
      "MC_GL_VERSION ",
      "MC_GLSL_VERSION ",
      "MC_FXAA_LEVEL",
      "MC_NORMAL_MAP",
      "MC_SPECULAR_MAP",
      "MC_RENDER_QUALITY",
      "MC_SHADOW_QUALITY",
      "MC_HAND_DEPTH",
      "MC_OLD_HAND_LIGHT",
      "MC_OLD_LIGHTING",
      "MC_",
      ".decode() did not read anything but decoded a message.",
      "text is empty",
      "HTTP/1.0",
      "empty text",
      "invalid version format: ",
      "protocolName",
      "empty protocolName",
      "invalid character in protocolName",
      "negative majorVersion",
      "negative minorVersion",
      "(\\S+)/(\\d+)\\.(\\d+)",
      "Invalid challenge",
      "Unable to resolve texture due to upward reference: ",
      "Unknown map",
      "Scaling at 1:",
      "(Level ",
      "TEXTURE_1D",
      "TEXTURE_2D",
      "TEXTURE_3D",
      "TEXTURE_RECTANGLE",
      "texts/end.txt",
      "PLAYERNAME",
      "XXXXXXXX",
      "texts/credits.txt",
      "Couldn't load credits",
      "[C]",
      "0 is not a valid status code for a RST_STREAM",
      "INVALID_STREAM",
      "REFUSED_STREAM",
      "UNSUPPORTED_VERSION",
      "FLOW_CONTROL_ERROR",
      "STREAM_IN_USE",
      "STREAM_ALREADY_CLOSED",
      "INVALID_CREDENTIALS",
      "FRAME_TOO_LARGE",
      "Tool modifier",
      "STICKY",
      "sticky",
      "items.png",
      "itemGroup.",
      "buildingBlocks",
      "decorations",
      "transportation",
      "misc",
      "search",
      "item_search.png",
      "tools",
      "combat",
      "brewing",
      "materials",
      "inventory.png",
      "_end",
      "TreeModel.valueForPathChanged: not implemented",
      "data payload cannot exceed 16777215 bytes",
      "--> Size = ",
      "(freed)",
      "SET_SIZE",
      "LERP_SIZE",
      "SET_CENTER",
      "INITIALIZE",
      "SET_WARNING_TIME",
      "SET_WARNING_BLOCKS",
      "PLUS",
      "MINUS",
      "MUL",
      "DIV",
      "MOD",
      "NEG",
      "neg",
      "PI",
      "pi",
      "sin",
      "cos",
      "asin",
      "acos",
      "TAN",
      "tan",
      "ATAN",
      "atan",
      "ATAN2",
      "atan2",
      "TORAD",
      "torad",
      "TODEG",
      "todeg",
      "MIN",
      "MAX",
      "CLAMP",
      "ABS",
      "abs",
      "FLOOR",
      "floor",
      "CEIL",
      "ceil",
      "EXP",
      "exp",
      "FRAC",
      "frac",
      "LOG",
      "POW",
      "pow",
      "RANDOM",
      "ROUND",
      "round",
      "SIGNUM",
      "signum",
      "SQRT",
      "sqrt",
      "FMOD",
      "fmod",
      "TIME",
      "IF",
      "NOT",
      "AND",
      "&&",
      "OR",
      "||",
      "GREATER_OR_EQUAL",
      ">=",
      "SMALLER",
      "SMALLER_OR_EQUAL",
      "<=",
      "==",
      "NOT_EQUAL",
      "!=",
      "BETWEEN",
      "between",
      "EQUALS",
      "equals",
      "IN",
      "TRUE",
      "FALSE",
      "vec2",
      "vec3",
      "INBOUND_IN",
      "OUTBOUND_IN",
      "_tmp",
      "Failed to delete ",
      "Root tag must be a named compound tag",
      "[UNNAMED TAG]",
      "Coordinates",
      "Mode",
      "Layout the mod should display.",
      "Show the coordiantes.",
      "C Counter",
      "Shows the C Counter",
      "Hide Y Coordinate",
      "Hide the Y coordinate.",
      "Show the direction the player is facing.",
      "Custom Line",
      "Coordinates Color",
      "Change the coordinates text color.",
      "Change the direction text color.",
      "(16, 65, 120) NW",
      "Shows your X, Y, and Z coordinates as well as your direction.",
      "(%1$d, %2$d, C: %3$s)",
      "(%1$d, %2$d)",
      "(%1$d, %2$d, %3$d, C: %4$s)",
      "(%1$d, %2$d, %3$d)",
      "X: ",
      "Y: ",
      "Z: ",
      "C: ",
      " N",
      " NE",
      " E",
      " SE",
      " S",
      " SW",
      " W",
      " NW",
      "%NL%",
      "N",
      "NE",
      "SE",
      "SW",
      "W",
      "NW",
      "%IP%",
      "%FPS%",
      "%DIR%",
      "%CPS%",
      "%COORDS%",
      "%1$d, %2$d, %3$d",
      "%X%",
      "%Y%",
      "%Z%",
      "ToggleSprint",
      "[Sprinting (Toggled)]",
      "Makes your sprint and sneak keys toggleable.",
      "deeznueces",
      "Sneak in containers is disabled.",
      "Sprint Status",
      "Toggle Sprint/Sneak Options",
      "Toggle Sprint",
      "Makes sprinting toggleable instead of held down.",
      "Toggle Sneak",
      "Makes sneaking toggleable instead of held down.",
      "Sneak In Container",
      "Allows sneaking in containers.",
      "Double Tap",
      "Determine if double tapping the moving forward key should make the player start sprinting.",
      "Fly Boost",
      "Determine if pressing the sprint key should boost the fly speed.",
      "Fly Boost Amount",
      "Change the boost amount.",
      "Fly Boost String",
      "Flying (%BOOST%x boost)",
      "Fly String",
      "Flying",
      "Riding String",
      "Descend String",
      "Descending",
      "Dismount String",
      "Dismounting",
      "Sneaking String",
      "Sneaking (Key Held)",
      "Sprinting Held String",
      "Sprinting (Key Held)",
      "Sprinting Vanilla String",
      "Sprinting (Vanilla)",
      "Sprinting Toggle String",
      "Sprinting (Toggled)",
      "Sneaking Toggle String",
      "Sneaking (Toggled)",
      "optifine/emissive.properties",
      "suffix.emissive",
      "EmissiveTextures: ",
      "mcpatcher/ctm/default/empty.png",
      "HellRandomLevelSource",
      "pig",
      "targets",
      "targets[",
      "passes",
      "passes[",
      "target",
      " is already defined",
      "pass",
      "intarget",
      "outtarget",
      "Input target '",
      "' does not exist",
      "Output target '",
      "auxtargets",
      "auxtarget",
      "textures/effect/",
      "Render target or texture '",
      "bilinear",
      "auxtargets[",
      "Uniform '",
      "minecraft:main",
      "entity.horse.name",
      "entity.donkey.name",
      "entity.mule.name",
      "entity.zombiehorse.name",
      "entity.skeletonhorse.name",
      "eating",
      "mob.horse.land",
      "HorseChest",
      "mob.horse.armor",
      "mob.horse.zombie.death",
      "mob.horse.skeleton.death",
      "mob.horse.death",
      "mob.horse.donkey.death",
      "mob.horse.zombie.hit",
      "mob.horse.skeleton.hit",
      "mob.horse.hit",
      "mob.horse.donkey.hit",
      "mob.horse.zombie.idle",
      "mob.horse.skeleton.idle",
      "mob.horse.idle",
      "mob.horse.donkey.idle",
      "mob.horse.angry",
      "mob.horse.donkey.angry",
      "mob.horse.gallop",
      "mob.horse.breathe",
      "mob.horse.wood",
      "mob.horse.soft",
      "mob.chickenplop",
      "mob.horse.jump",
      "EatingHaystack",
      "ChestedHorse",
      "HasReproduced",
      "Bred",
      "Variant",
      "Temper",
      "Tame",
      "ArmorItem",
      "SaddleItem",
      "Speed",
      "horse.jumpStrength",
      "Jump Strength",
      "textures/entity/horse/armor/horse_armor_iron.png",
      "textures/entity/horse/armor/horse_armor_gold.png",
      "textures/entity/horse/armor/horse_armor_diamond.png",
      "meo",
      "goo",
      "dio",
      "textures/entity/horse/horse_creamy.png",
      "textures/entity/horse/horse_chestnut.png",
      "textures/entity/horse/horse_brown.png",
      "textures/entity/horse/horse_black.png",
      "textures/entity/horse/horse_gray.png",
      "textures/entity/horse/horse_darkbrown.png",
      "hwh",
      "hcr",
      "hch",
      "hbr",
      "hbl",
      "hgr",
      "hdb",
      "textures/entity/horse/horse_markings_white.png",
      "textures/entity/horse/horse_markings_whitefield.png",
      "textures/entity/horse/horse_markings_whitedots.png",
      "textures/entity/horse/horse_markings_blackdots.png",
      "wo_",
      "wmo",
      "wdo",
      "bdo",
      "Payload may not be larger than 1048576 bytes",
      "Recipes",
      "org.apache.log4j.Logger",
      "enderman",
      "unexpected signal: ",
      "Searching for IPC: %s",
      "client_id",
      "api_endpoint",
      "Found a valid client (%s) with packet: %s",
      "Found preferred client: %s",
      "Looking for client build: %s",
      "Failed to close an open IPC pipe!",
      "Unsupported OS: ",
      "Sent packet: %s",
      "Encountered an IOException while sending a packet and disconnected!",
      "Win",
      "\\\\?\\pipe\\discord-ipc-",
      "/discord-ipc-",
      "XDG_RUNTIME_DIR",
      "TMP",
      "Failed to fetch mob spawner entity at (",
      "Only protocol http is supported: ",
      "Java/",
      "text/html, image/gif, image/png",
      "file:",
      "Interrupted",
      "Response is null",
      "Unknown synced attribute modifier",
      "dig.glass",
      "step.stone",
      "refCnt: ",
      "Modifier is already applied on this attribute!",
      "OF-Version",
      "= [ Description ] =\n",
      "Uploaded debug info.",
      "Error parsing configuration: ",
      "setblock",
      "commands.setblock.usage",
      "commands.setblock.outOfWorld",
      "commands.setblock.success",
      "commands.setblock.noChange",
      "thread must be alive.",
      "X0_Y0",
      "X0_Y90",
      "X0_Y180",
      "X0_Y270",
      "X90_Y0",
      "X90_Y90",
      "X90_Y180",
      "X90_Y270",
      "X180_Y0",
      "X180_Y90",
      "X180_Y180",
      "X180_Y270",
      "X270_Y0",
      "X270_Y90",
      "X270_Y180",
      "X270_Y270",
      "Authenticating",
      "Authenticated",
      "LoggingIn",
      "LoggedIn",
      "FindingIngestServer",
      "ReceivedIngestServers",
      "ReadyToBroadcast",
      "Starting",
      "Broadcasting",
      "Stopping",
      "Paused",
      "IngestTesting",
      "Recent access records: ",
      "Created at:",
      "textures/painting/paintings_kristoffer_zetterstrand.png",
      "Style{hasParent=",
      ", color=",
      ", bold=",
      ", italic=",
      ", underlined=",
      ", obfuscated=",
      ", clickEvent=",
      ", hoverEvent=",
      ", insertion=",
      "option.",
      "value.",
      ", valueDefault: ",
      ", paths: ",
      "cls",
      "type of deserialized instance not of required class.",
      "elemType",
      "length",
      "object is not an array",
      "unexpected array component type",
      "array length mismatch",
      "unable to load resource '",
      "obj",
      "sslContext",
      "SSL.writeToSSL() returned a non-positive value: ",
      "srcs",
      " (expected: offset <= offset + length <= srcs.length (",
      "dsts",
      " (expected: offset <= offset + length <= dsts.length (",
      "SSL_read failed: primingReadResult: ",
      "; OpenSSL error: '",
      "Inbound closed before receiving peer's close_notify: possible truncation attack?",
      "engine closed",
      "renegotiation unsupported",
      "encrypted packet oversized",
      "destroyed",
      "GRASS",
      "pardon",
      "commands.unban.usage",
      "commands.unban.failed",
      "commands.unban.success",
      "javazoom/jl/decoder/",
      "Retrieving: ",
      "publish",
      "commands.publish.usage",
      "INVERT_MOUSE",
      "options.invertMouse",
      "SENSITIVITY",
      "options.sensitivity",
      "FOV",
      "options.fov",
      "GAMMA",
      "options.gamma",
      "SATURATION",
      "options.saturation",
      "RENDER_DISTANCE",
      "options.renderDistance",
      "VIEW_BOBBING",
      "options.viewBobbing",
      "ANAGLYPH",
      "options.anaglyph",
      "FRAMERATE_LIMIT",
      "options.framerateLimit",
      "FBO_ENABLE",
      "options.fboEnable",
      "RENDER_CLOUDS",
      "options.renderClouds",
      "GRAPHICS",
      "options.graphics",
      "AMBIENT_OCCLUSION",
      "options.ao",
      "GUI_SCALE",
      "options.guiScale",
      "PARTICLES",
      "options.particles",
      "CHAT_VISIBILITY",
      "options.chat.visibility",
      "CHAT_COLOR",
      "options.chat.color",
      "CHAT_LINKS",
      "options.chat.links",
      "CHAT_OPACITY",
      "options.chat.opacity",
      "CHAT_LINKS_PROMPT",
      "options.chat.links.prompt",
      "SNOOPER_ENABLED",
      "options.snooper",
      "USE_FULLSCREEN",
      "options.fullscreen",
      "ENABLE_VSYNC",
      "options.vsync",
      "USE_VBO",
      "options.vbo",
      "TOUCHSCREEN",
      "options.touchscreen",
      "CHAT_SCALE",
      "options.chat.scale",
      "CHAT_WIDTH",
      "options.chat.width",
      "CHAT_HEIGHT_FOCUSED",
      "options.chat.height.focused",
      "CHAT_HEIGHT_UNFOCUSED",
      "options.chat.height.unfocused",
      "MIPMAP_LEVELS",
      "options.mipmapLevels",
      "FORCE_UNICODE_FONT",
      "options.forceUnicodeFont",
      "STREAM_BYTES_PER_PIXEL",
      "options.stream.bytesPerPixel",
      "STREAM_VOLUME_MIC",
      "options.stream.micVolumne",
      "STREAM_VOLUME_SYSTEM",
      "options.stream.systemVolume",
      "STREAM_KBPS",
      "options.stream.kbps",
      "STREAM_FPS",
      "options.stream.fps",
      "STREAM_COMPRESSION",
      "options.stream.compression",
      "STREAM_SEND_METADATA",
      "options.stream.sendMetadata",
      "STREAM_CHAT_ENABLED",
      "options.stream.chat.enabled",
      "STREAM_CHAT_USER_FILTER",
      "options.stream.chat.userFilter",
      "STREAM_MIC_TOGGLE_BEHAVIOR",
      "options.stream.micToggleBehavior",
      "BLOCK_ALTERNATIVES",
      "options.blockAlternatives",
      "REDUCED_DEBUG_INFO",
      "options.reducedDebugInfo",
      "ENTITY_SHADOWS",
      "options.entityShadows",
      "REALMS_NOTIFICATIONS",
      "options.realmsNotifications",
      "FOG_FANCY",
      "of.options.FOG_FANCY",
      "FOG_START",
      "of.options.FOG_START",
      "MIPMAP_TYPE",
      "of.options.MIPMAP_TYPE",
      "SMOOTH_FPS",
      "of.options.SMOOTH_FPS",
      "CLOUDS",
      "of.options.CLOUDS",
      "CLOUD_HEIGHT",
      "of.options.CLOUD_HEIGHT",
      "TREES",
      "of.options.TREES",
      "of.options.RAIN",
      "ANIMATED_WATER",
      "of.options.ANIMATED_WATER",
      "ANIMATED_LAVA",
      "of.options.ANIMATED_LAVA",
      "ANIMATED_FIRE",
      "of.options.ANIMATED_FIRE",
      "ANIMATED_PORTAL",
      "of.options.ANIMATED_PORTAL",
      "AO_LEVEL",
      "of.options.AO_LEVEL",
      "LAGOMETER",
      "of.options.LAGOMETER",
      "SHOW_FPS",
      "of.options.SHOW_FPS",
      "AUTOSAVE_TICKS",
      "of.options.AUTOSAVE_TICKS",
      "BETTER_GRASS",
      "of.options.BETTER_GRASS",
      "ANIMATED_REDSTONE",
      "of.options.ANIMATED_REDSTONE",
      "ANIMATED_EXPLOSION",
      "of.options.ANIMATED_EXPLOSION",
      "ANIMATED_FLAME",
      "of.options.ANIMATED_FLAME",
      "ANIMATED_SMOKE",
      "of.options.ANIMATED_SMOKE",
      "of.options.WEATHER",
      "of.options.SKY",
      "STARS",
      "of.options.STARS",
      "SUN_MOON",
      "of.options.SUN_MOON",
      "VIGNETTE",
      "of.options.VIGNETTE",
      "CHUNK_UPDATES",
      "of.options.CHUNK_UPDATES",
      "CHUNK_UPDATES_DYNAMIC",
      "of.options.CHUNK_UPDATES_DYNAMIC",
      "of.options.TIME",
      "CLEAR_WATER",
      "of.options.CLEAR_WATER",
      "SMOOTH_WORLD",
      "of.options.SMOOTH_WORLD",
      "VOID_PARTICLES",
      "of.options.VOID_PARTICLES",
      "WATER_PARTICLES",
      "of.options.WATER_PARTICLES",
      "RAIN_SPLASH",
      "of.options.RAIN_SPLASH",
      "PORTAL_PARTICLES",
      "of.options.PORTAL_PARTICLES",
      "POTION_PARTICLES",
      "of.options.POTION_PARTICLES",
      "FIREWORK_PARTICLES",
      "of.options.FIREWORK_PARTICLES",
      "PROFILER",
      "of.options.PROFILER",
      "DRIPPING_WATER_LAVA",
      "of.options.DRIPPING_WATER_LAVA",
      "BETTER_SNOW",
      "of.options.BETTER_SNOW",
      "FULLSCREEN_MODE",
      "of.options.FULLSCREEN_MODE",
      "ANIMATED_TERRAIN",
      "of.options.ANIMATED_TERRAIN",
      "SWAMP_COLORS",
      "of.options.SWAMP_COLORS",
      "RANDOM_ENTITIES",
      "of.options.RANDOM_ENTITIES",
      "SMOOTH_BIOMES",
      "of.options.SMOOTH_BIOMES",
      "CUSTOM_FONTS",
      "of.options.CUSTOM_FONTS",
      "CUSTOM_COLORS",
      "of.options.CUSTOM_COLORS",
      "SHOW_CAPES",
      "of.options.SHOW_CAPES",
      "CONNECTED_TEXTURES",
      "of.options.CONNECTED_TEXTURES",
      "CUSTOM_ITEMS",
      "of.options.CUSTOM_ITEMS",
      "AA_LEVEL",
      "of.options.AA_LEVEL",
      "AF_LEVEL",
      "of.options.AF_LEVEL",
      "ANIMATED_TEXTURES",
      "of.options.ANIMATED_TEXTURES",
      "NATURAL_TEXTURES",
      "of.options.NATURAL_TEXTURES",
      "EMISSIVE_TEXTURES",
      "of.options.EMISSIVE_TEXTURES",
      "HELD_ITEM_TOOLTIPS",
      "of.options.HELD_ITEM_TOOLTIPS",
      "DROPPED_ITEMS",
      "of.options.DROPPED_ITEMS",
      "LAZY_CHUNK_LOADING",
      "of.options.LAZY_CHUNK_LOADING",
      "CUSTOM_SKY",
      "of.options.CUSTOM_SKY",
      "FAST_MATH",
      "of.options.FAST_MATH",
      "FAST_RENDER",
      "of.options.FAST_RENDER",
      "TRANSLUCENT_BLOCKS",
      "of.options.TRANSLUCENT_BLOCKS",
      "DYNAMIC_FOV",
      "of.options.DYNAMIC_FOV",
      "DYNAMIC_LIGHTS",
      "of.options.DYNAMIC_LIGHTS",
      "ALTERNATE_BLOCKS",
      "of.options.ALTERNATE_BLOCKS",
      "CUSTOM_ENTITY_MODELS",
      "of.options.CUSTOM_ENTITY_MODELS",
      "ADVANCED_TOOLTIPS",
      "of.options.ADVANCED_TOOLTIPS",
      "SCREENSHOT_SIZE",
      "of.options.SCREENSHOT_SIZE",
      "CUSTOM_GUIS",
      "of.options.CUSTOM_GUIS",
      "RENDER_REGIONS",
      "of.options.RENDER_REGIONS",
      "SHOW_GL_ERRORS",
      "of.options.SHOW_GL_ERRORS",
      "SMART_ANIMATIONS",
      "of.options.SMART_ANIMATIONS",
      "Created",
      "Connecting",
      "Disconnecting",
      "options.stream.ingest.title",
      "options.stream.ingest.reset",
      "mx.sysinfo",
      "Linux",
      "/lib/libc.so.6",
      ".*/libc-(\\d+)\\.(\\d+)\\..*",
      "libc symlink contains unexpected destination: ",
      "/usr/lib/libstdc++.so.6",
      "/usr/lib/libstdc++.so.5",
      ".*/libstdc\\+\\+\\.so\\.(\\d+)\\.0\\.(\\d+)",
      "libstdc++ symlink contains unexpected destination: ",
      "cxx",
      "LEGACY",
      "MOJANG",
      "FOOT",
      "foot",
      "FORBIDDEN",
      "NETWORK_UNREACHABLE",
      "HOST_UNREACHABLE",
      "REFUSED",
      "TTL_EXPIRED",
      "COMMAND_NOT_SUPPORTED",
      "ADDRESS_NOT_SUPPORTED",
      "UNASSIGNED",
      "HOP",
      "STEP",
      "SPRINT",
      "COMPUTERNAME",
      "user.name",
      "PROCESSOR_IDENTIFIER",
      "PROCESSOR_LEVEL",
      "[CB] Error retrieving Hardware ID",
      "save-all",
      "commands.save.usage",
      "commands.save.start",
      "flush",
      "commands.save.flushStart",
      "commands.save.flushEnd",
      "commands.save.failed",
      "commands.save.success",
      "futures",
      "Hit Color",
      "Affect Armor",
      "Affected by brightness",
      "Animation Type",
      "Customize the damage tint overlay on entities.",
      "aycy (Fade animation)",
      "Damage Tint",
      "client/icons/mods/hittint.png",
      "details",
      "timestamps",
      "end",
      "large_image",
      "large_text",
      "small_image",
      "small_text",
      "party",
      "secrets",
      "spectate",
      "resourcePack.incompatible.confirm.title",
      "resourcePack.incompatible.confirm.",
      "new",
      "old",
      "resourcePack.incompatible",
      "resourcePack.incompatible.old",
      "resourcePack.incompatible.new",
      "readerIndex: %d (expected: 0 <= readerIndex <= writerIndex(%d))",
      "writerIndex: %d (expected: readerIndex(%d) <= writerIndex <= capacity(%d))",
      "readerIndex: %d, writerIndex: %d (expected: 0 <= readerIndex <= writerIndex <= capacity(%d))",
      "minWritableBytes: %d (expected: >= 0)",
      "writerIndex(%d) + minWritableBytes(%d) exceeds maxCapacity(%d): %s",
      "length(%d) exceeds src.readableBytes(%d) where src is: %s",
      "length(%d) exceeds dst.writableBytes(%d) where dst is: %s",
      "(ridx: ",
      ", widx: ",
      ", cap: ",
      ", unwrapped: ",
      "index: %d (expected: range(0, %d))",
      "index: %d, length: %d (expected: range(0, %d))",
      "srcIndex: %d, length: %d (expected: range(0, %d))",
      "minimumReadableBytes: ",
      "readerIndex(%d) + length(%d) exceeds writerIndex(%d): %s",
      "Failed to submit an exceptionCaught() event.",
      "The exceptionCaught() event that was failed to submit was:",
      "An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:",
      "Failed to fail the promise because it's done already: {}",
      "An exception was thrown by a user handler while handling an exceptionCaught event",
      "exceptionCaught",
      "promise already done: ",
      "promise.channel does not match: %s (expected: %s)",
      " not allowed for this operation",
      " not allowed in a pipeline",
      "input stream [",
      "DOWN_NORTH",
      "DOWN_SOUTH",
      "UP_NORTH",
      "UP_SOUTH",
      "DOWN_WEST",
      "DOWN_EAST",
      "UP_WEST",
      "UP_EAST",
      "SUNFLOWER",
      "SYRINGA",
      "ROSE",
      "PAEONIA",
      "commands.achievement.usage",
      "commands.achievement.unknownAchievement",
      "commands.achievement.give.success.all",
      "commands.achievement.take.success.all",
      "commands.achievement.alreadyHave",
      "commands.achievement.dontHave",
      "commands.achievement.give.success.one",
      "commands.achievement.take.success.one",
      "untouching"
   };
}
