package recovered.strings;

public class StringTable09 {
   public static String[] recoveredField3952 = new String[]{
      "item.banner.",
      ".name",
      "BlockEntityTag",
      "Patterns",
      "Color",
      "Pattern",
      ".",
      "Base",
      "BIOME_",
      "Expression already defined: ",
      "VertexFormat error: Trying to add a position VertexFormatElement when one already exists, ignoring.",
      "format: ",
      " elements: ",
      " ",
      "",
      ".dry.name",
      "wet",
      "Received SctpMessage is not complete, please add %s in the pipeline before this handler",
      "Failed to close a partially initialized socket.",
      "Failed to enter non-blocking mode.",
      "xPos",
      "zPos",
      "Blocks",
      "Data",
      "SkyLight",
      "BlockLight",
      "HeightMap",
      "TerrainPopulated",
      "Entities",
      "TileEntities",
      "TileTicks",
      "LastUpdate",
      "Y",
      "Sections",
      "Biomes",
      "random.bow",
      "Unsupported mob for MoveThroughVillageGoal",
      "#",
      "^",
      "~ ~",
      "###",
      "~#~",
      "~^~",
      "minecraft:mob.guardian.attack",
      "N/A (disabled)",
      "insecure",
      "TITLE",
      "SUBTITLE",
      "TIMES",
      "CLEAR",
      "RESET",
      "createWorld.customize.flat.title",
      "createWorld.customize.flat.tile",
      "createWorld.customize.flat.height",
      "createWorld.customize.flat.addLayer",
      " (NYI)",
      "createWorld.customize.flat.editLayer",
      "createWorld.customize.flat.removeLayer",
      "gui.done",
      "createWorld.customize.presets",
      "gui.cancel",
      "token cannot be null",
      "textures/entity/cow/mushroom_red.png",
      "Method",
      "method",
      "textures/entity/chicken.png",
      "zombie",
      "handlers",
      "handlers is empty.",
      "More than one exception was raised. Will report only the first one and log others.",
      "summon",
      "commands.summon.usage",
      "commands.summon.outOfWorld",
      "LightningBolt",
      "commands.summon.success",
      "commands.summon.tagError",
      "id",
      "commands.summon.failed",
      "Riding",
      "facing",
      "textures/entity/pig/pig_saddle.png",
      "Line Sep",
      "lineSep",
      "Tick",
      "Villages",
      "villages",
      "Name",
      "Modifiers",
      "Amount",
      "Operation",
      "UUIDMost",
      "UUIDLeast",
      "Ignoring unknown attribute '",
      "'",
      "Unable to create attribute: ",
      "generic.maxHealth",
      "Max Health",
      "generic.followRange",
      "Follow Range",
      "generic.knockbackResistance",
      "Knockback Resistance",
      "generic.movementSpeed",
      "Movement Speed",
      "generic.attackDamage",
      "content",
      "(data: ",
      ", decoderResult: ",
      "InLove",
      "[host=",
      ";port=",
      ";file=",
      "]",
      "<RETURN> to continue",
      "Time: ",
      "error",
      "failure",
      "There was ",
      ":",
      "There were ",
      "s:",
      ") ",
      "OK",
      " (",
      " test",
      "s",
      ")",
      "FAILURES!!!",
      "Tests run: ",
      ",  Failures: ",
      ",  Errors: ",
      "E",
      "F",
      "pathfind",
      "Couldn't render entity",
      "None",
      "Linear In/Out",
      "Linear Out",
      "Dinnerbone",
      "Grumm",
      "You",
      "animate.model.living",
      "client/logo_white.png",
      "While Typing",
      "ON",
      "Full",
      "[CHAT] ",
      "hypixel",
      "You can't tip the same person",
      "Still processing your most recent request!",
      "You've already tipped that person",
      "You cannot tip yourself!",
      "You can only use the /tip command",
      "You are not allowed to use commands as a spectator!",
      "Slow down! You can only use /tip every few seconds.",
      "You've already tipped someone in the past hour in ",
      "gg",
      "gl",
      "targetContentEncoding",
      "contentEncoder",
      "variants",
      "selectServer.select",
      "selectServer.direct",
      "addServer.enterIp",
      "Yes",
      "No",
      "address and connectionscontainer must not be null and you need at least 1 decoder",
      " can only be started once.",
      "WebSocketSelector-",
      "IOException during selector.close",
      "IOException during server.close",
      "Connection closed because of exception",
      "Shutdown due to fatal error",
      "Error during shutdown",
      "Interrupt during stop",
      "Removing connection which is not in the connections collection! Possible no handshake recieved! {}",
      "container.dispenser",
      "Items",
      "Slot",
      "CustomName",
      "minecraft:dispenser",
      "commands.generic.num.invalid",
      "Expected ",
      " to be a string, was ",
      "Missing ",
      ", expected to find a string",
      " to be a Boolean, was ",
      ", expected to find a Boolean",
      " to be a Float, was ",
      ", expected to find a Float",
      " to be a Int, was ",
      ", expected to find a Int",
      " to be a JsonObject, was ",
      ", expected to find a JsonObject",
      " to be a JsonArray, was ",
      ", expected to find a JsonArray",
      "...",
      "null (missing)",
      "null (json)",
      "an array (",
      "an object (",
      "a number (",
      "a boolean (",
      "HANDSHAKE_COMPLETE",
      "Invalid call to Particle.setTex, use coordinate methods",
      "Invalid call to Particle.setMiscTex",
      ", Pos (",
      ",",
      "), RGBA (",
      "), Age ",
      "tile",
      "item",
      "open",
      "hinge",
      "powered",
      "half",
      "value",
      "Cannot compare ",
      " with ",
      "=IoException",
      ".att",
      "Attr_",
      "in",
      "textures/entity/wolf/wolf.png",
      "textures/entity/wolf/wolf_tame.png",
      "textures/entity/wolf/wolf_angry.png",
      "Got external roll over signal.",
      "RollOver",
      "Expecting [RollOver] string.",
      "Unexpected exception. Exiting HUPNode.",
      "Comparing biomes",
      "Biomes being compared",
      "Biome A ID",
      "Biome B ID",
      "Biome A",
      "Biome B",
      "SHA1",
      "1.8.9",
      "rotation",
      "translation",
      "scale",
      "Expected 3 ",
      " values, found: ",
      "[",
      "out",
      "estimatedLength: ",
      "S",
      "T",
      "R",
      "Q",
      "compressionLevel: ",
      " (expected: 0-9)",
      "frame",
      "chat.type.admin",
      "logAdminCommands",
      "sendCommandFeedback",
      "false",
      "true",
      "#define ",
      " // Shader option ON",
      "//#define ",
      " // Shader option OFF",
      "§a",
      "§c",
      "//",
      "/shaders/",
      "^\\s*(//)?\\s*#define\\s+([A-Za-z0-9_]+)\\s*(//.*)?$",
      "^\\s*#if(n)?def\\s+([A-Za-z0-9_]+)(\\s*)?$",
      "failed to create a sctp server channel",
      "sctp server channel",
      "Failed to close a sctp server channel.",
      "failed to initialize a sctp server channel",
      "Failed to close a selector.",
      "Failed to create a new channel from an accepted sctp channel.",
      "Failed to close a sctp channel.",
      "Unsupported mob type for RestrictOpenDoorGoal",
      "negative length: ",
      "length wider than 32-bit",
      "Game mode: %s (ID %d). Hardcore: %b. Cheats: %b",
      "attributeNames[] cannot be null",
      "Cannot invoke a getter of ",
      "AttributeList attributes cannot be null",
      "Cannot invoke a setter of ",
      "postDeregister is called.",
      "preRegister called. Server=",
      ", name=",
      "preDeregister called.",
      "Missing MBean ",
      "Failed unregistering ",
      "SKY",
      "BLOCK",
      "******** ",
      " ***********",
      "%.2f, Math: %f, Helper: %f, diff: %f",
      "client/icons/left.png",
      "client/icons/right.png",
      "BACK",
      "Unable to connect to the server.",
      "Please try again later.",
      "You don't own any cosmetics.",
      "Cosmetics (",
      "gui.button.press",
      "dry",
      "Error: ",
      "buffer",
      "Out of size: ",
      " > ",
      "inputStream",
      "Failed to close a file.",
      "dest",
      "No file defined so cannot be renamed",
      "File too big to be loaded in memory",
      "wrapper",
      "initialization failure",
      "dictionary",
      "decompression failure",
      "failed to set the dictionary",
      "Unknown channel option: ",
      "Failed to set a channel option: ",
      "Failed to register an accepted channel: ",
      "HTTP",
      "HTTP-Version",
      "Status-Code",
      "Reason-Phrase",
      "Request-URI",
      "Not enough material for an HTTP header.",
      "\r\n",
      ": ",
      "E199AD21-BA8A-4C53-8D13-6182D5C69D3A",
      "Fleeing speed bonus",
      "cookie",
      "cookies",
      "$Version",
      "$Path",
      "$Domain",
      "Port",
      " // Shader option ",
      "prefix.",
      "suffix.",
      "off",
      "^\\s*#define\\s+(\\w+)\\s+(-?[0-9\\.Ff]+|\\w+)\\s*(//.*)?$",
      "Failed to instantiate ",
      "data",
      "idcounts",
      "org.apache.log4j.spi.LoggingEvent",
      "getPropertyKeySet",
      "org.apache.log4j.pattern.LogEvent",
      "Back to ",
      "Main Folder",
      "Explosion",
      "Explosions",
      "Flight",
      "Fireworks",
      "Flicker",
      "Trail",
      "Colors",
      "Type",
      "FadeColors",
      "X",
      " #X",
      "# X",
      "DOWN",
      "UP",
      "NORTH",
      "SOUTH",
      "WEST",
      "EAST",
      "stat.crafted",
      "stat.used",
      "stat.mined",
      "name",
      "empty name",
      "name contains non-ascii character: ",
      "name contains one of the following prohibited characters: =,; \\t\\r\\n\\v\\f: ",
      "name starting with '$' not allowed: ",
      "domain",
      "path",
      "comment",
      "commentUrl",
      "ports",
      "port out of range: ",
      ", domain=",
      ", path=",
      ", comment=",
      ", maxAge=",
      ", secure",
      ", HTTPOnly",
      " contains one of the following prohibited characters: ",
      ";\\r\\n\\f\\v (",
      "null",
      "Mixed: ",
      "Failed to complete handshake",
      "Friend.FriendBuilder(playerId=",
      ", status=",
      ", server=",
      ", online=",
      ", offlineSince=",
      ", onlineStatus=",
      "TCP_CORK",
      "TCP_KEEPIDLE",
      "TCP_KEEPINTVL",
      "TCP_KEEPCNT",
      "SO_REUSEPORT",
      "/reloadShaders",
      "/reloadChunks",
      "null input",
      "Failed to find org.slf4j.helpers.Util or its caller in the stack; this should not happen",
      "Reported exception:",
      "SLF4J: ",
      "textures/entity/cow/cow.png",
      "dig.wood",
      "variant",
      "Primary Sound Capture Driver",
      "Default",
      "random.fizz",
      "Dab",
      "user.home",
      "file.separator",
      "lf5",
      "mru_file_manager",
      "kick",
      "commands.kick.usage",
      "Kicked by an operator.",
      "commands.kick.success.reason",
      "commands.kick.success",
      "io.netty.noJdkZlibDecoder",
      "-Dio.netty.noJdkZlibDecoder: {}",
      "Layer ",
      " frame ",
      " no",
      " checksums",
      "Xing",
      "XingVBRHeader Corrupted",
      "VBRI",
      "VBRIVBRHeader Corrupted",
      "I",
      "II",
      "III",
      " kb/s",
      "32 kHz",
      "16 kHz",
      "8 kHz",
      "44.1 kHz",
      "22.05 kHz",
      "11.025 kHz",
      "48 kHz",
      "24 kHz",
      "12 kHz",
      "Stereo",
      "Joint stereo",
      "Dual channel",
      "Single channel",
      "MPEG-1",
      "MPEG-2 LSF",
      "MPEG-2.5 LSF",
      "free format",
      "32 kbit/s",
      "48 kbit/s",
      "56 kbit/s",
      "64 kbit/s",
      "80 kbit/s",
      "96 kbit/s",
      "112 kbit/s",
      "128 kbit/s",
      "144 kbit/s",
      "160 kbit/s",
      "176 kbit/s",
      "192 kbit/s",
      "224 kbit/s",
      "256 kbit/s",
      "forbidden",
      "8 kbit/s",
      "16 kbit/s",
      "24 kbit/s",
      "40 kbit/s",
      "288 kbit/s",
      "320 kbit/s",
      "352 kbit/s",
      "384 kbit/s",
      "416 kbit/s",
      "448 kbit/s",
      "Version",
      "Discard",
      "Secure",
      "HTTPOnly",
      "Comment",
      "CommentURL",
      "Domain",
      "Path",
      "Expires",
      "Max-Age",
      "RandomEntities",
      "textures.",
      "skins.",
      "No skins specified: ",
      "Texture not found: ",
      ":.",
      "0",
      "Failed to retrieve the list of available network interfaces",
      "Failed to find the loopback interface",
      "Loopback interface: {} ({}, {})",
      "Using hard-coded IPv6 localhost address: {}",
      "Using hard-coded IPv4 localhost address: {}",
      "/proc/sys/net/core/somaxconn",
      "{}: {}",
      "Failed to get SOMAXCONN from: {}",
      "{}: {} (non-existent)",
      "tintindex",
      "texture",
      "cullface",
      "Exception decoding audio frame",
      "pages",
      "book.signButton",
      "book.finalizeButton",
      "MC|BEdit",
      "MC|BSign",
      "author",
      "title",
      "\n",
      "_",
      "book.editTitle",
      "book.byAuthor",
      "book.finalizeWarning",
      "book.pageIndicator",
      "* Invalid book tag *",
      "textures/gui/book.png",
      "\u0000",
      "http://s.optifine.net/capes/",
      ".png",
      "capeof/",
      "[a-zA-Z0-9_]+",
      "Shaders",
      "of.options.shadersTitle",
      "of.options.shaders.shadersFolder",
      "of.options.shaders.shaderOptions",
      "cmd.exe /C start \"Open file\" \"%s\"",
      "/usr/bin/open",
      "java.awt.Desktop",
      "getDesktop",
      "browse",
      "shaderpacks",
      "Opening via system class!",
      "file://",
      "http://optifine.net/shaderPacks",
      "Tex Min: ",
      "Tex_n Mag: ",
      "Tex_s Mag: ",
      "ShadowClipFrustrum: ",
      "OpenGL: ",
      ", ",
      "FXAA 2x",
      "FXAA 4x",
      "os.name",
      "win",
      "mac",
      "solaris",
      "sunos",
      "linux",
      "unix",
      "0.5x",
      "0.6x",
      "0.66x",
      "0.75x",
      "0.83x",
      "0.9x",
      "1x",
      "1.16x",
      "1.33x",
      "1.5x",
      "1.66x",
      "1.8x",
      "2x",
      "Facing",
      "TileX",
      "TileY",
      "TileZ",
      "Direction",
      "Dir",
      "read-only",
      "Couldn't connect to world",
      "connect.failed",
      "disconnect.genericReason",
      "Unknown host '",
      "Close menu",
      "{}",
      "SLF4J: Failed toString() invocation on an object of type [",
      "[FAILED toString()]",
      "CHECK_PROTOCOL_VERSION",
      "READ_CMD_HEADER",
      "READ_CMD_ADDRESS",
      "Downloading Resource Pack",
      "Making Request...",
      "Downloading file (%.2f MB)...",
      "Deleting ",
      " as it does not match what we currently have (",
      " vs our ",
      ").",
      "Filesize is bigger than maximum allowed (file is ",
      ", limit is ",
      "Filesize was bigger than maximum allowed (got >= ",
      ", limit was ",
      "INTERRUPTED",
      "OPEN_URL",
      "open_url",
      "OPEN_FILE",
      "open_file",
      "RUN_COMMAND",
      "run_command",
      "TWITCH_USER_INFO",
      "twitch_user_info",
      "SUGGEST_COMMAND",
      "suggest_command",
      "CHANGE_PAGE",
      "change_page",
      "UPLOAD_SCREENSHOT",
      "upload_screenshot",
      "COPY_SCREENSHOT",
      "copy_screenshot",
      "()",
      "doEntityDrops",
      "frame-",
      "Item",
      "ItemRotation",
      "ItemDropChance",
      "left",
      "right",
      "LEFT",
      "RIGHT",
      "Tried to read NBT tag with too high complexity, depth > 512",
      "{",
      "Reading NBT data",
      "Corrupt NBT tag",
      "Tag type found",
      "Tag type expected",
      "Tag name",
      "Loading NBT data",
      "NBT Tag",
      "Tag type",
      "green",
      "red",
      "BUSY",
      "yellow",
      "UNKNOWN",
      "unknown",
      "Finalizing appender named [",
      "].",
      "Attempted to append to closed appender named [",
      "You have tried to set a null error-handler.",
      "selectWorld.renameButton",
      "selectWorld.renameTitle",
      "selectWorld.enterName",
      "textures/entity/creeper/creeper.png",
      " total; ",
      "Rcon",
      "A JSONArray text must start with '['",
      "Expected a ',' or ']'",
      "JSONArray initial value should be a string or collection or array.",
      "JSONArray[",
      "] not found.",
      "] is not a boolean.",
      "] is not a number.",
      "] is not an enum of type ",
      "] could not convert to BigDecimal.",
      "] could not convert to BigInteger.",
      "] is not a JSONArray.",
      "] is not a JSONObject.",
      "] not a string.",
      "Unable to write JSONArray value at index: 0",
      "Unable to write JSONArray value at index: ",
      "multiplayer.stopSleeping",
      "noclip",
      "WebSocketClientHandshaker should have been non finished yet",
      "read only",
      "Ping",
      "[19 ms]",
      "Displays your server latency.",
      "119",
      "ms",
      "Refresh Time",
      "Changes how many seconds the mod should refresh itself.",
      "Hide if no connection",
      "Hide the mod when no connection is found.",
      "Hide in Singleplayer",
      "Hid the mod in Singleplayer.",
      "Accurate Mode",
      "Shows ping from server list so its accurate at all times.",
      "Dynamic Color Range",
      "Determine if the text color should change dynamically based on ping amount.",
      "Bad Ping Range Threshold",
      "FULL",
      "options.chat.visibility.full",
      "SYSTEM",
      "options.chat.visibility.system",
      "HIDDEN",
      "options.chat.visibility.hidden",
      "LEFT_TO_RIGHT",
      "RIGHT_TO_LEFT",
      "RIGHT_TO_BACK",
      "LEFT_TO_BACK",
      "unknown ",
      " value: ",
      "STOPBITS_1",
      "STOPBITS_2",
      "STOPBITS_1_5",
      "textures/blocks/wool_colored_red.png",
      "Ping: (<1.3.x) from {}:{}",
      "%s§%d§%d",
      "legacy_query",
      "Ping: (1.4-1.5.x) from {}:{}",
      "§1\u0000%d\u0000%s\u0000%s\u0000%d\u0000%d",
      "MC|PingHost",
      "Ping: (1.6) from {}:{}",
      "Shader Options",
      "screen.",
      "of.options.shaderOptionsTitle",
      "controls.reset",
      "COD",
      "cod",
      "SALMON",
      "salmon",
      "CLOWNFISH",
      "clownfish",
      "PUFFERFISH",
      "pufferfish",
      "dst",
      "dstIndex: ",
      "src",
      "srcIndex: ",
      "direct buffer",
      "multiplayer.downloadingStats",
      "gui.achievements",
      "achievement.taken",
      "achievement.unknown",
      "achievement.requires",
      "textures/gui/achievement/achievement_background.png",
      "map_is_scaling",
      "version",
      "protocol",
      "Sec-WebSocket-Version",
      "UTF8",
      "ASCII",
      "&amp;",
      "&lt;",
      "&gt;",
      "&quot;",
      "&apos;",
      "&#x",
      "Empty string.",
      "' contains a space character.",
      "-->",
      "CDATA",
      "Expected 'CDATA['",
      "Missing '>' after '<!'.",
      "?>",
      "Mismatched close tag ",
      "Mismatched ",
      " and ",
      "Misshaped close tag",
      "Misshaped tag",
      "Missing value",
      "Unclosed tag ",
      "<",
      "</",
      "/>",
      "array",
      "\"",
      ">",
      "addresses",
      "https://servermappings.lunarclientcdn.com/servers.json",
      "The given array is NULL",
      "0x",
      "Can not make arrays with primitive elements (int, double), element class: ",
      "HttpPipelineSender",
      "sheep",
      "f",
      "creeper",
      "head",
      "armor",
      "body",
      "leg1",
      "leg2",
      "leg3",
      "leg4",
      "(",
      "RandomSeed",
      "generatorName",
      "generatorVersion",
      "generatorOptions",
      "GameType",
      "MapFeatures",
      "SpawnX",
      "SpawnY",
      "SpawnZ",
      "Time",
      "DayTime",
      "LastPlayed",
      "SizeOnDisk",
      "LevelName",
      "clearWeatherTime",
      "rainTime",
      "raining",
      "thunderTime",
      "thundering",
      "hardcore",
      "initialized",
      "allowCommands",
      "Player",
      "Dimension",
      "GameRules",
      "Difficulty",
      "DifficultyLocked",
      "BorderCenterX",
      "BorderCenterZ",
      "BorderSize",
      "BorderSizeLerpTime",
      "BorderSizeLerpTarget",
      "BorderSafeZone",
      "BorderDamagePerBlock",
      "BorderWarningBlocks",
      "BorderWarningTime",
      "Level seed",
      "Level generator",
      "Level generator options",
      "Level spawn location",
      "Level time",
      "Level dimension",
      "Level storage version",
      "Level weather",
      "Level game mode",
      "Failed to load texture: ",
      "Registering texture",
      "Resource location being registered",
      "Resource location",
      "Texture object class",
      "logo",
      "dynamic/%s_%d",
      "*** Reloading textures ***",
      "Resource packs: ",
      "mcpatcher/",
      "optifine/",
      "mob.sheep.shear",
      "Sheared",
      "mob.sheep.say",
      "mob.sheep.step",
      "scoreboard",
      "Objectives",
      "PlayerScores",
      "DisplaySlots",
      "Teams",
      "DisplayName",
      "TeamColor",
      "Prefix",
      "Suffix",
      "AllowFriendlyFire",
      "SeeFriendlyInvisibles",
      "NameTagVisibility",
      "DeathMessageVisibility",
      "Players",
      "slot_",
      "CriteriaName",
      "RenderType",
      "Objective",
      "Score",
      "Locked",
      "Tried to save scoreboard without having a scoreboard...",
      ";",
      "=",
      "oxygen",
      "filename",
      "contentType",
      "Content-Disposition: form-data; name=\"",
      "\"; ",
      "=\"",
      "\"\r\n",
      "Content-Type",
      "; charset=",
      "Content-Length",
      "Completed: ",
      "\r\nIsInMemory: ",
      "\r\nRealFile: ",
      " DefaultDeleteAfter: ",
      ".tmp",
      "FUp_",
      "SOCKS_AUTH_RESPONSE_DECODER",
      "Line",
      "line",
      "banlist",
      "commands.banlist.usage",
      "ips",
      "commands.banlist.ips",
      "commands.banlist.players",
      "players",
      "ForkJoinPool-",
      "-worker-",
      "Terminated",
      "Terminating",
      "Shutting down",
      "Running",
      ", parallelism = ",
      ", size = ",
      ", active = ",
      ", running = ",
      ", steals = ",
      ", tasks = ",
      ", submissions = ",
      "java.util.concurrent.ForkJoinPool.common.parallelism",
      "java.util.concurrent.ForkJoinPool.common.threadFactory",
      "java.util.concurrent.ForkJoinPool.common.exceptionHandler",
      "ForkJoinPool.commonPool-worker-",
      "Could not initialize intrinsics",
      "ctl",
      "stealCount",
      "plock",
      "indexSeed",
      "parkBlocker",
      "base",
      "qlock",
      "data type scale not a power of two",
      "modifyThread",
      "mob.skeleton.say",
      "mob.skeleton.hurt",
      "mob.skeleton.death",
      "mob.skeleton.step",
      "SkeletonType",
      "HANDSHAKE_ISSUED",
      "token:",
      "CA",
      "CB",
      "CC",
      "CD",
      ":host",
      ":method",
      ":scheme",
      ":status",
      ":path",
      ":version",
      "mob.endermen.stare",
      "client/preview/",
      "client/",
      "Iterator still used, oldList: ",
      ", newList: ",
      "remove",
      "textures/entity/boat.png",
      "id: ",
      ", boxes: ",
      ", submodels: ",
      "O",
      "-",
      "MC|AdvCdm",
      "advMode.setCommand",
      "advMode.command",
      "advMode.nearestPlayer",
      "advMode.randomPlayer",
      "advMode.allPlayers",
      "advMode.allEntities",
      "advMode.previousOutput",
      "Associated-To-Stream-ID cannot be negative: ",
      "Priority must be between 0 and 7 inclusive: ",
      "(last: ",
      "; unidirectional: ",
      "--> Stream-ID = ",
      "--> Associated-To-Stream-ID = ",
      "--> Priority = ",
      "--> Headers:",
      "Size",
      "wasOnGround",
      "mob.slime.",
      "big",
      "small",
      "mob.attack",
      "GROWING",
      "SHRINKING",
      "STATIONARY",
      "bulk",
      "Chunk render task was ",
      " when I expected it to be uploading; aborting task",
      "Rendering chunk",
      "dialect",
      "Already decorating",
      "childGroup",
      "childGroup set already",
      "childOption",
      "childKey",
      "childHandler",
      "childHandler not set",
      "childGroup is not set. Using parentGroup instead.",
      "childGroup: ",
      "childOptions: ",
      "childAttrs: ",
      "childHandler: ",
      "textures/entity/zombie/zombie.png",
      "textures/entity/zombie/zombie_villager.png",
      "RandomLevelSource",
      "Stronghold",
      "END",
      "BYTE",
      "SHORT",
      "INT",
      "LONG",
      "FLOAT",
      "DOUBLE",
      "BYTE[]",
      "STRING",
      "LIST",
      "COMPOUND",
      "INT[]",
      "unable to fit ",
      " into ",
      "SocketHubAppender-Monitor-",
      "server monitor thread shutting down",
      "server monitor thread shut down",
      "exception setting timeout, shutting down server socket.",
      "exception accepting socket, shutting down server socket.",
      "exception accepting socket.",
      "accepting connection from ",
      "exception creating output stream on socket.",
      "type",
      "promise",
      "pendingDataSize must be >= 0 but was ",
      "delta must be >= 0 but was ",
      "Memory Usage",
      "[Mem: 19%]",
      "Displays how much memory the game is using.",
      "%",
      "Mem"
   };
}
