package recovered.strings;

public class StringTable07 {
   public static String[] recoveredField3957 = new String[]{
      "commands.clone.success",
      "commands.clone.outOfWorld",
      "META-INF/io.netty.versions.properties",
      ".version",
      ".buildDate",
      ".commitDate",
      ".shortCommitHash",
      ".longCommitHash",
      ".repoStatus",
      "yyyy-MM-dd HH:mm:ss Z",
      "clean",
      " (repository: ",
      "HH:mm:ss",
      "Created Friends Manager",
      "Output buffers are different.",
      "--> Status: ",
      " GL version ",
      "java.net.preferIPv4Stack",
      "demo",
      "fullscreen",
      "checkGlErrors",
      "gameDir",
      "assetsDir",
      "resourcePackDir",
      "proxyHost",
      "proxyPort",
      "8080",
      "proxyUser",
      "proxyPass",
      "width",
      "height",
      "userProperties",
      "profileProperties",
      "assetIndex",
      "userType",
      "legacy",
      "Completely ignored arguments: ",
      "resourcepacks/",
      "Client Shutdown Thread",
      "Client thread",
      "key must not be empty.",
      "Unable to retrieve a system property '",
      "'; default values will be used.",
      "yes",
      "no",
      "Unable to parse the boolean system property '",
      "':",
      "using the default value: ",
      "Unable to parse the integer system property '",
      "Unable to parse the long integer system property '",
      "-?[0-9]+",
      "textures/entity/cat/black.png",
      "textures/entity/cat/ocelot.png",
      "textures/entity/cat/red.png",
      "textures/entity/cat/siamese.png",
      "Add first: ",
      "Add last: ",
      "Add after: ",
      "Remove: ",
      "List: ",
      "Wrong size, linked: ",
      ", used: ",
      "Wrong count, linked: ",
      ", count: ",
      "Wrong count back, linked: ",
      "Total size: ",
      "HttpPipelineReceiver",
      "Invalid status line: ",
      "Converting map!",
      "menu.convertingLevel",
      "menu.loadingLevel",
      "menu.generatingTerrain",
      "Preparing start region for level ",
      "Preparing spawn area",
      "resources.zip",
      "level://",
      "Saving chunks for level '",
      "'/",
      "Stopping server",
      "Saving players",
      "Saving worlds",
      "Can't keep up! Did the system time change, or is the server overloaded? Running {}ms behind, skipping {} tick(s)",
      "Time ran backwards! Did the system time change?",
      "Exception stopping the server",
      "Encountered an unexpected exception",
      "Exception in server tick loop",
      "crash-reports",
      "crash-",
      "yyyy-MM-dd_HH.mm.ss",
      "-server.txt",
      "This crash report has been saved to: ",
      "We were unable to save this crash report to disk.",
      "server-icon.png",
      "PNG",
      "data:image/png;base64,",
      "Couldn't load server icon",
      "root",
      "save",
      "tallying",
      "snooper",
      "jobs",
      "levels",
      "timeSync",
      "tick",
      "Exception ticking world",
      "Exception ticking world entities",
      "tracker",
      "connection",
      "tickables",
      "Server thread",
      "Profiler Position",
      "Player Count",
      "Server",
      "whitelist_enabled",
      "whitelist_count",
      "players_current",
      "players_max",
      "players_seen",
      "uses_auth",
      "gui_state",
      "enabled",
      "disabled",
      "run_time",
      "avg_tick_ms",
      "world[",
      "][dimension]",
      "][mode]",
      "][difficulty]",
      "][hardcore]",
      "][generator_name]",
      "][generator_version]",
      "][height]",
      "][chunks_loaded]",
      "worlds",
      "singleplayer",
      "server_brand",
      "gui_supported",
      "headless",
      "supported",
      "dedicated",
      "usercache.json",
      "minecraft:blocks/fire_layer_1",
      "textures/map/map_background.png",
      "textures/misc/underwater.png",
      "icon-",
      "Player List",
      "Show Row Background",
      "Highlight Own Row",
      "Highlight CheatBreaker Players' Row",
      "Use Ping Color for Row Background",
      "Row Background Color",
      "Self Row Color",
      "CheatBreaker Row Color",
      "Name Text Shadow",
      "Show CheatBreaker Logo",
      "Highlight CheatBreaker Players' Name",
      "Self Text Color",
      "CheatBreaker Text Color",
      "Ping Options",
      "Show Ping",
      "Show Ping as Number",
      "Ping Text Shadow",
      "Dynamic Ping Number Color",
      "Static Ping Color",
      "Low Ping Color",
      "Medium Ping Color",
      "High Ping Color",
      "Extremely High Ping Color",
      "Customize the player list tab.",
      "Tab",
      "textures/gui/icons.png",
      "container.repair",
      "container.repair.cost",
      "container.repair.expensive",
      "MC|ItemName",
      "textures/gui/container/anvil.png",
      "PickupDelay",
      "Thrower",
      "random.pop",
      "item.",
      "Item entity ",
      " has no item?!",
      "CONTINUOUS",
      "TEXT",
      "BINARY",
      "PING",
      "PONG",
      "CLOSING",
      "textures/entity/endercrystal/endercrystal_beam.png",
      "textures/entity/enderdragon/dragon_exploding.png",
      "textures/entity/enderdragon/dragon.png",
      "Preamble is greater than 4 bytes",
      "Offset exceeds maximum permissible value",
      "Offset is less than minimum permissible value",
      "Offset exceeds size of chunk",
      "mismatching checksum: ",
      "READ_NUM_HEADERS",
      "READ_NAME_LENGTH",
      "READ_NAME",
      "SKIP_NAME",
      "READ_VALUE_LENGTH",
      "READ_VALUE",
      "SKIP_VALUE",
      "END_HEADER_BLOCK",
      "doublePlant",
      "Received invalid header block",
      "Invalid Header Block",
      " (socket: ",
      "Discarded {0} messages due to full event buffer including: {1}",
      "org.apache.log4j.AsyncAppender.DONT_REPORT_LOCATION",
      "client/animatedlogo/128/logo_128_no_stars.png",
      "client/animatedlogo/128/logo_128_star_",
      "Potion Counter",
      "[10 Pots]",
      "Displays the amount of healing potions or bowls of soup in your inventory.",
      "Maxwell",
      "Hide When Empty",
      "Hide the mod when there are none of the selected counter item in your inventory.",
      "Count Healing potions or Soup.",
      "Pots",
      "Soup",
      "Netty Epoll Server IO #%d",
      "MinecartRideable",
      "EntityId",
      "Delay",
      "SpawnData",
      "MinSpawnDelay",
      "MaxSpawnDelay",
      "SpawnCount",
      "MaxNearbyEntities",
      "RequiredPlayerRange",
      "SpawnRange",
      "mobBaseTick",
      "CanPickUpLoot",
      "PersistenceRequired",
      "Equipment",
      "DropChances",
      "Leashed",
      "Leash",
      "NoAI",
      "checkDespawn",
      "sensing",
      "targetSelector",
      "goalSelector",
      "navigation",
      "mob tick",
      "controls",
      "look",
      "Random spawn bonus",
      "log4j.appender.",
      "log4j.logger.",
      "log4j.additivity.",
      "=false",
      "ClickEvent{action=",
      ", value='",
      "client/animatedlogo/64/logo_64_no_stars.png",
      "client/animatedlogo/64/logo_64_star_",
      "maxOrder should be < 30, but is: ",
      "val = %d, id & initial = %d, d = %d",
      "Chunk(",
      "%, ",
      "failed to initialize a socket",
      "Integer",
      "RIDEABLE",
      "CHEST",
      "MinecartChest",
      "FURNACE",
      "MinecartFurnace",
      "TNT",
      "MinecartTNT",
      "SPAWNER",
      "MinecartSpawner",
      "HOPPER",
      "MinecartHopper",
      "COMMAND_BLOCK",
      "MinecartCommandBlock",
      "/org/apache/log4j/lf5/config/defaultconfig.properties",
      "org.apache.log4j.lf5.DefaultLF5Configurator",
      "Error: Unable to open the resource",
      "This class should NOT be instantiated!",
      "spawner_minecart",
      "Field not found: RenderMinecart.modelMinecart",
      "Features",
      "PROTOCOL_RECEIVE_BUFFER_SIZE",
      "PROTOCOL_SEND_BUFFER_SIZE",
      "SYSTEM_RECEIVE_BUFFER_SIZE",
      "SYSTEM_SEND_BUFFER_SIZE",
      "Stepping back two steps is not supported",
      "Unable to preserve stream position",
      "Unable to read the next character from the stream",
      "Expected '",
      "' and instead saw '",
      "' and instead saw ''",
      "Substring bounds error",
      "Illegal escape.",
      ",:]}/\\\"[{;=#",
      " at ",
      " [character ",
      " line ",
      "textures/entity/spider_eyes.png",
      "Attempting connection to ",
      "Connection established. Exiting connector thread.",
      "Connector interrupted. Leaving loop.",
      "Remote host ",
      " refused connection.",
      "Could not connect to ",
      ". Exception is ",
      "unsupported message type: ",
      "Acct schedule not ok: ",
      " > 2*",
      " from ",
      "Monitor ",
      " Current Speed Read: ",
      " KB/s, Write: ",
      " KB/s Current Read: ",
      " KB Current Write: ",
      " KB",
      "MD5",
      "MD5 not supported on this platform - Outdated?",
      "SHA-1 is not supported on this platform - Outdated?",
      "textures/entity/wither/wither_armor.png",
      "MONSTER",
      "CREATURE",
      "WATER_CREATURE",
      "Swapped(",
      "mob.silverfish.say",
      "mob.silverfish.hit",
      "mob.silverfish.kill",
      "mob.silverfish.step",
      "Lifetime",
      "PlayerSpawned",
      "naturalRegeneration",
      "foodLevel",
      "foodTickTimer",
      "foodSaturationLevel",
      "foodExhaustionLevel",
      "cannot obtain source audio line",
      "Device test failed: ",
      "Scoreboard",
      "Background Width Padding",
      "Remove Scoreboard numbers",
      "Show Scorebaord Title",
      "Custom Text Color",
      "Scoreboard Numbers Color",
      "Top Background Color",
      "Move and customize the Minecraft scoreboard to your liking.",
      "Sidebar",
      "Cheat",
      "Breaker",
      "Steve",
      "Alex",
      "Only supported on java 7+.",
      "multicastAddress",
      "networkInterface",
      "sourceToBlock",
      ">, ",
      "endermite",
      "shutting down",
      "org.apache.log4j.chainsaw.ExitAction",
      "Invalid channel code: ",
      "channels",
      "Fuse",
      "ExplosionRadius",
      "ignited",
      "creeper.primed",
      "mob.creeper.say",
      "mob.creeper.death",
      "fire.ignite",
      "client/sound/",
      ".ogg",
      "ogg",
      "Error linking with the LibraryJavaSound plug-in",
      "Sound Library Loader",
      "Error starting SoundSystem. Turning off sounds & music",
      "Removed channel {} because it's not playing anymore",
      "Skipped playing soundEvent: {}, master volume was zero",
      "Unable to play unknown soundEvent: {}",
      "Unable to play empty soundEvent: {}",
      "Skipped playing sound {}, volume was zero.",
      "Playing sound {} for event {} as channel {}",
      "Pausing channel {}",
      "Resuming channel {}",
      "%s:%s:%s",
      "mcsounddomain",
      "TODO: Sanely handle url exception! :D",
      "SOUNDS",
      "OW KNOWS!",
      "Error executing task",
      "servers.dat",
      "servers",
      "Couldn't load server list",
      "Couldn't save server list",
      "offset: ",
      " (expected: 0 or greater)",
      "chunkSize: ",
      " (expected: a positive integer)",
      "WebSocketWriteThread-",
      "Null pointer",
      "Value out of sequence.",
      "Misplaced array.",
      "Misplaced endArray.",
      "Misplaced endObject.",
      "Null key.",
      "Misplaced key.",
      "Misplaced object.",
      "Nesting error.",
      "Nesting too deep.",
      "RED_SANDSTONE",
      "min=",
      ", max=",
      ", leftAlign=",
      "random.splash",
      "xTile",
      "yTile",
      "zTile",
      "inTile",
      "shake",
      "inGround",
      "arrowInfinite",
      "w",
      "msg",
      "tell",
      "commands.message.usage",
      "commands.message.sameTarget",
      "commands.message.display.incoming",
      "commands.message.display.outgoing",
      "POST",
      "Content-Language",
      "en-US",
      "Could not post to ",
      "GET",
      "Downloader %d",
      "FileWatchdog",
      "Was not allowed to read check file existance, file:[",
      "] does not exist.",
      "0.0.0.0",
      "Cancelled",
      "[Crash Handler] Sending Post",
      "CheatBreaker client Version: ",
      "container.brewing",
      "BrewTime",
      "minecraft:brewing_stand",
      "rw",
      "An exception was thrown by ",
      "deadline: ",
      " ns later",
      " ns ago",
      "now",
      ", cancelled",
      ", task: ",
      "state",
      "Scaled: (%d, %d). Absolute: (%d, %d)",
      "STDERR",
      "STDOUT",
      "No instances",
      "Motive",
      "of.options.animationsTitle",
      "of.options.animation.allOn",
      "of.options.animation.allOff",
      "generator.",
      ".info",
      "flat",
      "largeBiomes",
      "amplified",
      "customized",
      "debug_all_block_states",
      "default_1_1",
      "tp",
      "commands.tp.usage",
      "commands.tp.success.coordinates",
      "commands.tp.notSameDimension",
      "commands.tp.success",
      "Message",
      "debug",
      " fps ",
      " sf",
      " fr",
      " af",
      " aa",
      " reg",
      " sh",
      ", A: ",
      "Minecraft 1.8.9 (",
      "P: ",
      ". T: ",
      "Chunk-relative: %d %d %d",
      "Invalid",
      "Towards negative Z",
      "Towards positive Z",
      "Towards negative X",
      "Towards positive X",
      "XYZ: %.3f / %.5f / %.3f",
      "Block: %d %d %d",
      "Chunk: %d %d %d in %d %d %d",
      "Facing: %s (%s) (%.1f / %.1f)",
      "Biome: ",
      "Light: ",
      " sky, ",
      " block)",
      "Local Difficulty: %.2f (Day %d)",
      "Shader: ",
      "Looking at: %d %d %d",
      "Java: %s %dbit",
      "Mem: % 2d%% %03d/%03dMB",
      "Allocated: % 2d%% %03dMB",
      "CPU: %s",
      "Display: %dx%d (%s)",
      "Native: ",
      "MB",
      "GC: ",
      "MB/s",
      "ODD",
      "EVEN",
      "MARK",
      "SPACE",
      "recycled already",
      "Received unrequested status",
      "Old",
      "... and ",
      " more ...",
      "???",
      "Invalid server icon (unknown format)",
      "Finished",
      "Can't ping ",
      "textures/gui/container/inventory.png",
      "mob",
      "arrow",
      "onFire",
      "fireball",
      "thrown",
      "indirectMagic",
      "explosion.player",
      "explosion",
      ".player",
      "inFire",
      "lightningBolt",
      "inWall",
      "drown",
      "starve",
      "fall",
      "outOfWorld",
      "magic",
      "fallingBlock",
      "Zombie reinforcement caller charge",
      "Zombie reinforcement callee charge",
      "mob.zombie.say",
      "mob.zombie.hurt",
      "mob.zombie.death",
      "mob.zombie.step",
      "IsBaby",
      "IsVillager",
      "ConversionTime",
      "CanBreakDoors",
      "Random zombie-spawn bonus",
      "Leader zombie bonus",
      "mob.zombie.remedy",
      "zombie.spawnReinforcements",
      "Spawn Reinforcements Chance",
      "B9766B59-9566-4402-BC1F-2EE2A276D836",
      "Baby speed boost",
      "int",
      "float",
      "matrix",
      "2x2",
      "3x3",
      "4x4",
      "Uniform.set called with a too-small value array (expected ",
      ", got ",
      "). Ignoring.",
      "Uniform.upload called, but type value (",
      ") is not a valid type. Ignoring.",
      "Uniform.upload called, but count value (",
      ") is  not in the range of 1 to 4. Ignoring.",
      ") is not in the range of 1 to 4. Ignoring.",
      "commands.title.usage",
      "subtitle",
      "commands.title.usage.title",
      "times",
      "commands.title.usage.times",
      "commands.title.success",
      "commands.tellraw.jsonException",
      "/tip all",
      "rolling over count=",
      "maxBackupIndex=",
      "Renaming file ",
      " to ",
      "setFile(",
      ", true) call failed.",
      ", false) call failed.",
      "The objective name '",
      "' is too long!",
      "An objective with the name '",
      "' already exists!",
      "The player name '",
      "The team name '",
      "Player is either on another team or not on any team. Cannot remove from team '",
      "sidebar",
      "belowName",
      "sidebar.team.",
      "https://api.twitch.tv/kraken?oauth_token=",
      "token",
      "valid",
      "user_name",
      "Authenticated with twitch; username is {}",
      "Twitch shutdown hook",
      "Given twitch access token is invalid",
      "Could not authenticate with twitch",
      "(\\p{XDigit}{8})(\\p{XDigit}{4})(\\p{XDigit}{4})(\\p{XDigit}{4})(\\p{XDigit}+)",
      "$1-$2-$3-$4-$5",
      "objects",
      "indexes/",
      ".json",
      "hash",
      "Unable to parse resource index file: ",
      "Can't find the resource index file: ",
      "Realms-connect-task",
      "cmdType",
      "addressType",
      "host",
      " is not a valid IPv4 address",
      " IDN: ",
      " exceeds 255 char limit",
      " is not a valid IPv6 address",
      " is not in bounds 0 < x < 65536",
      "parameter must not be null",
      "connection closed unexpectedly by peer",
      "Connection is closed",
      "setworldspawn",
      "commands.setworldspawn.usage",
      "commands.setworldspawn.success",
      "textures/entity/guardian.png",
      "textures/entity/guardian_elder.png",
      "textures/entity/guardian_beam.png",
      "5CD17E52-A79A-43D3-A529-90FDE04B181E",
      "Drinking speed penalty",
      "textures/entity/slime/slime.png",
      "jlc",
      "Convertion failure: ",
      "No Body to decode",
      "Needs a boundary value",
      " was destroyed already",
      "discardThreshold must be >= 0",
      "Bad end of line",
      "Bad string: '",
      "Should not be called with the current getStatus",
      "Access out of bounds",
      "No Multipart delimiter found",
      "Mixed Multipart found in a previous Mixed Multipart",
      "Unknown Params: ",
      "Filename not found",
      "TransferEncoding Unknown: ",
      "Content-Type is absent but required",
      "forwards",
      "frontTopLeft",
      "DEVELOPMENT",
      "BETA",
      "beta",
      "Could not open ObjectInputStream to ",
      "Could not close connection.",
      "Caught java.io.EOFException closing conneciton.",
      "Caught java.net.SocketException closing conneciton.",
      "Caught java.io.InterruptedIOException: ",
      "Closing connection.",
      "Caught java.io.IOException: ",
      "Unexpected exception. Closing conneciton.",
      "org.apache.log4j.net.SocketNode",
      "Height",
      "Depth",
      "HPos",
      "client/icons/checkmark-64.png",
      "client/icons/pencil-64.png",
      " (Active)",
      "config",
      "cheatbreaker-client-",
      "\\.",
      ".cfg",
      "Zans Minimap",
      "Reset Position",
      "arrow-64.png",
      "Reset Settings",
      "String",
      "Background)",
      "Hot key",
      "Apply to all text",
      "Add Another",
      "CheatBreaker Settings",
      " Settings",
      "Original creator",
      "s: ",
      "Also known as: ",
      " is currently restricted:\n",
      " DOES NOT HAVE ANY OPTIONS.",
      "hot key",
      "min: ",
      "input source [",
      "Buggy ",
      " implementation; ",
      ".confirmShutdown() must be called ",
      "before run() implementation terminates.",
      "An event executor terminated with non-empty task queue (",
      "Unexpected exception from an event executor: ",
      "intact",
      "slightlyDamaged",
      "veryDamaged",
      "next must be called before each remove.",
      "lanServer.title",
      "selectServer.hiddenAddress",
      "matchItems",
      "source",
      "damage",
      "damageMask",
      "stackSize",
      "enchantmentIDs",
      "enchantmentLevels",
      "hand",
      "blend",
      "layer",
      "enchantment",
      "Unknown method: ",
      "Item not found: ",
      "texture.bow_standby",
      "texture.",
      "model.bow_standby",
      "model.",
      "block/",
      "item/",
      "Invalid integer: ",
      "Invalid float: ",
      "Invalid range list: ",
      "Invalid range: ",
      "nbt.",
      "any",
      "main",
      "Invalid hand: ",
      "No base path found: ",
      "No type defined: ",
      "No items defined: ",
      "No texture or model specified: ",
      "No enchantmentIDs specified: ",
      "No name found: ",
      "textures/items/",
      "bow",
      "fishing_rod",
      "shield",
      "texture.potion_overlay",
      "items/potion_overlay",
      "texture.potion_bottle_splash",
      "items/potion_bottle_splash",
      "texture.potion_bottle_drinkable",
      "items/potion_bottle_drinkable",
      "leather",
      "helmet",
      "chestplate",
      "leggings",
      "boots",
      "_overlay",
      "{\"parent\": \"builtin/generated\",\"textures\": {",
      "\"layer",
      "\": \"",
      "}}",
      ", items: [",
      "], textture: ",
      "inventory",
      "Custom Items: Model not found ",
      "vanillaLoader is null",
      "iModel is null",
      "stateModels is null",
      "registryTextures is null",
      "modelTextures is null",
      "Error registering model with ModelLoader: ",
      "models/",
      "durability",
      "description",
      "favicon",
      "const bool ",
      "; // Shader option ",
      "^\\s*const\\s*bool\\s*([A-Za-z0-9_]+)\\s*=\\s*(true|false)\\s*;\\s*(//.*)?$",
      "Don't know how to convert ",
      " back into data...",
      "tile.",
      "Block{",
      "wood",
      "oreGold",
      "oreIron",
      "oreCoal",
      "oreLapis",
      "blockLapis",
      "sandStone",
      "musicBlock",
      "goldenRail",
      "detectorRail",
      "pistonStickyBase",
      "pistonBase",
      "cloth",
      "flower1",
      "flower2",
      "mushroom",
      "blockGold",
      "blockIron",
      "stoneSlab",
      "stoneMoss",
      "stairsWood",
      "redstoneDust",
      "oreDiamond",
      "blockDiamond",
      "workbench",
      "crops",
      "sign",
      "doorOak",
      "stairsStone",
      "pressurePlateStone",
      "doorIron",
      "pressurePlateWood",
      "oreRedstone",
      "notGate",
      "button",
      "hellrock",
      "hellsand",
      "lightgem",
      "litpumpkin",
      "diode",
      "stainedGlass",
      "monsterStoneEgg",
      "stonebricksmooth",
      "fenceIron",
      "thinGlass",
      "melon",
      "pumpkinStem",
      "fenceGate",
      "stairsBrick",
      "stairsStoneBrickSmooth",
      "mycel",
      "netherBrick",
      "netherFence",
      "stairsNetherBrick",
      "netherStalk",
      "enchantmentTable",
      "brewingStand",
      "endPortalFrame",
      "whiteStone",
      "dragonEgg",
      "redstoneLight",
      "woodSlab",
      "stairsSandStone",
      "oreEmerald",
      "enderChest",
      "tripWireSource",
      "tripWire",
      "blockEmerald",
      "stairsWoodSpruce",
      "stairsWoodBirch",
      "stairsWoodJungle",
      "commandBlock",
      "cobbleWall",
      "flowerPot",
      "chestTrap",
      "weightedPlate_light",
      "weightedPlate_heavy",
      "comparator",
      "blockRedstone",
      "netherquartz",
      "quartzBlock",
      "stairsQuartz",
      "activatorRail",
      "clayHardenedStained",
      "thinStainedGlass",
      "stairsWoodAcacia",
      "stairsWoodDarkOak",
      "ironTrapdoor",
      "seaLantern",
      "hayBlock",
      "woolCarpet",
      "clayHardened",
      "blockCoal",
      "icePacked",
      "banner",
      "redSandStone",
      "stairsRedSandStone",
      "stoneSlab2",
      "spruceFenceGate",
      "birchFenceGate",
      "jungleFenceGate",
      "darkOakFenceGate",
      "acaciaFenceGate",
      "spruceFence",
      "birchFence",
      "jungleFence",
      "darkOakFence",
      "acaciaFence",
      "doorSpruce",
      "doorBirch",
      "doorJungle",
      "doorAcacia",
      "doorDarkOak",
      "%%",
      "Unsupported format: '",
      "TranslatableComponent{key='",
      ", args=",
      ", siblings=",
      ", style=",
      "%(?:(\\d+)\\$)?([A-Za-z%]|$)",
      "cannot have more than 8 options",
      "Unexpected exception while sending chunks.",
      "enchantment.protect.",
      "projectile",
      "Keep-Alive",
      "Proxy-Connection",
      "https",
      "Must be volatile",
      "Previous Page",
      "Next Page",
      "pardon-ip",
      "commands.unbanip.usage",
      "commands.unbanip.success",
      "commands.unbanip.invalid",
      "dropped",
      "held",
      "fishing_rod_cast",
      "bow_pulling_2",
      "bow_pulling_1",
      "bow_pulling_0",
      "Rendering item",
      "Item being rendered",
      "Item Type",
      "Item Aux",
      "Item NBT",
      "Item Foil",
      "anvil_intact",
      "anvil_slightly_damaged",
      "anvil_very_damaged",
      "black_carpet",
      "blue_carpet",
      "brown_carpet",
      "cyan_carpet",
      "gray_carpet",
      "green_carpet",
      "light_blue_carpet",
      "lime_carpet",
      "magenta_carpet",
      "orange_carpet",
      "pink_carpet",
      "purple_carpet",
      "red_carpet",
      "silver_carpet",
      "white_carpet",
      "yellow_carpet",
      "mossy_cobblestone_wall",
      "double_fern",
      "double_grass",
      "paeonia",
      "double_rose",
      "sunflower",
      "syringa",
      "birch_leaves",
      "jungle_leaves",
      "oak_leaves",
      "spruce_leaves",
      "acacia_leaves",
      "dark_oak_leaves",
      "birch_log",
      "jungle_log",
      "oak_log",
      "spruce_log",
      "acacia_log",
      "dark_oak_log",
      "chiseled_brick_monster_egg",
      "cobblestone_monster_egg",
      "cracked_brick_monster_egg",
      "mossy_brick_monster_egg",
      "stone_monster_egg",
      "stone_brick_monster_egg",
      "acacia_planks",
      "birch_planks",
      "dark_oak_planks",
      "jungle_planks",
      "oak_planks",
      "spruce_planks",
      "chiseled_quartz_block",
      "quartz_column",
      "red_sand",
      "chiseled_sandstone",
      "smooth_sandstone",
      "chiseled_red_sandstone",
      "smooth_red_sandstone",
      "acacia_sapling",
      "birch_sapling",
      "dark_oak_sapling",
      "jungle_sapling",
      "oak_sapling",
      "spruce_sapling",
      "sponge_wet",
      "black_stained_glass",
      "blue_stained_glass",
      "brown_stained_glass",
      "cyan_stained_glass",
      "gray_stained_glass",
      "green_stained_glass",
      "light_blue_stained_glass",
      "lime_stained_glass",
      "magenta_stained_glass",
      "orange_stained_glass",
      "pink_stained_glass",
      "purple_stained_glass",
      "red_stained_glass",
      "silver_stained_glass",
      "white_stained_glass",
      "yellow_stained_glass",
      "black_stained_glass_pane",
      "blue_stained_glass_pane",
      "brown_stained_glass_pane",
      "cyan_stained_glass_pane",
      "gray_stained_glass_pane",
      "green_stained_glass_pane",
      "light_blue_stained_glass_pane",
      "lime_stained_glass_pane",
      "magenta_stained_glass_pane",
      "orange_stained_glass_pane",
      "pink_stained_glass_pane",
      "purple_stained_glass_pane",
      "red_stained_glass_pane",
      "silver_stained_glass_pane",
      "white_stained_glass_pane",
      "yellow_stained_glass_pane",
      "black_stained_hardened_clay"
   };
}
