package recovered.strings;

public class StringTable10 {
   public static String[] recoveredField3958 = new String[]{
      "blue_stained_hardened_clay",
      "brown_stained_hardened_clay",
      "cyan_stained_hardened_clay",
      "gray_stained_hardened_clay",
      "green_stained_hardened_clay",
      "light_blue_stained_hardened_clay",
      "lime_stained_hardened_clay",
      "magenta_stained_hardened_clay",
      "orange_stained_hardened_clay",
      "pink_stained_hardened_clay",
      "purple_stained_hardened_clay",
      "red_stained_hardened_clay",
      "silver_stained_hardened_clay",
      "white_stained_hardened_clay",
      "yellow_stained_hardened_clay",
      "andesite_smooth",
      "diorite_smooth",
      "granite_smooth",
      "brick_slab",
      "cobblestone_slab",
      "old_wood_slab",
      "nether_brick_slab",
      "quartz_slab",
      "sandstone_slab",
      "stone_brick_slab",
      "red_sandstone_slab",
      "fern",
      "tall_grass",
      "acacia_slab",
      "birch_slab",
      "dark_oak_slab",
      "jungle_slab",
      "oak_slab",
      "spruce_slab",
      "black_wool",
      "blue_wool",
      "brown_wool",
      "cyan_wool",
      "gray_wool",
      "green_wool",
      "light_blue_wool",
      "lime_wool",
      "magenta_wool",
      "orange_wool",
      "pink_wool",
      "purple_wool",
      "red_wool",
      "silver_wool",
      "white_wool",
      "yellow_wool",
      "oak_fence",
      "oak_fence_gate",
      "iron_shovel",
      "iron_pickaxe",
      "iron_axe",
      "flint_and_steel",
      "apple",
      "coal",
      "charcoal",
      "diamond",
      "iron_ingot",
      "gold_ingot",
      "iron_sword",
      "wooden_sword",
      "wooden_shovel",
      "wooden_pickaxe",
      "wooden_axe",
      "stone_sword",
      "stone_shovel",
      "stone_pickaxe",
      "stone_axe",
      "diamond_sword",
      "diamond_shovel",
      "diamond_pickaxe",
      "diamond_axe",
      "stick",
      "bowl",
      "mushroom_stew",
      "golden_sword",
      "golden_shovel",
      "golden_pickaxe",
      "golden_axe",
      "string",
      "feather",
      "gunpowder",
      "wooden_hoe",
      "stone_hoe",
      "iron_hoe",
      "diamond_hoe",
      "golden_hoe",
      "wheat_seeds",
      "bread",
      "leather_helmet",
      "leather_chestplate",
      "leather_leggings",
      "leather_boots",
      "chainmail_helmet",
      "chainmail_chestplate",
      "chainmail_leggings",
      "chainmail_boots",
      "iron_helmet",
      "iron_chestplate",
      "iron_leggings",
      "iron_boots",
      "diamond_helmet",
      "diamond_chestplate",
      "diamond_leggings",
      "diamond_boots",
      "golden_helmet",
      "golden_chestplate",
      "golden_leggings",
      "golden_boots",
      "flint",
      "porkchop",
      "cooked_porkchop",
      "painting",
      "golden_apple",
      "oak_door",
      "bucket",
      "water_bucket",
      "lava_bucket",
      "minecart",
      "saddle",
      "redstone",
      "snowball",
      "milk_bucket",
      "clay_ball",
      "paper",
      "slime_ball",
      "chest_minecart",
      "furnace_minecart",
      "egg",
      "glowstone_dust",
      "cooked_cod",
      "cooked_salmon",
      "dye_black",
      "dye_red",
      "dye_green",
      "dye_brown",
      "dye_blue",
      "dye_purple",
      "dye_cyan",
      "dye_silver",
      "dye_gray",
      "dye_pink",
      "dye_lime",
      "dye_yellow",
      "dye_light_blue",
      "dye_magenta",
      "dye_orange",
      "dye_white",
      "bone",
      "sugar",
      "repeater",
      "shears",
      "pumpkin_seeds",
      "melon_seeds",
      "beef",
      "cooked_beef",
      "chicken",
      "cooked_chicken",
      "rabbit",
      "cooked_rabbit",
      "mutton",
      "cooked_mutton",
      "rabbit_foot",
      "rabbit_hide",
      "rabbit_stew",
      "rotten_flesh",
      "ender_pearl",
      "blaze_rod",
      "ghast_tear",
      "gold_nugget",
      "glass_bottle",
      "spider_eye",
      "fermented_spider_eye",
      "blaze_powder",
      "magma_cream",
      "ender_eye",
      "speckled_melon",
      "experience_bottle",
      "fire_charge",
      "writable_book",
      "emerald",
      "item_frame",
      "carrot",
      "potato",
      "baked_potato",
      "poisonous_potato",
      "map",
      "golden_carrot",
      "skull_skeleton",
      "skull_wither",
      "skull_zombie",
      "skull_char",
      "skull_creeper",
      "carrot_on_a_stick",
      "nether_star",
      "pumpkin_pie",
      "firework_charge",
      "netherbrick",
      "quartz",
      "tnt_minecart",
      "hopper_minecart",
      "armor_stand",
      "iron_horse_armor",
      "golden_horse_armor",
      "diamond_horse_armor",
      "lead",
      "name_tag",
      "record_13",
      "record_cat",
      "record_blocks",
      "record_chirp",
      "record_far",
      "record_mall",
      "record_mellohi",
      "record_stal",
      "record_strad",
      "record_ward",
      "record_11",
      "record_wait",
      "prismarine_shard",
      "prismarine_crystals",
      "fireworks",
      "command_block_minecart",
      "written_book",
      "textures/misc/enchanted_item_glint.png",
      "Not tesselating!",
      "Already tesselating!",
      "Expand tessellator buffer, old: ",
      ", new: ",
      "FLOAT_ARRAY",
      "textures/entity/chest/ender.png",
      "spreadplayers",
      "commands.spreadplayers.usage",
      "commands.spreadplayers.spreading.",
      "teams",
      "commands.spreadplayers.success.",
      "commands.spreadplayers.info.",
      "%.2f",
      "commands.spreadplayers.failure.",
      "gamemode",
      "commands.gamemode.usage",
      "gameMode.changed",
      "gameMode.",
      "commands.gamemode.success.other",
      "commands.gamemode.success.self",
      "sp",
      "adventure",
      "Shrug",
      "%m%n",
      "maxCapacity: ",
      "initialCapacity(%d) > maxCapacity(%d)",
      "initialBuffer",
      "initialBuffer is not a direct buffer.",
      "initialBuffer is a read-only buffer.",
      "newCapacity: ",
      "dstIndex: %d, length: %d (expected: range(0, %d))",
      "Too many bytes to read - Need ",
      "LANGUAGE",
      "client/icons/exit-64.png",
      "EXIT",
      "clientToken",
      "(version: ",
      ", keepAlive: ",
      "prototype",
      "getParserForType",
      "entitydata",
      "commands.entitydata.usage",
      "commands.entitydata.noPlayers",
      "commands.entitydata.tagError",
      "commands.entitydata.failed",
      "commands.entitydata.success",
      "CHANGE",
      "REMOVE",
      "Colormap",
      "format",
      "yVariance",
      "yOffset",
      "grid",
      "fixed",
      "Unknown format: ",
      "Source not defined: ",
      "Match blocks not defined: ",
      "^block([0-9]+).*$",
      "Non-standard palette size: ",
      "Invalid palette size: ",
      "CustomColors: ",
      "textures/blocks/",
      ", blocks: ",
      ", source: ",
      "Play started from frame ",
      "Play completed at frame ",
      "Created Branch Manager",
      "random.bowhit",
      "life",
      "inData",
      "pickup",
      "invulnerable",
      "flying",
      "mayfly",
      "instabuild",
      "mayBuild",
      "flySpeed",
      "walkSpeed",
      "abilities",
      "/cb_increase_time",
      "Static",
      "Increased time by ",
      "This mod command only works with the \"Static\" time type.",
      "Could not lookup user whitelist entry for ",
      "Failed to release a message: {}",
      "Failed to release a message: {} (decrement: {})",
      "container.crafting",
      "connection attempt already made",
      "demo.day.",
      "demo.day.warning",
      "demo.reminder",
      "Dialog",
      "Failures",
      "The list of failed tests",
      "You have tried to set a null level to root.",
      "Unknown? (Got ",
      "%4s",
      "%1$d / 0x%1$X / 0b%2$s",
      "commands.generic.player.notFound",
      "Exception generating new chunk",
      "Chunk to be generated",
      "%d,%d",
      "Position hash",
      "Generator",
      "Couldn't load chunk",
      "Couldn't save entities",
      "Couldn't save chunk",
      "Couldn't save chunk; already in use by another instance of Minecraft?",
      "ServerChunkCache: ",
      " Drop: ",
      "line.separator",
      "OCEAN",
      "COLD",
      "WARM",
      "setidletimeout",
      "commands.setidletimeout.usage",
      "commands.setidletimeout.success",
      "void future",
      "Created Network Manager",
      "REGISTER",
      "Received: ",
      "playerId=",
      ", Tags=",
      "Voice is: ",
      "NEUTRAL",
      "FORCED_OFF",
      "Voice Channel Received: ",
      "Channel has ",
      " members",
      "Added member [",
      "Added listener [",
      "Channel Update: ",
      " joined ",
      " channel. Press 'Unbound'!",
      "Joined ",
      " channel. Press 'Unbound' to talk!",
      " left ",
      "Deleted channel: ",
      "World Update: ",
      "Retrieved ",
      "\u001b[31m[CheatBreaker]\u001b[0m ",
      "Find text: ",
      "Search Record Messages",
      "=;",
      "secure",
      "Missing '=' in cookie parameter.",
      "expires",
      ";expires=",
      ";domain=",
      ";path=",
      ";secure",
      "§",
      "gui.yes",
      "gui.no",
      "seed",
      "commands.seed.usage",
      "commands.seed.success",
      "embedded",
      "RELATIVE",
      "maxPendingWrites: ",
      ".isEndOfInput() failed",
      "Failed to close a chunked input.",
      "Class Name",
      "class name",
      "Integrated Server (map_client.txt)",
      " ENTRY",
      " ENTRY ",
      " RETURN",
      " RETURN ",
      " THROW",
      "org.apache.log4j.LogXF",
      "address",
      "java.nio.Buffer.address: {}",
      "theUnsafe",
      "sun.misc.Unsafe.theUnsafe: {}",
      "copyMemory",
      "sun.misc.Unsafe.copyMemory: available",
      "sun.misc.Unsafe.copyMemory: unavailable",
      "java.nio.Bits",
      "unaligned",
      "^(i[3-6]86|x86(_64)?|x64|amd64)$",
      "java.nio.Bits.unaligned: {}",
      "SIMPLE",
      "ADVANCED",
      "channel not registered to an event loop",
      "[id: 0x%08x, %s %s %s]",
      "=>",
      ":>",
      "[id: 0x%08x, %s]",
      "[id: 0x%08x]",
      "squid",
      "tentacle",
      "tentacle1",
      "tentacle2",
      "tentacle3",
      "tentacle4",
      "tentacle5",
      "tentacle6",
      "tentacle7",
      "tentacle8",
      "FPS",
      "[144 FPS]",
      "Displays your frames per second.",
      "Show Minimum FPS",
      "MyWeighedRandomItem{weight=",
      ", model=",
      "Pack Tweaks",
      "Change how specific textures appear.",
      "Glass Options",
      "Clear Glass",
      "Removes the glass texture.\n\n§bOFF:§r No glass textures are removed.\n§bREGULAR:§r Only normal glass texture is removed.\n§bALL:§r Normal and stained glass textures are removed.",
      "String Options",
      "Colored String",
      "Show a solid color line instead of the texture pack's string texture.",
      "Colored String Color",
      "Fire Options",
      "First Person Fire",
      "Fire Opacity",
      "Fire Height",
      "Fire on Entities",
      "Vignette Options",
      "Vignette Type",
      "Amplified",
      "Vignette Opacity",
      "Vignette Minimum Opacity",
      "Vignette Maximum Opacity",
      "Vignette Opacity Multiplier",
      "Low Health Options",
      "Low Health Overlay",
      "Low Health Start",
      " hearts",
      "Low Health Opacity",
      "Pumpkin Overlay Options",
      "Show Pumpkin Overlay",
      "Pumpkin Overlay Opacity",
      "Inventory Options",
      "Transparent Inventory",
      "Show Inventory Tooltips",
      "client/icons/mods/packtweaks.png",
      "1.7.10",
      "LanServerDetector #",
      "Couldn't ping server",
      "ZB9hEJy5l+u8QARAlX9T0w",
      "textures/entity/endercrystal/endercrystal.png",
      "Customize World Settings",
      "Page 1 of 3",
      "Basic Settings",
      "options.customizeTitle",
      "createWorld.customize.custom.prev",
      "createWorld.customize.custom.next",
      "createWorld.customize.custom.defaults",
      "createWorld.customize.custom.randomize",
      "createWorld.customize.custom.presets",
      "createWorld.customize.custom.seaLevel",
      "createWorld.customize.custom.useCaves",
      "createWorld.customize.custom.useStrongholds",
      "createWorld.customize.custom.useVillages",
      "createWorld.customize.custom.useMineShafts",
      "createWorld.customize.custom.useTemples",
      "createWorld.customize.custom.useMonuments",
      "createWorld.customize.custom.useRavines",
      "createWorld.customize.custom.useDungeons",
      "createWorld.customize.custom.dungeonChance",
      "createWorld.customize.custom.useWaterLakes",
      "createWorld.customize.custom.waterLakeChance",
      "createWorld.customize.custom.useLavaLakes",
      "createWorld.customize.custom.lavaLakeChance",
      "createWorld.customize.custom.useLavaOceans",
      "createWorld.customize.custom.fixedBiome",
      "createWorld.customize.custom.biomeSize",
      "createWorld.customize.custom.riverSize",
      "tile.dirt.name",
      "createWorld.customize.custom.size",
      "createWorld.customize.custom.count",
      "createWorld.customize.custom.minHeight",
      "createWorld.customize.custom.maxHeight",
      "tile.gravel.name",
      "tile.stone.granite.name",
      "tile.stone.diorite.name",
      "tile.stone.andesite.name",
      "tile.oreCoal.name",
      "tile.oreIron.name",
      "tile.oreGold.name",
      "tile.oreRedstone.name",
      "tile.oreDiamond.name",
      "tile.oreLapis.name",
      "createWorld.customize.custom.center",
      "createWorld.customize.custom.spread",
      "createWorld.customize.custom.mainNoiseScaleX",
      "createWorld.customize.custom.mainNoiseScaleY",
      "createWorld.customize.custom.mainNoiseScaleZ",
      "createWorld.customize.custom.depthNoiseScaleX",
      "createWorld.customize.custom.depthNoiseScaleZ",
      "createWorld.customize.custom.depthNoiseScaleExponent",
      "createWorld.customize.custom.baseSize",
      "createWorld.customize.custom.coordinateScale",
      "createWorld.customize.custom.heightScale",
      "createWorld.customize.custom.stretchY",
      "createWorld.customize.custom.upperLimitScale",
      "createWorld.customize.custom.lowerLimitScale",
      "createWorld.customize.custom.biomeDepthWeight",
      "createWorld.customize.custom.biomeDepthOffset",
      "createWorld.customize.custom.biomeScaleWeight",
      "createWorld.customize.custom.biomeScaleOffset",
      "%5.3f",
      "%2.3f",
      "createWorld.customize.custom.page",
      "%d",
      "gui.all",
      "createWorld.customize.custom.confirmTitle",
      "createWorld.customize.custom.confirm1",
      "createWorld.customize.custom.confirm2",
      " frames",
      "io.netty.eventLoopThreads",
      "-Dio.netty.eventLoopThreads: {}",
      "net.minecraftforge.client.model.Attributes",
      "DEFAULT_BAKED_FORMAT",
      "Converted ",
      " frames in ",
      " ms (",
      " ms per frame.)",
      "File is a ",
      "Prased frame ",
      "Read frame ",
      "Decoded frame ",
      "Output: ",
      "Converting.",
      "No resource is associated with key \"",
      "org.apache.log4j.Category",
      "Unable to start LAN server detection: ",
      "selectServer.edit",
      "selectServer.delete",
      "selectServer.add",
      "selectServer.refresh",
      "selectServer.deleteQuestion",
      "' ",
      "selectServer.deleteWarning",
      "selectServer.deleteButton",
      "selectServer.defaultName",
      "multiplayer.title",
      "([a-zA-Z0-9]+)",
      "fire.fire",
      "flip",
      "alt",
      "axis",
      "period: 0 (expected: != 0)",
      " id: ",
      ", deadline: ",
      ", period: ",
      "daylightDetector",
      "direction",
      "Test",
      "textures/entity/ghast/ghast.png",
      "textures/entity/ghast/ghast_shooting.png",
      "HoverEvent{action=",
      "client/icons/star-21.png",
      "client/icons/star-filled-21.png",
      "skeleton",
      "javax.vecmath.ExceptionStrings",
      "VecMathI18N: Error looking up: ",
      "HitResult{type=",
      ", blockpos=",
      ", f=",
      ", pos=",
      ", entity=",
      "timeout",
      "splitter",
      "decoder",
      "prepender",
      "encoder",
      "CB-Client",
      "Lunar-Client",
      "lunarclient:pm",
      "CB-Binary",
      "[CB] ",
      "client/font/Play-Regular.ttf",
      "client/font/Play-Bold.ttf",
      "client/font/Roboto-Regular.ttf",
      "client/font/Roboto-Bold.ttf",
      "client/font/Ubuntu-M.ttf",
      "Starting CheatBreaker setup",
      "CheatBreaker Setup",
      "Settings",
      "EventBus",
      "Network Manager",
      "Emotes",
      "Radio",
      "Friends",
      "Titles",
      "https://cheatbreaker2.com/changelog",
      "Failed to load changelog.",
      "World Border",
      "Network Events",
      "Registered network events",
      "Fonts",
      "Configurations",
      "Properties",
      "Session",
      "Player Assets",
      "Finishing",
      "Finished startup in ",
      "ms!",
      "Minecraft 1.8.9",
      "cb",
      "In-Menus",
      "Away",
      "Busy",
      "Offline",
      "Online",
      "Attempting to connect to player assets server",
      "playerId",
      "HWID",
      "gitCommit",
      "branch",
      "buildType",
      "ws://dev.moose1301.cf/connect",
      "client/properties/app.properties",
      "git.commit.id.abbrev",
      "git.commit.id",
      "git.branch",
      "git.build.version",
      "Loaded client properties",
      "An error occurred when loading client properties",
      "session.minecraft.net",
      "Login",
      "authserver.mojang.com",
      "Account",
      "account.mojang.com",
      "API",
      "api.mojang.com",
      "Loaded mojang session status entries",
      "Loaded all fonts",
      "client/heads/",
      "https://minotar.net/helm/",
      "/32.png",
      "client/defaults/steve.png",
      "Connected to Discord IPC",
      "Failed to connect to Discord IPC",
      "Color Saturation",
      "Allows you to adjust the hue, saturation, brightness, and contrast of your screen.",
      "CANCEL",
      "ACCEPT",
      "ear1",
      "ear2",
      "Unterminated string.",
      "CONNECT",
      "BIND",
      "UDP",
      "Level",
      "level trace",
      "level debug",
      "level info",
      "level warn",
      "level error",
      "level fatal",
      "level ",
      "ban",
      "commands.ban.usage",
      "commands.ban.failed",
      "You are banned from this server.",
      "commands.ban.success",
      "Multiple vertex elements of the same type other than UVs are not supported. Forcing type to UV.",
      "minecraft:blocks/planks_oak",
      "minecraft:blocks/obsidian",
      "minecraft:blocks/lava_still",
      "minecraft:blocks/water_still",
      "minecraft:blocks/soul_sand",
      "minecraft:items/barrier",
      "_wall",
      "_double_slab",
      "_slab",
      "_wool",
      "_carpet",
      "_stained_hardened_clay",
      "_stained_glass_pane",
      "_stained_glass",
      "_monster_egg",
      "_log",
      "_planks",
      "_sapling",
      "java.net.SocketOption",
      "java.net.StandardSocketOptions",
      "cannot locate the IP_MULTICAST_TTL field",
      "cannot locate the IP_MULTICAST_IF field",
      "IP_MULTICAST_LOOP",
      "cannot locate the IP_MULTICAST_LOOP field",
      "getOption",
      "cannot locate the getOption() method",
      "setOption",
      "cannot locate the setOption() method",
      "dig.stone",
      "random.anvil_land",
      "properties",
      "Failed to add player. {} already is in chunk {}, {}",
      "Error initializing Twitch sdk: %s",
      "Error initializing Twitch chat: %s",
      "Already in channel: ",
      "Not in channel: ",
      "Error shutting down chat: %s",
      "Error flushing chat events: %s",
      "Error trying to download emoticon data: %s",
      "Error preparing emoticon data: ",
      "Error clearing emoticon data: ",
      "[Chat controller] {}",
      "minecraft:blocks/lava_flow",
      "minecraft:blocks/water_flow",
      "'%s' in ResourcePack '%s'",
      "lead_knot",
      "knot",
      "Field not found: RenderLeashKnot.leashKnotModel",
      "stop",
      "commands.stop.usage",
      "commands.stop.start",
      "lockState",
      "\n\r",
      "org.apache.log4j.LogMF",
      "Failed to introspect object ",
      "Failed to get value of property ",
      "authScheme",
      "snow_golem",
      "body_bottom",
      "left_hand",
      "right_hand",
      "SUCCESS_COUNT",
      "SuccessCount",
      "AFFECTED_BLOCKS",
      "AffectedBlocks",
      "AFFECTED_ENTITIES",
      "AffectedEntities",
      "AFFECTED_ITEMS",
      "AffectedItems",
      "QUERY_RESULT",
      "QueryResult",
      "Duplicate entity class: ",
      ", id1: ",
      ", id2: ",
      "Duplicate entity name: ",
      ", class1: ",
      ", class2: ",
      "CustomPanorama",
      "/panorama_",
      "blur1",
      "blur2",
      "blur3",
      "overlay1.top",
      "overlay1.bottom",
      "overlay2.top",
      "overlay2.bottom",
      ", weight: ",
      ", blur: ",
      ", overlay: ",
      "New: ",
      "Clone: ",
      "NewObj: ",
      "CloneObj: ",
      "NewObjDyn: ",
      "LEFT_TOP",
      "LEFT_MIDDLE",
      "LEFT_BOTTOM",
      "MIDDLE_TOP",
      "MIDDLE_MIDDLE",
      "MIDDLE_BOTTOM_LEFT",
      "MIDDLE_BOTTOM_RIGHT",
      "RIGHT_TOP",
      "RIGHT_MIDDLE",
      "RIGHT_BOTTOM",
      "matchers must at least contain one element",
      "Failed to open a sctp channel.",
      "Failed to close a partially initialized sctp channel.",
      "SimpleSocketServer-",
      "org.apache.log4j.net.SimpleSocketServer",
      " port configFile",
      ".xml",
      "already bound",
      "unsupported address type: ",
      "address already in use by: ",
      "lid",
      "knob",
      "Field not found: TileEntityEnderChestRenderer.modelChest",
      "Unsupported mob type for FollowOwnerGoal",
      "Particles",
      "General Particles",
      "Show Sprinting Particles",
      "Show Block Breaking Particles",
      "Lazily Load Particles",
      "Lazy Particle Amount",
      "Attack Particles",
      "Show When Damaged",
      "Override",
      "Show When Attacking",
      "Sharpness Particles",
      "Never",
      "Always",
      "Sharpness Multiplier",
      "Crit Particles",
      "Crit Multiplier",
      "Effect Particles",
      "Show Splash Particles",
      "Instant Splash Opacity",
      "Normal Splash Opacity",
      "Show Active Effect Particles",
      "Active Effect Opacity",
      "Ambient Effect Opacity",
      "Change how particles appear.",
      "dewgs (Multipliers)",
      "entityBaseTick",
      "rest",
      "Checking entity block collision",
      "Entity being checked for collision",
      "game.neutral.swim",
      "Colliding entity with block",
      "Block being collided with",
      "game.neutral.swim.splash",
      "Pos",
      "Motion",
      "FallDistance",
      "Fire",
      "OnGround",
      "Invulnerable",
      "PortalCooldown",
      "CustomNameVisible",
      "Silent",
      "Saving entity NBT",
      "Entity being saved",
      "UUID",
      "Loading entity NBT",
      "Entity being loaded",
      "%s['%s'/%d, l='%s', x=%.2f, y=%.2f, z=%.2f]",
      "~NULL~",
      "changeDimension",
      "reposition",
      "reloading",
      "Entity Type",
      "Entity ID",
      "Entity Name",
      "Entity's Exact location",
      "%.2f, %.2f, %.2f",
      "Entity's Block location",
      "Entity's Momentum",
      "Entity's Rider",
      "Entity's Vehicle",
      "glBindFramebuffer",
      "Wide lines",
      "shader recompiled",
      "[LWJGL] source: ",
      ", id: ",
      ", severity: ",
      ", message: ",
      "StackTrace",
      "WIN",
      "SHADER",
      "EXT",
      "APP",
      "OTHER",
      "DEPRECATED",
      "UNDEFINED",
      "PORTABILITY",
      "PERFORMANCE",
      "HIGH",
      "LOW",
      "Unknown (0x",
      "gamerule",
      "commands.gamerule.usage",
      "commands.gamerule.norule",
      "commands.generic.boolean.invalid",
      "commands.gamerule.success",
      "reducedDebugInfo",
      "NOT_POSSIBLE_HERE",
      "NOT_POSSIBLE_NOW",
      "TOO_FAR_AWAY",
      "OTHER_PROBLEM",
      "NOT_SAFE",
      "[{}]@.({}:{}): {}",
      "SOCKS_INIT_REQUEST_DECODER",
      "SIN",
      "COS",
      "ASIN",
      "ACOS",
      "Added: ",
      ", addedParent: ",
      "item.skull.player.name",
      "char",
      "Error updating custom uniform: ",
      "Custom uniform disabled: ",
      "horse",
      "upper_mouth",
      "lower_mouth",
      "horse_left_ear",
      "horse_right_ear",
      "mule_left_ear",
      "mule_right_ear",
      "neck",
      "horse_face_ropes",
      "mane",
      "tail_base",
      "tail_middle",
      "tail_tip",
      "back_left_leg",
      "back_left_shin",
      "back_left_hoof",
      "back_right_leg",
      "back_right_shin",
      "back_right_hoof",
      "front_left_leg",
      "front_left_shin",
      "front_left_hoof",
      "front_right_leg",
      "front_right_shin",
      "front_right_hoof",
      "mule_left_chest",
      "mule_right_chest",
      "horse_saddle_bottom",
      "horse_saddle_front",
      "horse_saddle_back",
      "horse_left_saddle_rope",
      "horse_left_saddle_metal",
      "horse_right_saddle_rope",
      "horse_right_saddle_metal",
      "horse_left_face_metal",
      "horse_right_face_metal",
      "horse_left_rein",
      "horse_right_rein",
      "Created Mod Manager",
      "keybind",
      " is already bound to another keybind!",
      "engine",
      "delegatedTaskExecutor",
      "handshakeTimeoutMillis: ",
      "closeNotifyTimeoutMillis: ",
      "Pending write on removal of SslHandler",
      "Unknown handshake status: ",
      "Swallowing a harmless 'connection reset by peer / broken pipe' error that occurred while writing close_notify in response to the peer's close_notify",
      "io.netty.",
      "read",
      "com.sun.nio.sctp.SctpChannel",
      "buffer must have at least 5 readable bytes",
      "not an SSL/TLS record: ",
      "_GCM_",
      "-GCM-",
      " HANDSHAKEN: ",
      "possible truncation attack",
      "SSLEngine.closeInbound() raised an exception.",
      "^.*(?:Socket|Datagram|Sctp|Udt)Channel.*$",
      "^.*(?:connection.*(?:reset|closed|abort|broken)|broken.*pipe).*$",
      "SSLEngine closed already",
      "handshake timed out",
      "nix",
      "nux",
      "architecture is ",
      " os.name is ",
      "ppc",
      "86",
      "amd",
      "64",
      "processor is ",
      " os.arch is ",
      "META-INF/lib/",
      "platform specific path is ",
      ".so",
      ".dll",
      "lib",
      ".dylib",
      "native library name ",
      "No native library available for this platform.",
      "IOException creating DefaultJniExtractor",
      "Can't load dynamic library",
      "Problem with library",
      "org.scijava.nativelib.NativeLibraryUtil",
      "Loading ",
      "width.",
      "Invalid value for ",
      "pC: %03d, pU: %1d, aB: %1d",
      "Chunk Batcher %d",
      "getUri",
      "sounds.json",
      "Invalid sounds.json",
      "Replaced sound event location {}",
      "sounds/",
      "File {} does not exist, cannot add it to event {}",
      "Could not load sound file ",
      ", cannot add it to event ",
      "IN YOU FACE",
      "meta:missing_sound",
      "non-sensical empty or null argument array",
      "SCTP_DISABLE_FRAGMENTS",
      "SCTP_EXPLICIT_COMPLETE",
      "SCTP_FRAGMENT_INTERLEAVE",
      "SCTP_INIT_MAXSTREAMS",
      "SCTP_NODELAY",
      "SCTP_PRIMARY_ADDR",
      "SCTP_SET_PEER_PRIMARY_ADDR",
      "BIT7",
      "7bit",
      "BIT8",
      "8bit",
      "binary"
   };
}
