package recovered.strings;

public class StringTable12 {
   public static String[] recoveredField3961 = new String[]{
      "Don't be sad. I'll do better next time, I promise!",
      "Don't be sad, have a hug! <3",
      "I just don't know what went wrong :(",
      "Shall we play a game?",
      "Quite honestly, I wouldn't worry myself about that.",
      "I bet Cylons wouldn't have this problem.",
      "Sorry :(",
      "Surprise! Haha. Well, this is awkward.",
      "Would you like a cupcake?",
      "Hi. I'm Minecraft, and I'm a crashaholic.",
      "Ooh. Shiny.",
      "This doesn't make any sense!",
      "Why is it breaking :(",
      "Don't do that.",
      "Ouch. That hurt :(",
      "You're mean.",
      "This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]",
      "There are four lights!",
      "But it works on my machine.",
      "CB-",
      "OutOfMemoryError",
      "Something went wrong",
      "OptiFine Version: ",
      "User: ",
      "= [ Crash Info ] =\n",
      "Crash ID: ",
      "\nStackTrace: ",
      "= [ System Info ] =\n",
      "OpenGlVersion: ",
      "OpenGlRenderer: ",
      "OpenGlVendor: ",
      "CpuCount: ",
      "OS: ",
      ") version ",
      "Java: ",
      "Java VM: ",
      "Memory: ",
      " MB)\n",
      "JVM Flags: ",
      "= [ Module Settings ] =",
      ": [",
      "]\n",
      "\n= [ Global Settings ] =",
      "Global: [",
      "]\n\n",
      "crashID",
      "osInfo",
      "memoryInfo",
      "%d total; %s",
      "Your client has crashed. \n\nPlease use the following code (also copied to your clipboard) when submitting a bug report: \n\nCB-",
      "Your client has ran out of memory.\nYou can increase memory allocation in the launcher. \n\nPlease use the following code (also copied to your clipboard) when submitting a bug report: \n\nCB-",
      "Out of Memory",
      "LINES_Y",
      "lines_y",
      "lines",
      "LINES_X",
      "lines_x",
      "LINES_Z",
      "lines_z",
      "EntityTag",
      "Control frame cant have fin==false set",
      "Control frame cant have rsv1==true set",
      "Control frame cant have rsv2==true set",
      "Control frame cant have rsv3==true set",
      "minecraft:crafting_table",
      "Key Strokes",
      "Key Options",
      "Show movement keys",
      "Show clicks",
      "Show spacebar",
      "Show sneak key",
      "Click Options",
      "Left CPS",
      "Separate",
      "Right CPS",
      "CPS Background Height",
      "CPS Color",
      "CPS Color (Pressed)",
      "Spacebar Options",
      "Show Spacebar Line",
      "Center Spacebar Line",
      "Spacebar Line Width",
      "Spacebar Line Height",
      "Spacebar Height",
      "Replace names with arrows",
      "Legacy Position",
      "Split Box Size",
      "Box size",
      "Box size height",
      "Fade Options",
      "Text Fade Time",
      "Background Fade Time",
      "Border Fade Time",
      "Text Color (Pressed)",
      "Background Color (Pressed)",
      "Border Color (Pressed)",
      "client/icons/mods/wasd.png",
      "Displays when your movement keys, mouse or spacebar is pressed.",
      "Fyu",
      " RCPS",
      "▲",
      "◀",
      "▼",
      "▶",
      "LMB",
      "SNEAK",
      " II",
      "item.brewingStand.name",
      "has_bottle_0",
      "has_bottle_1",
      "has_bottle_2",
      "maxInitialLineLength must be a positive integer: ",
      "maxHeaderSize must be a positive integer: ",
      "Chunked messages not supported",
      "headerBlock",
      "maxParams: ",
      "unterminated escape sequence at end of string: ",
      "partial escape sequence at end of string: ",
      "invalid escape sequence `%",
      "' at index ",
      " of: ",
      "Created Title Manager",
      "Using SLF4J as the default logging framework",
      "Using Log4J as the default logging framework",
      "Using java.util.logging as the default logging framework",
      "defaultFactory",
      "(Favorite)",
      "(+)",
      "(Un-favorite)",
      "(-)",
      "CHROMA",
      "FAST",
      "rewritePolicy",
      "org.apache.log4j.rewrite.RewritePolicy",
      "Nodes Selection changed",
      "Not implemented",
      "Duplicate stat id: \"",
      "\" and \"",
      "\" at id ",
      "Stat{id=",
      ", nameId=",
      ", awardLocallyOnly=",
      ", formatter=",
      ", objectiveCriteria=",
      "########0.00",
      "VOICE_ENABLED",
      "voiceEnabled",
      "MINIMAP_STATUS",
      "minimapStatus",
      "SERVER_HANDLES_WAYPOINTS",
      "serverHandlesWaypoints",
      "COMPETITIVE_GAMEMODE",
      "competitiveGame",
      "LEGACY_ENCHANTING",
      "legacyEnchanting",
      "LEGACY_COMBAT",
      "legacyCombat",
      "Start: ",
      ", end: ",
      ", yDelta: ",
      ", zDelta: ",
      "ChunkNibbleArrays should be 2048 bytes not: ",
      "map/",
      "Press a key to select a command, and again to use it.",
      "An exception was thrown while process a cancellation task",
      "player_combat",
      "primary_opponent",
      "Combat between ",
      " and others",
      "Invalid count: ",
      " <> ",
      "Invalid size: ",
      "Copy VBO range",
      "Expand VBO",
      "Copy VBO: ",
      "Mixed region draw modes: ",
      "optifine/lang/",
      "options.graphics.fast",
      "options.graphics.fancy",
      "generator.default",
      "Url",
      "TextureAtlas",
      "Terrace",
      "ChunkX",
      "ChunkZ",
      "BB",
      "Children",
      "Category Properties: ",
      "Category: ",
      "Contains at least one fatal LogRecord.",
      "Contains descendants with a fatal LogRecord.",
      "LogRecords in this category alone: ",
      "LogRecords in descendant categories: ",
      "LogRecords in this category including descendants: ",
      "Select All Descendant Categories",
      "Deselect All Descendant Categories",
      "Expand All Descendant Categories",
      "Collapse All Descendant Categories",
      "Remove All Empty Categories",
      "item.fireworks.flight",
      "Invalid Biome id",
      "DownfallBlock",
      "biome id",
      "downfalls[] size",
      "RawBiomeBlock",
      "biomes[] size",
      "Layer",
      "radius",
      "allowed",
      "Enchant",
      "init() can not be invoked if ",
      " was constructed with non-default constructor.",
      "inboundHandler",
      "outboundHandler",
      "inboundHandler must not implement ",
      " to get combined.",
      "outboundHandler must not implement ",
      "init() must be invoked before being added to a ",
      " if ",
      " was constructed with the default constructor.",
      "scheduledExecutables",
      "preRenderErrors",
      "Something's taking too long! '",
      "' took aprox ",
      " ms",
      "[UNKNOWN]",
      "options.title",
      "options.skinCustomisation",
      "Super Secret Settings...",
      "options.sounds",
      "options.stream",
      "options.video",
      "options.controls",
      "options.resourcepack",
      "options.snooper.view",
      "options.difficulty",
      "difficulty.lock.title",
      "difficulty.lock.question",
      "Controls: ",
      "Filter Level:",
      "Filter Thread:",
      "Filter Logger:",
      "Filter NDC:",
      "Filter Message:",
      "org.apache.log4j.chainsaw.ControlPanel",
      "SEND",
      "AES",
      "textures/gui/spectator_widgets.png",
      "Wave",
      "Lock",
      "Could not read configuration file [",
      "Ignoring configuration file [",
      "[log4j.configDebug] is deprecated. Use [log4j.debug] instead.",
      "log4j.reset",
      "log4j.threshold",
      "Hierarchy threshold set to [",
      "Finished configuring.",
      "Could not read configuration file from InputStream [",
      "Ignoring configuration InputStream [",
      "Reading configuration from URL ",
      "Could not read configuration file from URL [",
      "log4j.loggerFactory",
      "Setting category factory to [",
      "log4j.factory.",
      "log4j.rootCategory",
      "Could not find root logger information. Is this OK?",
      "log4j.category.",
      "log4j.renderer.",
      "log4j.throwableRenderer",
      "org.apache.log4j.spi.ThrowableRenderer",
      "Could not instantiate throwableRenderer.",
      "log4j.throwableRenderer.",
      "Handling log4j.additivity.",
      "=[",
      "Setting additivity for \"",
      "\" to ",
      "Parsing for [",
      "] with value=[",
      "Level token is [",
      "The root logger cannot be set to null.",
      "Category ",
      " set to ",
      "Parsing appender named \"",
      "Appender \"",
      "\" was already parsed.",
      "Could not instantiate appender named \"",
      "Parsing layout options for \"",
      "End of parsing for \"",
      ".errorhandler",
      "Parsing errorhandler options for \"",
      "End of errorhandler parsing for \"",
      "Parsed \"",
      "\" options.",
      ".filter.",
      "Filter key: [",
      "] class: [",
      "] props: ",
      "Missing class definition for filter: [",
      "E, dd-MMM-yy HH:mm:ss z",
      "GMT",
      "delimiters",
      "empty delimiters",
      "frame length exceeds ",
      "delimiter",
      "empty delimiter",
      "always",
      "never",
      "HIDE_FOR_OTHER_TEAMS",
      "hideForOtherTeams",
      "HIDE_FOR_OWN_TEAM",
      "hideForOwnTeam",
      "commands.trigger.usage",
      "commands.trigger.invalidPlayer",
      "commands.trigger.invalidObjective",
      "commands.trigger.disabled",
      "commands.trigger.invalidMode",
      "commands.trigger.success",
      "Bad packet id ",
      "Packet ",
      ") was larger than I expected, found ",
      " bytes extra whilst reading packet ",
      " IN: [{}:{}] {}",
      "PACKET_RECEIVED",
      "textures/entity/enderdragon/dragon_eyes.png",
      "tmplib",
      "java.library.tmpdir",
      "Unable to create native library working directory ",
      "local",
      "] logged in with entity id ",
      " at (",
      "MC|Brand",
      "multiplayer.player.joined.renamed",
      "multiplayer.player.joined",
      "loading single player",
      "removing player mount",
      "You are banned from this server!\nReason: ",
      "\nYour ban will be removed on ",
      "You are not white-listed on this server!",
      "Your IP address is banned from this server!\nReason: ",
      "The server is full!",
      "You logged in from another location",
      "moving",
      "placing",
      "Server closed",
      "banned-players.json",
      "banned-ips.json",
      "ops.json",
      "whitelist.json",
      "yyyy-MM-dd 'at' HH:mm:ss z",
      "Class ",
      " has no public constructor TestCase(String name) or TestCase()",
      "Cannot instantiate test case: ",
      "Exception in constructor: ",
      "Cannot access test case: ",
      " is not public",
      "No tests found in ",
      "Test method isn't public: ",
      "test",
      "icons/ok.gif",
      " - Failed",
      " - Error",
      " - Passed",
      "guardian",
      "eye",
      "spine",
      "spine1",
      "spine2",
      "spine3",
      "spine4",
      "spine5",
      "spine6",
      "spine7",
      "spine8",
      "spine9",
      "spine10",
      "spine11",
      "spine12",
      "tail1",
      "tail2",
      "tail3",
      "icons/hierarchy.gif",
      "Test Hierarchy",
      "The test hierarchy",
      "mcpatcher/anim/",
      "Texture animation: ",
      "Skipped: ",
      ", target texture not loaded from same resource pack",
      "from",
      "to",
      "TextureAnimation: Source texture not found: ",
      "TextureAnimation: Source texture has invalid number of frames: ",
      ", frames: ",
      "TextureAnimation: Target texture not found: ",
      "TextureAnimation: Animation coordinates are outside the target texture: ",
      "TextureAnimation: Invalid coordinates",
      "TextureAnimation: Source or target texture not specified",
      "/anim",
      "https://cheatbreaker2.com/restrictions",
      "restrictedMessage",
      "restrictedOptions",
      "restrictedAddresses",
      "restrictedServerMappingIDs",
      "client/logo_255_outer.png",
      "client/logo_108_inner.png",
      "menu.returnToMenu",
      "menu.returnToGame",
      "menu.shareToLan",
      "gui.stats",
      "Server List",
      "Mods (",
      "Some login services might be offline",
      "E, dd MMM yyyy HH:mm:ss z",
      "bossHealth",
      "sleep",
      "Uploading screenshot...",
      "Chat is hidden",
      "overlayMessage",
      "titleAndSubtitle",
      "˙",
      "chat",
      "jumpBar",
      "expBar",
      "expLevel",
      "selectedItemName",
      "demo.demoExpired",
      "demo.remainingTime",
      "food",
      "mountHealth",
      "record.nowPlaying",
      "textures/misc/vignette.png",
      "textures/misc/pumpkinblur.png",
      "Utility class",
      "fishingSpeed",
      "achievement.",
      ".desc",
      "mob.horse.leather",
      "Someone's been tampering with the universe!",
      "HORIZONTAL",
      "VERTICAL",
      "dimension",
      "xCenter",
      "zCenter",
      "colors",
      "Decorations",
      "rot",
      "optifine/natural.properties",
      "NaturalTextures: configuration \"",
      "Natural Textures: Parsing default configuration \"",
      "Natural Textures: Valid only for textures from default resource pack",
      "Natural Textures: Parsing configuration \"",
      "Natural Textures: Invalid \"",
      "\" line: ",
      "Natural Textures: Texture not found: \"",
      "NaturalTextures: ",
      "\\(",
      "tile.bed.notValid",
      "left_foot",
      "right_foot",
      "left_thigh",
      "right_thigh",
      "right_ear",
      "left_ear",
      "fireworks.",
      "largeBlast",
      "blast",
      "_far",
      "twinkle_far",
      "twinkle",
      "{} WebSocket version {} server handshake",
      "No HttpDecoder and no HttpServerCodec in the pipeline",
      "wsdecoder",
      "wsencoder",
      "textures/entity/banner/",
      "textures/entity/banner_base.png",
      "UNINITIALIZED",
      "CONNECTING",
      "CONNECTED",
      "CLOSED",
      "DISCONNECTED",
      "Callable(task: ",
      ", result: ",
      "commands.me.usage",
      "chat.type.emote",
      "failed to initialize an SPDY header block deflater: ",
      "failed to set the SPDY dictionary: ",
      "compression failure: ",
      "log.detail",
      "Program stack overflow: ",
      "Program stack empty",
      "CB|PING",
      "CheatBreaker Protocol Error -2a\n(Try updating your client)",
      "CheatBreaker Protocol Error -2b\n(Try updating your client)",
      "CB|PONG",
      "null:",
      "sctpChannel",
      "failed to initialize a sctp channel",
      "write",
      "connect",
      "Failed to close a ",
      " selector.",
      "Protocol version ",
      " not supported.",
      "SMOOTH",
      "smooth",
      "null_object",
      "null_class",
      "%n",
      "gui.toTitle",
      "Out of memory!",
      "Minecraft has run out of memory.",
      "This could be caused by a bug in the game or by the",
      "Java Virtual Machine not being allocated enough",
      "memory.",
      "To prevent level corruption, the current game has quit.",
      "We've tried to free up enough memory to let you go back to",
      "the main menu and back to playing, but this may not have worked.",
      "Please restart the game if you see this message again.",
      "Y_ROT",
      "X_ROT",
      "textures/entity/zombie_pigman.png",
      "FRAME_START",
      "MASKING_KEY",
      "PAYLOAD",
      "CORRUPT",
      "pulling_0",
      "pulling_1",
      "pulling_2",
      "value must not be null",
      "Accepting a client certificate: ",
      "Accepting a server certificate: ",
      "game.player.swim",
      "game.player.swim.splash",
      "random.drink",
      "random.eat",
      "Notch",
      "keepInventory",
      "game.player.hurt",
      "game.player.die",
      "Inventory",
      "SelectedItemSlot",
      "Sleeping",
      "SleepTimer",
      "XpP",
      "XpLevel",
      "XpTotal",
      "XpSeed",
      "SpawnForced",
      "EnderItems",
      "SelectedItem",
      "game.player.hurt.fall.big",
      "game.player.hurt.fall.small",
      "random.levelup",
      "OfflinePlayer:",
      "fragments must have at least one element",
      "Working...",
      "sheep_wool",
      "Not a RenderSheep: ",
      "client/defaults/crosshair_",
      "tailRef",
      "textures/gui/container/generic_54.png",
      "INTERACT",
      "ATTACK",
      "INTERACT_AT",
      "\\\\\"",
      "[-+]?[0-9]*\\.?[0-9]+[d|D]",
      "[-+]?[0-9]*\\.?[0-9]+[f|F]",
      "[-+]?[0-9]+[b|B]",
      "[-+]?[0-9]+[l|L]",
      "[-+]?[0-9]+[s|S]",
      "[-+]?[0-9]+",
      "[-+]?[0-9]*\\.?[0-9]+",
      "HTTP response: ",
      "Input stream closed: ",
      "player.models.local",
      "playermodels",
      "http://s.optifine.net",
      "cmdStatus",
      " is not in bounds 0 <= x <= 65535",
      "SINGLEPLAYER",
      "MULTIPLAYER",
      "finished",
      "in_wall",
      "capacity: ",
      " (expected: 0+)",
      "Chunk(s) at 0~25%:",
      "Chunk(s) at 0~50%:",
      "Chunk(s) at 25~75%:",
      "Chunk(s) at 50~100%:",
      "Chunk(s) at 75~100%:",
      "Chunk(s) at 100%:",
      "tiny subpages:",
      "small subpages:",
      "shadow pass",
      "pre shadow",
      "shadow bind sfb",
      "shadow camera",
      "shadow drawbuffers",
      "shadow readbuffer",
      "shadow fb",
      "shadow frustum",
      "shadow culling",
      "shadow prepareterrain",
      "shadow setupterrain",
      "shadow updatechunks",
      "shadow terrain",
      "shadow terrain solid",
      "shadow terrain cutoutmipped",
      "shadow terrain cutout",
      "shadow entities",
      "pre copy shadow depth",
      "copy shadow depth",
      "shadow pre-translucent",
      "shadow drawbuffers pre-translucent",
      "shadow translucent",
      "shadow entities 1",
      "shadow flush",
      "shadow postprocess",
      "shadow end",
      "Entity_",
      "zombie_pigman",
      "Adding item to inventory",
      "Item being added",
      "Item ID",
      "Item data",
      "Item name",
      "container.inventory",
      "deathScreen.deleteWorld",
      "deathScreen.leaveServer",
      "deathScreen.respawn",
      "deathScreen.titleScreen",
      "deathScreen.quit.confirm",
      "deathScreen.title.hardcore",
      "deathScreen.title",
      "deathScreen.hardcoreInfo",
      "deathScreen.score",
      "weights.",
      "biomes.",
      "heights.",
      "health.",
      "name.",
      "professions.",
      "collarColors.",
      "collar color",
      "baby.",
      "moonPhase.",
      "dayTime.",
      "weather.",
      "minHeight.",
      "maxHeight.",
      "Invalid minHeight: ",
      "Invalid maxHeight: ",
      "Invalid minHeight, maxHeight: ",
      "Invalid path: ",
      "More weights defined than skins, trimming weights: ",
      "Less weights defined than skins, expanding weights: ",
      "Invalid weight: ",
      "Invalid sum of all weights: ",
      "Invalid professions or careers: ",
      "Invalid collar colors: ",
      "Invalid skins for rule: ",
      "Video Settings",
      "options.videoTitle",
      "of.options.shaders",
      "of.options.quality",
      "of.options.details",
      "of.options.performance",
      "of.options.animations",
      "of.options.other",
      "of.message.shaders.aa1",
      "of.message.shaders.aa2",
      "of.message.shaders.af1",
      "of.message.shaders.af2",
      "of.message.shaders.fr1",
      "of.message.shaders.fr2",
      "of.message.shaders.an1",
      "of.message.shaders.an2",
      "HD_U",
      "HD",
      "OptiFine HD M6_pre2",
      "OptiFine HD M6_pre2 Ultra",
      "OptiFine M6_pre2 Light",
      "createWorld.customize.flat.layer.top",
      "createWorld.customize.flat.layer.bottom",
      "createWorld.customize.flat.layer",
      "+0-1+2+3+13&4-4",
      "cooked",
      "raw",
      "Literal",
      "literal",
      "Invalid character: '",
      "', in: ",
      "EXPLOSION_NORMAL",
      "EXPLOSION_LARGE",
      "largeexplode",
      "EXPLOSION_HUGE",
      "hugeexplosion",
      "FIREWORKS_SPARK",
      "fireworksSpark",
      "WATER_BUBBLE",
      "bubble",
      "WATER_SPLASH",
      "splash",
      "WATER_WAKE",
      "wake",
      "SUSPENDED",
      "suspended",
      "SUSPENDED_DEPTH",
      "depthsuspend",
      "CRIT",
      "crit",
      "CRIT_MAGIC",
      "magicCrit",
      "SMOKE_NORMAL",
      "smoke",
      "SMOKE_LARGE",
      "largesmoke",
      "SPELL",
      "spell",
      "SPELL_INSTANT",
      "instantSpell",
      "SPELL_MOB",
      "mobSpell",
      "SPELL_MOB_AMBIENT",
      "mobSpellAmbient",
      "SPELL_WITCH",
      "witchMagic",
      "DRIP_WATER",
      "dripWater",
      "DRIP_LAVA",
      "dripLava",
      "VILLAGER_ANGRY",
      "angryVillager",
      "VILLAGER_HAPPY",
      "happyVillager",
      "TOWN_AURA",
      "townaura",
      "NOTE",
      "PORTAL",
      "ENCHANTMENT_TABLE",
      "enchantmenttable",
      "FLAME",
      "LAVA",
      "FOOTSTEP",
      "footstep",
      "CLOUD",
      "cloud",
      "REDSTONE",
      "reddust",
      "SNOWBALL",
      "snowballpoof",
      "SNOW_SHOVEL",
      "snowshovel",
      "SLIME",
      "HEART",
      "heart",
      "BARRIER",
      "ITEM_CRACK",
      "iconcrack_",
      "BLOCK_CRACK",
      "blockcrack_",
      "BLOCK_DUST",
      "blockdust_",
      "WATER_DROP",
      "droplet",
      "ITEM_TAKE",
      "take",
      "MOB_APPEARANCE",
      "mobappearance",
      "sun.misc.SharedSecrets",
      "getJavaNioAccess",
      "getDirectBufferPool",
      "getMemoryUsed",
      "jdk.internal.misc.SharedSecrets",
      "jdk.internal.misc.VM",
      "Non-zero refCnt: {}",
      "Released: {}",
      "Failed to release an object: {}",
      ".release(",
      ") refCnt: ",
      "ANY_VALUE",
      "BOOLEAN_VALUE",
      "NUMERICAL_VALUE",
      "unknown type parameter '",
      "': ",
      "cannot determine the type of the type parameter '",
      "TE(",
      "),",
      "blockId",
      "blockData",
      "extending",
      "input was set already",
      "output was set already",
      "is",
      "os",
      "Expected to be able to write ",
      " bytes, ",
      "but only wrote ",
      "Badly compressed packet - size of ",
      " is below server threshold of ",
      " is larger than protocol maximum of ",
      "Select a player to teleport to",
      "Teleport to player",
      "Failed to close channel.",
      "Failed to configure channel.",
      "Provider error: failed to finish connect. Provider library should be upgraded.",
      "Invalid config : increase receive buffer size to avoid message truncation",
      "Provider error: failed to write message. Provider library should be upgraded.",
      " # ",
      "XX",
      "X#",
      "# ",
      "cache: ",
      ", tcache: ",
      ", allocated: ",
      ", tallocated: ",
      "Invalid Item!",
      "Type: ",
      "Invalid Entity!",
      "stats.tooltip.type.",
      "achievement",
      "statistic",
      "Invalid statistic/achievement!",
      "Missing protocol",
      "Unsupported protocol: ",
      "Can't open url for ",
      "Tried to handle twitch user but couldn't find them!",
      "Don't know how to handle ",
      "screenshots",
      "Progress",
      "1.8.9 (",
      "sjndfg",
      "https://api.imgur.com/3/image",
      "image",
      "7fd132c453b5486",
      "Authorization",
      "Client-ID 7fd132c453b5486",
      "https://i.imgur.com/",
      "http",
      "ViBH",
      "ViDF",
      "ViF",
      "ViL",
      "ViPH",
      "ViSH",
      "ViSmH",
      "ViST",
      "ViS",
      "ViStart",
      "ViSR",
      "ViTRH",
      "ViW",
      "shaders/program/",
      "Couldn't compile ",
      " program: ",
      "http resource descriptor must not be null",
      "blaze",
      "stick1",
      "stick2",
      "stick3",
      "stick4",
      "stick5",
      "stick6",
      "stick7",
      "stick8",
      "stick9",
      "stick10",
      "stick11",
      "stick12",
      "playerdata",
      "session.lock",
      "Failed to check session lock, aborting",
      "The save is being accessed from another location, aborting",
      "Old Chunk Storage is no longer supported.",
      "level.dat_old",
      "level.dat_new",
      ".dat.tmp",
      ".dat",
      "Failed to save player data for ",
      "Failed to load player data for ",
      "GVector0",
      "GVector1",
      "GVector2",
      "GVector3",
      "GVector4",
      "GVector5",
      "GVector6",
      "GVector7",
      "GVector8",
      "GVector9",
      "GVector10",
      "GVector11",
      "GVector12",
      "GVector13",
      "GVector14",
      "GVector15",
      "GVector23",
      "GVector16",
      "GVector24",
      "GVector25",
      "GVector20",
      "GVector21",
      "GVector22",
      "enchantment.level.2",
      "enchantment.level.3",
      "enchantment.level.4",
      "Took too long to log in",
      "Disconnecting ",
      "Error whilst disconnecting player",
      " lost connection: ",
      "Unexpected hello packet",
      "Unexpected key packet",
      "Invalid nonce!",
      "User Authenticator #",
      "mcpatcher/sky/world",
      "/sky",
      "CustomSky properties: ",
      "CustomSky: Texture not found: ",
      "CPS",
      "[9 CPS]",
      "Displays your clicks per second.",
      "Left Clicks",
      "Right Clicks",
      "9  2",
      "Determines which and when clicks should be shown.\n\n§bLeft Clicks:§r Only show left clicks.\n§bRight Clicks:§r Only show right clicks.\n§bBoth:§r Show both left and right clicks.\n§bHigher:§r Shows either left or right clicks depending which has a higher amount.",
      "Line Color",
      " Clicks",
      "enabled: ",
      ", src: ",
      ", dst: ",
      ", srcAlpha: ",
      ", dstAlpha: ",
      "Status request has been handled.",
      "offsetBold",
      "font/glyph_sizes.bin",
      "ÀÁÂÈÊËÍÓÔÕÚßãõğİıŒœŞşŴŵžȇ\u0000\u0000\u0000\u0000\u0000\u0000\u0000 !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\u0000ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜø£Ø×ƒáíóúñÑªº¿®¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αβΓπΣσμτΦΘΩδ∞∅∈∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■\u0000",
      "textures/font/unicode_page_%02x.png",
      "commands.clear.usage",
      "commands.clear.tagError",
      "commands.clear.failure",
      "commands.clear.testing",
      "commands.clear.success",
      "NOTSTARTED",
      "PREAMBLE",
      "HEADERDELIMITER",
      "DISPOSITION",
      "FIELD",
      "FILEUPLOAD",
      "MIXEDPREAMBLE",
      "MIXEDDELIMITER",
      "MIXEDDISPOSITION",
      "MIXEDFILEUPLOAD",
      "MIXEDCLOSEDELIMITER",
      "CLOSEDELIMITER",
      "PREEPILOGUE",
      "EPILOGUE",
      "EAT",
      "DRINK",
      "BOW",
      "NOT_YET_CONNECTED",
      "OPEN",
      "#0",
      " is not a @Sharable handler, so can't be added or removed multiple times.",
      "Failed to remove a handler: ",
      ".handlerAdded() has thrown an exception; removed.",
      ".handlerAdded() has thrown an exception; also failed to remove.",
      ".handlerRemoved() has thrown an exception.",
      "handlerType",
      "Duplicate handler name: ",
      "CustomPotionEffects",
      "item.emptyPotion.name",
      "potion.prefix.grenade",
      ".postfix",
      "potion.potency.",
      "potion.empty",
      "potion.effects.whenDrank",
      "waterWalker",
      "-h",
      "Invalid verbose level. Using default.",
      "Verbose Activated (level ",
      "-p",
      "Please specify an output filename after the -p option!",
      "FileName = ",
      "JavaLayer Converter :",
      "  -v[x]         verbose mode. ",
      "                default = 2",
      "  -p name    output as a PCM wave file",
      "  More info on http://www.javazoom.net",
      "Model: ",
      ", ao: ",
      ", gui3d: ",
      ", builtIn: ",
      ", particle: ",
      "General",
      "Quad: ",
      ", face: ",
      "Length: ",
      ", step: ",
      " xyz: ",
      " col: ",
      " u,v: ",
      "Cannot serialize a null array.",
      "Cannot have negative offset: ",
      "Cannot have length offset: ",
      "Cannot have offset of %d and length of %d with array of length %d",
      "Source array was null.",
      "Destination array was null.",
      "Source array with length %d cannot have offset of %d and still process four bytes.",
      "Destination array with length %d cannot have offset of %d and still store three bytes.",
      " last write attempt timed out.",
      " Force-closing the connection.",
      "inventory.binSlot",
      "textures/gui/container/creative_inventory/tab_",
      "textures/gui/container/creative_inventory/tabs.png",
      "tmp",
      "achievement_id",
      "achievement_name",
      "achievement_description",
      "Achievement '",
      "' obtained!",
      "https://dash-api.com/api/v3/allData.php",
      "stations",
      "genre",
      "square_logo_url",
      "current_song_url"
   };
}
