package recovered.strings;

public class StringTable15 {
   public static String[] recoveredField3962 = new String[]{
      "stream_url",
      "c contains null values",
      "element",
      "OutputSignal",
      "uvs",
      "Text",
      "of.options.shaders.DOWNLOAD",
      "ON_GROUND",
      "IN_AIR",
      "IN_WATER",
      "Field not found: TileEntityChestRenderer.simpleChest",
      "Primary",
      "Secondary",
      "Levels",
      "container.beacon",
      "minecraft:beacon",
      "A marker name cannot be null",
      "A null value cannot be added to a Marker as reference.",
      "Other cannot be null",
      "[ ",
      " ]",
      "bytes are not UTF-8",
      "mob.chicken.plop",
      "mob.chicken.say",
      "mob.chicken.hurt",
      "mob.chicken.step",
      "IsChickenJockey",
      "EggLayTime",
      "keepAlive",
      "You have been idle for too long!",
      "Invalid move packet received",
      "Illegal position",
      " moved too quickly! ",
      " moved wrongly!",
      " was kicked for floating too long!",
      "Flying is not enabled on this server",
      "Invalid player action",
      "build.tooHigh",
      "multiplayer.player.left",
      "Stopping singleplayer server as player logged out",
      "Sending packet",
      "Packet being sent",
      "Packet class",
      " tried to set an invalid carried item",
      "chat.cannotSend",
      "Illegal characters in chat",
      "chat.type.text",
      "disconnect.spam",
      "Invalid client command!",
      "Attempting to attack an invalid entity",
      "Player ",
      " tried to attack an invalid entity",
      "You have died. Game over, man, it's game over!",
      "(You just lost the game)",
      "Death in Hardcore",
      " just tried to change non-editable sign",
      "Invalid book tag!",
      "Couldn't handle book info",
      "Couldn't sign book",
      "MC|TrSel",
      "Couldn't select trade",
      "advMode.notEnabled",
      "advMode.setCommand.success",
      "Couldn't set command block",
      "advMode.notAllowed",
      "Couldn't set beacon",
      "Thread started",
      "Waiting for a connection",
      "Got a connection from ",
      "Error in accepting connections, stopping.",
      "org.apache.log4j.chainsaw.LoggingReceiver",
      "PENDING",
      "COMPILING",
      "UPLOADING",
      "DONE",
      " FPS]",
      "Invalid lightmap width: ",
      "coordinateScale",
      "heightScale",
      "lowerLimitScale",
      "upperLimitScale",
      "depthNoiseScaleX",
      "depthNoiseScaleZ",
      "depthNoiseScaleExponent",
      "mainNoiseScaleX",
      "mainNoiseScaleY",
      "mainNoiseScaleZ",
      "baseSize",
      "stretchY",
      "biomeDepthWeight",
      "biomeDepthOffset",
      "biomeScaleWeight",
      "biomeScaleOffset",
      "seaLevel",
      "useCaves",
      "useDungeons",
      "dungeonChance",
      "useStrongholds",
      "useVillages",
      "useMineShafts",
      "useTemples",
      "useMonuments",
      "useRavines",
      "useWaterLakes",
      "waterLakeChance",
      "useLavaLakes",
      "lavaLakeChance",
      "useLavaOceans",
      "fixedBiome",
      "biomeSize",
      "riverSize",
      "dirtSize",
      "dirtCount",
      "dirtMinHeight",
      "dirtMaxHeight",
      "gravelSize",
      "gravelCount",
      "gravelMinHeight",
      "gravelMaxHeight",
      "graniteSize",
      "graniteCount",
      "graniteMinHeight",
      "graniteMaxHeight",
      "dioriteSize",
      "dioriteCount",
      "dioriteMinHeight",
      "dioriteMaxHeight",
      "andesiteSize",
      "andesiteCount",
      "andesiteMinHeight",
      "andesiteMaxHeight",
      "coalSize",
      "coalCount",
      "coalMinHeight",
      "coalMaxHeight",
      "ironSize",
      "ironCount",
      "ironMinHeight",
      "ironMaxHeight",
      "goldSize",
      "goldCount",
      "goldMinHeight",
      "goldMaxHeight",
      "redstoneSize",
      "redstoneCount",
      "redstoneMinHeight",
      "redstoneMaxHeight",
      "diamondSize",
      "diamondCount",
      "diamondMinHeight",
      "diamondMaxHeight",
      "lapisSize",
      "lapisCount",
      "lapisCenterHeight",
      "lapisSpread",
      "STREAM_IDENTIFIER",
      "COMPRESSED_DATA",
      "UNCOMPRESSED_DATA",
      "RESERVED_UNSKIPPABLE",
      "RESERVED_SKIPPABLE",
      "waterWorker",
      " Spikes",
      "left_eye",
      "right_eye",
      "mouth",
      "textures/particle/particles.png",
      "RabbitType",
      "MoreCarrotTicks",
      "mob.rabbit.hop",
      "mob.rabbit.idle",
      "mob.rabbit.hurt",
      "mob.rabbit.death",
      "entity.KillerBunny.name",
      "mcpatcher/color.properties",
      "palette.format",
      "mcpatcher/colormap/",
      "water.png",
      "watercolorX.png",
      "pine.png",
      "pinecolor.png",
      "birch.png",
      "birchcolor.png",
      "swampgrass.png",
      "swampgrasscolor.png",
      "swampfoliage.png",
      "swampfoliagecolor.png",
      "sky0.png",
      "skycolor0.png",
      "fog0.png",
      "fogcolor0.png",
      "underwater.png",
      "underwatercolor.png",
      "underlava.png",
      "underlavacolor.png",
      "redstone.png",
      "redstonecolor.png",
      "xporb.png",
      "durability.png",
      "stem.png",
      "stemcolor.png",
      "pumpkinstem.png",
      "melonstem.png",
      "myceliumparticle.png",
      "myceliumparticlecolor.png",
      "custom/",
      "blocks/",
      "Invalid value: ",
      "Expected values: ",
      "mcpatcher/lightmap/world",
      "_rain.png",
      "_thunder.png",
      "particle.water",
      "drop.water",
      "particle.portal",
      "lilypad",
      "text.xpbar",
      "text.boss",
      "text.sign",
      "fog.nether",
      "fog.end",
      "sky.end",
      "egg.shell.",
      "Spawn egg shell",
      "egg.spots.",
      "Spawn egg spot",
      "collar.",
      "Wolf collar",
      "sheep.",
      "text.code.",
      "map.",
      "Map",
      "potion.",
      "xporb.time",
      "palette.block.",
      "Block palette: ",
      "Colormap not found: ",
      "CustomColors",
      "Invalid match blocks: ",
      "Block colormap: ",
      "Invalid block ID: ",
      "No match blocks: ",
      "Invalid color: ",
      "Colormap ",
      "Colormap properties: ",
      "Invalid spawn egg name: ",
      "Invalid spawn egg color: ",
      " colors: ",
      "potion.water",
      "iron",
      "foliage",
      "gold",
      "lapis",
      "adobe",
      "Steps",
      "maxNumComponents: ",
      "buffers",
      "cIndex: %d (expected: >= 0 && <= numComponents(%d))",
      "cIndex: %d, numComponents: %d (expected: cIndex >= 0 && cIndex + numComponents <= totalNumComponents(%d))",
      "should not reach here",
      ", components=",
      "attached",
      "aggregatePromise",
      "promises",
      "percent",
      "dig.",
      "step.",
      "Notifications",
      "&([abcdefghijklmrABCDEFGHIJKLMNR0-9])|(&$)",
      "§$1",
      "info",
      "xray",
      "lengthFieldLength must be either 1, 2, 3, 4, or 8: ",
      ") is less than zero",
      "length does not fit into a byte: ",
      "length does not fit into a short integer: ",
      "length does not fit into a medium integer: ",
      "The maxSize argument (",
      ") is not a positive integer.",
      "Negative array size [",
      "] not allowed.",
      "minecraft:blocks/glass_pane_top",
      "Unknown side: ",
      "mcpatcher/ctm/default/empty",
      "mcpatcher/ctm/",
      "ConnectedTextures: ",
      "ConnectedTextures file not found: ",
      "Multipass connected textures: ",
      "TextureAtlasSprite is not TextureAtlasSprite: ",
      "Invalid tile ID: ",
      "mcpatcher/ctm/default/",
      "textures/blocks/glass.png",
      "glass.properties",
      "glasspane.properties",
      "textures/blocks/bookshelf.png",
      "bookshelf.properties",
      "textures/blocks/sandstone_normal.png",
      "sandstone.properties",
      "textures/blocks/glass_",
      "_glass_",
      "/glass_",
      "/glass_pane_",
      "<default>",
      "key.forward",
      "key.categories.movement",
      "key.left",
      "key.back",
      "key.right",
      "key.jump",
      "key.sneak",
      "key.sprint",
      "key.inventory",
      "key.categories.inventory",
      "key.use",
      "key.categories.gameplay",
      "key.drop",
      "key.attack",
      "key.pickItem",
      "key.chat",
      "key.categories.multiplayer",
      "key.playerlist",
      "key.command",
      "key.screenshot",
      "key.categories.misc",
      "key.togglePerspective",
      "key.smoothCamera",
      "key.fullscreen",
      "key.spectatorOutlines",
      "key.streamStartStop",
      "key.categories.stream",
      "key.streamPauseUnpause",
      "key.streamCommercial",
      "key.streamToggleMic",
      "key.hotbar.1",
      "key.hotbar.2",
      "key.hotbar.3",
      "key.hotbar.4",
      "key.hotbar.5",
      "key.hotbar.6",
      "key.hotbar.7",
      "key.hotbar.8",
      "key.hotbar.9",
      "options.txt",
      "optionsof.txt",
      "of.key.zoom",
      "key.mouseButton",
      "%c",
      "of.message.an.shaders1",
      "of.message.an.shaders2",
      "of.general.max",
      "options.sensitivity.min",
      "options.sensitivity.max",
      "options.fov.min",
      "options.fov.max",
      "options.framerateLimit.max",
      " fps",
      "options.cloudHeight.min",
      "options.gamma.min",
      "options.gamma.max",
      " Kbps",
      "%.3f bpp",
      "mouseSensitivity",
      "fov",
      "oldGamma",
      "gamma",
      "invertYMouse",
      "renderDistance",
      "guiScale",
      "particles",
      "bobView",
      "anaglyph3d",
      "maxFps",
      "fboEnable",
      "fancyGraphics",
      "ao",
      "renderClouds",
      "resourcePacks",
      "incompatibleResourcePacks",
      "lastServer",
      "lang",
      "chatVisibility",
      "chatColors",
      "chatLinks",
      "chatLinksPrompt",
      "chatOpacity",
      "snooperEnabled",
      "enableVsync",
      "useVbo",
      "hideServerAddress",
      "advancedItemTooltips",
      "pauseOnLostFocus",
      "touchscreen",
      "overrideHeight",
      "overrideWidth",
      "heldItemTooltips",
      "chatHeightFocused",
      "chatHeightUnfocused",
      "chatScale",
      "chatWidth",
      "showInventoryAchievementHint",
      "mipmapLevels",
      "streamBytesPerPixel",
      "streamMicVolume",
      "streamSystemVolume",
      "streamKbps",
      "streamFps",
      "streamCompression",
      "streamSendMetadata",
      "streamPreferredServer",
      "streamChatEnabled",
      "streamChatUserFilter",
      "streamMicToggleBehavior",
      "forceUnicodeFont",
      "allowBlockAlternatives",
      "useNativeTransport",
      "entityShadows",
      "realmsNotifications",
      "soundCategory_",
      "modelPart_",
      "Skipping bad option: ",
      "Failed to load options",
      "invertYMouse:",
      "mouseSensitivity:",
      "fov:",
      "gamma:",
      "oldGamma:",
      "saturation:",
      "renderDistance:",
      "guiScale:",
      "particles:",
      "bobView:",
      "anaglyph3d:",
      "maxFps:",
      "fboEnable:",
      "difficulty:",
      "fancyGraphics:",
      "ao:",
      "renderClouds:false",
      "renderClouds:fast",
      "renderClouds:true",
      "resourcePacks:",
      "incompatibleResourcePacks:",
      "lastServer:",
      "lang:",
      "chatVisibility:",
      "chatColors:",
      "chatLinks:",
      "chatLinksPrompt:",
      "chatOpacity:",
      "snooperEnabled:",
      "fullscreen:",
      "enableVsync:",
      "useVbo:",
      "hideServerAddress:",
      "advancedItemTooltips:",
      "pauseOnLostFocus:",
      "touchscreen:",
      "overrideWidth:",
      "overrideHeight:",
      "heldItemTooltips:",
      "chatHeightFocused:",
      "chatHeightUnfocused:",
      "chatScale:",
      "chatWidth:",
      "showInventoryAchievementHint:",
      "mipmapLevels:",
      "streamBytesPerPixel:",
      "streamMicVolume:",
      "streamSystemVolume:",
      "streamKbps:",
      "streamFps:",
      "streamCompression:",
      "streamSendMetadata:",
      "streamPreferredServer:",
      "streamChatEnabled:",
      "streamChatUserFilter:",
      "streamMicToggleBehavior:",
      "forceUnicodeFont:",
      "allowBlockAlternatives:",
      "reducedDebugInfo:",
      "useNativeTransport:",
      "entityShadows:",
      "realmsNotifications:",
      "Failed to save options",
      "of.message.aa.shaders1",
      "of.message.aa.shaders2",
      "of.message.af.shaders1",
      "of.message.af.shaders2",
      "of.message.fr.shaders1",
      "of.message.fr.shaders2",
      "options.renderDistance.tiny",
      "options.renderDistance.short",
      "options.renderDistance.normal",
      "options.renderDistance.far",
      "of.options.renderDistance.extreme",
      "of.options.renderDistance.insane",
      "of.options.renderDistance.ludicrous",
      "of.options.mipmap.nearest",
      "of.options.mipmap.linear",
      "of.options.mipmap.bilinear",
      "of.options.mipmap.trilinear",
      "of.general.smart",
      "of.options.animation.dynamic",
      "of.options.save.45s",
      "of.options.save.90s",
      "of.options.save.3min",
      "of.options.save.6min",
      "of.options.save.12min",
      "of.options.save.24min",
      "of.options.time.dayOnly",
      "of.options.time.nightOnly",
      "of.general.restart",
      "of.options.framerateLimit.vsync",
      "ofRenderDistanceChunks",
      "ofFogType",
      "ofFogStart",
      "ofMipmapType",
      "ofOcclusionFancy",
      "ofSmoothFps",
      "ofSmoothWorld",
      "ofAoLevel",
      "ofClouds",
      "ofCloudsHeight",
      "ofTrees",
      "ofDroppedItems",
      "ofRain",
      "ofAnimatedWater",
      "ofAnimatedLava",
      "ofAnimatedFire",
      "ofAnimatedPortal",
      "ofAnimatedRedstone",
      "ofAnimatedExplosion",
      "ofAnimatedFlame",
      "ofAnimatedSmoke",
      "ofVoidParticles",
      "ofWaterParticles",
      "ofPortalParticles",
      "ofPotionParticles",
      "ofFireworkParticles",
      "ofDrippingWaterLava",
      "ofAnimatedTerrain",
      "ofAnimatedTextures",
      "ofRainSplash",
      "ofLagometer",
      "ofShowFps",
      "ofAutoSaveTicks",
      "ofBetterGrass",
      "ofConnectedTextures",
      "ofWeather",
      "ofSky",
      "ofStars",
      "ofSunMoon",
      "ofVignette",
      "ofChunkUpdates",
      "ofChunkUpdatesDynamic",
      "ofTime",
      "ofClearWater",
      "ofAaLevel",
      "ofAfLevel",
      "ofProfiler",
      "ofBetterSnow",
      "ofSwampColors",
      "ofRandomEntities",
      "ofSmoothBiomes",
      "ofCustomFonts",
      "ofCustomColors",
      "ofCustomItems",
      "ofCustomSky",
      "ofShowCapes",
      "ofNaturalTextures",
      "ofEmissiveTextures",
      "ofLazyChunkLoading",
      "ofRenderRegions",
      "ofSmartAnimations",
      "ofDynamicFov",
      "ofAlternateBlocks",
      "ofDynamicLights",
      "ofScreenshotSize",
      "ofCustomEntityModels",
      "ofCustomGuis",
      "ofShowGlErrors",
      "ofFullscreenMode",
      "ofFastMath",
      "ofFastRender",
      "ofTranslucentBlocks",
      "ofFogType:",
      "ofFogStart:",
      "ofMipmapType:",
      "ofOcclusionFancy:",
      "ofSmoothFps:",
      "ofSmoothWorld:",
      "ofAoLevel:",
      "ofClouds:",
      "ofCloudsHeight:",
      "ofTrees:",
      "ofDroppedItems:",
      "ofRain:",
      "ofAnimatedWater:",
      "ofAnimatedLava:",
      "ofAnimatedFire:",
      "ofAnimatedPortal:",
      "ofAnimatedRedstone:",
      "ofAnimatedExplosion:",
      "ofAnimatedFlame:",
      "ofAnimatedSmoke:",
      "ofVoidParticles:",
      "ofWaterParticles:",
      "ofPortalParticles:",
      "ofPotionParticles:",
      "ofFireworkParticles:",
      "ofDrippingWaterLava:",
      "ofAnimatedTerrain:",
      "ofAnimatedTextures:",
      "ofRainSplash:",
      "ofLagometer:",
      "ofShowFps:",
      "ofAutoSaveTicks:",
      "ofBetterGrass:",
      "ofConnectedTextures:",
      "ofWeather:",
      "ofSky:",
      "ofStars:",
      "ofSunMoon:",
      "ofVignette:",
      "ofChunkUpdates:",
      "ofChunkUpdatesDynamic:",
      "ofTime:",
      "ofClearWater:",
      "ofAaLevel:",
      "ofAfLevel:",
      "ofProfiler:",
      "ofBetterSnow:",
      "ofSwampColors:",
      "ofRandomEntities:",
      "ofSmoothBiomes:",
      "ofCustomFonts:",
      "ofCustomColors:",
      "ofCustomItems:",
      "ofCustomSky:",
      "ofShowCapes:",
      "ofNaturalTextures:",
      "ofEmissiveTextures:",
      "ofLazyChunkLoading:",
      "ofRenderRegions:",
      "ofSmartAnimations:",
      "ofDynamicFov:",
      "ofAlternateBlocks:",
      "ofDynamicLights:",
      "ofScreenshotSize:",
      "ofCustomEntityModels:",
      "ofCustomGuis:",
      "ofShowGlErrors:",
      "ofFullscreenMode:",
      "ofFastMath:",
      "ofFastRender:",
      "ofTranslucentBlocks:",
      "options.guiScale.auto",
      "options.guiScale.small",
      "options.guiScale.normal",
      "options.guiScale.large",
      "options.particles.all",
      "options.particles.decreased",
      "options.particles.minimal",
      "options.ao.off",
      "options.ao.min",
      "options.ao.max",
      "options.stream.compression.low",
      "options.stream.compression.medium",
      "options.stream.compression.high",
      "options.stream.chat.enabled.streaming",
      "options.stream.chat.enabled.always",
      "options.stream.chat.enabled.never",
      "options.stream.chat.userFilter.all",
      "options.stream.chat.userFilter.subs",
      "options.stream.chat.userFilter.mods",
      "options.stream.mic_toggle.mute",
      "options.stream.mic_toggle.talk",
      "Crosshair",
      "Crosshair Preview",
      "Preview Background",
      "Change the preview background to see what the crosshair can look like in multiple environments.",
      "Birch",
      "Roofed",
      "Swamp",
      "Hills",
      "Sky",
      "Use Pack Crosshair",
      "Add an outline around the crosshair.",
      "Dot",
      "Thickness",
      "Change the thickness of the crosshair.",
      "Outline Thickness",
      "Change the outline thickness of the crosshair.",
      "Change the size of the crosshair.",
      "Change how distant the cross is from the center.",
      "Dot Size",
      "Change the size of the dot.",
      "Vanilla Blending",
      "Make the crosshair's color invert depending on what you are looking at.",
      "Crosshair Color",
      "Change the color of the crosshair.",
      "Dot Color",
      "Change the color of the crosshair dot.",
      "Change the color of the crosshair outline.",
      "Replace the Vanilla crosshair with your own custom crosshair.",
      "Global",
      "===========================\n",
      "CategoryPath:                   \n",
      "---------------------------\n",
      "\nCategoryPath:\n\t",
      "<<NONE>>",
      "op",
      "commands.op.usage",
      "commands.op.failed",
      "commands.op.success",
      "iterator",
      "VERTEX",
      "vertex",
      "FRAGMENT",
      "fragment",
      "Unknown resource pack type: ",
      "Unknown resource pack file: ",
      ": Loading ",
      ": Error reading ",
      "Maximum number of displayed LogRecords: ",
      "Motion Blur",
      "Old Blur",
      "Revert to the previously used motion blur shader.",
      "Change the amount of blur intensity.",
      "Change the color of the motion blur.",
      "client/icons/mods/swordblur.png",
      "Adds a shader to blur your surroundings while moving.",
      "Fyu (Original)",
      "Moonsworth LLC (Newer shader)",
      "Phosphor",
      "TNT Timer",
      "Shows a timer above TNT.",
      "TNT Countdown",
      "client/icons/mods/tnt.png",
      "Dynamic Text Color",
      "Static Text Color",
      "0.00",
      "textures/entity/chest/trapped_double.png",
      "textures/entity/chest/christmas_double.png",
      "textures/entity/chest/normal_double.png",
      "textures/entity/chest/trapped.png",
      "textures/entity/chest/christmas.png",
      "textures/entity/chest/normal.png",
      "Hide when value is",
      "Hidden value(s)",
      "%VALUE% %LABEL%",
      "metadata section",
      "frametime",
      "Invalid default frame time",
      "frames",
      "Invalid animation->frames: expected array, was ",
      "Invalid width",
      "Invalid height",
      "interpolate",
      "frames[",
      "Invalid frame time",
      "index",
      "Invalid frame index",
      "Valid",
      "optifine/dynamic_lights.properties",
      "DynamicLights entities: ",
      "DynamicLights items: ",
      "DynamicLights: Parsing ",
      "DynamicLights",
      "DynamicLights: Error reading ",
      "Invalid entry: ",
      ", in:",
      "Object not found: ",
      "Invalid light level: ",
      "java.lang.ThreadGroup[name=",
      ", maxpri=",
      "   Thread=[",
      "Tesselating block in world",
      "Block being tesselated",
      "The limit MUST be > 0",
      "random.chestopen",
      "random.chestclosed",
      "Queue capacity exceeded",
      "tellraw",
      "commands.tellraw.usage",
      "textures/entity/enchanting_table_book.png",
      "Hash is too long (max 40, was ",
      "Updated custom string value successfully.",
      "Old Format",
      "Exception reading ",
      "Couldn't make new level",
      "Deleting level ",
      "Attempt ",
      "Unsuccessful in deleting contents.",
      "Couldn't delete directory ",
      "Couldn't delete file ",
      ".UNMARSHALLER",
      "remoteAddress not set",
      "remoteAddress",
      "handler not set",
      ", remoteAddress: ",
      "must be a readonly buffer: ",
      "An HTTP line is larger than ",
      "textures/entity/villager/villager.png",
      "textures/entity/villager/farmer.png",
      "textures/entity/villager/librarian.png",
      "textures/entity/villager/priest.png",
      "textures/entity/villager/smith.png",
      "textures/entity/villager/butcher.png",
      "right_wing",
      "left_wing",
      "bill",
      "chin",
      ", location: ",
      "failed to open a server socket channel",
      "failed to open a socket channel",
      "failed to open a rendezvous channel",
      "wrong type=",
      "wrong kind=",
      "A JSONObject text must begin with '{'",
      "A JSONObject text must end with '}'",
      "Expected a ':' after a key",
      "Duplicate key \"",
      "Expected a ',' or '}'",
      "JSONObject[",
      "] is not a Boolean.",
      "] could not be converted to BigInteger.",
      "] could not be converted to BigDecimal.",
      "] is not an int.",
      "] is not a long.",
      "Unable to increment [",
      "getClass",
      "getDeclaringClass",
      "\"\"",
      "\\b",
      "\\t",
      "\\n",
      "\\f",
      "\\r",
      "\\u",
      "-0",
      "val [",
      "] is not a valid number.",
      "JSON does not allow non-finite numbers.",
      "Bad value from toJSONString: ",
      "java.",
      "javax.",
      "Unable to write JSONObject value for key: ",
      "eq0",
      "sfd.ser",
      "Signature",
      "Unexpected length of stream identifier: ",
      "Unexpected stream identifier contents. Mismatched snappy protocol version?",
      "Received RESERVED_SKIPPABLE tag before STREAM_IDENTIFIER",
      "Found reserved unskippable chunk type: 0x",
      "Received UNCOMPRESSED_DATA tag before STREAM_IDENTIFIER",
      "Received UNCOMPRESSED_DATA larger than 65540 bytes",
      "Received COMPRESSED_DATA tag before STREAM_IDENTIFIER",
      "mob.villager",
      "banned-ips.txt",
      "banned-players.txt",
      "ops.txt",
      "white-list.txt",
      "d",
      "date",
      "yyyy-MM-dd HH:mm:ss,SSS",
      "HH:mm:ss,SSS",
      "dd MMM yyyy HH:mm:ss,SSS",
      "Could not instantiate SimpleDateFormat with pattern ",
      "Rendering class: [",
      "], Rendered class: [",
      "org.apache.log4j.or.ObjectRenderer",
      "Could not instantiate renderer [",
      "Could not find class [",
      "bites",
      "io.netty.initialSeedUniquifier",
      "initialSeedUniquifierGenerator",
      "Failed to generate a seed from SecureRandom within {} seconds. Not enough entrophy?",
      "Failed to generate a seed from SecureRandom due to an InterruptedException.",
      "-Dio.netty.initialSeedUniquifier: 0x%016x (took %d ms)",
      "n must be positive",
      "handle",
      "javax.swing.event.CellEditorListener",
      "promises contains null ChannelPromise",
      "container.dropper",
      "minecraft:dropper",
      ") call failed.",
      "File option not set for appender [",
      "Are you using FileAppender instead of ConsoleAppender?",
      "setFile called: ",
      "setFile ended",
      "dragon",
      "rear_leg",
      "front_leg",
      "rear_leg_tip",
      "front_leg_tip",
      "rear_foot",
      "front_foot",
      "wing_tip",
      "PERFORM_RESPAWN",
      "REQUEST_STATS",
      "OPEN_INVENTORY_ACHIEVEMENT",
      "Unknown data type: ",
      "Data value id is too big with ",
      "! (Max is ",
      "Duplicate id value for ",
      "Getting synched entity data",
      "Synched entity data",
      "Data ID",
      ".decode() must consume the inbound ",
      "data or change its state if it did not decode anything.",
      ".decode() method must consume the inbound data ",
      "or change its state if it decoded something.",
      ".REPLAY",
      "overlay",
      "textures/models/armor/%s_layer_%d%s.png",
      "_%s",
      "%s:textures/models/armor/%s_layer_%d%s.png",
      "bunnyhop",
      "Trimp",
      "Trimp Multiplier",
      "Hard cap",
      "Soft cap",
      "Soft cap degen",
      "Sharking",
      "Sharking surface tension",
      "Sharking water friction",
      "Air accelerate",
      "Max air accel per tick",
      "Uncapped BunnyHop",
      "Increased FallDistance",
      "0  ",
      "1  ",
      "2  ",
      "3  ",
      "4  ",
      "5  ",
      "6  ",
      "7  ",
      "8  ",
      "9  ",
      "10 ",
      "11 ",
      "12 ",
      "13 ",
      "14 ",
      "15 ",
      "16 ",
      "17 ",
      "18 ",
      "19 ",
      "20 ",
      "21 ",
      "22 ",
      "23 ",
      "24 ",
      "25 ",
      "26 ",
      "27 ",
      "28 ",
      "29 ",
      "30 ",
      "31 ",
      "32 ",
      "33 ",
      "carried",
      "carriedData",
      "mob.endermen.portal",
      "mob.endermen.scream",
      "mob.endermen.idle",
      "mob.endermen.hit",
      "mob.endermen.death",
      "020E0DFB-87AE-4653-9556-831010E291A0",
      " bytes]",
      "container.chestDouble",
      "E MMM d HH:mm:ss yyyy",
      "Error while trying to parse (",
      ") into",
      " a LogLevel.",
      "SEVERE",
      "WARNING",
      "CONFIG",
      "FINE",
      "FINER",
      "FINEST",
      "reader [",
      "Expected aisle with height of ",
      ", but was given one with a height of ",
      "Not all rows in the given aisle are the correct width (expected ",
      ", found one with ",
      "Empty pattern for aisle",
      "Predicates for character(s) ",
      " are missing",
      "OLD",
      "MAIN",
      "VANILLA",
      "Invalid entityFacing ",
      " for facing ",
      "Invalid facing: ",
      "DOWN_X",
      "down_x",
      "UP_Z",
      "up_z",
      "UP_X",
      "up_x",
      "DOWN_Z",
      "down_z",
      "stat.depleted",
      "alpha",
      "multiply",
      "dodge",
      "burn",
      "Unknown blend: ",
      "Length",
      "commands.players.usage",
      "commands.players.list",
      "uuids",
      "BLURPLE",
      "6debd47ed13483642cf09e832ed0bc1b",
      "GREY",
      "322c936a8c8be1b803cd94861bdfa868",
      "dd4dbc0016779df1378e7812eabaa04d",
      "0e291f67c9274a1abdddeb3fd919cbaa",
      "1cbd08c76f8af6dddce02c5138971129",
      "maxCachedBufferCapacity: "
   };
}
